### ISSUE TITLE
When I search with a string ,  after searching  coming back to the initial page Search "string" missing

### ISSUE THREAD

**Issue by mMARUF** [mozilla/addons-frontend#1979] opened 2017-03-06 20:00 UTC
Steps to reproduce : 
1. open latest firefox release  in android
2. then go to https://addons-dev.allizom.org/en-US/firefox/
3. then in the search bar write anything
4. then press the search icon   
5. then press the back button to go back  

Actual Result : 

In the search bar, the string which was  used as search keyword still is there . search string is missing from there 

Expected Result : 
 After coming back , the search string should have been there 

Screenshot - https://drive.google.com/open?id=0B75_JfziYeofcmM2UWlDSG9KZU0

**Comment by muffinresearch** [comment] 2017-03-07 10:57
It's hard to understand precisely the issue being reported here. The `Actual Result` description is unclear and contradictory.

If going by the `Expected Result` description the search term should be in the form when pressing back, this is working for me in both release and nightly on android 6.01.

If you still think there's an issue please could you provide more details including specific versions of android and browser?

**Comment by ValentinaPC** [comment] 2017-03-07 12:36
I think mMARUF is talking about https://github.com/mozilla/addons-frontend/issues/1748 .

**Comment by mMARUF** [comment] 2017-03-07 14:34
"Search extensions and themes" this is the search string. 
When I search with some keyword (eg. abc) , after that if U press the back button , in the search bar "abc" is still there. But  "Search extensions and themes" should have been there.

**Comment by muffinresearch** [comment] 2017-03-07 14:49
@mMARUF thanks for the clarification. I agree with @ValentinaPC this is a duplicate of #1748.

**Closed by muffinresearch** 2017-03-07 14:49 UTC
Labels: needs: info
