### ISSUE TITLE
Wrapping issues with the 'Download file' link from all versions page if longer version notes are present

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10484] opened 2021-04-23 13:46 UTC
### Describe the problem and steps to reproduce it:
1. Open the All versions page for the following add-on: https://addons-dev.allizom.org/en-US/firefox/addon/webmail-ad-regression2/versions/
2. Check the Older versions list where longer version notes are present
3. Observe the Download file link

### What happened?
The link has wrapping issues

### What did you expect to happen?
No layout issues

### Anything else we should know?
- this reproduces on all AMO servers on full and medium screen sizes, but not on mobile (portrait mode)
- as a side note, I personally don't think the 'Download file' or the `Install button` should be center-aligned.  I believe a better placement would be on the same line with the Version number.

[full screen]
![image](https://user-images.githubusercontent.com/31961530/115878511-4e6cee00-a451-11eb-97e8-0a70f0f839d0.png)

[medium]
![image](https://user-images.githubusercontent.com/31961530/115880463-6fced980-a453-11eb-8306-35d671e3ae2f.png)

**Comment by championshuttler** [comment] 2021-04-24 09:57
> better placement would be on the same line with the Version number.

IMO it would be better as well

The word is breaking specifically on the cases where notes are very long for the release notes, I tested locally and i think its a regression again due to mixing of 

```
    overflow-wrap: anywhere;
    word-break: break-word;
```    

😢

**Comment by championshuttler** [comment] 2021-04-26 22:37
Removing `overflow-wrap: anywhere;` fixing the issue for this button

**Comment by bobsilverberg** [comment] 2021-05-06 14:24
@willdurand You were discussing the use of `overflow-wrap: anywhere;` for a different issue (https://github.com/mozilla/addons-frontend/issues/10449). Do you want to take this one as well, as it also seems to be related to that?

**Comment by willdurand** [comment] 2021-05-06 15:50
> @willdurand You were discussing the use of `overflow-wrap: anywhere;` for a different issue (#10449). Do you want to take this one as well, as it also seems to be related to that?

Yes, probably.

**Comment by bobsilverberg** [comment] 2021-05-06 15:57
> > @willdurand You were discussing the use of `overflow-wrap: anywhere;` for a different issue (#10449). Do you want to take this one as well, as it also seems to be related to that?
> 
> Yes, probably.

That's a pretty non-committal answer. 😛 I'm going to assign it to you, and if you really don't want it you can hand it back.

**Comment by willdurand** [comment] 2021-05-07 12:22
I think this isn't a problem with `anywhere` but we should probably be using a grid here.

**Closed** 2021-05-11 15:54 UTC
Labels: component: add-on versions, component: ux, type: prod_bug

**Comment by AlexandraMoga** [comment] 2021-05-12 09:00
This issue is verified fixed on stage:

[desktop - install button]
![image](https://user-images.githubusercontent.com/31961530/117948136-8319ea00-b319-11eb-8334-2067eae49ac3.png)

[desktop - download file link]
![image](https://user-images.githubusercontent.com/31961530/117948175-8c0abb80-b319-11eb-8e2e-5d27b1c381e5.png)

[mobile - download file link]
![image](https://user-images.githubusercontent.com/31961530/117948211-93ca6000-b319-11eb-83a1-2ec9ffea2b19.png)
