### ISSUE TITLE
https://addons.mozilla.org/de/firefox/search-engines/  is dead end road

### ISSUE THREAD

**Issue by herrdeh** [mozilla/addons-frontend#7667] opened 2019-03-04 05:50 UTC
### Describe the problem and steps to reproduce it:

I was about to look for a updated ebay search engine, had deleted the old one.
### What happened?
I was led to a "oops, we cannot find this page" page
### What did you expect to happen?
Hopefully add new search engines.
### Anything else we should know?
German version, this may matter...

This is where I came from:
![grafik](https://user-images.githubusercontent.com/7152847/53713058-b2836100-3e49-11e9-9082-d06e9fa429f8.png)

And I was led to:
![grafik](https://user-images.githubusercontent.com/7152847/53713072-c202aa00-3e49-11e9-9855-36bb2f00fc24.png)

**Comment by EnTeQuAk** [comment] 2019-03-04 08:08
Interesting, a fix for this was released last Friday.

cc @muffinresearch @autrilla 

Duplicate of (closed last Friday) https://github.com/mozilla/addons-frontend/issues/7652

**Comment by EnTeQuAk** [comment] 2019-03-04 08:10
This seems to only affect 2-char language codes.

**Comment by AlexandraMoga** [comment] 2019-03-04 08:16
Ref https://github.com/mozilla/addons-frontend/issues/7664

**Comment by willdurand** [comment] 2019-03-04 13:29
cc @autrilla and @bqbn: we should update the fix that has been deployed last Friday

**Comment by autrilla** [comment] 2019-03-04 13:31
There is a PR for this already in cloudops-deployment. I'd say this can wait until next push, since it's P2?

**Comment by willdurand** [comment] 2019-03-04 13:32
> There is a PR for this already in cloudops-deployment. I'd say this can wait until next push, since it's P2?

I am not sure because according to the OP, it looks like the link comes from FF too.

**Comment by EnTeQuAk** [comment] 2019-03-04 13:32
This might very well be a p1-ish tbh, I only marked it as p2 to not make everyone cry on a Monday morning.

**Comment by herrdeh** [comment] 2019-03-04 15:24
Ok. Mine is 65.0.1 - so our beloved friends at ubuntu may be a bit slow.

**Comment by willdurand** [comment] 2019-03-04 15:26
> This might very well be a p1-ish tbh, I only marked it as p2 to not make everyone cry on a Monday morning.

I also think it is a p1.

**Comment by willdurand** [comment] 2019-03-04 17:38
We just deployed a fix to redirect to the right page. Sorry!

**Closed by willdurand** 2019-03-04 17:38 UTC
Labels: component: ops, priority: p1

**Comment by kumar303** [comment] 2019-03-04 17:47
This was fixed at the nginx level in https://github.com/mozilla-services/cloudops-deployment/pull/2983

**Comment by AlexandraMoga** [comment] 2019-03-05 10:00
I've tested with several localizations and the redirect seems to be working fine now.

Marking issue as verified fixed in FF 65.0.2, Win10x64
