### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by LudoThijssen** [mozilla/addons-frontend#7659] opened 2019-03-01 19:53 UTC
Text input field
right mouse click on text
choose language
add a dictionary
Page not found 
Standard language is Dutch

**Comment by AlexandraMoga** [comment] 2019-03-04 08:04
Thanks for the report. This is, however, a duplicate of https://github.com/mozilla/addons-frontend/issues/7658.

**Closed by AlexandraMoga** 2019-03-04 08:04 UTC
