### ISSUE TITLE
Reviews not visible in Desktop Pages

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2839] opened 2017-07-20 13:41 UTC
Steps to reproduce:

1. Login.
2. Go to the review section for an add-on that has 0 reviews.
3. Give a review with no text to the add-on.
4. Click on the "READ ALL 1 REVIEWS" button.

Expected results:
The review is displayed.

Actual results:
No reviews are displayed.

Notes/Issues:
If the user changes star ratting and adds a comment, the review is still not visible.
Reproduced on AMO-dev FF54(Win 10 64Bit). Reproducing around all servers.
Gif fro this issue:
![reviews not shown](https://user-images.githubusercontent.com/28138132/28420230-222fd2ac-6d6a-11e7-8b0c-449fc6885992.gif)

**Comment by brainzest** [comment] 2017-07-20 18:57
I see that the Review comment section is a mandatory field in old desktop site.  What is the general flow required with the current design?

**Comment by tofumatt** [comment] 2017-07-26 14:25
The comment is not required on the new site so in this case we should be showing 0 reviews so we don't link to a page without any reviews.

**Comment by kumar303** [comment] 2017-11-09 17:18
Since the review has no text it is getting hidden so saying that there is 1 review is a bug. This is a duplicate of https://github.com/mozilla/addons-frontend/issues/2327

**Closed by kumar303** 2017-11-09 17:18 UTC
Labels: project: amo, project: desktop pages, state: blocked, triaged
