### ISSUE TITLE
Upper and lowercases should have same search suggestions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5960] opened 2018-08-16 12:26 UTC
Steps to reproduce:
1.Go to AMO Stage and enter a search term with lower cases
2.Enter same search term with some uppercases

Expected results:
Same search suggestion in both cases

Actual results:
Search suggestions are different

Please see a video for this issue : 

![searchsuggestions](https://user-images.githubusercontent.com/1583842/44208358-cd6ddc80-a168-11e8-9c87-760c17e46d7a.gif)

**Comment by bobsilverberg** [comment] 2018-08-16 12:41
I wonder, is this something we should fix on the front-end (by always sending everything lowercase to the API), or on the back-end (by making the search case insensitive), or is it perhaps not a bug at all, and do we want to keep the search case insensitive?

Do you have an opinion @diox? @jvillalobos?

**Comment by jvillalobos** [comment] 2018-08-16 16:51
I don't think there's much value in having case-sensitive search for AMO. I think this should be fixed in the back-end.

**Comment by willdurand** [comment] 2018-08-17 04:54
This is not something we should address in the frontend anyway, we should send whatever the user types to the API, which will figure out what to do.

@vcarciu could you please open this issue on addons-server?

**Closed by willdurand** 2018-08-17 04:54 UTC

**Comment by vcarciu** [comment] 2018-08-17 15:28
Logged https://github.com/mozilla/addons-server/issues/9196
