### ISSUE TITLE
"All reviews" page numbers are different between old and new desktop format

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2825] opened 2017-07-19 12:38 UTC
Steps to reproduce:
1. Load All Review page for an add-on with reviews on multiple pages i.e. https://addons.allizom.org/en-US/firefox/addon/downthemall/reviews/
2. Go to the bottom of the page and see the number of pages i.e. 75
3. Click "View Mobile Site" link
4. Observe the number of pages i.e. 60

Expected results:
Number of pages is equal.

Actual results:
Number of pages is not equal. 

Notes/Issues:
_Clicking on "View Mobile Site" while in page 69 (nonexistent reviews page in new page format) will continuously load the new desktop page._
Verified on FF54(Win 7). Issue is reproducing on all servers.
No errors displayed in the console.
Screenshot for this issue:
![2017-07-19_1329](https://user-images.githubusercontent.com/15685960/28367086-1bf9cf0a-6c98-11e7-9ab4-7c7e7067bdf0.png)

**Comment by brainzest** [comment] 2017-07-23 10:29
The number of reviews (results) per page is 15 in new mobile site as compared to number of reviews  is 10 per page in old desktop.  Hence the number of pages aren't same.

**Comment by tsl143** [comment] 2017-07-23 16:53
@ValentinaPC  as mentioned by @brainzest 
For the legacy classic desktop website reviews per page is 20
For the new frontend reviews per page is 25

@tofumatt at legacy website we show some text like `Showing 1–20 of 1,490 `, shall we add same to new frontend website?

**Comment by tsl143** [comment] 2017-08-04 08:46
Ping

**Comment by tofumatt** [comment] 2017-08-04 08:51
@tsl143 That would be a separate issue from this, but yes the mocks in #2564 will show where in the pagination the user is.

I'm closing because this isn't a bug, it's just a difference in page sizes between the two versions of the site. This is working as intended, but there will be differences between old and new 😄

**Closed by tofumatt** 2017-08-04 08:51 UTC
Labels: project: amo, project: desktop pages

**Comment by kumar303** [comment] 2017-08-04 18:52
The classic site showed 20 per page. The new site is showing 25 per page which is why the page count is different. These types of comparisons are really helpful though -- we can use the old site (sometimes) to help make sure we are implementing things correctly.
