### ISSUE TITLE
After clicking any Category button ,it goes to the top of the home page first 

### ISSUE THREAD

**Issue by majedrifat** [mozilla/addons-frontend#1994] opened 2017-03-07 18:22 UTC
Steps to reproduce :
1.Open https://addons-dev.allizom.org/en-US/firefox/ in Fire OS
2.Tap on any button from 6 themes categories 
Actual Result:
After tap on button (e.g:Abstract) then  it goes top of the page for a moment and the layout of the homepage is shown and after few moments that category ( Abstract ) page is shown.

Expected Result:
The page should instantly redirect to the Abstract page . 

Attachment -

https://drive.google.com/folderview?id=0B1hODLOUkRLNbXFTWGJzRDBic1k

**Comment by muffinresearch** [comment] 2017-03-08 09:42
Duplicate of https://github.com/mozilla/addons-frontend/issues/1953

**Closed by muffinresearch** 2017-03-08 09:42 UTC
