### ISSUE TITLE
Wrong button selection order when navigating with Tab inside the Rate your experience card

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6246] opened 2018-09-14 09:08 UTC
Depends on https://github.com/mozilla/addons-frontend/issues/6579

STR:

1. Log in to AMO dev
2. Go to an add-on detail page
3. Navigate with Tab until you reach the Ratings card
4. Select a star by using your keyboard
5. Press Tab to move the focus on the Write a review button and Enter to open the review text box
6. Write a review 
7. Press Tab again until the focus is switched to the Submit review button

Actual result:
The focus moves to the *Cancel* button before it switches to the *Submit review* button

Expected result:
The *Submit review* button is focused before the *Cancel* button

Notes:
- reproduced on AMO -dev with FF62, Win10x64

![tab in ratings card](https://user-images.githubusercontent.com/31961530/45540918-49198280-b816-11e8-859c-1cda22127da2.gif)

**Comment by biskit1** [comment] 2018-10-10 15:21
@willdurand @bobsilverberg @AlexandraMoga
I tried replicating this issue in the dev environment, but the rating system seems to behave differently (it appears as a popup window). Is this because I'm running a local dev environment, and if so can someone please advise on how I might be able to accurately reproduce the error and test things out?

Should I be following the instructions laid out [here](https://github.com/mozilla/addons-frontend#running-amo-for-local-development)? 

Thanks!

**Comment by kumar303** [comment] 2018-10-10 17:57
Hi @biskit1 -- you are correct, this bug is a bit different now. I filed https://github.com/mozilla/addons-frontend/issues/6579 .

Sorry for the confusion as you tried to start developing this feature. The instructions you followed are up to date but this specific page was in a state of flux. If you update your code you should see the new review form now (not the overlay) but I would recommend looking at [contrib: welcome](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) issues instead. Those are ones that we think are ready for a contributor to work on. 

I see that you have already landed some patches -- thanks so much!

**Comment by kumar303** [comment] 2018-10-10 17:59
@biskit1 if you are most interested in review / rating features, we have a [handful of issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22contrib%3A+welcome%22+label%3A%22component%3A+add-on+ratings%22+) that are ready.

**Comment by biskit1** [comment] 2018-10-11 14:45
thanks @kumar303! I will take a look.

**Comment by kumar303** [comment] 2018-11-05 17:37
I'm going to dupe this to https://github.com/mozilla/addons-frontend/issues/6579 because the screen changed it a bit and that bug talks about the new screens.

**Comment by kumar303** [comment] 2018-11-07 22:51
Actually, yeah, after I got past the issue in https://github.com/mozilla/addons-frontend/issues/6579 I can see the problem with using the keyboard to access the *Submit review* button. I am re-opening this but I did update the description to fix the button names (which changed in some redesigning).

**Closed** 2018-11-09 15:39 UTC
Labels: component: add-on ratings, priority: p3, type: bug

**Comment by AlexandraMoga** [comment] 2018-11-12 07:38
Verified fixed on AMO -dev with FF63, Win10x64

![correct button selection](https://user-images.githubusercontent.com/31961530/48333056-af782100-e65e-11e8-92a2-ae784ac5fa66.gif)
