### ISSUE TITLE
Add Sort By feature in the new Edit Collection window

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4795] opened 2018-04-13 12:27 UTC
### Describe the problem and steps to reproduce it:

Would be helpful to have the ability to sort the list of add-ons in the new Edit Collection window.
(see Implement an EditableCollectionAddon component to support the new Edit collections screen https://github.com/mozilla/addons-frontend/issues/4778 )

Sort by clicking column title. Sort by Name, Date Added.

### What happened?
Cannot sort list of add-ons in the the Edit Collection window. Especially useful for larger collections.

### What did you expect to happen?
Ability to click the column title to sort list of add-ons.

### Anything else we should know?

See related:
Date Added column missing from new Edit Collection window: 
https://github.com/mozilla/addons-frontend/issues/4794

**Comment by smayer97** [comment] 2018-04-13 12:39
Also related:
Add an add-on to a collection from the edit screen 
https://github.com/mozilla/addons-frontend/issues/4590

**Comment by jvillalobos** [comment] 2018-04-13 15:44
Probably a duplicate of https://github.com/mozilla/addons-frontend/issues/3991. Reopen if it isn't addressed with that issue.

**Closed by jvillalobos** 2018-04-13 15:44 UTC

**Comment by smayer97** [comment] 2018-04-13 18:25
For working with larger collections, easier to find an add-on. 
Also keeps the view consistent when going from the list of addons in the view of the Collection to the Edit window.

**Comment by smayer97** [comment] 2018-04-13 18:36
Yes. It is a duplicate. Thx.

**Comment by smayer97** [comment] 2018-04-13 18:45
Sorry...NOT a duplicate... https://github.com/mozilla/addons-frontend/issues/3991 is about sorting the Add-on Collection main view. This request is about sorting the Edit Collection view.

**Comment by smayer97** [comment] 2019-11-28 07:08
As noted, this is not a duplicate request. Can this be re-opened?

**Comment by smayer97** [comment] 2020-10-04 16:55
Can this be re-opened please since this is not a duplicate request?

**Comment by jvillalobos** [comment] 2020-10-05 17:15
I see the sort options in the Edit mode and they appear to work. What's missing?

**Comment by smayer97** [comment] 2020-10-05 21:16
Some time ago, the sort only worked in the collection list but not while in edit mode. Not sure when this changed but I see now that it works in the edit mode too. 
So this is done. Sorry about that. Thanks kindly for following up.
