### ISSUE TITLE
User info card - More extensions and More themes sections display the username 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4796] opened 2018-04-13 14:40 UTC
STR:
1. Load AMO dev and go to Edit profile.
2. Make sure that the Username and Display Name are different or edit them and save changes. 
3. Go to View my profile and observe the name displayed in More extensions and More themes sections.

Expected result:
Display name is visible.

Actual result:
The username is displayed.

Notes:
This issue is reproducible on AMO dev with FF59(Win10).

![names](https://user-images.githubusercontent.com/33448286/38741083-c71b8906-3f41-11e8-8d58-1206f7f19c33.png)

**Comment by bobsilverberg** [comment] 2018-04-16 14:59
To be clear, this is not an exact duplicate of #4806. That issue is about the "More add-ons by author" card on the add-on detail page whereas this is about the same card, but on the profile page. The fix for both will be implemented in the same patch, so this can remain as the only open issue, but note that it covers both locations of the card.

**Closed** 2018-04-17 20:10 UTC
Labels: component: add-on, component: user profile, priority: p3, size: S, type: papercut

**Comment by ioanarusiczki** [comment] 2018-04-18 12:37
This issue is verified fixed on AMO dev with FF59 (Win10). 
@bobsilverberg I tested for https://github.com/mozilla/addons-frontend/issues/4806 and I noticed that when the display name is edited the add-on detail page has a delay in updating it on the add-ons detail page. Same situation if the display name field is left blank and only the username is edited.  Maybe a separate issue should be filed for this? Also noticed that this https://github.com/mozilla/addons-frontend/issues/4044 is still reproducible.
