### ISSUE TITLE
Review/rating replies are shown on profile

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-frontend#5684] opened 2018-07-20 20:18 UTC
### Describe the problem and steps to reproduce it:

- Reply to review/rating on an extension
- Go to profile
- Scroll to "My reviews" section

### What happened?
Replies are visible as if they are reviews the user wrote.

### What did you expect to happen?
Replies are not reviews, they do not have a star rating associated with them and leaving a review on your own extension would be weird, right?

### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/user/freaktechnik/

![image](https://user-images.githubusercontent.com/640949/43023331-c4d6994e-8c6a-11e8-963d-4ea05d3bda2a.png)

which are replies (to reviews from anonymous users, so I doubt the users will ever get to see the replies :frowning_face: ):

![image](https://user-images.githubusercontent.com/640949/43023344-d0e68c12-8c6a-11e8-9b8b-fa0c08e45fe0.png)

**Comment by mymindstorm** [comment] 2018-07-22 18:06
To add to this, you need to be logged into your account to see these in your profile.

**Comment by willdurand** [comment] 2018-07-23 09:15
> To add to this, you need to be logged into your account to see these in your profile.

Yes, this is by design. The "My reviews" section is personal.

As for the issue itself, I did not know the API would send both reviews and replies at the same time. That looks like something we need to fix.

**Comment by willdurand** [comment] 2018-07-23 09:53
The API returns both the reviews and replies (by developers) when requesting all the reviews for a given user. This is by design, and that's why the "My reviews" section shows reviews and replies without any distinction:

![screen shot 2018-07-23 at 11 38 03](https://user-images.githubusercontent.com/217628/43069651-f07734e6-8e6d-11e8-9a44-222266565810.png)

As @freaktechnik said, there is no rating for a reply, so displaying stars does not really make sense.

We discussed with @diox and @eviljeff on IRC about this issue. We do not have the full add-on loaded for each review returned by the API (only `id` and `slug`), mostly for performance reason. Therefore, there is no way for the frontend to know whether a given review is a reply to a review.

We concluded that it should be possible for the API to return a new boolean attribute for each review (e.g., `is_developer_reply`). Thanks to that, the frontend could change the look of a review that is, in fact, a reply:

![screen shot 2018-07-23 at 11 45 17](https://user-images.githubusercontent.com/217628/43069653-f0985946-8e6d-11e8-9293-1e0f1d8a82cc.png)

That's a quick and dirty UI proposal to: 1. remove the stars, 2. reuse the background color that we use for the developers' replies elsewhere.

@jvillalobos and @pwalm: what do you think?

**Comment by jvillalobos** [comment] 2018-07-23 16:20
This looks good to me.

**Comment by pwalm** [comment] 2018-07-23 22:31
Yep, looks good here too

**Comment by willdurand** [comment] 2018-07-26 08:36
Filed an issue on addons-server to request an API change: https://github.com/mozilla/addons-server/issues/8993.

**Comment by willdurand** [comment] 2018-08-08 12:14
API change landed in -dev: https://github.com/mozilla/addons-server/pull/9099

**Closed** 2018-08-11 15:54 UTC
Labels: component: user profile, priority: p3

**Comment by ioanarusiczki** [comment] 2018-08-13 13:51
Verified fixed on AMO dev with FF61(Win10&Android 8.0)
![developer response layout on user profile page](https://user-images.githubusercontent.com/33448286/44035819-0b992688-9f19-11e8-8a62-e635c5d5076d.png)
