### ISSUE TITLE
Added to collection message is permanent - won't fade away after 5 seconds

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5105] opened 2018-05-25 12:42 UTC
Followup for https://github.com/mozilla/addons-frontend/issues/4979

STR:
1. Load AMO dev and go to an existing collection or create a new one.
2. Click Edit my collection link and add an extension/theme.
3. Observe the green message displayed above the Find add-ons field.

Expected result:
Message should fade away after 5 seconds.

Actual result:
After the extension/theme is added to the list the message is permanent.

Notes:
This issue is reproducible on AMO dev with FF60(Win10 and Android 8.0). 

![add to collection - message](https://user-images.githubusercontent.com/33448286/40544782-1a74cd18-6032-11e8-8258-491bf73280dd.gif)

**Comment by willdurand** [comment] 2018-05-25 12:44
Duplicate of https://github.com/mozilla/addons-frontend/issues/5011?

**Comment by bobsilverberg** [comment] 2018-05-25 15:15
Yes, this duplicates #5011. Closing.

**Closed by bobsilverberg** 2018-05-25 15:15 UTC
Labels: component: collections
