### ISSUE TITLE
Install button is disabled in AMO-stage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2795] opened 2017-07-13 07:52 UTC
Steps to reproduce:
1. Load details page for an add-on on your Android device i.e. https://addons.allizom.org/en-US/android/addon/bluhell-firewall/
2. Observe the installation button

Expected results:
The button is active.

Actual results:
The button is not active.

Notes/Issues:
Verified on FF54(Android 7.1.2, win 7). Issue is only reproducing on stage.
- while accessing add-on details page, the Extensions tab is changed to Explore tab
- reproducing for personas also
- reproducing  also on new desktop pages 
- no errors in the console
Video for this issue:
![videotogif_2017 07 13_10 50 21](https://user-images.githubusercontent.com/15685960/28155903-3a208a5c-67b9-11e7-8345-ea8313a42b4c.gif)

**Comment by muffinresearch** [comment] 2017-07-13 09:24
I can't repro this on Android Nightly

**Comment by muffinresearch** [comment] 2017-07-13 09:28
Or Firefox Desktop Nightly on OSX

**Comment by ValentinaPC** [comment] 2017-07-13 09:33
Tried on **desktop**, on a new fresh-clean Nightly profile and the install button is active but at click a js error is displayed in the console.
Please see screenshot:
![js](https://user-images.githubusercontent.com/15685960/28159934-4cd8456e-67c7-11e7-9c0c-f7dea22eb9b1.png)

**Comment by tofumatt** [comment] 2017-07-13 10:31
The install fail on a fresh profile if the signatures for dev/stage aren't enabled: https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#install-add-ons-for-development

I can see in that console screenshot above it's complaining about bad signatures, so enabling them should fix the issue.

**Comment by ValentinaPC** [comment] 2017-07-13 11:36
I know what you mean, but the pref does not change the initial issue: install button is still disabled.
After searching deeper I came to the conclusion that, without any prefs set, dev and stage are different in what concerns the install buttons:
![dev](https://user-images.githubusercontent.com/15685960/28164426-04fde508-67d8-11e7-9d7a-5a12eb46daf3.png)
![stage](https://user-images.githubusercontent.com/15685960/28164427-05033440-67d8-11e7-8ddc-221618f8348a.png)

Maybe this will help you in discovering why installation does not work on stage.

**Comment by ValentinaPC** [comment] 2017-07-13 14:40
Seems like something fixed this issue. :)

**Comment by muffinresearch** [comment] 2017-07-13 14:43
@ValentinaPC are we ok to close this on the basis of re-opening if it happens again? It's a bit odd, I'd like to know the root cause, but I suspect if it's no longer reproducible that will be difficult.

**Comment by muffinresearch** [comment] 2017-07-13 14:46
Since #2796 has similarly resolved itself I'm going to close this. But feel free to reopen if it re-occurs.

**Closed by muffinresearch** 2017-07-13 14:46 UTC
Labels: project: amo, project: desktop pages, project: mobile pages v1
