### ISSUE TITLE
Add-ons that no longer exist are listed in "Up & Coming" section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3405] opened 2017-10-09 08:47 UTC
Steps to reproduce:
1. Load Extensions homepage i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Check "Up & Comng" section

Expected results:
Each add-on loads corresponding details page.

Actual results:
The section contains add-on that no longer exist.

Notes/Issues:
Verified on AMO-dev FF56(Win7). Issue is also reproducing on stage.
Video for this issue:
![no](https://user-images.githubusercontent.com/15685960/31330512-78cbd3c4-ace7-11e7-9599-0f4a6c280f5f.gif)

**Comment by willdurand** [comment] 2017-10-09 09:37
This could be a problem with our `dev`/`stage` data.

**Comment by AlexandraMoga** [comment] 2017-10-12 15:16
Notes/Issues:
This is now reproducing also for extensions displayed in the "Up & Coming" shelf (on AMO-dev with FF56 - Win10 and Android 7.0 - https://addons-dev.allizom.org/en-US/firefox/)

![up coming](https://user-images.githubusercontent.com/31961530/31503716-0fdf0194-af79-11e7-8291-58418f3d5cfc.gif)

**Comment by ValentinaPC** [comment] 2017-10-13 14:20
This is like https://github.com/mozilla/addons-server/issues/5588 if we access old AMO pages for the Up & Coming sort option, issue that was closed in favor of https://github.com/mozilla/addons-server/issues/5999 .

**Comment by ValentinaPC** [comment] 2017-11-01 10:10
@willdurand : hope this will not end up in prod, after the redesign push, it would be awful.

**Comment by willdurand** [comment] 2017-11-01 10:17
Right. It is already live in - prod (https://addons.mozilla.org/) and I was unable to find invalid add-ons.

**Comment by ValentinaPC** [comment] 2017-11-01 12:13
The redesign is not "by default" in prod, at tomorrow push I was referring. 
In production I have no rights to disable or delete an add-on versions (to leave it without any) that was public, to see if I can replicate, could you please try these scenarios, just to be sure that it is an only dev/stage issue?
Thanks!

**Comment by muffinresearch** [comment] 2017-11-07 12:59
Duplicate of https://github.com/mozilla/addons-server/issues/5999

**Closed by muffinresearch** 2017-11-07 12:59 UTC
Labels: project: amo, project: desktop pages, triaged
