### ISSUE TITLE
Placeholder content only (no details) at the new front end to slug 'AddonVerNumber'

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#4986] opened 2018-05-13 09:21 UTC
### Preamble

Symptoms comparable to recently closed [Impossible to load an add-on detail page when its slug begins with a dash followed by only numbers · Issue #4541 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/4541) however in this case: 

- I see nothing unusual in the slug
- at (dev) https://addons-dev.allizom.org/en-GB/firefox/addon/AddonVerNumber/ today there's nothing.

### Discovery (STR)

Immediately after manually allowing this week's 2018-12-05 update to version 1.10 of _Version Number in Add-ons Manager_, at `about:addons` I (probably) used the [Add-ons Manager Context Menu](https://addons.mozilla.org/addon/am-context/) to visit the home page of the updated extension. 

### Actual result

- https://addons.mozilla.org/addon/AddonVerNumber/ redirect to https://addons.mozilla.org/en-GB/firefox/addon/AddonVerNumber/ with placeholder content but **no** details for slug _AddonVerNumber_
- https://addons.mozilla.org/en-GB/firefox/addon/AddonVerNumber/versions/ does present details.

### Expected result

- https://addons.mozilla.org/addon/AddonVerNumber/ redirect to https://addons.mozilla.org/en-GB/firefox/addon/AddonVerNumber/ with placeholder content **and** details.

### Anything else we should know?

After reading parts of #4541: 

- I chose the classic desktop site view for https://addons.mozilla.org/en-GB/firefox/addon/AddonVerNumber/ and found details
- I wondered whether the new site view of https://addons-dev.allizom.org/en-GB/firefox/addon/AddonVerNumber/ would present details but no, that page simply is _not found_.

### Captures

Very soon after discovering the issue: 

- https://web.archive.org/web/*/https://addons.mozilla.org/en-GB/firefox/addon/AddonVerNumber/ (first saved 2018-12-05 04:22:38)
- https://archive.is/gG4LX (2018-12-05 04:22:59 UTC)

**Comment by bobsilverberg** [comment] 2018-07-05 18:12
This is pretty strange. I can confirm that going to https://addons.mozilla.org/en-US/firefox/addon/AddonVerNumber/ on the legacy site does show an add-on, but going to the same URL on the new front end only shows a screen with loading GIFS. I don't see any messages in the console which suggest a problem.

@wagnerand Is there anything specific about the add-on itself that might be causing this?

**Comment by wagnerand** [comment] 2018-07-05 18:23
@bobsilverberg the add-on is a legacy add-on. Does the new frontend support legacy add-on listings?

**Comment by bobsilverberg** [comment] 2018-07-05 18:43
Good question. I think it does, in that I don't think it does anything special to exclude them. I think it will just display whatever the API returns, regardless of whether an add-on is legacy or not. But I could be wrong about that.

**Comment by willdurand** [comment] 2018-07-06 08:36
Looks like a case sensitivity issue to me: https://addons.mozilla.org/en-US/firefox/addon/addonvernumber/

**Comment by willdurand** [comment] 2018-07-25 16:39
> Thanks @willdurand. Do we know if this is expected, or is it a bug? Should this URL be case sensitive?

That's a good question and I don't know, ping @diox

**Comment by willdurand** [comment] 2018-07-26 09:11
The API returns a valid response whether slug is `addonvernumber` or `AddonVerNumber`. The frontend shows a 404 because the slug in the URL is not the same as the one returned by the API (in its response). The correct slug for this add-on is: `addonvernumber`.

**Comment by willdurand** [comment] 2018-07-26 09:15
We came to the conclusion that this bug is legit and that we should fix it: IMO the best fix would be to send a server redirect (`sendServerRedirect()` with status = 301) in the `Addon` component if the `params.slug !== addon.slug`. It will require some changes to the `getAddonsForSlug()` selector to make it case insensitive.

**Comment by diox** [comment] 2018-08-02 16:09
Duplicate of https://github.com/mozilla/addons-frontend/issues/4271

**Closed** 2018-08-02 16:14 UTC
Labels: component: accessibility, component: add-on, type: bug
