### ISSUE TITLE
ERROR: 'Warning: Each child in an array or iterator should have a unique "key" prop[...]'

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1507] opened 2016-12-19 11:47 UTC
Errors like:

```
ERROR: 'Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `DiscoPaneBase`. See https://fb.me/react-warning-keys for more information.
    in MockedSubComponent (created by DiscoPaneBase)
    in DiscoPaneBase
```

are all over the test suite and make the output really noisy. Seems like just adding a `key` prop to things like https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/OverallRating.js#L78 fixes it, so it'd be nice to do that and quiet the tests a bit.

**Comment by kumar303** [comment] 2016-12-20 15:40
whoops, I missed this; I'll grab it. Generally when I look at the test suite output I cry. I would like to also fix https://github.com/mozilla/addons-frontend/issues/1373 and also clean up all the console logging.

**Comment by muffinresearch** [comment] 2017-01-03 09:52
Dupe of https://github.com/mozilla/addons-frontend/issues/764

**Comment by kumar303** [comment] 2017-01-12 17:20
I won't have time for this until after we launch the new AMO mobile V1

**Comment by muffinresearch** [comment] 2017-03-21 15:03
Closedin favour of Flow.

**Closed by muffinresearch** 2017-03-21 15:03 UTC
Labels: component: code quality, triaged
