### ISSUE TITLE
Navigation after an empty search in Extensions/Themes homepages is broken

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2953] opened 2017-08-16 11:02 UTC
Steps to reproduce:
1. Make an empty search in Extensions homepage https://addons-dev.allizom.org/en-US/firefox/search/?type=extension
2. Navigate to last pages i.e. page 500 - https://addons-dev.allizom.org/en-US/firefox/search/?app=firefox&page=500&type=extension

Expected results:
Results are listed.

Actual results:
Page is somehow broken.

Notes/Issues:
- same happens for empty search and navigation from Themes homepage - https://addons-dev.allizom.org/en-US/firefox/search/?app=firefox&page=2000&type=persona
Verified on AMO-dev FF54(Win 7). Issue is ONLY reproducing on -dev.
Video for this issue:
![loading](https://user-images.githubusercontent.com/15685960/29360290-e89c1768-828a-11e7-8ad1-1a221e0e65e1.gif)

May be a regression from #2665 ?

**Comment by tofumatt** [comment] 2017-08-16 11:10
Looks like this is related to the number of pages we're showing–they aren't accurate. Navigating to 400 works but 401 also renders an error.

It seems our page numbers are inaccurate.

**Comment by tofumatt** [comment] 2017-08-16 11:12
Looks like this is a dupe of #1971, basically–we don't use the right info from the API so we render the wrong number of pages.

**Closed by tofumatt** 2017-08-16 11:12 UTC
Labels: project: amo, project: desktop pages
