### ISSUE TITLE
Authentication check required

### ISSUE THREAD

**Issue by Aanandgupta** [mozilla/addons-frontend#10058] opened 2021-02-04 05:41 UTC
### Describe the problem and steps to reproduce it:
If we are using particular extension page in two tabs and if we log out from one of the page we are still able to change ratings from the other tab. and it reflects changes when we login again

### What did you expect to happen?
We should not be allowed to do any action  after we have been logged out.

![Screenshot (126)](https://user-images.githubusercontent.com/71023799/106848095-431de800-66d6-11eb-832d-49f930b87101.png)

![Screenshot (127)](https://user-images.githubusercontent.com/71023799/106849061-136fdf80-66d8-11eb-9e02-509d207e77da.png)

![Screenshot (128)](https://user-images.githubusercontent.com/71023799/106849819-68602580-66d9-11eb-9344-6b26e2375e4c.png)

**Comment by willdurand** [comment] 2021-02-17 14:08
@Aanandgupta can we actually complete an action? I can see why we'd be able to see buttons, etc. but after logout, the server should clear the cookies and auth stuff on its side, so actions should eventually fail I think.

**Comment by wagnerand** [comment] 2021-02-17 14:42
This sounds like a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1336652.

**Comment by willdurand** [comment] 2021-02-17 14:44
> This sounds like a duplicate of [bugzilla.mozilla.org/show_bug.cgi?id=1336652](https://bugzilla.mozilla.org/show_bug.cgi?id=1336652).

@wagnerand could you please cc me on this bug?

**Comment by wagnerand** [comment] 2021-02-17 14:48
> > This sounds like a duplicate of [bugzilla.mozilla.org/show_bug.cgi?id=1336652](https://bugzilla.mozilla.org/show_bug.cgi?id=1336652).
> 
> @wagnerand could you please cc me on this bug?

Done.

**Comment by willdurand** [comment] 2021-02-17 14:55
Yeah, maybe. So I think this isn't a frontend bug in any case.

**Closed by willdurand** 2021-02-17 14:55 UTC

**Comment by Aanandgupta** [comment] 2021-02-17 16:53
> @Aanandgupta can we actually complete an action? I can see why we'd be able to see buttons, etc. but after logout, the server should clear the cookies and auth stuff on its side, so actions should eventually fail I think.



> Yeah, maybe. So I think this isn't a frontend bug in any case.

@willdurand I think this is because we might only be checking session at the time page is mounted so we are allowed to change ratings even after we have been logged out in other tab (as page is not reloaded in the other tab so it acts as it is authorized) it could be fixed by checking authorization each time when we are changing ratings.and for all actions that are not be allowed without authentication and does not result in reloading of page as pages which results in reloading of page will again be checked for sessions and work correctly
