### ISSUE TITLE
Corresponding <title> for addons

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3487] opened 2017-10-13 01:49 UTC
### Describe the problem and steps to reproduce it:
Navigate to any addon details page : https://addons.mozilla.org/en-US/firefox/addon/measure-it/

### What happened?
The `<title>` of page is `Add-ons for Firefox`

### What did you expect to happen?
The `<title>` should be `Measure-it : Add-ons for Firefox` (The addon name)
Same that happens on legacy website

### Anything else we should know?
Mobile website
<img width="783" alt="screen shot 2017-10-13 at 7 16 59 am" src="https://user-images.githubusercontent.com/5318732/31526799-bab5ed40-afe6-11e7-9295-881316522e37.png">

Legacy website
<img width="781" alt="screen shot 2017-10-13 at 7 17 18 am" src="https://user-images.githubusercontent.com/5318732/31526793-b0d5633c-afe6-11e7-9824-0faa1d351e16.png">

**Comment by muffinresearch** [comment] 2017-10-13 10:17
Duplicate of https://github.com/mozilla/addons-frontend/issues/2184

**Closed by muffinresearch** 2017-10-13 10:17 UTC
