### ISSUE TITLE
Custom Persona/Edit Not working for checking theme designs!

### ISSUE THREAD

**Issue by MaDonnasPersonas** [mozilla/addons-frontend#1410] opened 2016-11-22 21:01 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I have to use the Custom/Edit to check the Persona theme designs and today it is not working. When you click on Custom/Edit (chrome://personas/content/customPersonaEditor.xul)  the design does not show up. Actually nothing happens.

**Comment by atsay** [comment] 2016-11-22 23:09
This is an issue with the [Personas Plus](https://addons.mozilla.org/firefox/addon/personas-plus) add-on @wagnerand

**Comment by wagnerand** [comment] 2016-11-22 23:12
I tested this before releasing the new version and it worked fine for me. Can you please provide detailed steps to reproduce the issue? Thank you.

**Comment by MaDonnasPersonas** [comment] 2016-11-22 23:12
Thanks, Amy.

**Comment by wagnerand** [comment] 2016-11-22 23:13
Also, can you please check the browser console for any errors? That would be most helpful, thank you.

**Comment by MaDonnasPersonas** [comment] 2016-11-22 23:16
Well, ya got me there. I don't know how to check the browser console. Tell
me how and I will do so, but the problem is with both my PC and laptop.

**Comment by MaDonnasPersonas** [comment] 2016-11-22 23:29
Is this any help?

**Comment by wagnerand** [comment] 2016-11-22 23:38
After the issue happened, go to Tools -> Web Developer -> Browser Console (should be CTRL+Shift+J). Just select everything in there and please file a new issue with that on https://github.com/mozilla/personas-plus/issues

Thank you!

I'm closing this one since it's the wrong repository and to save others some emails.

**Closed by wagnerand** 2016-11-22 23:38 UTC
