### ISSUE TITLE
infos in top right box should be linked

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#3788] opened 2017-11-05 07:28 UTC
Please see the attached screenshot. The number of users should be a link to the stats (if public stats are enabled or the developer is logged in), the number of reviews should be a link to the reviews view. There is already a "Read all 197 reviews" link on the page but on a different place and the box top right is the first thing I see after the extension name and the "Read all 197 reviews" link is not within the viewport. That's the reason why I didn't know where the reviews are on my first visit. My opinion is: if there is a number of reviews it should be linked to the reviews.

<img width="480" alt="bildschirmfoto 2017-11-05 um 08 24 00" src="https://user-images.githubusercontent.com/1100614/32412774-c5925c5c-c202-11e7-99c8-a70f7996d8fa.png">

**Comment by tofumatt** [comment] 2017-11-05 07:43
I agree about the review number being linked but we removed the user stats link because that link is elsewhere on the page and not all (or even many popular) add-ons have public stats, so the inconsistent link there that wasn’t very discoverable and didn’t clearly indicate what it was linking to wasn’t great.

- Matt (Sent from mobile)

**Comment by tofumatt** [comment] 2017-11-05 12:37
Seems like this is a duplicate of #3157; we'll track the issue there but clearly the review count/average in the top-right card should be linking to more reviews.

**Closed by tofumatt** 2017-11-05 12:37 UTC
