### ISSUE TITLE
Navigating inside AMO mobile has no loading animation implemented

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-frontend#1897] opened 2017-02-24 15:15 UTC
*Environment*
Firefox: Nightly 54.0a1
Mobile device: Samsung S7 (Android 6.0.1)

*Steps to reproduce*
1. Go to AMO mobile –dev homepage.
2. Navigate inside AMO mobile:
-	go to Extensions/Themes page
-	go to any of the Extensions/Themes categories from homepage
-	browse all Extensions/Themes
-	use Firefox Add-ons home button
-	Log out
Observe the behavior when loading a page.

*Expected results*
A loading animation (loading progress bar) indicates a page is loading.

*Actual results*
No loading animations can be seen by the user.

*Notes*
1. Reproducibility: 5/5.
2. Loading animations are a common practice on web and we believe AMO should make no exception.

**Comment by muffinresearch** [comment] 2017-02-24 19:49
Duplicate of #1219 and #1156

**Closed by muffinresearch** 2017-02-24 19:49 UTC
Labels: state: duplicate

**Comment by raresmsv** [comment] 2017-02-27 15:54
@muffinresearch : Will a loading animation be implemented for any action that implies navigation? Cause from what I've read in the other two bugs, one is referring to "Rating Submission" and the other one to "Search feature". That is why I've logged a more generic issue, trying to cover any action that requires a loading indicator.

Regards,
RaresM
