### ISSUE TITLE
Glitch in Extensions homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2885] opened 2017-08-02 08:50 UTC
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Click on "Browse all extensions"/"Browse all themes"

Expected results:
Page is loaded without any issues.

Actual results:
For a few seconds Extensions homepage with themes or Themes homepage with extensions is loaded.

Notes/Issues:
- longer glitch in Extensions page
- reproducing also if Extensions/themes tabs are clicked directly 
- also reproducing on device
Verified on AMO-dev FF54(Win 7, Android 7.2.1).
Video for this issue:
![glitch](https://user-images.githubusercontent.com/15685960/28865333-329f9ace-7778-11e7-8901-e6ef1b69d03b.gif)

May be related to #2859

**Comment by muffinresearch** [comment] 2017-08-02 11:48
Duplicate of https://github.com/mozilla/addons-frontend/issues/2882

**Closed by muffinresearch** 2017-08-02 11:48 UTC
Labels: project: amo, project: desktop pages, state: duplicate

**Comment by ValentinaPC** [comment] 2017-08-02 12:56
@muffinresearch: saw that bug, but thought is about no loading bar. Sry!
