### ISSUE TITLE
Bad link in Web browser customization 

### ISSUE THREAD

**Issue by gwiggin** [mozilla/addons-frontend#7654] opened 2019-03-01 09:42 UTC
### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/search-engines/

**Comment by muffinresearch** [comment] 2019-03-01 10:50
Thanks for the report, however, this is a duplicate of https://github.com/mozilla/addons-frontend/issues/7652

**Closed by muffinresearch** 2019-03-01 10:50 UTC
