### ISSUE TITLE
Firefox extension for Kindle. Link broken.

### ISSUE THREAD

**Issue by kevitivity** [mozilla/addons-frontend#8149] opened 2019-06-10 06:46 UTC
### Describe the problem and steps to reproduce it:
Download link for Firefox kindle extension is nroken.
URL: https://www.amazon.com/gp/sendtokindle/firefox

### What happened?
Page not found :oops"
### What did you expect to happen?
download start.
### Anything else we should know?

https://www.amazon.com/gp/sendtokindle/firefox

**Comment by jvillalobos** [comment] 2019-06-10 17:38
Closing as a duplicate of https://github.com/mozilla/addons-frontend/issues/7282

**Closed by jvillalobos** 2019-06-10 17:38 UTC
