### ISSUE TITLE
not saving to prefenece 

### ISSUE THREAD

**Issue by mickyfan2345** [mozilla/addons-frontend#5203] opened 2018-06-05 20:46 UTC

**Comment by mickyfan2345** [comment] 2018-06-05 20:47
all themes selected will not save it when im signed in it gives me this Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it. do you think it could be with the new update of firefox

**Comment by muffinresearch** [comment] 2018-06-06 13:00
Hi @mickyfan2345 this bug report doesn't give us enough information to know what the problem is - please can you provide as much information as possible:

* Can you tell us the URL you were on when you saw this error?
* What were you trying to do when you saw this error?
* What version of Firefox are you using?
* Please provide any screenshots that help us identify where the problem is.

**Comment by muffinresearch** [comment] 2018-06-06 13:28
Duplicate of #5116

**Closed by muffinresearch** 2018-06-06 13:28 UTC
Labels: needs: info

**Comment by mickyfan2345** [comment] 2018-06-06 16:39
i've given you all i can on the problem i given you screen shots using
firefox 60.0.1 (64-bit) i was trying to save it to my account this is the
first url i go to
https://addons.mozilla.org/en-US/firefox/themes/abstract/?sort=up-and-coming
and this is the second it takes me to i don't know what more i can give you
please help me

thanks

**Comment by mickyfan2345** [comment] 2018-06-09 16:53
i've given you all i can on the problem i given you screen shots using
firefox 60.0.1 (64-bit) i was trying to save it to my account this is the
first url i go to https://addons.mozilla.org/en-US/firefox/themes/abstract/?
sort=up-and-coming and this is the second it takes me to i don't know what
more i can give you please help me

thanks
https://mail.google.com/mail/u/1/#inbox/163d52f863f00779?projector=1&messagePartId=0.1
