### ISSUE TITLE
Ratings infotip doesn't match the actual rating stars associated with an add-on

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4186] opened 2018-01-19 08:55 UTC
STR:

1. Access AMO homepage and go to Extensions tab
2. In Extensions homepage, click on "See more top rated extensions" (i.e. https://addons.mozilla.org/en-US/firefox/search/?sort=rating&type=extension)
3. Hover over the rating of the first listed add-on

Expected result:
A tooltip witch matches the actual stars associated with the add-on is displayed

Actual result:
The tooltip shows different rating information than the actual rating stars

Notes:
Reproduced on all AMO servers with FF57 (Win10)
This can also be checked in the add-on details page by hovering over the rating statistics (https://addons.mozilla.org/en-US/firefox/addon/pakkujs/)

![image](https://user-images.githubusercontent.com/31961530/35142474-130d01dc-fd07-11e7-9bf0-6d40118d19b9.png)

**Comment by KhushilMistry** [comment] 2018-01-22 03:27
Hey, I want to work on this issue.
I have gone through all the components. I guess its creating problem in rating component.
Here, what can be wrong ? Rating-half-star class or Description ?

**Comment by kumar303** [comment] 2018-01-22 15:35
@KhushilMistry thanks for your interest.

This creates the half-star. The comment explains how we calculate half stars. https://github.com/mozilla/addons-frontend/blob/181b81e7e3e6c0e17da386558d8a8fb62ffe1c0d/src/ui/components/Rating/index.js#L58

This creates the "5 out of 5" label. https://github.com/mozilla/addons-frontend/blob/181b81e7e3e6c0e17da386558d8a8fb62ffe1c0d/src/ui/components/Rating/index.js#L94

I suggest an approach like this:
* By inspecting the values (using developer tools), figure out which one of those two functions is calculating half-stars incorrectly
* Introduce a shared helper function so that half-stars are only calculated in one place
* Add unit tests for your changes

@AlexandraMoga do you know of any examples on dev or stage?

**Comment by AlexandraMoga** [comment] 2018-01-23 09:37
There aren't such clear examples on dev and stage, 
I had two add-ons which I thought might be affected but, after checking the rule you are using for calculating half stars, I am not so sure they are the best examples.
Nevertheless, here is what I had in mind:
for -dev: https://addons-dev.allizom.org/en-US/firefox/addon/code_count/
for stage: https://addons.allizom.org/it/firefox/addon/tab-mix-plus/
![image](https://user-images.githubusercontent.com/31961530/35268352-864e1212-0031-11e8-83e5-ebbcf258b261.png)

**Comment by kumar303** [comment] 2018-01-23 18:19
Showing 4 stars with a label of 'Rated 4.4 out of 5' would be expected behavior in that case. We only render a half-star for rating values between 4.5 and 5.0.

**Comment by caitmuenster** [comment] 2018-02-21 16:38
Hey @ KhushilMistry, how's it going with this bug?

**Comment by KhushilMistry** [comment] 2018-02-21 16:53
Really Sorry, I was working on another bug. I will make PR for this in a day.

**Comment by KhushilMistry** [comment] 2018-02-26 19:21
I have added PR for this #4429. Can anyone review this ?

**Comment by tofumatt** [comment] 2018-02-26 19:31
@KhushilMistry Yes we've seen the PR but sometimes we're a bit behind reviewing contributor PRs as we're a small team and I've been out sick. We'll get to the PR ASAP though; we check through our open PRs regularly 😄

**Comment by KhushilMistry** [comment] 2018-02-26 19:33
Okay Thanks 😄

**Comment by jvillalobos** [comment] 2018-04-05 17:56
This affects the rating perception of AMO add-ons, and has been noticed by multiple developers. I'm bumping this up in priority. @KhushilMistry, are you still working on this? I saw some review comments that are pending resolution.

**Comment by KhushilMistry** [comment] 2018-04-05 18:01
Hey, Yeah. I will update the PR in a day.

**Comment by bobsilverberg** [comment] 2018-04-12 13:32
Having said that, the above appears to be what the code is currently doing, so I'm not sure where the problem is. The PR attached was attempting to change the way stars are rendered, but I think they are being rendered as expected, and maybe the problem is with the tooltip instead. The original example shows 4 1/2 stars being rendered but a tooltip of "Rated 5 out of 5", which does seem like a problem. The second example, at https://github.com/mozilla/addons-frontend/issues/4186#issuecomment-359733473, does not demonstrate a problem, at least not if what I've documented above for behaviour is correct.

@jvillalobos Could you please summarize what the problem is, and how the current behaviour needs to change?

**Comment by bobsilverberg** [comment] 2018-04-12 19:37
Yes @jvillalobos, please file a separate issue about the rounding explaining exactly how you think it should work. After that's done I think we can close this as I cannot reproduce even the initial example.

**Comment by jvillalobos** [comment] 2018-04-12 21:51
Closing per previous comment.

**Closed by jvillalobos** 2018-04-12 21:51 UTC
Labels: component: add-on ratings, component: ux, priority: p2, project: amo, project: desktop pages, size: S, type: bug, type: papercut

**Comment by AlexandraMoga** [comment] 2018-04-17 09:31
My initial issue was targeting the tooltip displayed for a particular add-on but after a re-check on prod, I can see that the same add-on is showing now the right/current calculation logic. 
![image](https://user-images.githubusercontent.com/31961530/38861393-26314664-423b-11e8-8788-1978997e7eef.png)

Based on that I will mark this as verified fixed.
