### ISSUE TITLE
Server error on add-on listing page on mobile

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-frontend#2647] opened 2017-06-28 17:26 UTC
### What happened?
Got a Server Error (Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.) while viewing an add-on listing on mobile.

STR: Open the [URL](
https://addons.mozilla.org/en-US/android/addon/6898/) on Firefox for Android (or any other browser on Android) 

### What did you expect to happen?
Add-on listing to appear just fine
### Anything else we should know?
[Screenshot](https://user-images.githubusercontent.com/607379/27650930-767192aa-5beb-11e7-874b-498fda13b5d8.png)
https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/618227/

**Comment by tofumatt** [comment] 2017-06-28 17:27
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/2646. Thanks for filing, willl have a fix very soon!

**Closed by tofumatt** 2017-06-28 17:27 UTC

**Comment by SVSanta** [comment] 2017-07-04 13:03
Verified this on AMO-dev FF54(Android 6.0.1).
Postfix screenshot:
![no error android](https://user-images.githubusercontent.com/28138132/27831220-5e6e1520-60d2-11e7-886b-88162b86cdfa.jpg)
