### ISSUE TITLE
Search result page crashes with a 504 or a 404 error when changing the page language

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#1713] opened 2017-02-06 16:16 UTC
### Steps to reproduce
1. Open addons-dev.allizom.org on your android device.
2. Perform a search.
3. Scroll to the bottom of the page and change the language.

### Expected results:
The page is localized in the selected language.

### Actual results:
The page crashes with a 404 error or a 504 error.

### Notes/Issues:
Verified in FF51(Android 7.1.1) in addons-dev.allizom.org
Please view this screenshots:
![screenshot_20170206-181234](https://cloud.githubusercontent.com/assets/15685441/22655191/0e7484c2-ec98-11e6-8c4b-84d6ea4e1016.png)

**Comment by muffinresearch** [comment] 2017-02-08 17:38
Duplicate of #1401

**Closed by muffinresearch** 2017-02-08 17:38 UTC
Labels: duplicate, mobile pages v1
