### ISSUE TITLE
AMO header disappears when viewing in Arabic (right-to-left issue?)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1578] opened 2017-01-06 22:07 UTC
### What happened?

I viewed the AMO site in Arabic

### What did you expect to happen?

It should show the header but instead the header appears very dim.

### Anything else we should know?

Here it is in Arabic:

![screenshot 2017-01-06 16 03 44](https://cloud.githubusercontent.com/assets/55398/21734616/eaa63e68-d429-11e6-8892-0fa6cc70afdd.png)

This is what it should look like (using English as an example)

![screenshot 2017-01-06 16 04 00](https://cloud.githubusercontent.com/assets/55398/21734629/fe01df1c-d429-11e6-8f38-b519729eba2e.png)

**Comment by tofumatt** [comment] 2017-01-06 23:10
This is probably a duplicate of #1253; if it happens in another locale that you haven't previously visited it's definitely the same as #1253.

**Closed** 2017-01-06 23:11 UTC
Labels: amo, duplicate

**Comment by kumar303** [comment] 2017-01-09 16:57
Ah, yes, thanks. I can no longer reproduce it so it sounds like the same bug.
