### ISSUE TITLE
Opening `addons.mozilla.org` from Firefox for Android, and attempting to install an add-on downloads an .xpi

### ISSUE THREAD

**Issue by padenot** [mozilla/addons-frontend#11920] opened 2022-11-21 13:59 UTC
### Describe the problem and steps to reproduce it:

STR:
- Google `ublock origin firefox` from Firefox for Android (any current version)
- Open the first result (pointing to https://addons.mozilla.org/fr/firefox/addon/ublock-origin/)
- Tap the button to add the add-on to Firefox

Expected:
- The add-on is added to Firefox (like on desktop), after a prompt probably

Actual:
- An `.xpi` file is downloaded

Apparently, based on the URL I went to the desktop site, but no warning was visible, and the website had a mobile layout.

I've filed https://github.com/mozilla-mobile/fenix/issues/27923 on the Firefox for Android side, but I was asked to open something here as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-108)

**Comment by diox** [comment] 2022-11-21 14:05
The real issue for us is that we should have displayed a warning : the user is on the /firefox/ page instead of /android/ ...

**Comment by bobsilverberg** [comment] 2022-11-21 16:19
> The real issue for us is that we should have displayed a warning : the user is on the /firefox/ page instead of /android/ ...

I believe this is happening because the add-on is compatible with both desktop and Android, so our code does not see it as incompatible on this page and therefore no warning is displayed. I think this is the expected behaviour and I'm not sure there's any reason to change it. The fact that it downloads an xpi file is expected, as we don't support installing add-ons on android directly from AMO.

**Comment by willdurand** [comment] 2023-11-02 09:45
This issue appears to be fixed in Nightly (and likely Beta).

**Closed by willdurand** 2023-11-02 09:45 UTC
Labels: platform:android, component:add-on, priority:p4

**Comment by ioanarusiczki** [comment] 2023-11-07 10:45
@willdurand 

I looked over AMO dev on Fenix 119.0.1 and 121.0a1

- the layout should be alright, 4 extensions for the recommended shelf, and 8 on the trending shelf. 
- On 119.0.1 the see more trending link has only  recommeded (and a couple of line) add-ons compared to 121.0a1 where see more link will display 165 results. 
- search results work as expected
- I'll check installs once this lands on -stage


https://github.com/mozilla/addons-frontend/assets/33448286/20822c7f-5669-4df8-8c58-50c3fdcd7ae6

**Comment by vcarciu** [comment] 2023-11-07 11:09
I verified this as fixed in Firefox Release. Attempting to install an addon will trigger the direct installation of the extension.

I will mark the issue as verified.

**Comment by KevinMind** [comment] 2024-05-05 17:49
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-108
