### ISSUE TITLE
Deleted my favorite

### ISSUE THREAD

**Issue by NatoBoram** [mozilla/addons-frontend#4006] opened 2017-11-29 03:45 UTC
### Describe the problem and steps to reproduce it:

1. Delete your favourite collection
2. Go to your favourites

### What happened?

404

### What did you expect to happen?

I should not be able to delete my favourites. There should be an option to completely reset it to default values as if it was a new account, tho. Now, when I try to access my favourites from my profile to add new ones, I get a 404.

### Anything else we should know?

https://addons.mozilla.org/en-US/android/collections/NatoBoram/favorites/

**Comment by kumar303** [comment] 2017-11-29 04:45
Thanks for taking the time to file an issue. This is a duplicate of https://github.com/mozilla/addons-frontend/issues/3884 ; we should have a fix shortly.

**Closed by kumar303** 2017-11-29 04:45 UTC

**Comment by NatoBoram** [comment] 2017-11-29 05:25
Thanks!
