### ISSUE TITLE
Add an interface/popup for developers to reply to reviews

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2775] opened 2017-07-12 00:52 UTC
Add a page that developers can use to reply to a review.

**Comment by muffinresearch** [comment] 2017-09-08 17:22
I'm not sure but I don't see any UX for this in the sketch file, but I might have missed it? @pwalm do you have something for this?

**Comment by pwalm** [comment] 2017-09-12 21:42
There is no ux for this on paper, but I have it in my brain. Lemme mock it up and post it here.

**Comment by kumar303** [comment] 2017-09-20 15:46
I'm nominating for MVP removal because I think we could do this as a follow-up feature.

**Comment by jvillalobos** [comment] 2017-09-21 23:42
Being able to reply to reviews can be pretty important for developers. I wouldn't object to dropping the All Reviews page from the MVP, but if we keep it this should also be included.

**Comment by kumar303** [comment] 2017-09-22 14:34
> I wouldn't object to dropping the All Reviews page from the MVP

Just to be clear, we currently do have a mobile listing of all reviews: https://addons.mozilla.org/en-US/firefox/addon/youtube-high-definition/reviews/ (which is reachable on desktop)

The All Reviews issue we have marked as MVP is to give it a desktop style.

**Comment by kumar303** [comment] 2017-09-26 14:50
@pwalm I'm going to start with the mobile styles since we can use the same overlay as writing/editing a review

**Comment by kumar303** [comment] 2017-09-26 14:51
Also @tofumatt added a nice inline textarea UX that might be nice here so that the context of the review you are replying to is fully in view.

**Comment by kumar303** [comment] 2017-09-26 14:58
The inline textarea (added for abuse reports) appears like this when you click a button. This might work well for review replies but I'm going to look at both that and the overlay and start with whichever is easiest to implement. We can always fix it up later.

<img width="321" alt="screenshot 2017-09-26 09 56 03" src="https://user-images.githubusercontent.com/55398/30867290-29b7d26a-a2a1-11e7-8612-27e1ee06e571.png">

**Comment by pwalm** [comment] 2017-09-28 21:47
First pass at a flow for this:
1) Developer sees a "Reply to this user" below each review.
<img width="1281" alt="screen shot 2017-09-28 at 2 42 21 pm" src="https://user-images.githubusercontent.com/6797635/30991858-c2e517c0-a45b-11e7-9099-f1ea22c37c81.png">

2) Launches a modal window with a reply field.
3) Dev can preview reply.
4) Dev can then publish.
<img width="1296" alt="screen shot 2017-09-28 at 2 42 57 pm" src="https://user-images.githubusercontent.com/6797635/30991900-f06fbf56-a45b-11e7-89fd-2c7768f83bdc.png">

5) Reply appears below original review
<img width="1325" alt="screen shot 2017-09-28 at 2 44 35 pm" src="https://user-images.githubusercontent.com/6797635/30991908-fe9c69e4-a45b-11e7-98aa-05211076a020.png">

**Comment by tofumatt** [comment] 2017-09-28 23:05
I dig it! I wouldn't call that a modal though–I think of a modal as a window that appears above all content and prevents interaction with the rest of the content/page until it's completed/dismissed. It's also disconnected from the content it's related to by virtue of it appearing above *all other* content.

I definitely prefer your UX where it *doesn't* prevent interaction with the rest of the page and is also clearly related to the review it's replying to–the developer knows which comments they're addressing because their response is below what they're replying to.

Unless you meant it SHOULD be a modal we copy the original review into. I guess we could do that but I'd say the best option would be to have the reply textarea and dismiss/submit buttons appear inline, right under the review (similar to how we currently implement the "Report Abuse" inline textarea for add-on pages on the new front-end). That way the original review and response are clearly connected.

**Closed** 2017-10-04 21:47 UTC
Labels: component: add-on ratings, needs: ux, priority: mvp, project: 2017 Q3, project: amo, project: desktop pages, triaged

**Comment by kumar303** [comment] 2017-10-05 21:44
Oh, huh, this was a dupe of https://github.com/mozilla/addons-frontend/issues/2773 which was implemented in https://github.com/mozilla/addons-frontend/pull/3334

**Comment by kumar303** [comment] 2017-10-05 21:46
> Should the user who left the review have the possibility to edit his comment...?

Yes, but that will happen in https://github.com/mozilla/addons-frontend/issues/3368
