### ISSUE TITLE
License link is not listed in add-on details page until after refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2435] opened 2017-05-25 11:47 UTC
Steps to reproduce:
1. Load details page for an add-on that has license (there are a bunch of old add-ons without license)
2. Go to "More information" section and observe the license link

Expected results:
License link is displayed.

Actual results:
License link is not displayed.

Notes/Issues:
- license link is displayed after page refresh.
Verified on FF53(Android 6.0.1). Issue is reproducing on all AMO servers.
Video for this issue:
![videotogif_2017 05 25_14 43 15](https://cloud.githubusercontent.com/assets/15685960/26449115/1971329c-4159-11e7-9b0a-9b0424e2dac5.gif)

**Comment by kumar303** [comment] 2017-05-25 16:10
There is another bug similar to this but I can't find it. I think the root cause is that when the search results get loaded, we use the add-on data from those results to populate the add-on detail page. If you refresh the add-on detail page, it makes an actual API result to get add-on data. 

I think we should stop using the add-on data from search results and always make an API request. The search results contain partial add-on data so it's only going to cause more bugs like this.

**Comment by ValentinaPC** [comment] 2017-05-26 05:47
@kumar303 : Are you talking about this https://github.com/mozilla/addons-frontend/issues/2412 ? :)

**Comment by tsl143** [comment] 2017-05-26 10:44
@kumar303 Yes that is the cause.
When we use `addons/search` API the `License` key is `null`
When we use `addons/addon/${slug}` API the `License` key has desired data

Consider ->
https://addons-dev.allizom.org/api/v3/addons/search/?app=android&q=facebook%20redirect&page=1&lang=en-GB

https://addons-dev.allizom.org/api/v3/addons/addon/flink-removal/

**Comment by kumar303** [comment] 2017-05-26 15:27
@tsl143 yes, exactly. I think we should just use the add-on detail API result for all cases. I plan to do that change as part of https://github.com/mozilla/addons-frontend/issues/2442

> Are you talking about this #2412 ? :)

That's similar but I don't think it's caused by the same exact problem. It would require some investigation to know for sure.

**Comment by kumar303** [comment] 2018-03-21 20:35
This was fixed in https://github.com/mozilla/addons-frontend/issues/2573 . I was able to verify it just now. Let me know if anyone can still reproduce the bug.

We definitely need to be careful about this data type in the future. I filed https://github.com/mozilla/addons-frontend/issues/4624 to help.

**Closed by kumar303** 2018-03-21 20:35 UTC
Labels: priority: p3, project: amo, triaged, type: papercut

**Comment by ioanarusiczki** [comment] 2018-03-22 10:27
Verified this issue on AMO dev and AMO stage with FF59 (Win10) and it is no longer reproducible. 

![licence](https://user-images.githubusercontent.com/33448286/37765234-57cbd1ae-2dcc-11e8-9db5-216ef1b1fbe4.gif)
