### ISSUE TITLE
Add languages for spellcheck brocken

### ISSUE THREAD

**Issue by alexander91** [mozilla/addons-frontend#7661] opened 2019-03-02 15:02 UTC
### Describe the problem and steps to reproduce it:

Right mouse button, check spelling other languages

### What happened?

page not fount

### What did you expect to happen?

page where I can add languages

**Comment by AlexandraMoga** [comment] 2019-03-04 08:08
Thanks for the report. This is, however, a duplicate of https://github.com/mozilla/addons-frontend/issues/7658

**Closed by AlexandraMoga** 2019-03-04 08:08 UTC
