### ISSUE TITLE
CSS is broken on -dev; CORS errors reported in the browser console 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9925] opened 2020-12-16 10:34 UTC
### Describe the problem and steps to reproduce it:
1. Load AMO -dev with the browser console opened
2. Notice the page layout and the console messages

### What happened?
The CSS is not loaded and the following errors can be seen in the console:
```
Access to CSS stylesheet at 'https://addons-amo-dev-cdn.allizom.org/amo-0f67d0acb9f599965ba2.css' from origin 'https://addons-dev.allizom.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://addons-amo-dev-cdn.allizom.org/amo-0f67d0acb9f599965ba2.css net::ERR_FAILED
Access to script at 'https://addons-amo-dev-cdn.allizom.org/amo-5c62d6abfc3e7e8be81c.js' from origin 'https://addons-dev.allizom.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://addons-amo-dev-cdn.allizom.org/amo-5c62d6abfc3e7e8be81c.js net::ERR_FAILED
```

### What did you expect to happen?
AMO frontend is loaded successfully

**Comment by bobsilverberg** [comment] 2020-12-16 13:40
We saw something similar on Friday, but it resolved itself, and it seems that this is now working again too.

@bqbn Do you recall if we knew what the problem was on Friday? Is there anything we can do to mitigate this?

@AlexandraMoga Can you confirm that this is now fixed?

**Comment by AlexandraMoga** [comment] 2020-12-16 13:45
@bobsilverberg yes, the issue appears to be fixed now. The site is loaded correctly and I'm not seeing the CORS errors anymore.

**Comment by bqbn** [comment] 2020-12-16 21:11
> Do you recall if we knew what the problem was on Friday?

No, we didn't find out what happened last Friday.

> Is there anything we can do to mitigate this?

@bobsilverberg I think we first need to understand what the cause is, then we can think about how to mitigate or fix it.

**Comment by bqbn** [comment] 2020-12-17 01:17
The `addons-amo-dev-cdn.allizom.org` domain is served by a CloudFront distribution that is backed by an S3 bucket. There is no Nginx involved in this case.

I noticed the following difference for the `amo-0f67d0acb9f599965ba2.css` file:

```
$ curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0" -I https://addons-amo-dev-cdn.allizom.org/amo-0f67d0acb9f599965ba2.css
HTTP/1.1 200 OK
Content-Type: text/css
Content-Length: 660081
Connection: keep-alive
Date: Wed, 16 Dec 2020 09:40:36 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Last-Modified: Tue, 15 Dec 2020 09:56:42 GMT
ETag: "b5526c18e2b91d3a31653e316614d208"
Cache-Control: max-age=315360000, immutable
Expires: Sun, 15 Dec 2030 09:56:36 GMT
x-amz-version-id: X.K7NjQTzzZSe39GFO1YNRjxEHcTgfMW
Accept-Ranges: bytes
Server: AmazonS3
Vary: Accept-Encoding
X-Cache: Hit from cloudfront
Via: 1.1 0bb842bd5868b86440983b936bb0adef.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SEA19-C1
X-Amz-Cf-Id: 0Bpv41tEuTT8pyAyVDLCluh1DWu2BDUshxi-olaXKWk8K996xvMNuw==
Age: 53800
```

and

```
$ curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0" -H "accept-encoding: gzip" -I https://addons-amo-dev-cdn.allizom.org/amo-0f67d0acb9f599965ba2.css
HTTP/1.1 200 OK
Content-Type: text/css
Connection: keep-alive
Date: Tue, 15 Dec 2020 10:22:35 GMT
Last-Modified: Tue, 15 Dec 2020 09:56:42 GMT
ETag: W/"b5526c18e2b91d3a31653e316614d208"
Cache-Control: max-age=315360000, immutable
Expires: Sun, 15 Dec 2030 09:56:36 GMT
x-amz-version-id: X.K7NjQTzzZSe39GFO1YNRjxEHcTgfMW
Server: AmazonS3
Content-Encoding: gzip
Vary: Accept-Encoding
X-Cache: Hit from cloudfront
Via: 1.1 fec77e486350d1bd33f526a760d8b5a4.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SEA19-C1
X-Amz-Cf-Id: 16kR7qK0b8H6D5-GnOnWWrYR48F4sHVW-ErLKkjEJVq5OLdjNKQC0A==
Age: 137626
```

Basically the `Access-Control-Allow-Origin` header was returned when I passed the `accept-encoding` header, but it was not returned when I didn't pass the `accept-encoding` header. A browser probably always passes the `accept-encoding` header, so that might explain the error in the browser.

I then tested downloading the `amo-5c62d6abfc3e7e8be81c.js` file with and without the `accept-encoding` header, and observed the same result.

However, here is what's interesting. I then invalidated the cache for `amo-5c62d6abfc3e7e8be81c.js` file and test it again. This time, both time it returned the `Access-Control-Allow-Origin` header, with or without the `accept-encoding` header.

```
$ curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0" -I https://addons-amo-dev-cdn.allizom.org/amo-5c62d6abfc3e7e8be81c.js
HTTP/1.1 200 OK
Content-Type: application/javascript
Content-Length: 1738818
Connection: keep-alive
Date: Thu, 17 Dec 2020 00:48:55 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Last-Modified: Tue, 15 Dec 2020 09:56:46 GMT
ETag: "89aab34a159cd47b0b128d53f0408d12"
Cache-Control: max-age=315360000, immutable
Expires: Sun, 15 Dec 2030 09:56:36 GMT
x-amz-version-id: nOD1JrWYpJQ7SxzC9QNg1VfNzlF_s07D
Accept-Ranges: bytes
Server: AmazonS3
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 c9b161639a9353c2354b895548ea9fca.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SEA19-C1
X-Amz-Cf-Id: -KYbX8V7rF1IsH4sIwTMCwHF-3yhQyNo2pjoR0tblc9CGIvemkV2sQ==
```
and
```
$ curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0" -H "accept-encoding: gzip" -I https://addons-amo-dev-cdn.allizom.org/amo-5c62d6abfc3e7e8be81c.js
HTTP/1.1 200 OK
Content-Type: application/javascript
Connection: keep-alive
Date: Thu, 17 Dec 2020 00:49:07 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Last-Modified: Tue, 15 Dec 2020 09:56:46 GMT
ETag: W/"89aab34a159cd47b0b128d53f0408d12"
Cache-Control: max-age=315360000, immutable
Expires: Sun, 15 Dec 2030 09:56:36 GMT
x-amz-version-id: nOD1JrWYpJQ7SxzC9QNg1VfNzlF_s07D
Server: AmazonS3
Content-Encoding: gzip
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 3a6260aec53985f2e6eb8a637c47918d.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SEA19-C1
X-Amz-Cf-Id: KdSv0MFdJOYEGPzNHULLPFxY0pnK9zt2EXD3iORX-KzsDcp8cct2bA==
```

Note the two `X-Cache: Miss from cloudfront` above, which is expected since I invalidated the cache for that file before running the `curl` command.

The question I don't have an answer is that, why the files were cached in CloudFront without the `Access-Control-Allow-Origin` header in the first place? Because in my test, after I invalidated the cache for one of the files, and then re-downloaded that file, the `Access-Control-Allow-Origin` header was cached in both cases (with or without the `accept-encoding` header).

@AlexandraMoga next time if you ran into the issue, please post the full request/response headers in the browser. That may be helpful for troubleshooting the issue.

**Comment by AlexandraMoga** [comment] 2020-12-17 14:44
@bqbn these are the request and response headers I get for https://addons-amo-dev-cdn.allizom.org/amo-40224139947874a2e917.css. In this case I've been using Chrome, as the error seemed to reproduce more consistently there. This data was taken from launching the browser with no pre-exiting cache. 


**Request headers**
```
Accept: text/css,*/*;q=0.1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: addons-amo-dev-cdn.allizom.org
Origin: https://addons-dev.allizom.org
Referer: https://addons-dev.allizom.org/
Sec-Fetch-Dest: style
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
```
**Response Headers**
```
Age: 3985
Cache-Control: max-age=315360000, immutable
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/css
Date: Thu, 17 Dec 2020 09:56:36 GMT
ETag: W/"b5526c18e2b91d3a31653e316614d208"
Expires: Tue, 17 Dec 2030 09:46:44 GMT
Last-Modified: Thu, 17 Dec 2020 09:46:53 GMT
Server: AmazonS3
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: 1.1 d124c249f6bd52641e04ffb388920c68.cloudfront.net (CloudFront)
X-Amz-Cf-Id: v3G_qw2bYLEIc-mPn-4EpIFas9mR7Avcyz6SEyTL4fzid1y2kpKIYQ==
X-Amz-Cf-Pop: LHR50-C1
x-amz-version-id: RrpJdLWv3zSisgFdSqBIjqq26RfAGACE
X-Cache: Hit from cloudfront
```

**Comment by bqbn** [comment] 2020-12-17 23:05
I see `X-Cache: Hit from cloudfront` in your response headers and I wonder what could have put it in there.

Because after I invalidated the cache for that file, and then used the same request headers to download that file, I got the `Access-Control-Allow-Origin` header back (notice the `X-Cache: Miss from cloudfront` header in below ouput. 

```
$ curl -I -H "Accept: text/css,*/*;q=0.1" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-US,en;q=0.9" -H "Connection: keep-alive" -H "Host: addons-amo-dev-cdn.allizom.org" -H "Origin: https://addons-dev.allizom.org" -H "Referer: https://addons-dev.allizom.org/" -H "Sec-Fetch-Dest: style" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-site" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" https://addons-amo-dev-cdn.allizom.org/amo-40224139947874a2e917.css
HTTP/1.1 200 OK
Content-Type: text/css
Connection: keep-alive
Date: Thu, 17 Dec 2020 18:18:37 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Last-Modified: Thu, 17 Dec 2020 09:46:53 GMT
ETag: W/"b5526c18e2b91d3a31653e316614d208"
Cache-Control: max-age=315360000, immutable
Expires: Tue, 17 Dec 2030 09:46:44 GMT
x-amz-version-id: RrpJdLWv3zSisgFdSqBIjqq26RfAGACE
Server: AmazonS3
Content-Encoding: gzip
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 2241406ac19fffc8f35d6ddef8e22f56.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SEA19-C1
X-Amz-Cf-Id: biNzY4BhCwNIOnIKmzsqDsNkOcP74jqRrPxBVtxq9o9x6J8GhccDuw==
```

**Comment by bqbn** [comment] 2020-12-19 00:21
I filed a support case with AWS, and they've said,

> it appears that for the request where the CORS headers are lacking the Origin header doesn't seem to have been forwarded in the request to the S3 origin for the original request. 

They're conducting further investigation into the case, and I'll update this issue when I hear more from them.

**Comment by bqbn** [comment] 2021-01-09 01:21
Do we have any process or command that tries to "GET" or "HEAD" an object with an "Access-Control-Request-Method" or "Access-Control-Request-Headers" header? 

Because so far, that is the only way we find that can put an object into the CDN without the CORS headers. For example,

```
$ curl -sv -o /dev/null -H "Access-Control-Request-Method: POST"  https://addons-amo-dev-cdn.allizom.org/amo-00048ab4f75ad6c677c0.css
... ...
> GET /amo-00048ab4f75ad6c677c0.css HTTP/1.1
> Host: addons-amo-dev-cdn.allizom.org
> User-Agent: curl/7.64.1
> Accept: */*
> Access-Control-Request-Method: POST
>
< HTTP/1.1 200 OK
< Content-Type: text/css
< Content-Length: 359107
< Connection: keep-alive
< Date: Fri, 08 Jan 2021 22:18:14 GMT
< Last-Modified: Fri, 21 Dec 2018 22:25:53 GMT
< ETag: "6f41d3e1f09652b641e46daf772d7ca3"
< Cache-Control: max-age=315360000, immutable
< Expires: Thu, 21 Dec 2028 22:25:51 GMT
< x-amz-version-id: 0hkKAVSVLSgXY0sGuz3XzqdTiBcW9cgQ
< Accept-Ranges: bytes
< Server: AmazonS3
< Vary: Accept-Encoding
< X-Cache: Miss from cloudfront
< Via: 1.1 c7c3cdef911c9ee3c1a83a78f425dc5b.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: HIO50-C1
< X-Amz-Cf-Id: REG6YBRXwNGDcoq1oKtKrGx2rnCOcWpSufE3G1lOZ0H2ReZalqSR8A==
```

Note the `X-Cache: Miss from cloudfront` header and no `Access-Control-Allow-Origin` header was returned in the above example. 

If that were the first request right after a push, then it could have put a no-CORS-header object into CDN, and subsequent requests would see `X-Cache: Hit from cloudfront` but without CORS headers.

A well written browser should have only used "OPTIONS" method with the "Access-Control-Request-Method" or "Access-Control-Request-Headers" header. Since "OPTIONS" method is blocked by our CDN, that won't put a bad object in our CDN. However, if something is doing what the above example shows as the very first request after a new push, it can explain the issue reported in this ticket.

**Comment by willdurand** [comment] 2021-01-12 08:38
> Do we have any process or command that tries to "GET" or "HEAD" an object with an "Access-Control-Request-Method" or "Access-Control-Request-Headers" header?

I can't think of anything. It's really weird that this would happen mainly on -dev.

**Comment by bobsilverberg** [comment] 2021-01-18 19:36
@bqbn @willdurand Should we close this issue, or keep it open in case this happens again?

**Comment by bqbn** [comment] 2021-01-19 21:44
We put in a temporary workaround on 1/8 that lets the CDN always add a `Access-Control-Request-Method: GET` header for the requests it forwards to S3 (override if the header already exists in the requests).

Let's wait for a little longer before closing this.

**Comment by bqbn** [comment] 2021-01-28 01:13
AWS got back to us with the following,

> For now, you should continue to use your workaround since you confirmed that you are no longer seeing files being cached with missing CORS response headers.
>
> CloudFront currently doesn't support conditional header forwarding based on request method, however, I have contact your Technical Account Manager to raise the feature request on your behalf. Since feature requests are handled by another team, I can't give a time-frame as to if / when it will be implemented, however this is valued input that will help us to improve the CloudFront service.


It is still not clear what caused the issue in -dev environment. Like I mentioned in the above, before [the workaround](https://github.com/mozilla-services/cloudops-deployment/pull/4176), using a "GET" or "HEAD" request with an "Access-Control-Request-Method" or "Access-Control-Request-Headers" header can re-produce the issue. However we don't know if that's what caused it, and if it is what would have sent such a request to trigger the issue.

**Comment by AlexandraMoga** [comment] 2021-02-08 16:23
@bqbn I've been seeing a CORS error on stage this time.

These are the errors shown in the browser console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-amo-cdn.allizom.org/amo-f5f5f159df8ed61a4850.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

None of the “sha512” hashes in the integrity attribute match the content of the subresource.
```
Not sure what the second one is about.

As actual effects on the site, I've noticed that the search suggestion list is not loaded when a search term is entered in the field. 

I have the following request/response headers for https://addons-amo-cdn.allizom.org/amo-f5f5f159df8ed61a4850.js:

Request headers:

```
GET /amo-f5f5f159df8ed61a4850.js HTTP/1.1
Host: addons-amo-cdn.allizom.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: https://addons.allizom.org
Connection: keep-alive
Referer: https://addons.allizom.org/
Sec-Fetch-Dest: script
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
```
Response header:

```
HTTP/1.1 200 OK
Content-Type: application/javascript
Transfer-Encoding: chunked
Connection: keep-alive
Date: Fri, 05 Feb 2021 14:19:43 GMT
Last-Modified: Fri, 05 Feb 2021 13:44:21 GMT
ETag: W/"1f73e045b60e3cdbad465a004f91e526"
Cache-Control: max-age=315360000, immutable
Expires: Wed, 05 Feb 2031 13:44:19 GMT
x-amz-version-id: N_3Or5tq_I4iE9ZOQbjuaBzPkJyZsquK
Server: AmazonS3
Content-Encoding: gzip
Vary: Accept-Encoding
X-Cache: Hit from cloudfront
Via: 1.1 ec53ea7490128507417199834543513b.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SFO5-C1
X-Amz-Cf-Id: qXS7trHOG6wnUpS54Lqf_vXlpQVXT9qLK51_0-youslwIxnRPFpNjg==
Age: 265922
```

**Comment by bqbn** [comment] 2021-02-08 23:55
I have applied https://github.com/mozilla-services/cloudops-deployment/pull/4176 to -stage env as well.

We'll apply it to -prod this Thursday before the push.

**Comment by AlexandraMoga** [comment] 2021-02-09 11:02
I'm no longer reproducing the error today. I'll keep a watch on this issue as asked.

**Comment by willdurand** [comment] 2021-02-10 16:09
should be fixed this week

**Closed by willdurand** 2021-02-10 16:09 UTC
Labels: component: ops, priority: p3
