### ISSUE TITLE
Show all domains in list of permissions

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#7634] opened 2019-02-25 12:41 UTC
There is no way for a user to know what all domains can an extension access data from if the host permissions >= 4.

Consider this extension https://addons.mozilla.org/en-US/firefox/addon/google-search-result-shortcuts
It says it can access data from google.com, google.ad, google.ae and **`190 other domains`** - This information is kind of really insufficient and vague for a user.
I am sure we dont want to put all 190 domains in product page, but may be a popup or `see more` kind of stuff may help.

![image](https://user-images.githubusercontent.com/5318732/53338046-f84ca080-3902-11e9-93ca-62b3c0800297.png)

**Comment by willdurand** [comment] 2019-03-14 15:52
That's a good question. /cc @jvillalobos

**Comment by jvillalobos** [comment] 2019-03-14 22:56
There might be a dupe of this one somewhere, because I know we've talked about it before. The current display is consistent with Firefox, and I think it's fine as a default. 

Having a secondary exhaustive list sounds like a good idea, but it would need to account for an arbitrary number of permissions. If we get the UX for it, I'm for doing it.

**Comment by willdurand** [comment] 2020-03-30 14:52
@mirefly wanna give it a try? :D

**Comment by willdurand** [comment] 2020-03-30 14:53
Reopening this one because FF has been fixed to display all the permissions/domains.

**Comment by mirefly** [comment] 2020-03-30 16:35
@willdurand Yeah, I am gonna have a try.

**Comment by mirefly** [comment] 2020-03-31 05:52
@willdurand  Listing all permission will push some cards ("Release note" and "Add to collection") to the very end of the page when there are many domain names. It looks not good. Do we want to simply list all permissions, or just show the "other host/site names" as tooltip text when mouse over the text "Access your data in ** other domains" (or other suggestions)?

**Comment by willdurand** [comment] 2020-03-31 07:11
could we use a `ShowMoreCard`?

**Closed** 2020-04-07 16:18 UTC
Labels: component: add-on, contrib: welcome, priority: p4

**Comment by AlexandraMoga** [comment] 2020-04-08 11:23
Verified fixed on stage.

Before:
![image](https://user-images.githubusercontent.com/31961530/78777916-178d7c80-79a3-11ea-8d04-436da67d5f42.png)

After:
![image](https://user-images.githubusercontent.com/31961530/78778448-f711f200-79a3-11ea-9e81-43c9084d19a2.png)
This is the add-on example from stage: https://addons.allizom.org/en-US/firefox/addon/many-domain-perms/
All the given domains are now visible on the detail page by expanding the Permissions card (clicking Read more)
