### ISSUE TITLE
Don't use <select> on AMO when there is 4-5 items to pick from

### ISSUE THREAD

**Issue by edouard-lopez** [mozilla/addons-frontend#3979] opened 2017-11-27 10:01 UTC
### Describe the problem and steps to reproduce it:

Addon filter UI use `<select>` when it will be a lot better to use `<input type=radio>`

### What happened?

![selection_125](https://user-images.githubusercontent.com/1212392/33261058-e0bc8384-d361-11e7-8c38-8646309e492f.png)

### What did you expect to happen?

Have all options available directly so I can scan them. 

More info: [Dropdowns Should be the UI of Last Resort](https://www.lukew.com/ff/entry.asp?1950)

**Comment by jvillalobos** [comment] 2017-11-27 15:27
Closing as duplicate of https://github.com/mozilla/addons-frontend/issues/3942

**Closed by jvillalobos** 2017-11-27 15:27 UTC
