### ISSUE TITLE
youtubenem jatszale a videokat HTML5 Követel kristonimre02@gmail.com

### ISSUE THREAD

**Issue by jimmy1948** [mozilla/addons-frontend#4217] opened 2018-01-24 20:14 UTC

**Comment by tofumatt** [comment] 2018-01-24 20:16
Closing due to lack of information.

Please add information to your issue including the error you encountered, a URL (if applicable), and steps to reproduce.

**Closed by tofumatt** 2018-01-24 20:16 UTC

**Comment by jimmy1948** [comment] 2018-01-24 20:19
youtube nemjatszale a vdeokat HTML5 Lejatszotkövetel

**Comment by tofumatt** [comment] 2018-01-24 20:20
Hi @jimmy1948,

If you're having an issue with the add-ons site please let us know what the issue is and which URL you encountered the error on.

It sounds like you're encountering an issue with YouTube, which we can't help with.
