### ISSUE TITLE
Total number of reviews seems slightly bigger than the rest of the text on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3188] opened 2017-09-20 10:57 UTC
Steps to reproduce:
1. Load details page for an add-on with reviews on your Android device  i.e. https://addons-dev.allizom.org/en-US/android/addon/lastpass-password-manager/
2. Observe reviews section

Expected results:
There are no display issues.

Actual results:
The total number of reviews seems slightly bigger than the rest of the text.

Notes/Issues:
Verified on AMO-dev FF55(Android 7.2.1).
Screenshot for this issue:
![2017-09-20_1349](https://user-images.githubusercontent.com/15685960/30640292-08379192-9e0b-11e7-8d4d-63c76ed65172.png)

**Comment by muffinresearch** [comment] 2017-09-20 12:32
This is not just on android:

<img width="517" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30643778-27d00b40-9e08-11e7-8a3c-6389fe5244ff.png">

**Comment by tofumatt** [comment] 2017-09-20 12:33
That text is the same same as the "Read More" link elsewhere. This is working as intended, so closing as won't fix.

That said: we should have this be non-small-caps. I've filed #3190 for that though.

**Closed by tofumatt** 2017-09-20 12:33 UTC
