### ISSUE TITLE
Kanji chars generate layout issues for summary in add-on details pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3964] opened 2017-11-23 10:30 UTC
Steps to reproduce:
1. Add a 2 rows summary in Japanese (or other language that uses kanji chars) for an add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/disconnect/
2. Go to add-on details page and observe summary section

Expected results:
There are no display or layout issues.

Actual results:
A vertical scrollbar is displayed.

Notes/Issues:
- reproducing also for themes;
Verified on AMO-dev FF57(Win 7). Reproducing on all servers.
Screenshot for this issue:
![2017-11-23_1225](https://user-images.githubusercontent.com/15685960/33168413-80cceeac-d049-11e7-979e-ef7a35800b44.png)

**Comment by muffinresearch** [comment] 2017-11-23 16:19
@ValentinaPC is that link reproducing currently for you? I don't see the issue at the moment going to https://addons-dev.allizom.org/en-US/firefox/addon/disconnect/

**Comment by ValentinaPC** [comment] 2017-11-24 08:48
Yes, that is the link.
I have other:
https://addons.mozilla.org/en-US/firefox/addon/rej/ (you must me an admin to see this one)
Screenshot from https://addons-dev.allizom.org/en-US/firefox/addon/disconnect/
![2017-11-24_1047](https://user-images.githubusercontent.com/15685960/33202354-e3157032-d104-11e7-80e7-59de2cf7eebe.png)

Maybe your are using Mac OS and that is why the scrollbar is less visible. Don't know.

**Comment by muffinresearch** [comment] 2018-02-05 18:28
Duplicate of https://github.com/mozilla/addons-frontend/issues/4074

**Closed by muffinresearch** 2018-02-05 18:28 UTC
Labels: component: add-on, component: i18n, project: amo, project: desktop pages
