### ISSUE TITLE
A user review doesn't appear to be removed when it is deleted from a permalink

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6321] opened 2018-09-20 08:32 UTC
Follow up for #2771 

STR:

1, Log in to AMO stage
2. Go an add-on details page
3. Review the add-on
4. Go to the add-on reviews page
5. Click on the permalink next to the review you've just written
6. Delete the review and see the results

Actual result:
The review is still displayed at the top of the list after you've deleted it

Expected result:
The review is no longer displayed at the top of the list after it is deleted

Notes:
- the review is still displayed if the page is refreshed
- also reproduced when deleting developer replies
- if you look at the total number of reviews you will see that the number is actually decreasing
- if you open again the add-on reviews page, you will see that your review was in fact removed
- reproduced on dev and stage with FF 62, Win10x64

![deleting review from permalink](https://user-images.githubusercontent.com/31961530/45805962-88d5e380-bcc8-11e8-991d-0267a7e8354d.gif)

Permalink to a deleted review as seen by another user or when logged out:
![image](https://user-images.githubusercontent.com/31961530/45805999-9ab78680-bcc8-11e8-9bc1-ddb13b7dd586.png)

**Comment by bobsilverberg** [comment] 2018-09-20 12:07
We’re you logged in with an admin account when seeing this? This is expected behaviour with an admin account because admins can see deleted reviews.

**Comment by AlexandraMoga** [comment] 2018-09-20 12:29
Oh, yes, I was using an admin account. With a normal user you will get a "Review not found" message which sort of makes sense. 
I guess admins will more likely use Admin Tools to manage reviews, so probably they will not bump into this use case.

**Comment by bobsilverberg** [comment] 2018-09-20 12:41
Yes, I discussed this with @diox when I first noticed this, and we decided that we could keep this as a "hidden feature" for admins, giving them a way to see a deleted review via the frontend, rather than via the admin site. It does not affect non-admin users, so I'm going to close this issue.

**Closed by bobsilverberg** 2018-09-20 12:41 UTC
Labels: component: add-on ratings, priority: p1

**Comment by kumar303** [comment] 2018-09-21 19:34
It would be nice to put a banner saying that the review was deleted. I filed https://github.com/mozilla/addons-frontend/issues/6351 but it's low priority.
