### ISSUE TITLE
Featured extension shelf - valid extensions for Android are filtered out 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6652] opened 2018-10-16 14:32 UTC
STR:
1. Load AMO dev and observe the "Featured extension" shelf on android
2. From More menu click "Add-ons for Firefox" and refresh page (the refresh issue is filed [https://github.com/mozilla/addons-frontend/issues/6650](url)
3. Install extensions from this shelf on android such as this [one](https://addons-dev.allizom.org/en-US/firefox/addon/magic-actions-for-youtube-test/?src=featured) or this[ one ](https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/?src=featured)

Expected results:
The extensions installed should be available for android too while using the android filter https://addons-dev.allizom.org/en-US/android/

Actual results:
The extensions are not displayed in the Featured extensions shelf while the android filter is used.

Notes:
This issue is reproducible on AMO dev with FF62 - Android 8.0 & Win10

This is the android filter https://addons-dev.allizom.org/en-US/android/  
![android filter](https://user-images.githubusercontent.com/33448286/47023839-2e199580-d169-11e8-9af1-ff5eeae9f839.png)
 
And the shelf with Firefox filter https://addons-dev.allizom.org/en-US/firefox/
![ff filter](https://user-images.githubusercontent.com/33448286/47023893-5acdad00-d169-11e8-9768-3c6d4c7dfc61.png)

**Comment by AlexandraMoga** [comment] 2018-10-22 08:47
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/4084

**Comment by AlexandraMoga** [comment] 2018-10-22 08:47
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/4084

**Closed** 2019-01-08 13:45 UTC
Labels: platform: android, type: bug
