### ISSUE TITLE
AMO page for my add-on not available unless logged in

### ISSUE THREAD

**Issue by Shadoefax** [mozilla/addons-frontend#4902] opened 2018-04-30 21:53 UTC
### Describe the problem and steps to reproduce it:
I uploaded my new extension "Paste Email Plus for Quantum" to AMO a few days ago.  The URL for the extension is [https://addons.mozilla.org/en-US/firefox/addon/paste-email-plus-for-quantum/](https://addons.mozilla.org/en-US/firefox/addon/paste-email-plus-for-quantum/), but the page is only available when I am logged in to AMO.  If I am not logged in, a "Page not found" message is displayed.

I assume that if it is happening to me, it will happen to others that do not have an AMO account or are not logged in.

### What happened?
I get a "Page not found" message.

### What did you expect to happen?
A page to be displayed allowing me to install the extension.

### Anything else we should know?
On the _AMO Developer Hub > My Add-ons_ page, the status is "Awaiting Review", but on the _Developer Hub > Status & Versions_ page the status is "Approved".

More information on [Mozilla Discourse](https://discourse.mozilla.org/t/new-add-on-not-appearing-on-amo-unless-logged-in/28146)

**Comment by jvillalobos** [comment] 2018-04-30 23:06
The submission was auto-approved, but for some reason only the file was changed to `Approved`, while the add-on kept a status of `Awaiting Review`. That's what caused the listing to be invisible to anyone but the developer.

I fixed the status of the add-on, so it become visible shortly. I'd like to keep this issue open to investigate the cause of the problem.

/cc @wagnerand @diox

**Comment by wagnerand** [comment] 2018-05-02 09:29
@Shadoefax did you by any chance disable and re-enable a version in your developer hub?

**Comment by Shadoefax** [comment] 2018-05-02 12:57
No.  I didn't even know that was an option.

I did have to upload the extension two or three times (to fix minor validation errors), but after that it appeared to be published.

**Comment by diox** [comment] 2018-05-03 10:01
This add-on has now been rejected, which doesn't help figure out what was wrong originally...

**Comment by wagnerand** [comment] 2018-05-17 09:26
@conorgil Happy to help! could you please email amo-admins AT mozilla DOT org with a link to your add-on?

**Comment by conorgil** [comment] 2018-05-18 20:28
@wagnerand I think there is definitely a bug in the submission process. Just like @Shadoefax , I submitted an updated version of my extension and it magically "fixed" things. I didn't do anything else other than upload a new version.

So, it appears to be working for me now, but it seems there is some kind of systematic bug too. Let me know if I can help by providing info, etc.

The extension link is https://addons.mozilla.org/en-US/firefox/addon/2fa-notifier/

**Comment by diox** [comment] 2018-07-03 11:20
It looks like it's the same underlying issue as https://github.com/mozilla/addons-server/issues/6962

Essentially the hypothesis in that issue is that a task / cron re-saved the add-on just at the wrong time, overwriting the values set for `status` and/or `current_version`, leaving it in a weird state.

The fix for one of the tasks we noticed could cause this is going out this week. Closing this issue as a duplicate, if you can reproduce with a newly submitted version/add-on after this Thursday, please comment in the [addons-server issue](https://github.com/mozilla/addons-server/issues/6962).

**Closed by diox** 2018-07-03 11:20 UTC
Labels: state: duplicate
