### ISSUE TITLE
RSS feeds are returning 404

### ISSUE THREAD

**Issue by jmmerz** [mozilla/addons-frontend#7650] opened 2019-02-28 20:24 UTC
### Describe the problem and steps to reproduce it:

Try to download an RSS feed of extension updates from AMO. A few examples that worked until this morning:
* https://addons.mozilla.org/en-US/firefox/extensions/format:rss?sort=updated
* https://addons.mozilla.org/en-US/firefox/extensions/privacy-security/format:rss?sort=updated

### What happened?
The RSS feeds now return 404.

### What did you expect to happen?
Expected addons.mozilla.org to return a valid RSS feed.

**Comment by jvillalobos** [comment] 2019-02-28 20:47
Closing as a dupe of https://github.com/mozilla/addons-server/issues/7182

You can use the API to obtain this information: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html

In particular, [this extension](https://addons.mozilla.org/addon/latest-on-amo/) exemplifies how to use the API to display the latest extensions.

**Closed by jvillalobos** 2019-02-28 20:47 UTC
