### ISSUE TITLE
[suggestion] Rating stars look disabled

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3769] opened 2017-11-03 05:26 UTC
### Describe the problem and steps to reproduce it:
navigate to https://addons.mozilla.org/en-US/firefox/addon/pearltrees/reviews/
Observe the ratings given by user.

### What happened?
Rating stars have color `#737373`, this gives impression that it is disabled 

### What did you expect to happen?
Can be used a bright color like `#329AF0`

### Anything else we should know?
<img width="813" alt="screen shot 2017-11-03 at 10 52 06 am" src="https://user-images.githubusercontent.com/5318732/32361368-a8a7c916-c085-11e7-9b50-eea2c2e10676.png">

@pwalm

**Comment by muffinresearch** [comment] 2017-11-03 09:03
Duplicate of #3754

**Closed** 2017-11-03 09:03 UTC
Labels: state: duplicate
