### ISSUE TITLE
Add-ons collection is not updated until the page is not reloaded.

### ISSUE THREAD

**Issue by ShivangiKakkar** [mozilla/addons-frontend#5980] opened 2018-08-18 01:24 UTC
### Description:
Newly added add-ons dont show up in `View My Collection` till the page is reloaded.

### Steps to reproduce it: 
1.) Go to `View My Collections`.
2.) In your collection, you will have your added add-ons.
3.) Select one or more add-on & add it to your collection if you have one. Otherwise, make a new collection then add add-ons to it.
4.) You will see the no. of add-ons remain the same and the newly added add-on doesn't reflect in the add-on count untill you reload the page. Moreover, if you go inside a particular collection you won't see the newly added add-ons.

### What happened?
Add-ons or add-on count under `View My Collection` is not updated until we reload the page.

### What did you expect to happen?
It should update the collection without reloading the page.

### Anything else we should know?
Obviously, this doesn't happen for the very first time you run the app.

## First Step:
![webp net-gifmaker](https://user-images.githubusercontent.com/35342019/44294015-c51fb980-a2ae-11e8-9be0-0cb7c79ee276.gif)

## Second step:
![webp net-gifmaker 1](https://user-images.githubusercontent.com/35342019/44294119-d3220a00-a2af-11e8-9a8d-71837ba94c08.gif)

**Comment by ShivangiKakkar** [comment] 2018-08-18 14:34
@willdurand 
Do we need to do something else to work on this issue?

**Comment by willdurand** [comment] 2018-08-20 08:34
mmh I can't find it but I thought we fixed that already.. /ping @bobsilverberg

**Comment by AlexandraMoga** [comment] 2018-08-20 11:05
This issue is actually a duplicate of #5723

**Closed** 2018-08-20 12:00 UTC
Labels: state: duplicate
