### ISSUE TITLE
Keyboard navigation is not possible in search results or other pages where the recommended badge is present

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9152] opened 2020-02-11 13:41 UTC
STR:
1. Go to a See more... link, an add-on category, the profile page or a private collection where a recommended add-on is available. 
2. Press `Tab` and try to navigate in the list of add-ons.

Actual result:
It goes back and forth between the add-on name and the recommended badge. 

Expected result:
It jumps to the next add-on in the list. 

Notes: 
This issue is reproducible on AMO dev in search results which include see more links, add-on categories and also on the user profie or collections pages. 
It is not reproducible on AMO stage. 

AMO dev

![recommended badge problem1](https://user-images.githubusercontent.com/33448286/74241323-7193fd80-4ce4-11ea-8500-43a59e9b9a2c.gif)

AMO stage 

![AMO stage no problem](https://user-images.githubusercontent.com/33448286/74241472-c6d00f00-4ce4-11ea-9559-aa352c99a656.gif)

**Comment by mirefly** [comment] 2020-02-11 20:14
It looks like this is caused by the nested anchor tags which is[ not recommended by standard](https://www.w3.org/TR/REC-html40/struct/links.html#h-12.2.2). And FF could not handle this case well. I could not reproduce this bug in Chrome.

**Comment by bobsilverberg** [comment] 2020-02-11 20:28
Yeah, we shouldn't be nesting anchor tags. This has bitten us before. I didn't realize that that's what we had here. I guess we need to fix that.

**Comment by bobsilverberg** [comment] 2020-02-11 20:32
If we cannot figure out a good way to handle this, we might have to revert the changes made for https://github.com/mozilla/addons-frontend/pull/9096. That should never have been merged if it caused nested anchors, but I didn't realize at the time that it did. We might need a different solution to https://github.com/mozilla/addons-frontend/issues/8724, instead of trying to deal with the fallout after the fact.

**Comment by bobsilverberg** [comment] 2020-02-11 20:34
Do you have any ideas for resolving this, @mirefly, or do you think we should undo the changes from #9096 and start that one again from scratch?

**Comment by mirefly** [comment] 2020-02-11 20:57
@bobsilverberg I do not have good ideas to fix this issue from what we have now. Probably it is easier to undo changes from #9096 first.

[This example](https://stackoverflow.com/questions/5214363/alternative-to-nested-anchor-tags) may be a better way to fix #9096 without nesting anchor tags.

**Comment by bobsilverberg** [comment] 2020-02-12 11:51
I'm going to revert both the patch from #9096 and also your follow-up from #9147, which will no longer be needed after the revert of #9096, and then I'll reopen the issue from #8724.

**Closed** 2020-02-12 12:30 UTC
Labels: priority: p2, type: bug, type: regression

**Comment by ioanarusiczki** [comment] 2020-02-14 12:18
@bobsilverberg Verified on AMO dev with FF73(Win10). 

![Keyboard navigation works](https://user-images.githubusercontent.com/33448286/74531249-ccbc2f00-4f34-11ea-81cf-26d2a6f0c55d.gif)
