### ISSUE TITLE
"None" text listed for theme with no description

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2233] opened 2017-04-05 14:34 UTC
Steps to reproduce:

1. Load https://addons.allizom.org/en-US/android/ (or any version of AMO)
2. Search for a theme without a description. Example: search for 'Flag of France'
3. Tap the result to view the theme detail page

Expected results:
No text displayed in the "About this persona" section.

Actual results:
"None" text is displayed.

Notes/Issues:
* If you refresh the page while on the detail view, the "None" goes away

Verified on FF52(Win 7). Issue is reproduced all around AMO-servers.

![none](https://cloud.githubusercontent.com/assets/15685960/25942029/3742e18c-3644-11e7-91f9-158bd7b85e9f.gif)

**Comment by kumar303** [comment] 2017-04-05 15:27
Huh. That's really odd that only a device can reproduce this. Since it's `None` this is probably coming from the API response. Could you try turning on HTTP logging for Android so I can see the API response? I don't know if this works on Android or not but it's worth a try: https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging#Using_aboutnetworking

**Comment by ValentinaPC** [comment] 2017-05-11 09:22
I found something 💃 - while being on desktop with Mobile site view on or on device "None" option is removed after page refresh - this is why I somehow missed it on responsive design mode.
See video:
![none](https://cloud.githubusercontent.com/assets/15685960/25942029/3742e18c-3644-11e7-91f9-158bd7b85e9f.gif)

I've also tried the HTTP logging method. Will attach the .txt file.
[log1.txt-main.txt](https://github.com/mozilla/addons-frontend/files/992481/log1.txt-main.txt)

Sorry for the delay.

**Comment by kumar303** [comment] 2017-05-11 19:40
Thanks, this was really helpful. I assigned it to @tofumatt since he's worked on part of this before. The bug is caused by using state that was loaded from the search API result (which is different than state loaded from the add-on detail API result) but I didn't locate the exact cause when I glanced at it. 

@tofumatt we should probably try to make the detail page always behave in the same way to keep things sane and simple. Perhaps the detail component could always hit the API even though it will introduce a new API request.

**Comment by muffinresearch** [comment] 2017-06-14 16:42
This is still reproducible on -dev:
 
<img width="394" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/27144172-c6821878-5128-11e7-9c1d-cb0d7999bb9b.png">

**Comment by tofumatt** [comment] 2017-06-14 16:44
Same as #2569.

**Closed** 2017-06-16 16:38 UTC
Labels: component: ux, project: amo, project: mobile pages v1, state: pull request ready

**Comment by ValentinaPC** [comment] 2017-06-19 06:49
Verified as fixed on AMO-dev FF53(Android 7.1.2, Win 7)
Theme with no description will have no "About this persona" section.
Postfix screenshots: 
![desktop-mobile](https://user-images.githubusercontent.com/15685960/27272704-4ed8d7ee-54d4-11e7-9b7c-a8e8bff002fe.png)
