### ISSUE TITLE
Link on User Profile Page Leads to HTTP 404, Link:"My Favorite Add-ons"

### ISSUE THREAD

**Issue by peterfnet** [mozilla/addons-frontend#4001] opened 2017-11-28 20:55 UTC
### Describe the problem and steps to reproduce it:
1. Start by navigating to user profile page for current user; my profile that I used: `https://addons.mozilla.org/en-US/firefox/collections/peterfnet/`
2. In the left column, click on the link labeled "My Favorite Add-ons"; navigates to `https://addons.mozilla.org/en-US/firefox/collections/peterfnet/favorites/`

### What happened?
- Resulting page gave an error: "Page not - found"

### What did you expect to happen?
- I expected that I would be navigated to a page that includes a list of Add-ons I've used, rated, or commented on.

### Anything else we should know?
- That even though I am remote and distant, I care about you and your feelings. Hold me.

**Comment by kumar303** [comment] 2017-11-29 00:03
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/3884 which we chose not to fix since the concept of *favorites* are going away (all collections will be equal instead). However, the 404 is pretty confusing so we will be routing that URL to the classic site in https://github.com/mozilla/addons-frontend/issues/3888

> ... even though I am remote and distant, I care about you and your feelings

Thank you

**Closed by kumar303** 2017-11-29 00:03 UTC
