### ISSUE TITLE
Selecting a category from themes in home page does not return any results

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#1658] opened 2017-01-26 14:57 UTC
### Describe the problem and steps to reproduce it:
Navigate to https://addons-dev.allizom.org/en-US/android/ and select a category from themes.

### What happened?
The message “No results were found” is displayed.

### What did you expect to happen?
A list with themes for the selected category should be displayed.

### Anything else we should know?
Verified on FF50.1.0 (Android 7.1.1) in -dev server.
Here is a video: 
![video2](https://cloud.githubusercontent.com/assets/15885467/22367194/f91e3080-e488-11e6-8f65-2ddf32bf313f.gif)

**Comment by muffinresearch** [comment] 2017-02-08 17:56
Needs investigation might be a dupe.

**Comment by ValentinaPC** [comment] 2017-02-09 08:01
I've logged a dupe, sorry for that - https://github.com/mozilla/addons-frontend/issues/1723
I'll leave it on you guys to choose where to continue.
Thanks!

**Comment by tofumatt** [comment] 2017-02-09 14:54
Closing as a dupe of #1723, which I already marked as in-progress so I'll keep open 😄

**Closed by tofumatt** 2017-02-09 14:54 UTC
Labels: amo, mobile pages v1, needs info
