### ISSUE TITLE
No se encuentra el modulo

### ISSUE THREAD

**Issue by andymartinez21** [mozilla/addons-frontend#5517] opened 2018-07-06 20:36 UTC

**Comment by muffinresearch** [comment] 2018-07-09 08:17
This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services. 

From the description it's unclear what the issue is. Please can you provide as much information as possible so that we can understand what the issue is?

Please include screenshots and URLs so we know where on the website the problem is occurring.

I'm closing this for now but please re-open if you have additional information.

**Closed by muffinresearch** 2018-07-09 08:17 UTC
