### ISSUE TITLE
Show that an addon cannot be uninstalled

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1086] opened 2016-09-19 15:24 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1297028 has added a hint to tell that an addon cannot be uninstalled.

We need to add support for this and show a disabled state for installed to show in the UI  that the add-on cannot be uninstalled.

**Comment by muffinresearch** [comment] 2016-09-19 15:25
Relates to #959

**Comment by willdurand** [comment] 2019-08-05 12:43
marking this issue as duplicate of https://github.com/mozilla/addons-frontend/issues/8418

**Closed by willdurand** 2019-08-05 12:43 UTC
Labels: priority: p4, project: amo, triaged
