### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by gggustafson** [mozilla/addons-frontend#5831] opened 2018-08-02 17:04 UTC
On the page 

https://support.mozilla.org/en-US/questions/756226#answer-107517

the link 

BookmarksToolbars: https://addons.mozilla.org/firefox/addon/46159/

is broken.

**Comment by muffinresearch** [comment] 2018-08-02 17:08
Duplicate of https://github.com/mozilla/addons-frontend/issues/5830

**Closed by muffinresearch** 2018-08-02 17:08 UTC
