### ISSUE TITLE
Add-ons name is needed in "My reviews" on user profile page

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-frontend#7380] opened 2019-01-12 04:26 UTC
### Describe the problem and steps to reproduce it:
1. Open a user profile page to view, the UX like #4282.

### What happened?
It lists the user's reviews, which is useful. But when it's just a star rating (it's the default option for UX now), it looks like only one rating and relative time. Even if the review has content, the mentioned add-ons are often difficult to identify.

### What did you expect to happen?
Show the add-on name and its link (easy to share or open) for user's reviews.

### Anything else we should know?
![](https://user-images.githubusercontent.com/1769875/51069173-e66db180-1664-11e9-913f-44091c88a306.png)
![](https://user-images.githubusercontent.com/1769875/51069174-e79ede80-1664-11e9-91e4-af7b9514c6f1.png)

**Comment by mirefly** [comment] 2019-01-13 22:02
There was some discussion in #5469

**Comment by bobsilverberg** [comment] 2019-01-14 17:44
This looks like a duplicate of #5858

**Closed by bobsilverberg** 2019-01-14 17:44 UTC
