### ISSUE TITLE
Move `AddonReviewListItem` logic into the `UserReview` component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5598] opened 2018-07-13 19:49 UTC
The `AddonReviewListItem` and `UserReview` are similar. In fact, `AddonReviewListItem` relies on the `UserReview`, which is a "read-only" component to display user reviews. The `UserReview` component has been introduced in #5416 to avoid duplicate style, extracting style from `AddonReviewListItem`.

We could go a step further by merging both component, so that we can use the same component when displaying user reviews, no matter if we want read-only or read-write mode.

**Comment by kumar303** [comment] 2018-09-07 14:19
This is technically a dupe of https://github.com/mozilla/addons-frontend/issues/6104 now. Even though https://github.com/mozilla/addons-frontend/issues/6104 was filed later on, I'm going to keep that one open since it will help QA understand which pages to test for this change.

**Closed by kumar303** 2018-09-07 14:19 UTC
Labels: component: add-on ratings, component: code quality, priority: p4
