### ISSUE TITLE
Store collection add-on notes/comments in reducer state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4193] opened 2018-01-22 16:55 UTC
In order to display add-on comments (https://github.com/mozilla/addons-frontend/issues/3890) we need to store add-on notes in state.

They are currently ignored: https://github.com/mozilla/addons-frontend/blob/181b81e7e3e6c0e17da386558d8a8fb62ffe1c0d/src/amo/reducers/collections.js#L443

For QA: please test for any regressions in collection related pages (including the home page).

Collections tracker: https://github.com/mozilla/addons-frontend/issues/2782

**Comment by kumar303** [comment] 2018-03-16 19:36
Here's an idea for what the state change should look like:

```diff
diff --git a/src/amo/reducers/collections.js b/src/amo/reducers/collections.js
index 85c13ae86..d7a4a5230 100644
--- a/src/amo/reducers/collections.js
+++ b/src/amo/reducers/collections.js
@@ -241,6 +241,11 @@ export type ExternalCollectionAddon = {|
   notes: string | null,
 |};
 
+export type CollectionAddonType = {|
+  ...ExternalCollectionAddon,
+  addon: AddonType,
+|};
+
 type ExternalCollectionAddons = Array<ExternalCollectionAddon>;
 
 export type ExternalCollectionDetail = {|
@@ -521,12 +526,21 @@ export const deleteCollectionBySlug = (
   };
 };
 
+export const createInternalCollectionAddon = (
+  item: ExternalCollectionAddon
+): CollectionAddonType => {
+  return {
+    addon: createInternalAddon(item.addon),
+    downloads: item.downloads,
+    notes: item.notes,
+  };
+}
+
 export const createInternalAddons = (
   items: ExternalCollectionAddons
-): Array<AddonType> => {
+): Array<CollectionAddonType> => {
   return items.map((item) => {
-    // This allows to have a consistent way to manipulate addons in the app.
-    return createInternalAddon(item.addon);
+    return createInternalCollectionAddon(item);
   });
 };
 
```

**Comment by bobsilverberg** [comment] 2018-06-07 19:57
This is a duplicate of PR #5170

**Closed by bobsilverberg** 2018-06-07 19:57 UTC
Labels: component: collections, priority: p3, size: M, triaged
