### ISSUE TITLE
`yarn test` should test all the things

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2281] opened 2017-04-19 18:14 UTC
We use `yarn test` for day to day development. This runs the unit tests and wait for file changes. Let's enhance this command to also do the following when a file changes:

* Check for lint
  * The manual workaround for this is `yarn lint`
* check for Flow errors
  * The manual workaround for this is keeping another shell open with `yarn flow:dev`

**Comment by kumar303** [comment] 2017-04-19 18:15
We could also rename this to `npm start` if that's easier since we aren't really using that right now.

**Comment by aayushsanghavi** [comment] 2017-06-19 17:19
@kumar303 the linting part of this issue was fixed in #2583.
Do we need to check for flow errors in `yarn test`?

**Comment by kumar303** [comment] 2017-06-20 22:21
> the linting part of this issue was fixed in #2583.

That patch only added linting to `yarn test-once` which runs the entire suite an exits.

The `yarn test` command is more complex; it waits for files to change and then re-runs the tests. Ideally, I'd like that to check for lint and Flow errors when files change in addition to re-running tests. However, this may be tricky since we use [jest](https://facebook.github.io/jest/) to accomplish the watching and re-running. I did a quick google search and I don't even know if this is possible.

**Comment by aayushsanghavi** [comment] 2017-06-22 07:28
Oh, okay. I guess I wasn't careful in reading the issue and mistook it for `yarn test-once`. My bad 😅!

**Comment by willdurand** [comment] 2018-08-18 02:50
> However, this may be tricky since we use jest to accomplish the watching and re-running. I did a quick google search and I don't even know if this is possible.

I am wondering if we should spend time on this issue given that:

- `yarn test` runs the test suite, that makes sense and it is common (what I dislike is the `--watch` mode though)
- most of us have Flow (and maybe ESLint) integrated in their IDE (I have all of that and I use `vim` with very few plugins)
- Jest heuristic to re-run the tests is quite interesting and we might have to skip that if we want to trigger tests + lint + flow on source code changes

If we want a simple command for our contributors, we could add a `double-check` command though.

WDYT?

**Comment by willdurand** [comment] 2018-08-18 02:50
@kumar303 ^

**Comment by kumar303** [comment] 2018-10-15 20:14
Sorry, I missed this comment. I don't use editor integration for Flow and linting. I think `yarn test` (in watch mode) would be a good place to see lint errors, though. Not everyone is able or willing to configure their editor for these kind of things yet everyone can run `yarn test`. 

As a side note: I really don't have a good reason for not configuring my editor for Flow and linting; there are ten different ways to do it and I just haven't made time for it.

**Comment by willdurand** [comment] 2018-11-13 16:12
I tried to setup https://github.com/jest-community/jest-runner-eslint today, but this does not work. It will only lint the errors for the current focus test file, which is a common use case we have.

Here is my patch:

```diff
diff --git a/jest-runner-eslint.config.js b/jest-runner-eslint.config.js
new file mode 100644
index 000000000..5ae664394
--- /dev/null
+++ b/jest-runner-eslint.config.js
@@ -0,0 +1,6 @@
+// See: https://github.com/jest-community/jest-runner-eslint#options
+module.exports = {
+  cliOptions: {
+    config: `${__dirname}/.eslintrc`,
+  },
+};
diff --git a/jest.config.js b/jest.config.js
index eae3f8769..5d7b07c5b 100644
--- a/jest.config.js
+++ b/jest.config.js
@@ -1,4 +1,4 @@
-module.exports = {
+const defaultConfig = {
   collectCoverageFrom: ['src/**/*.{js,jsx}'],
   coveragePathIgnorePatterns: [
     '<rootDir>/node_modules/',
@@ -17,21 +17,14 @@ module.exports = {
     // Alias bin for bin scripts.
     '^bin/(.*)$': '<rootDir>/bin/$1',
   },
-  reporters: [
-    '<rootDir>/tests/jest-reporters/fingers-crossed.js',
-    '<rootDir>/tests/jest-reporters/summary.js',
-    '<rootDir>/tests/jest-reporters/flow-check.js',
-  ],
-  setupTestFrameworkScriptFile: '<rootDir>/tests/setup.js',
-  testPathIgnorePatterns: [
-    '<rootDir>/node_modules/',
-    '<rootDir>/(assets|bin|config|coverage|dist|docs|flow|locale|src)/',
-  ],
-  testMatch: ['**/[Tt]est(*).js?(x)', '**/__tests__/**/*.js?(x)'],
   // This will initialize the jsdom document with a URL which is necessary
   // for History push state to work.
   // See https://github.com/ReactTraining/react-router/issues/5030
   testURL: 'http://localhost/',
+  testPathIgnorePatterns: [
+    '<rootDir>/node_modules/',
+    '<rootDir>/(assets|bin|config|coverage|dist|docs|flow|locale|src)/',
+  ],
   transform: {
     '^.+\\.js$': 'babel-jest',
     // This transforms images to be a module that exports the filename.
@@ -39,13 +32,39 @@ module.exports = {
     '^.+\\.(jpg|jpeg|gif|png)$': '<rootDir>/tests/fileTransformer',
   },
   transformIgnorePatterns: ['<rootDir>/node_modules/'],
+  verbose: false,
+};
+
+module.exports = {
+  reporters: [
+    '<rootDir>/tests/jest-reporters/fingers-crossed.js',
+    '<rootDir>/tests/jest-reporters/summary.js',
+    '<rootDir>/tests/jest-reporters/flow-check.js',
+  ],
   watchPlugins: [
     'jest-watch-typeahead/filename',
     'jest-watch-typeahead/testname',
+    'jest-runner-eslint/watch-fix',
   ],
   watchPathIgnorePatterns: [
     '<rootDir>/bin/server.js',
     '<rootDir>/webpack-assets.json',
   ],
-  verbose: false,
+  // Projects can be used for configuring different runners. We configure the
+  // default runner for the `test` project and the `eslint` runner for the
+  // `lint` project.
+  projects: [
+    {
+      displayName: 'test',
+      ...defaultConfig,
+      setupTestFrameworkScriptFile: '<rootDir>/tests/setup.js',
+      testMatch: ['**/[Tt]est(*).js?(x)', '**/__tests__/**/*.js?(x)'],
+    },
+    {
+      displayName: 'lint',
+      ...defaultConfig,
+      runner: 'jest-runner-eslint',
+      testMatch: ['/**/*.js?(x)'],
+    },
+  ],
 };
diff --git a/package.json b/package.json
index 711664bbb..7f8872b2f 100644
--- a/package.json
+++ b/package.json
@@ -320,8 +320,9 @@
     "http-proxy": "^1.16.2",
     "intl": "^1.2.5",
     "intl-locales-supported": "^1.0.0",
-    "jest": "^23.1.0",
+    "jest": "^23.6.0",
     "jest-enzyme": "^7.0.0",
+    "jest-runner-eslint": "^0.7.1",
     "jest-watch-typeahead": "^0.2.0",
     "json-loader": "^0.5.4",
     "mock-express-request": "^0.2.0",
 
```

**Comment by willdurand** [comment] 2018-11-13 16:19
The patch above relies on Jest's `projects` feature, which can configure different projects (think monorepo) but it is also the recommended way to use a different runner. The problem is that the full test suite is run first, and then eslint is run. Therefore, `yarn test` takes more time to complete.

We should explore the reporter approach I think.

**Closed** 2018-11-19 19:30 UTC
Labels: component: code quality, priority: p4, qa: not needed, state: pull request ready, triaged
