### ISSUE TITLE
Redirect to seamonkey and thunderbird apps via user agent

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3728] opened 2017-10-31 21:14 UTC
### Describe the problem and steps to reproduce it:

* Set your user agent to that of seamonkey or thunderbird
* Load a page without an app, such as `https://addons-dev.allizom.org/en-US/`

### What happened?

You are redirected to `https://addons-dev.allizom.org/en-US/firefox/`

### What did you expect to happen?

* For a seamonkey user agent you should be redirected to `https://addons-dev.allizom.org/en-US/seamonkey/`
* For a thunderbird user agent you should be redirected to `https://addons-dev.allizom.org/en-US/thunderbird/`

### Anything else we should know?

* seamonkey and thunderbird URLs are still served from the legacy site: https://github.com/mozilla/addons-frontend/issues/3719
* As of https://github.com/mozilla/addons-frontend/issues/3678 the `addons-frontend` server will need to be in charge of redirects

**Comment by muffinresearch** [comment] 2017-11-01 08:47
Duplicate of https://github.com/mozilla/addons-frontend/issues/3719

**Closed by muffinresearch** 2017-11-01 08:47 UTC
Labels: priority: mvp-polish

**Comment by muffinresearch** [comment] 2017-11-01 08:51
@kumar303 not sure if this is at cross purposes with #3719, as that issue was about making sure SeaMonkey and Thunderbird UAs only ever see the legacy site not just based on paths - that was already in place.

Let me know if I've misunderstood anything.

**Comment by kumar303** [comment] 2017-11-01 14:35
@muffinresearch I'm confused. The STR up above on dev lands me https://addons-dev.allizom.org/en-US/firefox/ but it should land me at https://addons-dev.allizom.org/en-US/thunderbird/ (or seamonkey). With my patch it will do so.

**Comment by muffinresearch** [comment] 2017-11-01 16:55
We talked about this on irc, the confusion was caused by kumar's UA extension not setting the test UA  correctly.

**Comment by kumar303** [comment] 2017-11-01 19:15
Yeah, I was experiencing some kind of bug where the UA was not getting applied to the request. 

The clarification I was missing is that nginx *will* inspect the user agent. It always serves the legacy site to seamonkey/thunderbird UAs and the legacy site does redirects as expected.
