### ISSUE TITLE
Submitting an empty review should fail with an error

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1837] opened 2017-02-16 18:31 UTC
### Describe the problem and steps to reproduce it:
- go to an add-on detail page
- select a rating
- on the review entry page press the submit button without writing a review

### What happened?

The form closed without error

### What did you expect to happen?

It should show an error saying that you didn't actually write a review

Also, if you try to edit a review and make it empty you will see this error: "body: This field may not be blank.". I wanted to add that here so that we support the edit case when addressing this issue.

- go to an add-on detail page
- select a rating
- enter review text and submit
- back on the detail page, select a new star rating
- delete all review text
- try to submit the empty review

See https://github.com/mozilla/addons-frontend/issues/1837#issuecomment-288134811 for the proposal on what to do

**Comment by mstriemer** [comment] 2017-02-16 19:08
I thought the review body wasn't required. I find it odd that there's no "submit without comment" button or something.

**Comment by tofumatt** [comment] 2017-02-16 19:11
I think it's not required, but if you don't want to submit review text (body) then you should navigate back/out of the modal, rather than hitting "submit".

Though admittedly, it's weird to not hit "submit" on the modal. We should make sure it's clear the user can leave a star rating without text by not making the "back" on the review modal say "cancel". And that the stars are submitted regardless of body submission.

**Comment by mstriemer** [comment] 2017-02-16 19:14
I don't think "Cancel" is right though. Because it might seem like you are cancelling your entire review. "Skip" is probably less verbose without making it seem like no review will be submitted.

**Comment by tofumatt** [comment] 2017-02-16 19:15
> I don't think "Cancel" is right though. Because it might seem like you are cancelling your entire review. "Skip" is probably less verbose without making it seem like no review will be submitted.

Yeah, sorry, that's what I meant to say but failed to 😄

"Skip" is perfect, I was failing to find the right single word.

**Comment by muffinresearch** [comment] 2017-02-22 17:39
@pwalm what is the expected behaviour for this flow?

**Comment by pwalm** [comment] 2017-02-22 19:43
I can't actually leave a review, AMO mobile won't let me log in. But, here is what i've proposed:
<img width="581" alt="img_0026" src="https://cloud.githubusercontent.com/assets/6797635/23229006/826835c4-f8f3-11e6-9b7d-28d4c49ac508.PNG">

After rating, you are sent to "write a review", where a link at the bottom of the page will say "Submit a star rating without leaving a review." Tapping that will exit the review flow.

**Comment by kumar303** [comment] 2017-02-22 21:00
> AMO mobile won't let me log in.

Could you elaborate on that? Sounds like something we should address.

**Comment by pwalm** [comment] 2017-02-22 21:32
Lol yes

I go through the login flow, it sends me an email code to verify my login, I enter the code and it sends me back to the extension detail page. I try to leave a star rating and it tells me I'm not logged in.

**Comment by muffinresearch** [comment] 2017-02-23 19:31
@pwalm an issue with the link is it makes the function of the cancel button a bit ambiguous. 

I wonder if one possible way to step around that might be to have the rating click lead to the overlay (and not yet submit anything) and then the user can tweak their rating and optionally add a review. Submit saves the data, and then cancel will bail on the whole rating process. 

Would that work or would that lead to more people bailing on leaving anything?

Here's an example of what I mean:

<img alt="welcome_-_web_demo_project" src="https://cloud.githubusercontent.com/assets/1514/23275283/d495351c-f9fd-11e6-82a2-244b6a7df039.png">

**Comment by kumar303** [comment] 2017-02-23 19:59
> Would that work or would that lead to more people bailing without leaving any rating whatsoever?

Yeah, I'm afraid of this. I think psychologically it will be easier for someone to select a star rating vs. think up a coherent sentence explaining why they like/dislike the add-on. I would rather us capture that initial star rating instead of throwing it away.

**Comment by kumar303** [comment] 2017-02-23 20:07
> I go through the login flow, it sends me an email code to verify my login, I enter the code and it sends me back to the extension detail page. I try to leave a star rating and it tells me I'm not logged in.

Huh. I can't reproduce it on https://addons-dev.allizom.org/ . I used a new Firefox profile to make sure all cookies were cleared. I also tried verifying the account in a separate browser but each time I was logged in as expected and could enter a star rating.

**Comment by muffinresearch** [comment] 2017-02-23 20:09
> Huh. I can't reproduce it on https://addons-dev.allizom.org/ . I used a new Firefox profile to make sure all cookies were cleared. I also tried verifying the account in a separate browser but each time I was logged in as expected and could enter a star rating.

I think this may have been fixed by recent changes @mstriemer made to the way fxa is setup.

**Comment by tofumatt** [comment] 2017-03-21 16:25
We discussed this and I think a better UX would be that after clicking/submitting a star, a review textarea simply appears under the stars with a submit button and allows the user to submit their optional review text. The stars would have already been submitted. We'd ditch the modal so their review feels less disjointed and the text would feel optional.

Thoughts/does this make sense @pwalm?

**Comment by pwalm** [comment] 2017-03-23 15:41
That does make sense, although I thought we had moved away from that style of interaction? Happy to move back that way, I like it better than a modal.

**Comment by tofumatt** [comment] 2017-03-23 15:53
Hmmm, if we moved away from it I'm not sure why and when a few of us (@muffinresearch and @kumar303) chatted about it in London we agreed moving away from the modal would be better... so we'll try that.

**Comment by grahamperrin** [comment] 2017-11-02 18:50
Of course, I treated the ability to rate without writing as a feature :-)

**Closed** 2018-06-27 17:13 UTC
Labels: component: add-on ratings, priority: p3, project: amo, triaged
