### ISSUE TITLE
Downloads analytics

### ISSUE THREAD

**Issue by marataziat** [mozilla/addons-frontend#6737] opened 2018-10-24 12:51 UTC
### Describe the problem and steps to reproduce it:
Someone overcounted my downloads and as you see:
[Screenshot](https://i.imgur.com/JIp3Gnr.png)
These horizontal lines show 100-200 downloads on 30 Sep, but I have got only 5 downloads on this day :)

https://addons.mozilla.org/en-US/firefox/addon/charlesproxy4hackerone/statistics/?last=30

**Comment by jvillalobos** [comment] 2018-10-24 13:19
Closing as a duplicate of https://github.com/mozilla/addons/issues/820

**Closed by jvillalobos** 2018-10-24 13:19 UTC
