### ISSUE TITLE
Search suggestions are not displayed when performing a search

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#1730] opened 2017-02-07 13:21 UTC
### Steps to reproduce:
1. Open addons-dev.allizom.org on your Android device.
2. Tap the search field and enter some text.

### Expected results:
There are suggestions displayed under the search field.(https://mozilla.invisionapp.com/share/GY8O3Z4ZE#/screens/190292721) 

### Actual results:
No suggestions are displayed.

### Notes/Issues:
Verified in FF51(Android 7.1.1)
![screenshot_20170207-145244](https://cloud.githubusercontent.com/assets/15685441/22691959/70225200-ed45-11e6-8ce7-843ffbd08656.png)

**Comment by tofumatt** [comment] 2017-02-07 13:22
Autocomplete is not part of the mobile v1. Moved this to the v2 label for now.

**Comment by tofumatt** [comment] 2017-02-08 18:48
This is a duplicate of #1079.

**Closed by tofumatt** 2017-02-08 18:48 UTC
Labels: amo, mobile pages v2
