### ISSUE TITLE
Switch from isNaN to Number.isNaN

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4179] opened 2018-01-18 12:02 UTC
We should consider switching our use of the global `isNaN` to `Number.isNaN` - if we make this change we should make sure that we understand the subtle differences related to coercion in the global function in case we are currently reliant on that behaviour.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

See https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=isNaN&type= for all instances.

**Comment by KhushilMistry** [comment] 2018-01-22 04:36
Hey, I want to work on this issue.
Will make a pull request as soon as possible.

**Comment by muffinresearch** [comment] 2018-01-22 16:26
@KhushilMistry ok thank! I'll mark this contrib:assigned, please reference this issue in the PR.

**Comment by willdurand** [comment] 2018-01-22 16:35
@muffinresearch how does that `Number.isNaN` behave on the server?

**Comment by KhushilMistry** [comment] 2018-01-24 15:15
Hey, I have made a PR #4214. Can you review this ?

**Comment by tofumatt** [comment] 2018-01-24 15:18
> Hey, I have made a PR #4214. Can you review this ?

Sure thing, we get notifications of new PRs so someone from the team will take a look next chance we get. There's no need to notify us in the issue 😄

**Comment by kumar303** [comment] 2018-01-24 22:24
In all cases, we use `isNaN()` to check whether a string is numeric or not. On further inspection, `Number.isNaN()` is not intended for this case. It seems intended for checking if a value is literally `NaN`.

Actually, this led me to discover a bug: https://github.com/mozilla/addons-frontend/issues/4218

I'm closing this for now because I can't think of a case where we need `Number.isNaN()`.

**Closed by kumar303** 2018-01-24 22:24 UTC
Labels: component: code quality, contrib: assigned, triaged

**Comment by kumar303** [comment] 2018-01-24 22:41
Whoops, the bug I said I discovered was not a bug.

However, I think it would be risky to try and port some things to `Number.isNaN()` and not others. When glancing at our usage of `isNaN()`, it will only be safe to use `Number.isNaN()` in one case. Feel free to re-open if someone thinks we should still pursue it.

**Comment by willdurand** [comment] 2018-05-07 09:58
FWIW, Airbnb suggests to use `Number.isNaN` only: https://github.com/airbnb/javascript#standard-library--isnan.
