### ISSUE TITLE
Sometimes a saved star rating disappears

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1812] opened 2017-02-14 18:40 UTC
### Describe the problem and steps to reproduce it:

* Go to the add-on detail page
* Log in
* Rate the add-on for the first time
* Refresh the page

### What happened?

Sometimes the star rating you just entered does not appear. It may look like you had not actually rated the add-on.

### What did you expect to happen?

The saved star rating should always appear.

### Anything else we should know?

This is blocked on https://github.com/mozilla/addons-server/issues/3986

As a workaround, what we do is request [all user reviews](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews-by-a-user) and filter by add-on and version to find the one that matches. However, the current code does not use paging to find all results which is why the rating sometimes "disappears."

**Comment by kumar303** [comment] 2017-03-21 16:14
Fixed in https://github.com/mozilla/addons-frontend/issues/1838

**Comment by kumar303** [comment] 2017-03-21 16:15
for QA: this was pretty hard to reproduce to begin with (the add-on had to have had enough ratings to exceed the page size)

**Comment by ValentinaPC** [comment] 2017-03-22 11:58
I am still able to reproduce this on AMO-dev FF52(Android 6.0.1), intermittently.
Used add-on: https://addons-dev.allizom.org/en-US/android/addon/facebook-phishing-protector/?src=search
Video for this issue:
![videotogif_2017 03 22_13 56 07](https://cloud.githubusercontent.com/assets/15685960/24196730/9d3c25b6-0f07-11e7-918c-6d0cc616de33.gif)

**Comment by kumar303** [comment] 2017-03-22 17:42
This is probably the same as https://github.com/mozilla/addons-frontend/issues/2019 but I don't know if it's related to the original patch for #1812 or not yet.

**Comment by ValentinaPC** [comment] 2017-03-23 07:49
> This is probably the same as #2019 but I don't know if it's related to the original patch for #1812 or not yet.

In #2019 A review is dismissed, here, the review is made...until ...the end :)

**Comment by kumar303** [comment] 2017-03-24 10:14
> In #2019 A review is dismissed

Dismissing the text review doesn't matter because at that point the initial star rating selection has already been saved. You can submit the text review, cancel the text review, dismiss the text review, whatever -- when you refresh the page, and the same thing happens. The root cause is that the API response to show the saved star rating is cached too aggressively (https://github.com/mozilla/addons-server/issues/5006).

**Comment by muffinresearch** [comment] 2018-01-29 17:57
@vcarciu is this still an issue?

**Comment by vcarciu** [comment] 2018-01-30 12:51
@muffinresearch  : no, the issue is not reproducible anymore. We can close it.

**Closed by vcarciu** 2018-01-30 12:51 UTC
Labels: priority: p4, project: amo, project: mobile pages v1, triaged
