### ISSUE TITLE
PopUp Box not disappearing on clicking

### ISSUE THREAD

**Issue by ashigupta007** [mozilla/addons-frontend#4888] opened 2018-04-28 09:55 UTC
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/addon/tomlinson-designs-logo/?src=hotness
The popup created does not gets disappeared on clicking on left and right side but not on top and bottom.

### What happened?
the rate your experience popup box doesnot gets disappeared onclicking the left and right side of the popup box. but it does get disappeared on clicking on top and bottom side
### What did you expect to happen?
The popup must close if clicked outside the popup window.
![screenshot 2018-04-28 15 15 14](https://user-images.githubusercontent.com/26579662/39395121-5e26bcaa-4af8-11e8-8328-905cfa956d15.png)

### Anything else we should know?

Mentored by: @CuriousLearner @realslimshanky

**Comment by AlexandraMoga** [comment] 2018-04-30 06:03
Duplicate of #3691

**Closed by AlexandraMoga** 2018-04-30 06:03 UTC
