### ISSUE TITLE
Store auth token/payload in an `account` or `user` reducer

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1820] opened 2017-02-15 03:44 UTC
We need to display some information about the logged in user in the UI. Specifically in #1751, we'd like to display the username instead of the text **Log out** in `AuthenticateButton` when the user is logged in.

The auth token contains the user's email, user ID and username. That data should be parsed from the auth token and put into this reducer.

Blocks #1751, supports #1644.

**Comment by mstriemer** [comment] 2017-02-15 03:44
You can find some information on how to parse JWTs at https://jwt.io/.

**Comment by mstriemer** [comment] 2017-02-15 03:47
Actually we already have a function to [decode the user ID](https://github.com/mozilla/addons-frontend/blob/711bf11f5af28c8a0e0904bedfeecc9f299a5cc8/src/core/reducers/authentication.js#L10). That could be updated to return the username and email address too and then that could be hooked up to this reducer.

**Comment by kumar303** [comment] 2017-02-15 20:30
Yeah, it stores the [userId in state](https://github.com/mozilla/addons-frontend/blob/711bf11f5af28c8a0e0904bedfeecc9f299a5cc8/src/core/reducers/authentication.js#L38) so that could easily be extended to store user name / email.

**Comment by muffinresearch** [comment] 2017-03-21 16:17
This will be impacted by moving to an HMAC token.

**Comment by kumar303** [comment] 2017-05-11 15:37
This is a dupe of https://github.com/mozilla/addons-frontend/issues/1644 or at least they can be done at the same time

**Closed by kumar303** 2017-05-11 15:37 UTC
Labels: component: code quality, project: 2017 Q2, project: mobile pages v2, triaged
