### ISSUE TITLE
Texts and options etc are overlapping each other in AMO

### ISSUE THREAD

**Issue by alice0775** [mozilla/addons-frontend#7653] opened 2019-03-01 05:50 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

The problem is reproduced on Nightly67.0a1 and Firefos65.0.1 and Chrome as well

1. open https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/
2. Scroll down

### What happened?

Texts and options etc are overlapping each other

### What did you expect to happen?

Should display properly

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Screenshot: https://screenshots.firefox.com/DL6OGmhd5PpYS1oU/addons.mozilla.org

**Comment by willdurand** [comment] 2019-03-01 09:47
I can reproduce and this is a valid bug: I believe it is because of the user content that is rendered into this page. It looks like we produce invalid HTML...

**Comment by muffinresearch** [comment] 2019-03-01 12:42
Looking at dev tools it looks like there are two footers rendered.

![ublock_origin_version_history_-_25_versions_ _add-ons_for_firefox__en-us_](https://user-images.githubusercontent.com/1514/53638788-4fae8180-3c1f-11e9-85be-e6a5312c499f.jpg)

This doesn't appear to happen from client-side navigation.

**Comment by muffinresearch** [comment] 2019-03-01 12:52
I've also seen this on the details page.

**Comment by willdurand** [comment] 2019-03-01 15:23
> I've also seen this on the details page.

same, huh.

**Comment by muffinresearch** [comment] 2019-03-01 18:43
Looks like the details page issue is only seen when client-side navigating from a deep-linked all versions page, looks like the additional footer that has been rendered isn't removed which is why it's only seen occasionally.

**Comment by muffinresearch** [comment] 2019-03-01 18:47
I've updated the one release notes I found with a missing opening `<ul>` and that fixed it.

A lot of the release notes seems to have missing closing tags which the means it's reliant on those being added implicitly so we should file a follow-up to do a better job of ensuring valid HTML on the way in.

**Closed by muffinresearch** 2019-03-01 18:47 UTC
Labels: component: add-on versions, component: ux, priority: p1

**Comment by AlexandraMoga** [comment] 2019-03-04 10:18
The layout issues is fixed both on the versions and addon details pages.
