### ISSUE TITLE
It will not show me my theme collection

### ISSUE THREAD

**Issue by TherealDarkelegance** [mozilla/addons-frontend#7935] opened 2019-04-26 11:03 UTC
### Describe the problem and steps to reproduce it:

I started a new theme collection and it wont allow me to view or access it. It allows me to add to it but not access the collection

**Comment by jvillalobos** [comment] 2019-04-26 16:13
Can you post the link to the collection?

**Comment by TherealDarkelegance** [comment] 2019-04-26 18:09
How can I if it keep saying I can't view it???
That is literally the problem

________________________________

**Comment by jvillalobos** [comment] 2019-04-29 16:55
The URL of the page where you see the error message might be helpful

**Comment by willdurand** [comment] 2019-05-09 14:50
I am closing this issue for now until we can have more information (we can reopen the issue once we have more info). There is nothing we can do for now.

**Closed by willdurand** 2019-05-09 14:50 UTC
Labels: state: investigating

**Comment by TherealDarkelegance** [comment] 2019-05-09 16:20
I sent you the link he requested.
As stated, I add the themes to collection but it's not allowing me to view any of the themes! Now after I told him I really enjoyed my theme and didn't wish to lose it, it's wiped clean from my browser!


And you're telling me you aren't going to do anything??

________________________________

**Comment by willdurand** [comment] 2019-05-10 14:50
Sorry about that. Could you maybe give us your email address so that we can look at your profile?

**Comment by TherealDarkelegance** [comment] 2019-05-10 16:04
I'm literally writing from it. The previous guy asked for the link that I was having issue with,  I sent it. Them my theme which I loved got wiped.  Now this.

Are you having a laugh ??

________________________________

**Comment by jvillalobos** [comment] 2019-05-10 16:47
I don't see the link in this thread. Can you post it again?

**Comment by TherealDarkelegance** [comment] 2019-05-21 10:35
AGAIN...

https://addons.mozilla.org/en-US/firefox/collections/


________________________________

**Comment by jvillalobos** [comment] 2019-05-21 20:19
Thanks. So, on that page you see a list of your collections, right? And it's one of those collections that you can't access?

Can you click on the collection you can't access and share the link to that? The link to the All Collections page doesn't help us find the cause of the problem.

**Comment by TherealDarkelegance** [comment] 2019-05-21 21:15
I went to the link "view my collection" from the drop down menu and the link I provided it what I get!

No matter how many themes "I put in collection" each time I go to "view my collection" I get that error page.

What else can I show you?????
________________________________

**Comment by TherealDarkelegance** [comment] 2019-05-21 21:17
[cid:d55f3601-d41a-4186-98ea-81be8bdc5b8a]

T<http://art-of-darkelegance.daportfolio.com>HIS IS WHAT I GET WHEN I CLICK ON THE LINK OF "VIEW MY COLLECTION"
________________________________

**Comment by jvillalobos** [comment] 2019-05-21 21:26
If you click on View My Profile in the same dropdown, where does it take you? I can see if there's anything odd with your account.
