### ISSUE TITLE
License link doesn't show up when you go from the guides pages

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#7134] opened 2018-11-30 14:49 UTC
Depends on https://github.com/mozilla/addons-server/issues/10232

### Describe the problem and steps to reproduce it:
Go to the home page
Click to one of the guides pages
Click on one of the addons from the guides page
Notice there is no License link

### What happened?

When I access an addon via the guides page, I don't show the license link

### What did you expect to happen?
the license link should be there

//cc @bobsilverberg

**Comment by bobsilverberg** [comment] 2018-11-30 18:15
This sounds similar to the issue discussed at https://github.com/mozilla/addons-frontend/pull/7018#discussion_r236379495. I will look into it.

**Comment by bobsilverberg** [comment] 2018-11-30 19:30
Here's what's going on:

When the Guides page is loaded:

1. The `Guides` component dispatches the `fetchGuidesAddons` action, which calls the `fetchGuidesAddons` saga.
2. The `fetchGuidesAddons` saga uses the `Search` API to retrieve the add-ons, which are then loaded into state, which also loads the versions into state.

When the Add-on Detail page is loaded by clicking on a link:
3. In `mapStateToProps` it retrieves the add-on and version details from state. Because these were loaded during #2 above, a new fetch is not dispatched. This is contrary to what happens when the home page is loaded. When the home page is loaded the add-ons are not loaded into the addons reducer state, so when you click on an add-on from the home page a fetch *is* dispatched by the `Addon` component.

The problem is that the `Search` API, which is used in #2 above, does not return any license information, which means that the version loaded into state has a `license` of `null`. Because `fetchAddon` is not dispatched when navigating to the `Addon` component, this same version is used which results in there being no license link.

I'm not sure how to best deal with this. Here are some ideas/questions:
1. Should `Addon` always dispatch `fetchAddon` when it is first accessed from another component, even if the information for the add-on already exists in state? This might be difficult to accomplish.
2. Maybe `Guides` could use a different API to retrieve the add-on information, which includes the full `license` info? The problem is that the `Search` API returns `null` for license`. I'm not sure if another API currently exists to retrieve data for multiple add-ons but that also returns `license` info.
3. If such an API doesn't already exist, and we think that is the correct way to deal with this issue, then do we need another API, or can `Search` be changed to allow a consumer to request that `license` info be included?

This problem probably also affects `releaseNotes` as they are also excluded from the `Search` API.

**Comment by kumar303** [comment] 2018-11-30 20:10
Storing incomplete add-on / version objects in the same place as complete objects is confusing and leads to many subtle bugs. Here some ideas:


1. Keep letting the guides saga load incomplete add-ons / versions as it does now. On the add-on detail page, re-fetch the version if the one in state appear to be incomplete (i.e. missing `license` or `release_notes`). Since those two fields are optional it may get a bit tricky for empty values. We could probably use `null` to indicate that a license has been fetched and *does not* exist for the given version. This approach feels like it would be fragile since we'll have to guess about incompleteness. It may be an easy quick fix, though.

2. Store the incomplete parts of a version in separate state objects. For example, instead of storing [`PartialExternalAddonVersionType`](https://github.com/mozilla/addons-frontend/blob/63036238065a977e5b90e29e32532e55bcefadaa/src/core/reducers/versions.js#L65) and [`ExternalAddonVersionType`](https://github.com/mozilla/addons-frontend/blob/63036238065a977e5b90e29e32532e55bcefadaa/src/core/reducers/versions.js#L96) in the [same place](https://github.com/mozilla/addons-frontend/blob/63036238065a977e5b90e29e32532e55bcefadaa/src/core/reducers/versions.js#L114), lift the `license` and `release_notes` data into new state objects, keyed by version ID. This will make it easy for the add-on detail page to load: it will look to see if the add-on / version *and* license *and* release notes have already loaded. If not, it will re-fetch the add-on. This approach feels more robust but may require more effort.

**Comment by bobsilverberg** [comment] 2018-11-30 20:16
Thanks @kumar303. I figured I might as well document a third option which we discussed, which is probably not quite as good as #2 above, but better than #1.

Add an `isComplete` flag to `AddonVersionType` which indicates whether it is complete or not. Combine this with a new action to load an incomplete add-on, which would be called from any saga that knows it has incomplete add-ons (e.g., due to calling the `Search` API). Logic could then check this `isComplete` property to see whether an add-on needs to be re-fetched or not.

I do agree that #1 is probably the best short-term solution as it requires the least amount of changes/work and will fix the problem.

**Comment by rebmullin** [comment] 2018-11-30 21:54
Another approach, which I brought up here: https://github.com/mozilla/addons-server/issues/9765#issuecomment-431480159 is using the addons API (instead of the search API). I had different reasons for using this but ultimately it was voted against since you would be making 3 calls (vs 1) but this *might* be something to revisit because of the special circumstances here..?

Another thought...at one point there was a loadGuideAddons specifically for guides but it had some dupe work as `loadAddonResults` in the addons reducer and it was suggested I use that instead. Is it worth bringing that back if this is causing issues here?

I also like the idea of possibly having these in their own objects (no 2 above). I am not sure of the work involved there. It sounds like you might already know tho and are looking at shorter term solutions as a step towards this.

**Comment by bobsilverberg** [comment] 2018-12-11 17:52
@diox I was chatting with @rebmullin about this and I wanted to check one last thing with you before we proceed with a front-end fix. What do you think of the idea of adding a switch to the `Search` API which would allow a consumer to request that "full" add-ons be returned, as opposed to "partial" add-ons, which are what are currently returned and exclude `license` and `release_notes`? This would allow most uses of the Search API to behave exactly as they do now, and only if the `fullAddons` switch is turned on (and it would be off by default) would we be returning extra data.

I know we try to avoid adding all kinds of arbitrary switches to APIs, but a partial vs full switch seems like a pretty good idea to me, and won't really lead to a bunch of other switches being requested/required as we're not targeting specific fields.

Please let me know what you think.

**Comment by diox** [comment] 2018-12-12 17:21
The problem with that approach is that we do not have that info in our Elasticsearch index at all at the moment (and the search API avoids database entirely, it pulls all the data from the ES index). The reason why we don't have license text is that it can be quite big, and we have to handle potential translations, all that is a lot of data for not much benefit in the search API in the general case.

**Comment by bobsilverberg** [comment] 2018-12-12 17:32
Thanks @diox. I'm not sure if it helps, but we don't actually need the license text. It's okay to leave that out as we do for all add-ons. We just need the other license fields (`name`, `url`, `is_custom`) and the `release_notes`. Is that doable, or are we missing some of that info in ES?

**Comment by diox** [comment] 2018-12-12 18:08
We're still missing... well, of of those really. But without the license text it's a lot more doable. I wouldn't mind adding those 3 license fields, even include them in all search results. The releases notes is a little more annoying, but we can probably live with it, especially if it's not returned for every search and behind a query parameter. Can you file an addons-server issue ? I'll get it done before the first push next year.

**Comment by bobsilverberg** [comment] 2018-12-17 15:06
Thanks @diox. I have opened https://github.com/mozilla/addons-server/issues/10232.

**Comment by bobsilverberg** [comment] 2019-01-14 21:07
I believe this was fixed via https://github.com/mozilla/addons-server/issues/10232

**Closed by bobsilverberg** 2019-01-14 21:07 UTC
Labels: component: add-on, priority: p3, type: bug

**Comment by AlexandraMoga** [comment] 2019-01-16 14:20
Verified fixed on AMO -dev with FF64, WIn10x64

![2019-01-16_16-14-59](https://user-images.githubusercontent.com/31961530/51254812-88193980-19aa-11e9-9b30-f455c754491d.gif)
