### ISSUE TITLE
Android users visiting `/firefox/` pages get enabled Install buttons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6136] opened 2018-09-04 19:49 UTC
This might be a duplicate, but I couldn't find it. It came up again in [this Discourse thread](https://discourse.mozilla.org/t/amo-allowing-mobile-installation-when-it-is-not-marked-as-compatible/).

The problem is that Android users may end up on a `/firefox/` link on AMO because that's how it's generally linked to online. When a `/firefox/` page is visited on Android, the Install button is enabled even if the add-on is not compatible.

Maybe we should redirect Android users to `/android/`, or make the buttons check for device compatibility regardless of the platform in the URL, or both.

**Comment by muffinresearch** [comment] 2019-04-10 15:50
@jvillalobos The button being enabled when incompatible definitely sounds like a bug that we should fix.

For the other part, we generally don't second guess users based on URL parameters. Whether that's client application or locale.

One way we could deal with this is to set a banner to inform the user they're viewing a page that doesn't match their platform. They would then have the option to follow a link to see the same page for the correct client application or optionally we could also add a cookied "don't show this again" to not ever show that banner again whilst the cookie is present.

**Comment by jvillalobos** [comment] 2019-04-10 16:31
Fixing the install button and adding the banner sounds like a good approach to me.

**Comment by sneakypete81** [comment] 2019-10-07 17:19
This is still an issue: https://addons.mozilla.org/en-GB/firefox/addon/update-scanner/ shows an install button on Android, despite the add-on being marked as incompatible.

**Comment by jvillalobos** [comment] 2019-10-07 20:36
Just added this to a Q4 project related to this problem. It's a secondary goal, so it's okay to drop if there isn't enough time to cover it.

**Closed** 2019-11-12 17:01 UTC
Labels: platform: android, priority: p3, triaged

**Comment by sneakypete81** [comment] 2019-11-12 20:44
@bobsilverberg thanks for looking at this. Unfortunately the recent changes haven't fixed this issue. I now see the yellow warning when browsing the amo/firefox section, but the "Add to Firefox" button is still enabled. The install button should always be disabled on the Android platform if the addon is not compatible with Android.

STR:
* In the developer hub, observe that the addon has only been listed for Firefox, not Firefox for Android:
   <img width="480" alt="image" src="https://user-images.githubusercontent.com/38854/68708429-9664c180-058b-11ea-8070-4946fe622ae4.png">
* On an android device, visit https://addons.mozilla.org/firefox/addon/update-scanner.

Expected behaviour:
* "Add to firefox" button disabled and warning displayed.

Actual behaviour:
* "Add to firefox" button enabled and warning displayed ("This listing is not intended for this platform. Browse add-ons for Firefox on Android)

**Comment by bobsilverberg** [comment] 2019-11-12 20:49
@sneakypete81 This fix has not been deployed to production yet. The fix should be there after the push on Thursday, November 14th, which happens around noon EST.

**Comment by sneakypete81** [comment] 2019-11-12 21:56
Ah, ok. Thanks, I'll be patient!

**Comment by ioanarusiczki** [comment] 2019-11-13 11:45
@bobsilverberg Verified on dev with FF68.2.0 (Android 8.0)
The button is disabled. 

![the button is inactive](https://user-images.githubusercontent.com/33448286/68760987-c6f43c00-061b-11ea-86d7-4d5d4e625eba.png)
