### ISSUE TITLE
Use Redux to change overlay state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1708] opened 2017-02-04 02:45 UTC
### Describe the problem and steps to reproduce it:

Hide / show an [Overlay](https://github.com/mozilla/addons-frontend/blob/master/src/ui/components/Overlay/index.js) like `overlay.hide()` or `overlay.show()`

### What happened?

It toggles the overlay using internal component state

### What did you expect to happen?

It should dispatch an action and use Redux state instead

### Anything else we should know?

Redux all the things! This will let us:
* time travel while debugging
* extract a complete state tree of user actions when debugging a problem
* understand how UI state changes across our entire app using lots of awesome redux devtools

**Comment by muffinresearch** [comment] 2017-03-21 15:48
Dupe of #1250

**Closed by muffinresearch** 2017-03-21 15:48 UTC
Labels: component: code quality, triaged
