### ISSUE TITLE
Red error messages are displayed for a second when returning to an extension detail page - intermittent

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6633] opened 2018-10-15 14:05 UTC
STR:
1. Load AMO dev and login with an admin or developer account (I tested with both types)
2. Go to the detail page of a submitted add-on 
3. Click on the name of the author to see open the user profile page
4. Click the back button

Expected results:
The add-ons detail page is displayed

Actual results:
For a short while some red error messages are visible on the detail page.

Notes:
Please note that the issue is intermittent, I could reproduce it more easily on AMO dev than on AMO stage with two accounts I'm frequently using for testing so in order to observe this issue you must click on the author's name multiple times and then click the "back" button. 
Reproducible on AMO dev with FF662 - Win 10

Example
![error occured intermittent issue1](https://user-images.githubusercontent.com/33448286/46955786-6c954e80-d09c-11e8-9fee-ccabc6b17c2c.gif)

**Comment by kumar303** [comment] 2018-10-17 22:39
This is happening because you are navigating very quickly and the browser has aborted one of the requests (which is what the error is about). It's also a dupe of https://github.com/mozilla/addons-frontend/issues/5392 so I'm closing it. I don't think this is likely to happen in real site usage.

**Closed by kumar303** 2018-10-17 22:39 UTC
Labels: component: landing pages, type: bug
