### ISSUE TITLE
[layout issue]Unauthorized addon should give 404 error

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3212] opened 2017-09-22 15:54 UTC
### Describe the problem and steps to reproduce it:
Navigate to https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/

### What happened?
Gives not found page

### What did you expect to happen?
Empty blank blocks

### Anything else we should know?
The API gives 403 error.
Can be treated same as #3061 
Produced on dev server(didnt find 403 addon on production server)
<img width="1274" alt="screen shot 2017-09-22 at 9 19 49 pm" src="https://user-images.githubusercontent.com/5318732/30753235-53f4e99a-9fdc-11e7-96dc-5f620ee05d45.png">

**Comment by muffinresearch** [comment] 2017-09-22 17:04
Dupe of #2769

**Closed by muffinresearch** 2017-09-22 17:04 UTC
