### ISSUE TITLE
Adding new dictionary points to invalid place.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [mozilla/addons-frontend#7660] opened 2019-03-02 14:21 UTC
### Describe the problem and steps to reproduce it:

Link in context menu is pointing to invalid place.
![obraz](https://user-images.githubusercontent.com/27734421/53683239-ccfcf380-3cfe-11e9-993c-3301dc503bef.png)

### What happened?

I've been redirected to 404 page.

### What did you expect to happen?

I wanted to add new dictionary for spellchecking.

**Comment by AlexandraMoga** [comment] 2019-03-04 08:07
Thanks for the report. This is, however, a duplicate of https://github.com/mozilla/addons-frontend/issues/7658

**Closed by AlexandraMoga** 2019-03-04 08:07 UTC
