### ISSUE TITLE
Number of reviews is not incremented after review submission

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3904] opened 2017-11-14 13:09 UTC
Steps to reproduce:

1. Go to an add-on details page on AMO-dev (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/vertical-tabbar/)
2. Observe the current number of reviews available in the rating and statistics section
3. Navigate to the rating section and submit your own review
4. Notice again the number of reviews available for this add-on

Expected result:
Number of reviews is incremented by 1 in both mentioned sections

Actual result;
Number of reviews remains unchanged

Notes: this issue also affects unrated add-ons as for these cases the add-on appears to have no written reviews even after the 1st review is submitted; the number of reviews is not incremented in "All reviews' page either
Not sure if this is a regression from [#2327](https://github.com/mozilla/addons-frontend/issues/2327#event-1339087541) or [#6761](https://github.com/mozilla/addons-server/issues/6761#issuecomment-343995592)
Reproduces on AMO-dev with FF56 (Win 10)

![reviews issue](https://user-images.githubusercontent.com/31961530/32781311-3f6ff59c-c94d-11e7-895d-9f5cd03a3424.gif)

**Comment by kumar303** [comment] 2017-11-16 16:06
This is caused by an issue with the API: https://github.com/mozilla/addons-server/issues/6942

**Comment by kumar303** [comment] 2017-11-16 16:22
We located the root cause. This is a dupe of https://github.com/mozilla/addons-server/issues/6942 -- you can follow that issue to know when the fix will be on dev. This blocks release so it will go out in today's deploy. Thanks for catching this! It was a serious issue.

**Closed by kumar303** 2017-11-16 16:22 UTC
Labels: component: add-on ratings, project: amo, project: desktop pages, state: blocked, triaged

**Comment by AlexandraMoga** [comment] 2017-11-17 09:24
Verified as fixed on all AMO servers with FF57 (Win 10 and Android 7.0)

![fix_reviews](https://user-images.githubusercontent.com/31961530/32939940-cd0f4400-cb89-11e7-8d49-6b0974452ce7.gif)
