### ISSUE TITLE
The landing page for Cookies link won't display its header

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4289] opened 2018-02-01 09:18 UTC
Steps to reproduce:
1. Load AMO stage and go to Footer section.
2. Click on Cookies.
3. Observe the landing page.

Expected results:
The header of the page and the red title "Websites, Communications &Cookies Privacy Notice" are displayed.

Actual results:
The middle and the footer of the page is displayed.

Notes:
This issue is reproducible on all AMO servers, using FF58 (Win 10, Android 8.0.0)

![cookies link](https://user-images.githubusercontent.com/33448286/35670481-62f16b2c-0741-11e8-8499-36878d69552e.gif)

**Comment by tofumatt** [comment] 2018-02-01 10:02
The link goes to the cookies section directly (see the link: `https://www.mozilla.org/privacy/websites/#cookies`) and it puts the cookies bit at the top of the page, but because this page is minimal enough we could probably link to the top.

**Comment by tofumatt** [comment] 2018-02-01 10:05
Actually, we link to the privacy policy page in the footer as well. Linking to it again with different text would be weird. I'm gonna close this as working as intended.

**Closed by tofumatt** 2018-02-01 10:05 UTC
Labels: component: homepage, priority: p4, project: amo, size: S, type: bug
