### ISSUE TITLE
New add-on version will not display a user rating/review assigned to a previous version

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4529] opened 2018-03-09 15:39 UTC
STR:

1. Log in to AMO and pick an extension to view its details page
2. Write a review for this add-on and make sure your review is posted
3. Submit a new version for this extension and approve it
4. Go to add-on details page again and check the rating section

Actual result:
There is no record of a previous rating left by your user (stars are not colored)

Expected result:
A user rating assigned to a previous version should not be cleared when a new add-on version is submitted (stars should be colored)

Notes: 
- if the user goes to add-on reviews page, he can see that a review he previously posted is listed
- reproduced on all AMO servers with FF58 WIn10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/37215496-c2c75b6a-23c0-11e8-8b68-173a326886d4.png)

![image](https://user-images.githubusercontent.com/31961530/37215331-5464241e-23c0-11e8-8e68-779c5193e42a.png)

**Comment by muffinresearch** [comment] 2018-06-27 17:52
@jvillalobos is this expected/by design?

**Comment by jvillalobos** [comment] 2018-06-27 21:35
No, we shouldn't be filtering ratings by version.

**Comment by bobsilverberg** [comment] 2018-08-24 14:53
I'm not sure how we should address this. We currently record ratings/reviews for a particular add-on version. Is this issue suggesting that we want to stop doing that, and only have one review per add-on per user (i.e., not one review per version)? 

@jvillalobos @kumar303

**Comment by jvillalobos** [comment] 2018-08-24 16:31
> only have one review per add-on per user (i.e., not one review per version)?

That's what I think we should do, yes.

**Comment by bobsilverberg** [comment] 2018-08-24 16:45
I think this will mostly need to be dealt with on the back end then, although our code will have to change to not submit/request a version any longer.

@diox What do you think?

**Comment by kumar303** [comment] 2018-08-27 15:53
The backend API is designed for one review per version. We may be able to workaround this structure on the frontend, I'm not sure.

**Comment by kumar303** [comment] 2018-08-27 15:59
Related: we have some dead code that used to support the case of editing a review for a previous version. It no longer works and is not covered by any tests. https://codecov.io/gh/mozilla/addons-frontend/src/76640e28035b1581096b49ac6064cef37635ad4f/src/amo/components/RatingManager/index.js#L129

Fixing the code I pasted up above is not trivial. I'm just posting it here for reference.

**Comment by bobsilverberg** [comment] 2018-08-27 16:00
I think it would be best to deal with it on the backend, which is why I pinged @diox. If we have to deal with it on the frontend we might be able to do that, but we should investigate a backend fix first, imo.

**Comment by kumar303** [comment] 2018-08-27 16:04
What I meant was that the backend and frontend may be able to change independently, i.e. the frontend may not need to wait for any backend changes here.

Going from one review *per version* to one review *per add-on* should be easy on the frontend since it's less granular. No API constraints will get in our way. We just have to update our query for fetching the existing review and we'll need to decide how to deal with multiple reviews for one add-on.

**Comment by diox** [comment] 2018-09-06 17:38
Please file an addons-server issue for this if we want to remove the per-version thing. Although @kumar is right to say you don't stricly need backend support for this and can just not query per version, there are some optimizations and constraints we could change to support this on addons-server.

**Comment by bobsilverberg** [comment] 2018-09-10 17:46
I opened https://github.com/mozilla/addons-server/issues/9393 to request this change be implemented on the server side. If that isn't something that is possible in the near term we may still consider doing this on the front end, but there are other higher priority issues right now.

**Comment by kumar303** [comment] 2018-09-10 17:46
Primarily, we want to stop making saved reviews disappear when developer's publish new add-on versions.

We can maybe do a quick fix for this on the frontend by calling [`getReviews()`](https://github.com/mozilla/addons-frontend/blob/38cd4d9ddea5d601854a7828982d5104d9ff4793/src/amo/api/reviews.js#L210) without `version` then sorting the results in descending order (by version number) to display the latest saved review.

**Closed** 2018-11-06 15:17 UTC
Labels: component: add-on ratings, needs: discussion, priority: mvp, priority: p3

**Comment by AlexandraMoga** [comment] 2018-11-07 12:18
Verified fixed on AMO -dev with FF63, Win10x64

![2018-11-07_13-55-58](https://user-images.githubusercontent.com/31961530/48131097-8e4ab580-e297-11e8-996a-05ff7a252379.gif)
