### ISSUE TITLE
Add static version of the Primary Hero content ahead of data driven version

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8247] opened 2019-07-03 22:15 UTC
Part of [this PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#).

Immediately below the header in the AMO homepage (only the desktop version, under `/firefox/`), show a large promotional module for one extension: 

<img width="1864" alt="61815619-92792c00-ae42-11e9-9483-d2e852e5d1e7_png__PNG_Image__1866 × 929_pixels_" src="https://user-images.githubusercontent.com/1514/61817785-3e247b00-ae47-11e9-94e5-b9dbe2adfa72.png">

The URL for the button should have `src=homepage-first-shelf`, and an event should be logged on GA when it's clicked, recording a click on the first shelf and the extension that was on the shelf.

This will be completely hardcoded with no randomization and will eventually be replaced by a data-driven version. 

**Ship date is expected for September 17 at the earliest**

- This should be behind a flag. Please check before enabling on the 8th that it should be enabled.

@devaneymoz and @brassy- to provide:

## Primary Shelf

* Top text *Note: the text at the top should read "Recommended", not "Recommendation".*
* Heading
* Description
* Button copy 
* Button Link
* Image 
* Overlay shape (see the bottom left corner of the example).
* Gradient stops.

### Other open questions

* Where should this content be placed on the homepage and is this instead of the other primary content we currently have or does it replace part of it?

This content will be provided via a doc @jvillalobos will link to as the content is not public yet.

**Comment by jvillalobos** [comment] 2019-07-12 20:49
Closing in favor of https://github.com/mozilla/addons-frontend/issues/8305, since it looks like we'll be able to do both this quarter.

**Comment by muffinresearch** [comment] 2019-07-24 17:36
Re-opening this since we're going to need to get a static version shipped sooner to meet a new deadline.

**Comment by kumar303** [comment] 2019-07-24 19:16
> This content will be provided via a doc @jvillalobos will link to as the content is not public yet.

@jvillalobos what's the plan for L10n? I see an [idea here](https://docs.google.com/a/mozilla.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit?disco=AAAADQxh0kk) but that's outside of our normal L10n flow.

**Comment by muffinresearch** [comment] 2019-07-24 19:21
@kumar303 If the content is landed as hard-coded content it will be handled as per normal addons-frontend l10n processes. Naturally, at that point we'll need to be ok with the content being public.

**Comment by kumar303** [comment] 2019-07-24 19:22
OK, then I will assume it is acceptable that the content will be public before launch.

**Comment by devaneymoz** [comment] 2019-07-24 19:27
By when do we need final copy for the hard-coded content?

**Comment by muffinresearch** [comment] 2019-07-24 19:40
> OK, then I will assume it is acceptable that the content will be public before launch.

@kumar303 Yeah the only other option I see is to use un-translated placeholders and leave the real copy to the last minute, but that would limit translations in advance. @jvillalobos @devaneymoz should be able to advise on where we'll stand with making the content + copy public to get this landed.

**Comment by muffinresearch** [comment] 2019-07-24 19:41
> By when do we need final copy for the hard-coded content?

@devaneymoz ASAP, though see above the questions/comments re: making the copy public. The copy will be public as soon as it's pushed up here for review even if it's not initially on the site until configured to be live.

**Comment by jvillalobos** [comment] 2019-07-24 19:47
I created [this doc](https://docs.google.com/document/d/1KaOneS2w0E4NS7kc5DmXQRlBUNRPCm-6-JP-d6KfRl0/edit#) to keep track of the content before it needs to be published.

**Comment by devaneymoz** [comment] 2019-07-24 22:03
Final copy is in the [doc](https://docs.google.com/document/d/1KaOneS2w0E4NS7kc5DmXQRlBUNRPCm-6-JP-d6KfRl0/edit#).

**Comment by jvillalobos** [comment] 2019-07-29 20:00
I updated the launch date for Sept 17, based on current information. I believe this still means we'll need the static version, since time is still short, but the urgency drops quite a bit. Apologies for the scramble!

**Comment by kumar303** [comment] 2019-07-29 20:29
No problem. At least we'll get a jump on it. My current plan is to continue landing the PR since it's already gone through one round of review. It will be hidden behind a flag and I replaced all copy with placeholders, as you can see in the screenshots: https://github.com/mozilla/addons-frontend/pull/8400

Even if we never ship a static version (only a dynamic one) it will make the development process easier if we land this static version first.

**Closed** 2019-07-30 15:43 UTC
Labels: component: add-on recommendations, component: homepage, priority: p3

**Comment by AlexandraMoga** [comment] 2019-07-31 11:08
I've verified the new homepage hero on -dev, mostly in terms of its layout and format and less for its contents (which are only placeholders atm)

The  hero is responsive to various screen sizes and text orientations. 

I've also reproduced the small glitch @willdurand mentioned in https://github.com/mozilla/addons-frontend/pull/8400#issuecomment-516420446 when the page is in rtl mode at ~470px:

![image](https://user-images.githubusercontent.com/31961530/62207089-f26c5700-b39b-11e9-9048-94c2a6ef41fa.png)

However, the issue from https://github.com/mozilla/addons-frontend/pull/8400#issuecomment-516418457 did not reproduce for me.

**Comment by kumar303** [comment] 2019-07-31 15:05
@AlexandraMoga can you file an issue for the RTL small screen glitch? I'll see what I can do. Thanks.
