### ISSUE TITLE
Increased 500 errors after 2019.02.14-2 release

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#7597] opened 2019-02-15 03:26 UTC
### Describe the problem and steps to reproduce it:
We have seen increased 500 errors after 2019.02.14-2 release. Please see the sceenshot below:

![image](https://user-images.githubusercontent.com/2209111/52832422-4fde4700-308d-11e9-80ad-78786c65bfc7.png)

Even thought the absolute rate (<0.06 per second) seems to be low, but it is considered 3 times more than before. So unless something has changed and this is expected, this much increase is definitely an indication of some issue.

### What happened?
We are not sure yet. Operation conditions haven't changed for this release. And the increase of 500 happened immediate after the push finishes (judging by the time on the screenshot).

The `disco-recommendations` waffle was enabled for this release, but not sure it's related or not.

### What did you expect to happen?
If the increase of 500 is not expected due to some code changes, we should probably figure out a way to reduce it to its normal level.

### Anything else we should know?
n/a

**Comment by diox** [comment] 2019-02-15 12:39
Looks like it's https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/5219460/?query=is:unresolved

**Comment by willdurand** [comment] 2019-02-15 13:08
The 500 error is caused by an error in the `NotFound` component (404 error page). This error comes from a localized string that has two sets of `linkStart/linkEnd` parameters:

```
"%(linkStart)sextensions%(linkEnd)s or %(secondLinkStart)sthemes%(secondLinkEnd)s."
```

The locale file contains a translated string that is valid (according to our linter) but the sets are inverted:

```
"%(secondLinkStart)stemas%(secondLinkEnd)s ou %(linkStart)sextensões%(linkEnd)s disponíveis."
```

I believe it does not really matter to have the first link before or after the second link, especially for this particular case **but** our code should be able to deal with that, i.e. it should not throw an error and ideally use the localized string no matter the order of these sets of link parameters.

**Comment by willdurand** [comment] 2019-02-15 13:09
I opened a PR to fix the locale file: https://github.com/mozilla/addons-frontend/pull/7598.

Let's try to fix our code now...

**Comment by willdurand** [comment] 2019-02-15 15:40
@bqbn we can push a hotfix if you want to reduce the number of 500. The patch is harmless given that it is a locale file that has been fixed.

**Comment by willdurand** [comment] 2019-02-15 16:41
This would be the commit to cherry-pick as a hotfix: https://github.com/mozilla/addons-frontend/commit/05b8987c5ec67b5169dabbb135cb2a0a40e239e4 (cc @kumar303)

**Comment by bqbn** [comment] 2019-02-15 16:53
I think next week is fine now that we've identified the issue and have a fix.

Next, can QA help re-produce this in -stage and verify the fix before pushing it to -prod?

**Comment by kumar303** [comment] 2019-02-15 18:31
@willdurand thanks for the quick fix

> The 500 error is caused by an error in the `NotFound` component
> ...
> https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/5219460/?query=is:unresolved

Sigh, yeah. We decided to throw an error there because the way it relied on slicing made the code very delicate. It's probably still a good idea to throw but I'm not sure.

**Comment by AlexandraMoga** [comment] 2019-02-18 07:30
I've navigated around various pages on AMO stage using `pt-BR` but I haven't run into 500 errors. I'm not sure how else I should try to reproduce the issue.

**Comment by willdurand** [comment] 2019-02-18 08:16
@AlexandraMoga could you try a page that returns a 404? Like an add-on detail page with an non-existent slug.

**Comment by AlexandraMoga** [comment] 2019-02-18 08:42
@willdurand thanks for the tip. I was able to reproduce the 500 error on stage with multiple pages that should be returning a 404 instead. 

The issue looks fixed on -dev.

**Comment by willdurand** [comment] 2019-02-19 15:18
> Sigh, yeah. We decided to throw an error there because the way it relied on slicing made the code very fragile. It's probably still a good idea to throw but I'm not sure.

It is even more fragile with two links in the same string 😞  I am not sure what to do here to be honest, I spent some time trying to find a better way to handle two links into a string, but I don't like the code I wrote for that.

I also think we should `throw` (as it is currently). Yet, I believe the i18n linter catches issues when a `linkStart` or `linkEnd` is missing. It did not catch any issue here because there is no issue with the localized string itself, it is the code that deals with the two links that is problematic. Maybe we should just detect which link comes first 🤷‍♂️

**Comment by kumar303** [comment] 2019-02-20 17:47
To recap, the quick fix preventing 500s landed in https://github.com/mozilla/addons-frontend/pull/7598

The next step is to try and come up with a way to prevent this kind of localization problem from occurring again.

**Closed** 2019-04-11 08:51 UTC
Labels: component: i18n, component: static pages, priority: p3, state: pull request ready

**Comment by kumar303** [comment] 2019-04-11 20:19
Could you add some steps for QA? I think it's just a matter of checking for regressions in some localizations.

**Comment by willdurand** [comment] 2019-04-11 20:30
ah, I forgot to update this issue. I'll add a quick not related to the `NotFound` component, thanks!

**Comment by ioanarusiczki** [comment] 2019-04-17 09:03
@willdurand I verified on both AMO stage and AMO prod for 500 errors for Not Found- 404 pages in the `de`, `pt-BR` and `en-US` but I couldn't generate a 500. 
Verified with FF66(Win10).
