### ISSUE TITLE
Make l10n comments to every string or related group of strings obligatory

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozilla/addons-frontend#3790] opened 2017-11-06 09:47 UTC
AMO Frontend is growing and deciding where exactly a string is shown the UI becomes difficult. The last few batches of strings made this even more complicated because they contained a lot of new strings from different areas.

For proper translation the localizer have to know the context of the string at hand. No string in AMO Frontend provides localization note or other context meaningful information. To better illustrate the issue will use this example string: https://pontoon.mozilla.org/en-GB/amo-frontend/all-resources/?string=173274

> I can see that this string is in some menu by the path to its invocation `(#: src/amo/components/FlagReviewMenu/index.js:116)`. That means it should be possibly shorter. It is related to a flagged something. From what I know previously it is possible to be related to flagged user review. Am I right? I don't know. Have to check with the site. And have to setup the test environment. Flag a review etc, etc.
> This is because I know or can recall what I've translated before for this project. What about the new localizers that doesn't have this knowledge?

Localizer should not be forced to go to the site to check up the context. Please provide a meaningful localization notes for every string or related group of strings. This note should contain explanation as to how the string is used, where in the UI and any other specifics that may influence the l10n process (probably very vague expression). This way the localizer can focus on l10n rather than checking with the site every few strings.

Keep in mind that l10n is voluntary and every effort in reducing the time needed for l10n process is very much appreciated by the l10n community.

**Comment by muffinresearch** [comment] 2017-11-08 14:58
Duplicate of https://github.com/mozilla/addons-frontend/issues/2307

**Closed by muffinresearch** 2017-11-08 14:58 UTC
