### ISSUE TITLE
The uninstall option is available in "Get Add-ons" page for a "requires restart" add-on that was previously removed from "Extensions" tab

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2119] opened 2017-03-21 14:48 UTC
From https://github.com/mozilla/addons-server/issues/4659

Prerequisites:
- disco pane is set to point -dev

Steps to reproduce:
1. Install a "requires restart" add-on from Add-ons Manager - Get Add-ons page i.e. Video DownloadHelper
2. Restart the browser to apply changes
3. Go to "Extensions" tab and click "Remove" button
4. Go to "Get Add-ons" - refresh the page
5. Click the switch button to uninstall the add-on

Expected results:
User is not able to click the switch button because of a green banner that displays a message that you need to restart the browser to apply changes.

Actual results:
User can click the switch button and receive an error message "An unexpected error occurred during uninstall."

Notes/Issues:
- reproducing only for "requires restart" add-ons
    
Verified on FF55(Win 7).
Video for this issue: 
![error](https://cloud.githubusercontent.com/assets/15685960/24152939/c219d16a-0e55-11e7-94fa-61f8916a211e.gif)

**Comment by muffinresearch** [comment] 2017-03-21 17:40
I think this might be just out of date content, because dev has very old versions of some add-ons that are buggy.

**Comment by ValentinaPC** [comment] 2017-03-22 10:19
> I think this might be just out of date content because dev has very old versions of some add-ons that are buggy.

I almost sure that this will reproduce in production too, If we would have "requires restart" add-ons in about:addons.

**Comment by muffinresearch** [comment] 2017-03-22 10:53
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/580

**Closed by muffinresearch** 2017-03-22 10:53 UTC
Labels: project: disco pane, triaged

**Comment by muffinresearch** [comment] 2017-03-22 10:55
> I almost sure that this will reproduce in production too, If we would have "requires restart" add-ons in about:addons

@sdevaney do we ever have content in the disco pane that requires restart?

**Comment by devaneymoz** [comment] 2017-03-22 16:02
@muffinresearch No, never. Never will.
