### ISSUE TITLE
Use ImmutableJS for Redux state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6103] opened 2018-08-29 15:10 UTC
**For QA**: please check for regressions on the following pages: *TBA*

The Redux pattern only fully works if the state object is 100% immutable. Usually we are pretty good about this and can catch mistakes in code review but mistakes still creep in (see https://github.com/mozilla/addons-frontend/issues/6102). 

Let's remove the cognitive burden of looking for mistakes and just use ImmutableJS, which will throw an error for any accidental mutation.

https://redux.js.org/recipes/usingimmutablejs

There are some downsides that we should consider -- outlined in the article above.

**Comment by willdurand** [comment] 2018-09-05 09:18
> Immutable.JS works best for collections of data, and the larger the better. It can be slow when your data comprises lots of small, simple JavaScript objects, with each comprising a few keys of primitive values.

🤕 it does not look like a good fit for us...

If the issue is about removing `delete` calls in the reducers (which is clearly a programming mistake, partly due to JavaScript being a bad programming language), we could probably use ESLint instead/only?

**Comment by kumar303** [comment] 2018-09-05 19:12
Yes, I think we could use a lint rule to discourage `delete` usage but there are other referencing issues that can pop up, too. If you copy an object and re-assign one of its properties then you might be editing the old state tree as well. Maybe we just need to get better about reviewing reducer code but I worry that it will be hard to catch all mutation mistakes.

**Comment by willdurand** [comment] 2019-07-05 10:21
While this might be a good idea, I don't think we'll realistically implement this so I am going to close this issue for now. We can still reopen it if needed.

**Closed by willdurand** 2019-07-05 10:21 UTC
Labels: component: code quality, priority: p3, triaged
