### ISSUE TITLE
Exact matches are not displayed higher than other results

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#3853] opened 2017-11-09 09:41 UTC
Steps to reproduce:
1.Go to AMO homepage https://addons.allizom.org/en-US/firefox/ using FF58
2. Type "Adblock Plus" in the search field
3. Observe the search suggestions from the  drop down list

Expected results:
Exact matches are displayed higher than other results.

Actual results:
Exact matches are not displayed higher than other results.

Notes/Issues:
Verified on AMO-stage FF58(Win 10)
Screenshot for this issue:
![screenshot 9](https://user-images.githubusercontent.com/33448286/32598522-ab0cda40-c542-11e7-94fb-598e464277e3.png)

**Comment by muffinresearch** [comment] 2017-11-09 10:24
@ioanarusiczki thanks for the bug report. This looks to be a duplicate of https://github.com/mozilla/addons-server/issues/6837 - I'll add a note re: this being about search suggestions too to make sure it's covered.

**Closed by muffinresearch** 2017-11-09 10:24 UTC
Labels: state: duplicate
