### ISSUE TITLE
Stop using UTM params for internal tracking

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10272] opened 2021-03-25 15:13 UTC
In https://github.com/mozilla/addons-frontend/issues/9547 we switched from using the custom `src` param to UTM to track attribution for add-on downloads. It turns out that internal use of UTM can have a negative impact on internal GA data and could also impact search crawlers.

One option is to go back to using `src` for internal links, and another Raphael suggested is to use a `#` fragment instead. Whatever solution we come up with, we should make sure that it doesn't change the way downloads are counted. We'll still tell developers to use UTM for external referral, so if our internal links use `src=something`, that should be the equivalent of using `utm_source=addons.mozilla.org&utm_medium=referral&utm_content=something` in the download records.

**Comment by bobsilverberg** [comment] 2021-03-25 17:29
We should document here all of the reasons that we need UTM params currently. One has to do with Firefox and add-on installs, and @willdurand is going to update the issue with that information.

**Comment by jvillalobos** [comment] 2021-03-25 21:38
1. We use UTM to keep track of external sources linking to AMO. So, if devs are linking to their add-on listing pages, we want them to use UTM so we know how much they contribute to AMO traffic.
2. Those params are passed along to the download URL and are [recorded in telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1653020), which is then used to generate the download stats on AMO. It's possible we need to change something in Firefox for that to continue working with whatever we use for internal links (or maybe convert back to UTM for the download URL path?).

**Comment by willdurand** [comment] 2021-03-27 23:01
Some more information about UTM params for **internal** tracking:

- The number of sessions counted increases artificially, because every click on an internal link with UTM parameters results in a new session.
- A conversion can no longer be traced back to the original, external source of the traffic, because the new session uses the source and medium information from the UTM parameters, which makes it more difficult to quantify the contribution of various external traffic sources to your conversions.
- If a new visitor clicks on an internal link with UTM parameters right on the landing page, this immediately results in a new session. The upshot of this is that the bounce rate for visitors from external sources increases artificially.

Source: https://www.smashingmagazine.com/2017/08/tracking-internal-marketing-campaigns-google-analytics/

The following article seems to imply that any UTM param can start a new session: http://www.kotaraindustries.com/2018/10/google-analytics-campaign-based-session-expiration/, which is related to [some official docs](https://support.google.com/analytics/answer/2731565?hl=en).

**Comment by bobsilverberg** [comment] 2021-03-29 23:38
Thanks for the info, @willdurand. That seems to confirm what Raphael had told us. You were going to add something specific about what Firefox needs in order to record the correct info in telemetry. My (possibly flawed) understanding from the conversations is that Firefox needs these UTM params to exist on the URL when the add-on is installed. Is that accurate? Is there another way for AMO to pass the values of these UTM params to Firefox without having them present on the URL?

**Comment by willdurand** [comment] 2021-03-30 07:20
> Thanks for the info, @willdurand. That seems to confirm what Raphael had told us. You were going to add something specific about what Firefox needs in order to record the correct info in telemetry. My (possibly flawed) understanding from the conversations is that Firefox needs these UTM params to exist on the URL when the add-on is installed. Is that accurate? Is there another way for AMO to pass the values of these UTM params to Firefox without having them present on the URL?

Indeed, FF records the UTM parameters present in the URL of the page during the install flow, and they are available in Telemetry _via_ the `install_stats` event. There is currently no other way to pass these UTM params to FF.

**Comment by bobsilverberg** [comment] 2021-03-30 12:57
> > Thanks for the info, @willdurand. That seems to confirm what Raphael had told us. You were going to add something specific about what Firefox needs in order to record the correct info in telemetry. My (possibly flawed) understanding from the conversations is that Firefox needs these UTM params to exist on the URL when the add-on is installed. Is that accurate? Is there another way for AMO to pass the values of these UTM params to Firefox without having them present on the URL?
> 
> Indeed, FF records the UTM parameters present in the URL of the page during the install flow, and they are available in Telemetry _via_ the `install_stats` event. There is currently no other way to pass these UTM params to FF.

I'll see if I can test whether us adding the URL params to the page *after* the navigation has happened will still create a new session. If it will not, then perhaps that's something we can do for now, but also investigate changing Firefox so we can provide that data in another manner.

**Comment by bobsilverberg** [comment] 2021-04-07 16:29
We discussed this in the standup today and the feeling is that we'd prefer to move these utm params into a fragment, and have Firefox updated to utilize them from the fragment instead of requiring URL params.

**Comment by willdurand** [comment] 2021-04-07 16:37
> We discussed this in the standup today and the feeling is that we'd prefer to move these utm params into a fragment, and have Firefox updated to utilize them from the fragment instead of requiring URL params.

Does that mean we want to prevent these utm params from being collected by GA?

Do we still need to support utm params in the query string? These will be collected by GA.

We will need to request an uplift for ESR. Also we should think about the impact such a change in FF will have (in terms of supported versions but also code).

In any case, the best short term solution is to remove the utm params on our internal links.

**Comment by bobsilverberg** [comment] 2021-04-08 19:55
I did a bit of digging and it doesn't look like simply moving the params into the fragment will work at all. GA will still interpret those as utm params and therefore start a new session. I think we need to take a closer look at where we are using utm params for internal links and why we are doing that. What problems are we trying to solve with that technique (other than the FF attribution issue)? This should be the starting point of further conversation.

**Comment by bobsilverberg** [comment] 2021-04-12 12:51
Ok, it sounds like simply removing them from internal links for now is what we should do, but we also need to figure out a long-term solution. @willdurand as the person who worked on the stats portion, do you have any suggestions for how we might approach this long-term?

**Comment by willdurand** [comment] 2021-04-12 12:56
> Ok, it sounds like simply removing them from internal links for now is what we should do, but we also need to figure out a long-term solution. @willdurand as the person who worked on the stats portion, do you have any suggestions for how we might approach this long-term?

I don't know yet, I'll think about it.

A quick question, though: if we want to keep utm params for download stats but don't want to use them in our own GA, then could we strip the utm params before sending the url to GA?

**Comment by bobsilverberg** [comment] 2021-04-12 13:50
> > Ok, it sounds like simply removing them from internal links for now is what we should do, but we also need to figure out a long-term solution. @willdurand as the person who worked on the stats portion, do you have any suggestions for how we might approach this long-term?
> 
> I don't know yet, I'll think about it.
> 
> A quick question, though: if we want to keep utm params for download stats but don't want to use them in our own GA, then could we strip the utm params before sending the url to GA?

We don't "send" the url to GA, per se, GA observes a user's navigation on our site, based on the URLs that they visit, so there isn't really an opportunity to strip them from the URL before sending to GA, unless I am misunderstanding what you are asking. There are some `events` that we send to GA, but I believe those are outside the scope of what we're concerned with in this issue.

**Comment by willdurand** [comment] 2021-04-12 14:04
> We don't "send" the url to GA, per se, GA observes a user's navigation on our site, based on the URLs that they visit, so there isn't really an opportunity to strip them from the URL before sending to GA, unless I am misunderstanding what you are asking. There are some `events` that we send to GA, but I believe those are outside the scope of what we're concerned with in this issue.

We don't? https://github.com/mozilla/addons-frontend/blob/577cdf2d8b846a21990264bc676b34848bc6d244/src/amo/client/base.js#L65-L71

**Comment by bobsilverberg** [comment] 2021-04-12 14:11
Ah, I forgot about that. I thought that simply including the GA code on each page was what was allowing GA to track page views, but apparently not. Let me give that a try.

**Comment by bobsilverberg** [comment] 2021-04-12 15:52
@willdurand This is quite confusing. In our call to `tracking.pageView`, we're using the value `location.pathname` for `page`, and `location.pathname` doesn't include URL params. As well, the data we send to GA in the beacon does not include any utm params. Here's an example:

```
v=1&
_v=j89&
a=364015569&
t=pageview&
_s=14&
dl=http%3A%2F%2Flocalhost%2Fen-US%2Ffirefox%2Fextensions%2F&
dp=%2Fen-US%2Ffirefox%2Faddon%2Fterms-of-service-didn-t-read%2F&
ul=en-us&
de=UTF-8&
dt=&
sd=24-bit&
sr=1500x900&
vp=1500x900&
je=0&
_u=SACAAEABAAAAAC~&
jid=&
gjid=&
cid=453297148.1618240203&
tid=UA-36116321-7&
_gid=928744072.1618240203&
cd3=addons-frontend&
cd4=TAAR_COHORT_INCLUDED&
cd5=TAAR-LITE-AB&
z=1524599184
```

but looking at the data recorded in GA, I can see that we are capturing the utm params for `source`, `medium` and `content`, so it's a bit of a mystery how this is all working (and I think this led to my belief that it was via a mechanism not under our control).

I'll do a bit more digging, but it doesn't look like there is a way to change our existing code for pageViews that you linked to above to exclude this data, as we aren't currently including it.

**Comment by willdurand** [comment] 2021-04-12 16:09
So I would think that we only track utm params on page loads, i.e. when we first land on AMO, which is likely what we want.

**Comment by bobsilverberg** [comment] 2021-04-12 16:34
Ah, the data I was looking at, that looked like we were sending `utm_content`, was actually for `localhost`, so any page refresh which already had utm params would show up in GA. Looking at the data on prod, it does look like `utm_content` is only being populated from links from outside of the site, and that we do not record it for any of the internal links. I suppose that means that we don't actually have a problem with this at all, provided all of these internal links are client-side navigation (which they should be).

Do you concur, @willdurand?

**Comment by bobsilverberg** [comment] 2021-04-12 20:11
I looked at all of the places we're adding utm params to links in addons-frontend, and documented them in a [Google Doc](https://docs.google.com/document/d/1tiym4jJBHOjK-tRYK3_lVmluF-A9auicBq3ytQ1nVnA/edit?usp=sharing). It looks like everywhere we are adding utm params to internal links, those links are also client-side links. Based on the discussions of the past few comments, I don't think that having utm params on internal links is harmful if they are only for client-side navigation, as they shouldn't be sent to GA in that case. That would make this issue invalid, at least for the case of creating new GA sessions.

The crawl budget issue still exists, but I'm not sure how critical that is. We should bring all of this up for discussion in the next SEO meeting.

**Comment by willdurand** [comment] 2021-04-14 15:48
> Do you concur, @willdurand?

I do!

**Comment by bobsilverberg** [comment] 2021-04-14 19:31
I have confirmed that we are not sending utm params to GA for any of our internal links, therefore the "new session" issue does not exist for us. The reason we aren't sending utm params is that we are not sending *any* URL params to GA, and that may not have been intentional. We may want to send *some* URL params to GA to aid in site analysis. For example, I don't think we have any data on what search terms users are using on our site, because we never send the `q` URL param to GA.

I assume we haven't seen a need to do any analysis on any of the data that is transmitted in URL params, which is why this hasn't come up in the past. It may be that we'll never need to do this, but if we do find a time in the future where we want to start capturing URL params, then we need to be careful not to send any utm params to GA.

I'm going to leave this issue open until our next SEO meeting, but it's possible we'll be able to simply close it after a bit more discussion. We might need a separate issue opened about how URL params are affecting our crawl budget.

**Comment by bobsilverberg** [comment] 2021-05-06 17:04
As per all of the discussion above, I am going to close this issue.

**Closed by bobsilverberg** 2021-05-06 17:04 UTC
Labels: component: analytics, component: homepage, needs: discussion, priority: p3
