### ISSUE TITLE
Usage of addon.type in "About this ADDONTYPE" means we show internal add-on types on the page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2567] opened 2017-06-13 23:57 UTC
### Describe the problem and steps to reproduce it:
We use `addon.type` at https://github.com/mozilla/addons-frontend/blob/093abd393b85d5f64761f0facf782198863221ac/src/amo/components/Addon/index.js#L250 and this leads to us showing text like "About this persona" rather than "about this theme".

We actually have a function already that takes API addon type and converts it to user-facing text in the Rating component (https://github.com/mozilla/addons-frontend/blob/790d7db747fd33f69ec84e2b3e93fff3ffd219e2/src/amo/components/RatingManager/index.js#L122) so we should abstract that functionality out into a utility function and use it here.

Or just have another switch case, which might make more sense for localisers.

### What happened?
Showed "persona" in the user-facing text.

### What did you expect to happen?
Showed "theme" in the user-facing text.

### Anything else we should know?
<img width="309" alt="screenshot 2017-06-14 00 53 09" src="https://user-images.githubusercontent.com/90871/27109714-6ad90ac2-509c-11e7-8a33-de8376c7623a.png">

**Comment by muffinresearch** [comment] 2017-07-11 17:16
Related to https://github.com/mozilla/addons-frontend/issues/2705

**Comment by muffinresearch** [comment] 2017-07-11 17:17
Marking as a dupe of #2705

**Closed** 2017-07-25 17:13 UTC
Labels: contrib: maybe good first bug, project: amo, state: duplicate, triaged
