### ISSUE TITLE
Pages stuck in "loading" mode when an error is thrown

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3313] opened 2017-10-02 16:27 UTC
When we use a `loading` flag in a reducer and the API layer throws an error (e.g. 400 or 404), then the redux state keeps `loading` set to `true`, which results in a page stuck in "loading" mode sent by the server.

For instance, here is a search result that throws a 400: https://addons.allizom.org/en-US/firefox/search/?platform=pouet&q=ad&type=extension. We do not get any error displayed and the page does not look nice. In #3268, I implemented a similar mechanism that should render a `NotFound` component when a 404 error is caught. Yet this does not work either.

Note: This does not seem to be the case when SSR is disabled.

**Comment by kumar303** [comment] 2017-10-02 17:02
For handling unexpected errors (likely a 500), see https://github.com/mozilla/addons-frontend/issues/2905

**Comment by muffinresearch** [comment] 2017-10-03 13:03
Here's an example of what it looks like for https://addons.mozilla.org/en-US/firefox/search/?platform=bogus


<img width="1452" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31126272-1df6b1d8-a843-11e7-9eec-ed11ee32b0fd.png">**

**Comment by muffinresearch** [comment] 2017-10-03 13:04
If this is linked to directly then it's something we should fix pre-release. If it's an edge case we might be able to de-prioritise it for post-release.

**Comment by kumar303** [comment] 2017-10-04 16:37
Why is this marked as MVP? Would a user ever see this broken loading state by using the site in a normal fashion?

**Comment by tofumatt** [comment] 2017-10-04 16:41
It's rendering the wrong page (eg not an error page) on the server, which seems bad. I just went to a 404 add-on and it seemed to send it down in a loading state then change to 404 once the client render happened.

**Comment by kumar303** [comment] 2017-10-04 16:43
Yes but you only encounter a 404 through atypical usage. I agree we should fix it but I don't see a case for marking this as an MVP bug.

**Comment by willdurand** [comment] 2017-10-04 16:51
I have downgraded this issue but marked it as "priority: post release" because I think we should care about errors (a lot) and I think it also impacts our productivity (I spent some time fighting with the error handler).

**Comment by willdurand** [comment] 2017-10-04 17:02
One more thing (well many more actually):

- the error handler does not generate the same IDs between the client and the server, resulting is a different state. This is not nice because it means we are not consistent between the server and the client. Most of our error handling code (like rendering an error) is framed upon the state. Yet, because the client and server states are different, the app behaves in a weird manner.

- we do not handle all the errors equally and it is not consistent when we have to deal with special errors (status codes: 401, 403, 404 for instance). I think the HOC should be responsible for dealing with these particular errors but I am not sure how.

**Comment by kumar303** [comment] 2017-10-04 17:06
> the error handler does not generate the same IDs between the client and the server, resulting is a different state.

That may be a more serious bug. Could you make sure something is on file (with STR) where it bites us? The only cases I know of are not serious because the client re-runs the loading code and ultimately shows the right error.

**Comment by willdurand** [comment] 2017-10-04 17:24
> That may be a more serious bug. Could you make sure something is on file (with STR) where it bites us? The only cases I know of are not serious because the client re-runs the loading code and ultimately shows the right error.

I think it is a problem everywhere we use the following pattern:

- a loading flag is stored in the reducer state
- `dispatch` is not triggered if `loading` is set to `true`
- `NotFound` component is rendered in the component `render()` by introspecting the `errorHandler` instance
- we have to deal with `4xx`

Example:

- the collection view with an invalid collection (private or nonexistent), but it is fixed by this hack: https://github.com/mozilla/addons-frontend/blob/f5d4c80024200a9b0b01b614343412ec30c8f2da/src/amo/components/Collection/index.js#L200-L206
- the search results with a bogus query parameter

Stating this, I am wondering if I did not shoot myself in the foot. I guess fixing this problem would prevent the client to re-run the code.

**Comment by kumar303** [comment] 2017-10-23 15:06
I've been thinking we just need to go through all components and make them render errors *instead* of content. Right now, most components render their error at the top of the content. There will be a few exceptions mostly around form controls.

**Comment by willdurand** [comment] 2017-10-24 13:11
Not sure I understand @kumar303 I get a bit stuck on this issue, because there are a few things I dont fully understand I guess, but it seems your last comment implies an easy solution..

**Comment by kumar303** [comment] 2017-10-24 19:29
I don't know of an easy solution to the problem where the error handler ID is different on the server vs. client.

I was saying that one easy fix is to stop mixing loading content with error content. We should just display the error.

To illustrate it, we current do this a lot:

```js
render() {
  return (
    <div>
      {errorHandler.renderErrorIfPresent()}
      <SomeContent loading={!content} content={content} />
    </div>
  );
}
```

But perhaps this would be better:


```js
render() {
  if (errorHandler.hasError()) {
    return errorHandler.renderError();
  }
  return (
    <div>
      <SomeContent loading={!content} content={content} />
    </div>
  );
}
```

However, this might be a moot point if we can't sync error IDs between client and server. However, it's worth pointing out that the search page loading logic [is just flawed](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Search/index.js#L61). This is one reason why it doesn't render an error. 

If it were written correctly then the flow would look like this: 1) server renders, loads data, and encounters an error; 2) client renders, sees that it does not have data and does not have an error (because of the ID bug); 3) client tries to load data, encounters an error; 4) user finally sees the real error even though it happened twice. Hopefully, most components will work more like this until we fix the ID bug.

**Comment by muffinresearch** [comment] 2017-10-26 21:27
This is slightly to one side of the specifics of this issue but it would be ideal if the eventual error handling solution could know the difference between page level errors and component level errors.

## Page level error examples

For example if a details page call doesn't find an addon that page should render the NotFound component and if directly rendered by the server it should be a 404 (or maybe 410 gone if explicitly removed).

Similarly a search page request that asks for a page or results that don't exist, should similarly be 404 when directly linked and should also render the NotFound component.

## Component error examples

* Find as you type API request fails, this should show an error at a component level.
* A details page renders fine but there's an error in the more add-ons by some-user widget api call. This should only need to show the error at the component level.

It's not limited to specific API endpoints necessarily e.g. you might want a search request to sometimes be able to provide the page-level error and sometimes the component level one depending on the context of use.

**Comment by muffinresearch** [comment] 2017-10-31 10:49
@tofumatt are you actively working on this?

**Comment by tofumatt** [comment] 2017-10-31 11:23
Nope, I'm not; I've unassigned myself as I'm working on a few UI polishes before the tag.

**Comment by muffinresearch** [comment] 2017-11-02 13:01
I'm raising the priority of this as a post-release fix. We can probably break this up a bit more, the main thing to fix as a p2 is sorting out the stuck loading state (it's quite easy to get to one if you refresh a page with bad params) on search for example.

Surfacing the http status codes correctly is important too - if that can be part of the fix for the stuck loading state that's a bonus but if we need to split that out into something else that's fine.

**Comment by willdurand** [comment] 2017-11-02 13:58
Looking into this now.

**Closed** 2017-11-09 21:25 UTC
Labels: priority: p2, project: 2017 Q4, project: amo, triaged

**Comment by ValentinaPC** [comment] 2017-11-10 10:23
Verified this for an empty search, add-on type - themes - and observe that it is still reproducing.
Please see screenshot:
![2017-11-10_1221](https://user-images.githubusercontent.com/15685960/32653836-d9cef3c0-c611-11e7-93a8-5a7f9263ecbe.png)

Is this, somehow, not in -dev yet?
Thanks!

**Comment by willdurand** [comment] 2017-11-10 10:58
It has not been deployed in -dev yet, investigating...

**Comment by willdurand** [comment] 2017-11-10 17:14
should be in -dev now.

**Comment by willdurand** [comment] 2017-11-13 13:35
@ValentinaPC I think those are issues caused by the API and not the frontend.

**Comment by willdurand** [comment] 2017-11-13 14:00
@ValentinaPC so there is a limit of 25k add-ons returned by the API. I'll fix the frontend to take that into account. Could you create a new issue for that? The pagination cannot have more than 1000 pages.

**Comment by ValentinaPC** [comment] 2017-11-13 14:36
I found this issue: https://github.com/mozilla/addons-frontend/issues/1971 - is this ok or should I still log another issue?

**Comment by willdurand** [comment] 2017-11-13 14:38
> I found this issue: #1971 - is this ok or should I still log another issue?

This is another issue.

**Comment by ValentinaPC** [comment] 2017-11-13 15:05
I've logged https://github.com/mozilla/addons-frontend/issues/3887
We can mark this one verified.
