### ISSUE TITLE
after writing a wrong word in a iput box, i got a red line under it to show it was misspelled. I then right-clicked on the word and tried to install a new dictionary, i was the redirected to this page: https://addons.mozilla.org/en-GB/firefox/dictionaries/

### ISSUE THREAD

**Issue by RayBomb87** [mozilla/addons-frontend#7663] opened 2019-03-03 07:02 UTC

**Comment by AlexandraMoga** [comment] 2019-03-04 08:08
Thanks for the report. This is, however, a duplicate of https://github.com/mozilla/addons-frontend/issues/7658

**Closed by AlexandraMoga** 2019-03-04 08:08 UTC
