### ISSUE TITLE
The profile picture placeholder from the user info card is too small

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4648] opened 2018-03-28 10:02 UTC
Follow up for #4283 

Prerequisites: user has _not_ set a profile picture to their account

STR:

1. Log in to AMO-dev and select 'View profile' from the user menu
2. Observe the profile image in the user info card

Actual result:
The profile picture placeholder is much smaller than what is depicted in the [mocs](https://user-images.githubusercontent.com/90871/35629616-fcb243f4-0696-11e8-8b0b-024e96ec04cd.png)

Expected result:
The profile picture placeholder has the same dimensions as displayed in the mocs

Notes:
- reproduced on AMO-dev, with FF59, WIn10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/38021843-9e724d72-3286-11e8-9027-c70054b85bc3.png)

**Comment by tofumatt** [comment] 2018-03-28 13:31
😱 Oops, thanks for catching this, should be an easy fix.

**Comment by svitlana-galianova** [comment] 2018-03-28 16:18
Hey, I would like to work on this issue

**Comment by tofumatt** [comment] 2018-03-28 16:22
Hi @svitlana-galianova, thanks for your interest but I'm going to be taking this issue. 😄 You can have a look at our "contrib: good first bugs" issues to find issues to contribute to.

**Comment by svitlana-galianova** [comment] 2018-03-28 16:29
@tofumatt I should have waited for your response...

**Comment by tofumatt** [comment] 2018-03-28 16:50
It's cool! In the future you should check the "assigned" field in GitHub; if the issue is assigned it's best not to work on it, but I hadn't actually started so it's okay 😄

**Closed** 2018-03-31 22:28 UTC
Labels: component: user profile, component: ux, contrib: assigned, priority: p3

**Comment by AlexandraMoga** [comment] 2018-04-02 08:34
Verified as fixed on AMO-dev, FF59, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/38189565-7ee0c916-3669-11e8-9fc7-af286fa3a77d.png)
