### ISSUE TITLE
User profile - Unresponsive page after clicking on a review 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5472] opened 2018-07-02 12:00 UTC
STR:
1. Load AMO dev and go to View my profile page - make sure you have a couple of reviews.
2. Open a new tab and go to an extension's detail page and make a review.
3. Go back to View my profile into the other tab and refresh the page.
4. Click on the review, if it opens click back and then click other reviews displayed below until the page becomes unresponsive.

Expected result:
The add-ons detail page is displayed.

Actual result:
The page becomes unresponsive and a yellow message appears "A web page is slowing down your browser..."

Notes:
This issue is reproducible on AMO dev with FF61(Win10). 
![unrespponsive page2](https://user-images.githubusercontent.com/33448286/42162668-405f8740-7e08-11e8-8f7a-c618b7eb880a.gif)
![error](https://user-images.githubusercontent.com/33448286/42162718-7c947e96-7e08-11e8-8f23-723a6dec0708.png)

**Comment by muffinresearch** [comment] 2018-07-04 15:59
This sounds bad - would be good to investigate and understand the cause. Marking as P2 to discuss in the stand-up.

**Comment by muffinresearch** [comment] 2018-07-04 16:43
@ioanarusiczki I can't reproduce this. Also the browser console messages don't appear to have any reference to AMO js - can you still reproduce this in a clean profile?

**Comment by ioanarusiczki** [comment] 2018-07-12 09:45
@muffinresearch Others cannot reproduce this either but I could reproduce it only twice now (issue is intermittent) with a clean profile and new account.  I'm on Win10x86, FF61. 

![clean profile](https://user-images.githubusercontent.com/33448286/42625816-66a169b6-85d1-11e8-9fdb-b263c37f75d6.png)

**Comment by muffinresearch** [comment] 2018-07-12 09:49
@ioanarusiczki can you repro on a more recent nightly too?

**Comment by willdurand** [comment] 2018-07-12 10:34
The logs in the console are normal in the last screenshot.

Can it be Windows-only? I cannot reproduce either, and I don't really see what could cause this problem yet.

@ioanarusiczki can you reproduce on Edge and/or Chrome?

**Comment by ioanarusiczki** [comment] 2018-07-12 11:07
@willdurand I could only reproduce it with Edge. But not with Chrome.

**Comment by bobsilverberg** [comment] 2018-08-30 21:35
This has been open for nearly 2 months without much activity or investigation. @ioanarusiczki have you seen this behaviour again since then? Can you see if it's still reproducible?

**Comment by kumar303** [comment] 2018-09-05 19:54
I was able to randomly reproduce this the other day on Firefox Nightly. I am suspicious that it is the same infinite loop problem mentioned in https://github.com/mozilla/addons-frontend/pull/6108#issuecomment-418534121

**Comment by bobsilverberg** [comment] 2018-09-05 19:58
> I am suspicious that it is the same infinite loop problem mentioned in https://github.com/mozilla/addons-frontend/pull/6108#issuecomment-418534121

If that's true, then I have a fix for it! Stay tuned...

**Comment by kumar303** [comment] 2018-09-05 20:00
I just updated my comment to say a *similar* loading problem because I realized the unresponsive page is not the add-on detail page, it's the add-on review listing page. 

The review listing page also does not check for a loading flag:

https://github.com/mozilla/addons-frontend/blob/7a293e510bab942784d680cf2bd4ae8edf70627a/src/amo/components/AddonReviewList/index.js#L90-L91

This is all just a theory!

**Comment by kumar303** [comment] 2018-09-06 19:31
Sorry for the confusion. I was mistaken in my last comment. The screencast at the top of this issue shows that the infinite loop *is* happening on the add-on review listing page.

I am very confident that the patch for https://github.com/mozilla/addons-frontend/issues/6105 has solved this issue! @ioanarusiczki could you re-test it?

**Closed by kumar303** 2018-09-06 19:31 UTC
Labels: component: user profile, needs: info, priority: p3

**Comment by ioanarusiczki** [comment] 2018-09-07 13:43
@kumar303 
I tested it on Win10 with FF62, FF64, Edge - AMO dev and a couple of tests on AMO stage too - I could no longer reproduce the issue.  Sometimes the listed review pages last longer to load after they're clicked from the user profile page.
I'm marking it verified fixed.
