### ISSUE TITLE
Add "report abuse" button on add-on detail page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2759] opened 2017-07-12 00:23 UTC
We'll need a way to report an add-on.

Relies on https://github.com/mozilla/addons-server/issues/5595

**Comment by muffinresearch** [comment] 2017-09-13 16:19
Duplicate of #2759

**Closed** 2017-09-26 12:42 UTC
Labels: priority: mvp, project: 2017 Q3, project: amo, project: desktop pages, state: pull request ready, triaged

**Comment by AlexandraMoga** [comment] 2017-09-26 15:32
Verified on AMO-dev FF55(Win10) and FF55 Android 7.0

Postfix video:

![reportabuse-desktop](https://user-images.githubusercontent.com/31961530/30868420-3ce22714-a2e7-11e7-9183-f04e04660354.gif)
