### ISSUE TITLE
Introduce Photon-style notification bar

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3706] opened 2017-10-31 02:56 UTC
We need to introduce the photon [notification ("message") bar](http://design.firefox.com/photon/components/message-bars.html) into AMO. I'll provide specs on how it should be integrated into our site properly soon.

For QA: please check the style of notifications against the spec (linked above). Here are some screenshots of what has been changed: https://github.com/mozilla/addons-frontend/pull/4149

Be sure to check the list at the top of https://github.com/mozilla/addons-frontend/pull/4149 for what has *not* been implemented yet.

**Comment by willdurand** [comment] 2017-10-31 10:38
I have updated the labels since this looks more like a post release feature than a mvp-polish.

**Comment by kumar303** [comment] 2017-11-15 18:07
In addition to incompatibility notices, the error notifications also need updating. Here are some examples:

<img width="663" alt="screenshot 2017-11-15 12 04 00" src="https://user-images.githubusercontent.com/55398/32852411-6d706e44-c9fd-11e7-9d1c-da23cad6e2e0.png">
<img width="370" alt="screenshot 2017-11-15 12 06 24" src="https://user-images.githubusercontent.com/55398/32852414-6f7bf58c-c9fd-11e7-82d1-6b4b7b0190d9.png">

**Comment by pwalm** [comment] 2017-11-16 23:57
Implementation of this one is going to take a bit of problem-solving, but the design system team and I are working on it.

**Comment by pwalm** [comment] 2017-11-20 23:42
Here are the implementation mocks. Basically, the notification should appear in the block to which it pertains (how we've been doing it, but always at the top).
![screen shot 2017-11-20 at 3 33 34 pm](https://user-images.githubusercontent.com/6797635/33046980-3e938ffc-ce08-11e7-9fe5-c4ddeafcd918.png)

Full-width notifications look a bit odd, might have to finesse them a bit.
![screen shot 2017-11-20 at 3 41 21 pm](https://user-images.githubusercontent.com/6797635/33047178-4b085834-ce09-11e7-8b17-7f8e098fd186.png)

**Comment by AlexandraMoga** [comment] 2018-01-17 13:32
I've verified this on AMO-dev (Win10, Android 7.0) and here are my observations:
1. The suggestion was to have the notifications displayed at the top of the current block, but I see that  the position hasn't changed
2. The [specs](https://design.firefox.com/photon/components/message-bars.html) suggest that the information icon for error messages should be a **`!`**, but we have here an **`i`**
3. The error text was to be white, however links included in this text are blue and not very legible
4. The notification text doesn't seem to be perfectly aligned inside the notification banner
5. At page refresh, the notification banners changes sizes
6. The 'Download Firefox' banner was not added (not so sure if it was intended or not for this patch)

Notes:
Based on the above observations, I'm re-opening this issue. If you want to track any of these points separately, I can open new cases. 
Also, I don't think that there are current actions that trigger a success message on the new AMO, so I was not able to cover these notifications.


Screenshots:
![image](https://user-images.githubusercontent.com/31961530/35044605-c0fcee34-fb99-11e7-8ec8-9bbc22a652cc.png)
![refresh](https://user-images.githubusercontent.com/31961530/35044619-ca080dec-fb99-11e7-8047-5103aa1c511a.gif)
</br>
![image](https://user-images.githubusercontent.com/31961530/35044790-5567ae4c-fb9a-11e7-998b-cb807d5d0866.png)

**Comment by tofumatt** [comment] 2018-01-17 14:23
Agreed on the links especially, they should be white alongside the text colour.

- Matt (Sent from mobile)

**Comment by kumar303** [comment] 2018-01-17 18:11
Thanks @AlexandraMoga, this is really helpful! I made a new issue as https://github.com/mozilla/addons-frontend/issues/4169 since it will be easier for me to track. A general rule of thumb is to only re-open an issue if we need to revert the code that landed. This is because we use issues to track which code is going out in what release. In this case, I don't think we need to revert the code but I will fix this ASAP. If necessary, we can cherry pick the new patch so that it makes it into the release.

**Closed by kumar303** 2018-01-17 18:11 UTC
Labels: component: ux, priority: post release, size: L, triaged, type: feature

**Comment by AlexandraMoga** [comment] 2018-01-18 15:09
Since the issues mentioned above will be tracked separately, I am marking this as verified fixed.
