### ISSUE TITLE
Selecting "All" for Operating System after a blank search will return "No addons found"

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#6578] opened 2018-10-10 15:34 UTC
Steps to reproduce: 
1.Go to addons.mozilla.org and perform a blank search
2.Under filter results section, select "All" for "Operating system"

Expected results:
All extensions compatible with all operating systems should be displayed

Actual results:
No addons found

NOTES:
Reproducible in prod

Please see a video for this bug : 
![blanksearch](https://user-images.githubusercontent.com/1583842/46747915-19e21e00-ccbb-11e8-97b6-18e29678c33a.gif)

**Comment by jvillalobos** [comment] 2018-10-10 17:16
Dupe of https://github.com/mozilla/addons-frontend/issues/6117

**Closed by jvillalobos** 2018-10-10 17:16 UTC
