### ISSUE TITLE
Unable to install Privacy Badger for Android from AMO gallery listing

### ISSUE THREAD

**Issue by ghostwords** [mozilla/addons-frontend#10100] opened 2021-02-18 17:33 UTC
I am unable to install Privacy Badger by visiting [Privacy Badger's listing in the AMO gallery on Android](https://addons.mozilla.org/android/addon/privacy-badger17/) and clicking "Add to Firefox".

The problems occurs with both the latest Firefox stable (Firefox Daylight 86.1.0-rc.1) and Firefox Nightly on a Nokia 6.1 running Android 10.

### What happened?

I get a file download prompt. After the download completes, I get a button to "Open" the file, tapping which produces a purple "Could not open file" notification. 

### What did you expect to happen?

Privacy Badger gets installed.

### Anything else we should know?

I was under the impression that users should be able to install recommended extensions from AMO (as opposed to the addons manager) as of Firefox 85: https://blog.mozilla.org/addons/2021/01/20/extensions-in-firefox-for-android-update/

**Comment by acornestean** [comment] 2021-02-19 10:30
I managed to find a way to consistently reproduce the issue. Below you can find the STR (the example below is for Nightly, however these are applicable to all versions: Release, Beta and the 86.1.0-rc.1 release candidate used by the reporter).

Steps to reproduce:
1. Install the latest Nightly from the Play Store
2. Launch Nightly
3. Go to the Privacy Badger AMO page (https://addons.mozilla.org/en-US/android/addon/privacy-badger17/)
NOTE: Access AMO by typing addons.mozilla.org in the URL bar. Once AMO loads, search for the add-on via the search field on the page.
4. Close Nightly
5. Re-launch Nightly (the last accessed page will load i.e the Privacy Badger AMO page) 
6. Tap the “+ Add to Firefox” button
7. Tap “Allow” on the “Allow Firefox Nightly to access photos, media, and files on your device?” prompt which will be displayed
8. A file download prompt will be displayed. Tap “Download”
9. After the file download is finished, tap “Open”
10. The “Could not open file” notification is displayed

Note that the issue can be reproduced with any currently supported add-on and once triggered will persist until a fresh install of the browser.

Tested on a Samsung Galaxy S7 Edge running Android 8.0.0 with the following Firefox versions:
- Nightly 210218 (Build: 2015794075), GV: 87.0a1-20210218092411
- Beta 86.0.0-beta.5 (Build: 2015793427), GV: 86.0-20210212222924
- Release 85.1.3 (Build: 2015792283), GV: 85.0.2-20210208133944
- Firefox 86.1.0-rc.1 (Build: 2015793705), GV: 86.0-20210215141125

**Comment by willdurand** [comment] 2021-02-19 10:35
I am not sure we can have very reproducible STR to be honest *but* this bug is easy to trigger most of the time, and it's an actual bug indeed. The API returns download URLs that have `firefox` instead of `android` in their paths, and Fenix checks that `android` is present (it's a bit more than that but that's the gist of it).

Fenix is a bit too restrictive but the API shouldn't return a download URL with a random app name. Instead, it should use the `app` query parameter when provided (which AMO frontend passes already). We never noticed this issue before because the `app` in the download URL has no meaningful value anymore these days.

If we can fix the bug on the API side, installs in Fenix should be fixed in a week.

**Comment by ghostwords** [comment] 2021-02-19 14:52
I can reproduce 100% of the time. Uninstalling and reinstalling Firefox Daylight stable didn't make a difference.

**Comment by willdurand** [comment] 2021-02-22 17:14
I fixed our API code: https://github.com/mozilla/addons-server/pull/16598, which should fix this issue. The fix will be deployed on Thursday at 9AM PT.

**Closed by willdurand** 2021-02-22 17:15 UTC
Labels: platform: android, priority: p2, type: prod_bug

**Comment by ioanarusiczki** [comment] 2021-02-23 15:37
@willdurand This issue is reproducible right now on AMO stage at all times, with the steps given by @acornestean : when I am on a detail page of an add-on and I close and reopen the browser and after the page is reloaded I tap the Install button, the download described above is triggered and it ends with "could not open file" message. 

But on AMO dev where the fix landed - this is no longer reproducible.  - with Android 10.0 FF 87

I'm going to take a final look tomorrow on stage when the fix lands.

**Comment by ghostwords** [comment] 2021-02-23 17:12
@willdurand I'm curious, what made this bug not consistently reproducible for you?

**Comment by willdurand** [comment] 2021-02-25 17:23
@ghostwords the server could decide to serve the right download url sometimes

**Comment by willdurand** [comment] 2021-02-25 17:24
this bug should be fixed now, please let us now if there are still issues.

**Comment by ghostwords** [comment] 2021-02-25 18:48
Looks good, thank you!
