### ISSUE TITLE
Modules pour Firefox (fr)

### ISSUE THREAD

**Issue by bnhassin** [mozilla/addons-frontend#7753] opened 2019-03-22 21:30 UTC

**Comment by bnhassin** [comment] 2019-03-22 21:34
![image](https://user-images.githubusercontent.com/1473765/54854248-9bba8680-4cf2-11e9-9bc2-05d595dd01e1.png)

**Comment by jvillalobos** [comment] 2019-03-22 22:03
Dupe of https://github.com/mozilla/addons-frontend/issues/7736

**Closed by jvillalobos** 2019-03-22 22:03 UTC
