### ISSUE TITLE
Add support for OpenSearch

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-frontend#7207] opened 2018-12-12 15:13 UTC
This replaces https://github.com/mozilla/addons-server/issues/10072

I think this should be fairly easy and helpful to some users.

tldr; add something along the lines of

```html

        <link title="Firefox Add-ons"
          rel="search" type="application/opensearchdescription+xml"
          href="/en-US/firefox/opensearch.xml" />
```

Linking to https://addons.mozilla.org/en-US/firefox/opensearch.xml or provide our own opensearch.xml on addons-frontend.

**Comment by muffinresearch** [comment] 2018-12-12 15:50
Duplicate of https://github.com/mozilla/addons-frontend/issues/3836

**Closed by muffinresearch** 2018-12-12 15:50 UTC
Labels: priority: p4

**Comment by EnTeQuAk** [comment] 2018-12-12 15:51
Oops, shame on me :see_no_evil:
