### ISSUE TITLE
Add support for appversion and platform in search query params

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2706] opened 2017-07-07 17:01 UTC
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1263313 we're going to need to add support for `appversion` and `platform` query strings in search urls.

**Comment by kumar303** [comment] 2017-08-24 19:08
Also see https://github.com/mozilla/addons-frontend/issues/2998

**Comment by tofumatt** [comment] 2017-08-24 19:10
Support is added in #2995, but sending it by default can be a smaller follow-up bug.

**Comment by ValentinaPC** [comment] 2017-09-12 06:37
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by tofumatt** [comment] 2017-09-12 12:30
When searching from Windows, Mac, or Linux the appropriate operating system should be selected in the search filters by default.

**Comment by ValentinaPC** [comment] 2017-09-12 13:32
Verified this on FF55 using Windows 7, MacOS Sierra v.10.12 and Linux 16.04
Appropriate operating system is selected in Filter menu by default.
Marking this verified-fixed.

**Comment by ValentinaPC** [comment] 2017-09-13 09:11
@tofumatt : Due to the fact that https://github.com/mozilla/addons-frontend/issues/3096 was opened yesterday, I did not checked those pages.
Do we want the appropriate operating system be displayed there too? Because is not.
Please see screenshot:
![2017-09-13_1210](https://user-images.githubusercontent.com/15685960/30369281-910c98b2-987c-11e7-82a7-387450da7259.png)

**Comment by tofumatt** [comment] 2017-09-13 14:28
@ValentinaPC Yes it should be setting the operating system param there. Can you check the request to see if it is being sent to the API? It could be the issue is we just aren't setting it in the UI which is an easy fix 😄

**Comment by ValentinaPC** [comment] 2017-09-13 15:15
There are some API requests but not an operating system param in there:
![2017-09-13_1800](https://user-images.githubusercontent.com/15685960/30384606-72e6a63a-98ad-11e7-9fed-cde295c7e258.png)

And I've also saw something interesting while searching - at page refresh param change.
In "More..." pages the operating system param is displayed correctly after page refresh.
Logged - https://github.com/mozilla/addons-frontend/issues/3121 for the refresh issue.

**Comment by tofumatt** [comment] 2017-09-13 15:20
Okay then something is wrong here and this needs be re-opened.

**Comment by tofumatt** [comment] 2017-09-17 15:12
I just tested this on production on my Windows 10 laptop and my MacBook Pro. It set Windows as the OS on Windows and MacOS as the OS on Mac, so closing this as fixed.

**Closed by tofumatt** 2017-09-17 15:12 UTC
Labels: project: 2017 Q3, project: desktop pages, triaged

**Comment by vcarciu** [comment] 2017-09-18 13:25
We observed that if you are going directly to "More highly rated themes/extensions" or "More popular themes/extensions" (ie. https://addons-dev.allizom.org/en-US/firefox/search/?sort=rating&type=extension), the platform is still not retrieved.

After discussing with @tofumatt , we agreed to open a new issue.
