### ISSUE TITLE
Product page for deleted theme throws 500 for admins

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#8258] opened 2019-07-05 16:28 UTC
### Describe the problem and steps to reproduce it:

Visit https://addons.mozilla.org/en-US/firefox/addon/1423860/ with admin privileges.

### What happened?

500: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/6018696/

### What did you expect to happen?

See the theme page.

**Comment by willdurand** [comment] 2019-07-05 16:35
I believe we have other similar issues opened for that. It's tricky because we usually don't hit those bugs in -dev and we (developers) aren't admins in prod (or even stage).

**Comment by kumar303** [comment] 2019-07-05 16:38
...and [`Addons`](https://github.com/mozilla/addons-frontend/blob/19202fac6b49ea151a9b53d303076ee338f06448/src/amo/pages/Addon/index.js) doesn't use Flow 😞

**Comment by willdurand** [comment] 2019-07-08 10:18
This issue is likely a duplicate of https://github.com/mozilla/addons-frontend/issues/3845.

**Closed by willdurand** 2019-07-08 10:18 UTC
Labels: priority: p3, type: bug
