### ISSUE TITLE
Remove focus style on "Choose photo" button on mobile devices

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5629] opened 2018-07-17 09:50 UTC
Followup for https://github.com/mozilla/addons-frontend/issues/5573

~~STR:~~
~~1. Load AMO dev and go to Edit my profile page~~
~~2. Click the "delete this picture" button~~

~~Actual result:~~
~~The new focus style is visible as mentioned here https://github.com/mozilla/addons-frontend/pull/5572~~

~~Expected result:~~
~~Once the button is tapped a border is visible for a short while.~~

~~Notes:~~
~~This issue is reproducible on AMO dev with FF61, Android 8.0.~~
~~Not reproducible on Win10.~~

![android focus style - delete button](https://user-images.githubusercontent.com/33448286/42810132-e02db086-89bf-11e8-9557-b74e0bccb3a0.gif)

---

UPDATE: so the issue is about a button not having a focus style on Android *but* it is the case for ALL other buttons. So, instead of adding focus style on the delete button, we want to remove focus style on the "Choose a photo" button only on mobile devices.

The code is here: https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/UserProfileEditPicture/index.js

**Comment by willdurand** [comment] 2018-07-17 13:40
> @willdurand I don't understand your edit to the title. That seems to confuse what's been reported which is about the "Delete This Picture" not having focus afaict.

I updated the description too: only the "Choose Photo" button has a focus style on Android. The report was about the "Delete This Picture" button indeed, but the underlying problem was the opposite.

**Comment by willdurand** [comment] 2018-07-18 19:38
@muffinresearch for consistency, there is no focus style on buttons on mobile devices. If we want focus style, we'll do it globally.

**Comment by muffinresearch** [comment] 2018-07-19 09:10
> @muffinresearch for consistency, there is no focus style on buttons on mobile devices. If we want focus style, we'll do it globally.

How do we determine "Mobile" in this case? I wonder if we're potentially going to remove focus inadvertently if we make that decision based on viewports alone.

Maybe we should consider doing using something like [-moz-focusring](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring) or the more future facing https://github.com/WICG/focus-visible (which has a polyfill). These solutions look at providing ways to make a decision on focus styling based on using a keyboard versus a mouse.

There might be some arguments that suggest that we should always focus irrespective of the source and we should weigh that up too.

**Comment by willdurand** [comment] 2018-07-19 09:17
> How do we determine "Mobile" in this case? I wonder if we're potentially going to remove focus inadvertently if we make that decision based on viewports alone.

I don't have the answer right now.

> Maybe we should consider doing using something like -moz-focusring or the more future facing WICG/focus-visible (which has a polyfill). These solutions look at providing ways to make a decision on focus styling based on using a keyboard versus a mouse.
>
> There might be some arguments that suggest that we should always focus irrespective of the source and we should weigh that up too.

That would probably be easier to implement focus everywhere than trying to remove focus on this specific button, so I am not against the idea at all (quite the contrary).

I don't really know why we do not have focus on mobile yet, I did not investigate. Maybe it is the mobile browser that does that.

**Comment by SeanPrashad** [comment] 2018-12-20 18:37
Code for this issue can be found here:

https://github.com/mozilla/addons-frontend/blob/1baa3ee4fd67141c6a32294eb5b50a4cd0bea82a/src/amo/components/UserProfileEditPicture/index.js#L79-L98

**Comment by SeanPrashad** [comment] 2018-12-20 18:54
Hey @ioanarusiczki 🙂👋🏽 I was trying to reproduce this locally but _I think_ the issue is gone:

![recreate_focus_button_issue](https://user-images.githubusercontent.com/13009507/50304669-908b5c80-045e-11e9-83bd-cadf05ef54ad.gif)

**Note**: I am using the developer tools within Firefox to try and recreate this - I don't have access to an Android phone 😓

**Comment by willdurand** [comment] 2019-01-02 08:06
Indeed, let's close this bug.

**Closed by willdurand** 2019-01-02 08:06 UTC
Labels: component: user profile, contrib: welcome, platform: android, priority: p4
