### ISSUE TITLE
An error is displayed when a collaborator is deleting a persona from Mozilla featured personas collection

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5499] opened 2018-07-04 16:14 UTC
Steps to reproduce:
1.Add an user to an admin group with Collections:Contribute persmission
2.Using that user open https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/
3.Press Edit button, delete any persona and press save

Expected results:
The persona is deleted without problems

Actual results:
An error saying that "You do not have permission to perform this action." is displayed without any reason

Please see video for this bug : 
![collectionscontribute](https://user-images.githubusercontent.com/1583842/42287295-74358008-7fbe-11e8-8999-ba332cfc1e11.gif)

**Comment by vcarciu** [comment] 2018-07-04 16:16
Follow up from #5163

**Comment by bobsilverberg** [comment] 2018-07-04 17:03
I think this is expected. @eviljeff can you confirm? Can someone with Collections:Contribute actually edit the featured-personas collection, or are they only allowed to add, remove and update add-ons in that collection?

If the latter then this behaviour is expected, but we should probably remove or disable the "Save collection" button.

**Comment by eviljeff** [comment] 2018-07-04 17:09
@diox's latest changes prevent the `Collections:Contribute` from doing anything other than getting the detail response on the Collection itself.  (And adding, deleting, and updating the add-ons in it).  I don't know if that was deliberate.

**Comment by diox** [comment] 2018-07-05 10:47
That was the idea, yes. Allow those contributors to change the add-ons, but not the collection itself.

**Comment by bobsilverberg** [comment] 2018-07-05 13:11
That makes sense to me too. I will file an issue to deal with the UX for the edit form.

**Comment by bobsilverberg** [comment] 2018-07-05 17:17
This is now a duplicate of #5508.

**Closed by bobsilverberg** 2018-07-05 17:17 UTC
Labels: component: collections, priority: p3
