### ISSUE TITLE
In bookmarks section of Android firefox, I had this link which read firefox:customize with add-ons. Clicking on it said page doesn't exist and I was pointed to this section to file an issue.

### ISSUE THREAD

**Issue by Mithil467** [mozilla/addons-frontend#8111] opened 2019-06-01 09:09 UTC

**Comment by aplaice** [comment] 2019-06-02 11:00
Thanks for filing!

I think that this is a duplicate of https://github.com/mozilla/addons-frontend/issues/8059.

**Closed** 2019-06-03 08:46 UTC
