### ISSUE TITLE
Some themes from featured collection are not featured

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3578] opened 2017-10-20 06:20 UTC
Steps to reproduce:
1. Load Themes homepage https://addons.mozilla.org/en-US/android/themes/
2. Tap on More Featured Themes link https://addons.mozilla.org/en-US/android/search/?featured=true&type=persona
3. Click on "Kaleidoscope" - https://addons.mozilla.org/en-US/android/addon/kaleidoscope/

Expected results:
Theme has "featured" label.

Actual results:
Some themes from featured collection are not featured.

Notes/Issues:
Other examples:
- https://addons.mozilla.org/en-US/android/addon/autumn1366x768/
- https://addons.mozilla.org/en-US/android/addon/clouds17-1/
- https://addons.mozilla.org/en-US/android/addon/animated-botanical-gardens/

Verified on AMO-prod FF56(Android 7.2.1, Win 7). Didn't manage to reproduce it in dev.
Video for this issue:
![featured](https://user-images.githubusercontent.com/15685960/31807589-c82c6d8c-b577-11e7-8973-dea1adb1ab1e.gif)

**Comment by willdurand** [comment] 2019-07-05 10:46
This is likely due to an API bug and it might not be reproducible anymore, so I am going to close this issue.

**Closed by willdurand** 2019-07-05 10:46 UTC
Labels: priority: p3, project: amo, project: desktop pages, triaged

**Comment by AlexandraMoga** [comment] 2019-07-05 11:05
I wasn't able to reproduce this anymore. if we run into the issue again, we'll open a server bug.
