### ISSUE TITLE
There is no page for the collection you created.

### ISSUE THREAD

**Issue by roman90sv** [mozilla/addons-frontend#4803] opened 2018-04-15 02:04 UTC
But I can edit and delete collections.
___
![45](https://user-images.githubusercontent.com/35082918/38774161-7ca2a588-406a-11e8-8165-b4139c52133b.JPG)
___
Also, add-ons that I add to the collection have a "pending" status.
___
![4545](https://user-images.githubusercontent.com/35082918/38774165-82bde7ca-406a-11e8-81d3-97d7f33b0385.JPG)

**Comment by bobsilverberg** [comment] 2018-04-16 14:08
Thanks for the bug report @roman90sv. It looks like the slug for your collection is `00` (that is two zeros), is that correct? I believe there may be a problem displaying collections with slugs that only contain numbers, and I think there may in fact be an issue filed for that already. I'll take a look for that, but can you please confirm the above? If your collection does have a slug of `00`, could you try changing it to something other than just numbers, e.g., `a00`, and see if that fixes the problem?

**Comment by AlexandraMoga** [comment] 2018-04-17 06:02
@bobsilverberg  the same issue was reported in #4653, which is now closed and waiting to be handled at the server level.

**Comment by bobsilverberg** [comment] 2018-04-17 13:29
Thanks @AlexandraMoga. Let's wait to see if @roman90sv reports that changing the slug fixes the issue, and then I think we can close this as a duplicate.

**Comment by bobsilverberg** [comment] 2018-04-26 08:55
As there has been no response from @roman90sv, and this definitely looks like a duplicate of #4653, I'm going to close it.

**Closed by bobsilverberg** 2018-04-26 08:55 UTC
