### ISSUE TITLE
All categories clip once at any category tap

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2174] opened 2017-03-24 13:01 UTC
Steps to reproduce:
1. Load categories page on your device https://addons-dev.allizom.org/en-US/android/extensions/categories/
2. Tap on any category

Expected results:
There are no display o layout issues.

Actual results:
At one category tap, all categories clip once.

Notes/Issues:
Verified on AMO-dev FF52(Android 6.0.1).
Video for this issue: 
![videotogif_2017 03 24_14 57 37](https://cloud.githubusercontent.com/assets/15685960/24295288/b1908132-10a2-11e7-878e-c865d6a91c66.gif)

**Comment by tsl143** [comment] 2017-05-27 17:54
I am unable to reproduce the error, in addition I get already blue color hyper links(visited links becomes black). (production and dev)

![photo6147712460195473333](https://cloud.githubusercontent.com/assets/5318732/26523347/7c7101d4-4333-11e7-9278-55af58f6e925.jpg)
![photo6147712460195473334](https://cloud.githubusercontent.com/assets/5318732/26523348/7cbd0340-4333-11e7-832c-fff6052890e6.jpg)

**Comment by ValentinaPC** [comment] 2017-05-29 07:20
The initial issue is no longer reproducing in any browsers while using FF53(Android 7.1.2)
I think the behavior exposed above is intended, even ig in my opinion should behave the other way around.

**Comment by tsl143** [comment] 2017-05-29 07:31
@muffinresearch As initial issue is not reproducible, so shall we close this, or we shall go ahead and implement Valentina's opinion?

**Comment by kumar303** [comment] 2017-05-30 16:13
Since the issue is no longer reproducible, we can close it. Thanks for everyone's time on this.

**Closed by kumar303** 2017-05-30 16:13 UTC
Labels: component: ux, contrib: maybe good first bug, priority: enhancement, project: amo, project: mobile pages v1, triaged
