### ISSUE TITLE
ChehareTime add-on detail page throws a 404 when opened from Most popular extensions section

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#2021] opened 2017-03-08 16:49 UTC
### Steps to reproduce:
1. Open addons-dev.allizom.org on your android device.
2. Tap on the Extensions button
3. Scroll down to Most popular extensions section
4. Tap on ChehareTime add-on

### Expected results:
The add-on detail page is opened. 

### Actual results:
404 error 

### Notes/Issues
When searching for that add-on and opening from the search result list, the add-on detail page is opened correctly.
Verified in FF51(Android 6.0.1)
Screencast for this issue:
![404detailpage](https://cloud.githubusercontent.com/assets/15685441/23713605/270c6938-042f-11e7-90eb-7c84dc7fdc24.gif)

**Comment by muffinresearch** [comment] 2017-03-09 10:24
I suspect this may be something to do with using search state for the details page but it needs further investigation.

**Comment by kumar303** [comment] 2017-03-10 15:37
This is the exact add-on I was looking at when I filed https://github.com/mozilla/addons-frontend/issues/2035 The issue is that ChehareTime was deleted on dev so it shouldn't have shown up in search results at all. Closing this as a dupe but thanks for the report!

**Closed by kumar303** 2017-03-10 15:37 UTC
Labels: project: amo, project: mobile pages v1
