### ISSUE TITLE
Firefox banner now shows up on product detail page for non firefox clients

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6985] opened 2018-11-20 01:15 UTC
This was removed from the product page  I'll try to find the issue) but I think after some recent changes to the compatibility component, it appears again. 

![Alt text](https://monosnap.com/image/9F53q8yfaJQ7JxdB22hh0kQ3eKnbj3.png)

I noticed this when I was working on the guides page. I am using a flag to hide this (see https://github.com/mozilla/addons-frontend/pull/6984/files#diff-7611bdafdbbf234e67c5903578512b28R35) but it occurred to me we actually may want this on this detail page too. If you look at stage and prod it isn't currently there...

cc @bobsilverberg

**Comment by willdurand** [comment] 2018-11-20 08:38
That looks like a regression, which should be fixed before today's tag ideall.

**Comment by willdurand** [comment] 2018-11-20 09:31
I believe the issue is here: https://github.com/mozilla/addons-frontend/pull/6956/files#diff-ca1fb480f1768d9c6bdbe73f055ac4a5L501

We should only render the `AddonCompatibilityError` component when `isFirefox` is `true`, no?

**Comment by bobsilverberg** [comment] 2018-11-20 13:10
> We should only render the `AddonCompatibilityError` component when `isFirefox` is `true`, no?

Well, the idea was to move as much of the logic into `AddonCompatibilityError` as possible. If we always want this behaviour, we should change `AddonCompatibilityError` to return `null` if the browser is Firefox. Otherwise every consumer will have to check for `isFirefox` and decide whether to render the `AddonCompatibilityError` or not.

@willdurand WDYT?

**Comment by willdurand** [comment] 2018-11-20 13:13
> Well, the idea was to move as much of the logic into `AddonCompatibilityError` as possible. If we always want this behaviour, we should change `AddonCompatibilityError` to return `null` if the browser is Firefox. Otherwise every consumer will have to check for `isFirefox` and decide whether to render the `AddonCompatibilityError` or not.
> 
> @willdurand WDYT?

I do agree, @rebmullin has a patch that you might want to reuse to fix this issue in https://github.com/mozilla/addons-frontend/pull/6984. I commented on it to update it a bit, but that'd be nice to see a PR with only this change: https://github.com/mozilla/addons-frontend/pull/6984/files/062fa04704d67a61616dc3807386f4428746acf7#diff-7611bdafdbbf234e67c5903578512b28

**Comment by bobsilverberg** [comment] 2018-11-20 13:15
Yes, I just saw that! That looks like a good approach, but if we actually know that we never want to show the notice when Firefox is the browser, we don't need a flag - we could just always hide it when the browser is Firefox.

WDYT about that approach?

**Comment by willdurand** [comment] 2018-11-20 13:16
> Yes, I just saw that! That looks like a good approach, but if we actually know that we never want to show the notice when Firefox is the browser, we don't need a flag - we could just always hide it when the browser is Firefox.
> 
> WDYT about that approach?

That's correct, heh 😄 (/me needs a coffee)

**Closed** 2018-11-20 14:06 UTC
Labels: component: add-on, priority: p1, type: regression

**Comment by ioanarusiczki** [comment] 2018-11-21 08:14
@willdurand I verified the detail pages on AMO -dev with Chrome and Edge but there's no green banner as @rebmullin mentioned above. 

![green banner](https://user-images.githubusercontent.com/33448286/48827482-1049dc80-ed76-11e8-9908-f6cbc72fc422.png)
