### ISSUE TITLE
 UX: list view (lists/listings): show dates of add-ons

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3832] opened 2017-11-08 02:28 UTC
## Observation

The classic look included dates. 

## Enhancement request

Somehow show dates in the new look. 

## Background

From [post 17](https://discourse.mozilla.org/t/-/20860/17?u=grahamperrin) under _Test the new look of addons.mozilla.org! - Add-ons / addons.mozilla.org - Mozilla Discourse_: 

> … wherever you see `sort=updated` you can change it to `sort=created` so, for themes (personas):
> 
> - https://addons.mozilla.org/firefox/search/?type=persona&sort=created
> 
> – **and then ignore** the word _Relevance_, to the left.
> 
> Compared to the classic look, the new does not show the dates. It’s probably to be done, but not yet on a milestone.

In [post 44](https://discourse.mozilla.org/t/-/20860/44?u=grahamperrin) _lemur_ wrote:

> … Will there be “dates” associated with each extension?
> 
> For example, before, I’d like the last extension I saw on the list, as well as the date (in my case, 10-30). Now, there’s no way to know what’s come out since then – _especially_ if the last extension I saw has been deleted …

@Lemur ⬆️ please, was that you? Or someone else with the same nickname?

**Comment by muffinresearch** [comment] 2017-11-08 14:23
@grahamperrin please can you provide some screenshot to illustrate what you're referring to?

**Comment by tofumatt** [comment] 2017-11-08 15:23
This (appears to be) a duplicate of #3783.

@grahamperrin Thanks for filing issues but please follow the issue template a bit closer. Try to keep the issues concise; the quoting and attribution makes it hard to tell what the actual issue being reported is. Including steps to reproduce an issue would be great 😄

Please try to include URLs and screenshots as well, as @muffinresearch. Doing so will mean we can act on the issue faster as we won't need to spend as much time triaging it 😄

**Closed by tofumatt** 2017-11-08 15:23 UTC
Labels: needs: info, triaged
