### ISSUE TITLE
Enable adzerk integration for Sponsored shelf

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9836] opened 2020-11-04 18:48 UTC
Update the `default.js` config to turn `enableFeatureUseAdzerkForSponsoredShelf` on.

**Comment by bobsilverberg** [comment] 2020-11-05 18:45
This has just been pushed to stage, so should be available for testing on stage shortly.

**Comment by bobsilverberg** [comment] 2020-11-05 19:18
The shelf is not appearing on stage because the API is returning 0 results. We need to make sure there are sponsored add-ons on stage that have ids that correspond to the creatives on Adzerk. I'm not sure who is going to take care of that. We will also need to make sure similar data exists in prod, or the shelf will disappear next Thursday when we push.

cc @jvillalobos

**Comment by jvillalobos** [comment] 2020-11-05 19:28
Prod currently has the list of 5 that we have on the pilot. I don't know who's managing the stage list.

**Comment by bobsilverberg** [comment] 2020-11-05 19:29
I just added a creative to the "addons-stage Homepage Sponsored Shelf" on Adzerk for the only Sponsored add-on I could find on stage. I know that sometimes it takes awhile for it to show up in the responses.

**Comment by ioanarusiczki** [comment] 2020-11-10 11:44
@bobsilverberg Results on AMO stage:
- the POST requests on https://addons.allizom.org/api/v4/shelves/sponsored/impression/ after the homepage loads and https://addons-dev.allizom.org/api/v4/shelves/sponsored/event/  at click and install are present. Issues used as reference: https://github.com/mozilla/addons-frontend/issues/9762 and https://github.com/mozilla/addons-frontend/issues/9720

- there's only one addon on the shelf so I could not verify https://github.com/mozilla/addons-server/issues/15678 with https://github.com/mozilla/addons-frontend/issues/9719 on AMO stage. On AMO dev the reordering after a page refresh was working well. 

- making serveral requests on the shelf API https://addons.allizom.org/api/v4/shelves/sponsored/ I've noticed that sometimes it returns 0 addons and sometimes it's 1. As a result, the frontend sometimes shows the shelf with 1 addon and sometimes the shelf is not displayed.  This issue is not reproducible on AMO dev - the 6 addons are shown (as I mentioned in https://github.com/mozilla/addons-server/issues/15617#issuecomment-708289590)

**Comment by bobsilverberg** [comment] 2020-11-10 14:26
@ioanarusiczki Thanks for verifying this. I just added some more matching add-ons to Adzerk that should match up with sponsored add-ons on stage. It often takes awhile for these to show up in queries, but hopefully at some point soon there will be a few more results to work with.

I'm not sure what's happening with the "sometimes 0 results" thing. I recall seeing that on dev when we first started testing this as well. Let's see if that improves when the new add-ons show up.

**Comment by bobsilverberg** [comment] 2020-11-10 14:28
> Prod currently has the list of 5 that we have on the pilot. I don't know who's managing the stage list.

I assume that everything is configured properly so that when we enable this on prod, only Adzerk creatives that correspond to prod add-ons will be used? Can you confirm that @eviljeff?

**Comment by eviljeff** [comment] 2020-11-10 14:37
> 
> 
> > Prod currently has the list of 5 that we have on the pilot. I don't know who's managing the stage list.
> 
> I assume that everything is configured properly so that when we enable this on prod, only Adzerk creatives that correspond to prod add-ons will be used? Can you confirm that @eviljeff?

I don't know who's managing the stage list either 😆 

Ops added the prod credentials for Adzerk to the ENV file.

**Comment by bobsilverberg** [comment] 2020-11-10 14:44
> 
> I don't know who's managing the stage list either 😆
>

Well, apparently I am. 😛 
 
> Ops added the prod credentials for Adzerk to the ENV file.

Ok, so on prod we're using an entirely separate Adzerk account, so there's no danger of retrieving a creative that was created for dev or stage?

**Comment by eviljeff** [comment] 2020-11-10 15:12
It's a separate account for prod, yes.

**Comment by ioanarusiczki** [comment] 2020-11-11 10:26
@bobsilverberg Some techincal issues on stage right now but the sponsored shelf is loading. 

Same problems though, it shows 1, 2, 3 or maximum of 4 addons. 

Name and IDs:
manthease-mosel-codcanzeemanthease-mosel-codcanzee ID 1004189 Sponsored
NoScript Security Suite ID 722 Sponsored
RoboForm Password Manager ID 1004704 Sponsored
SearchbyImageSearchSearchbyImageSearchSearchbyImag ID 620019 Sponsored
Search by Image ID 1004532 Verified
Activity Log check ID 620410 Sponsored
Ciuvo - ID 249334 - which look like it's been deleted

![right now](https://user-images.githubusercontent.com/33448286/98800472-20529f00-2419-11eb-8dd5-d12756e98ef3.gif)


No matter how many times I reload AMO dev - the behavior since https://github.com/mozilla/addons-server/issues/15617#issuecomment-708289590 didn't change.

**Comment by eviljeff** [comment] 2020-11-11 14:40
Are all 14 of those creatives defined in the stage shelf actually valid promoted addons?  Otherwise the response from Adzerk is going to get padded by add-ons we can't display each time (and the more they aren't displayed, the more they will be included as Adzerk tries to equalise out the impression counts).

**Comment by eviljeff** [comment] 2020-11-11 14:41
If we're trying to test normal operation there shouldn't be any invalid add-ons in the Adzerk flight - that's an error condition that will send an email to AMO admins about for prod AMO.

**Comment by ioanarusiczki** [comment] 2020-11-11 15:50
@eviljeff 

 I edited the stage [flight](https://app.adzerk.com/#!/flight/12619540/edit/) added 2 line and 2 verified addons. 
When I had all 9 add-ons active in Adzerk the frontend displayed in rotation 6 add-ons (including the line and verified). 

I de-activated 3 of them, so there are 6 available add-ons in Adzerk right now. I refreshed AMO stage - several times and sometimes I see 4 addons, other times 5 addons, but never 6. 

![ultimele teste](https://user-images.githubusercontent.com/33448286/98833051-3dea2d80-2446-11eb-8f22-3d580e5105bc.gif)

**Comment by eviljeff** [comment] 2020-11-11 17:50
I can confirm with a manual curl query there is normally only 4 or 5 results (I did get 6 once).  I can't see why.

**Comment by ioanarusiczki** [comment] 2020-11-12 10:04
@eviljeff 

As I said: https://github.com/mozilla/addons-server/issues/15920#issuecomment-725969126

AMO stage: 
active addons on AMO stage in Adzerk and AMO:
1002798,1004704,620410,1005144,619985,1004511
Unlike in the dev flight I did not remove addons, I left them not being "active".  I see 5 add-ons

Result:

![not 6 on AMO stage](https://user-images.githubusercontent.com/33448286/98925315-835a3980-24de-11eb-95e6-3ae1b888c777.gif)

Then I removed all the add-ons which were not "active" from the flight and I finally have 6 add-ons but sometimes 5. 

![5 or 6 on AMO stage](https://user-images.githubusercontent.com/33448286/98925843-2f9c2000-24df-11eb-891a-059dd43ccf98.gif)

I'm going to reopen.

**Comment by bobsilverberg** [comment] 2020-11-12 14:52
I just double checked the creatives in the stage flight and they all seem valid. I am also consistently seeing 6 add-ons in the sponsored shelf now. Is this another case of Adzerk just taking some time to catch up with changes to creatives?

**Comment by ioanarusiczki** [comment] 2020-11-12 15:00
@bobsilverberg AMO dev still has that issue right now.

**Comment by bobsilverberg** [comment] 2020-11-12 15:03
I'll double check the creatives in the dev flight as well.

**Comment by eviljeff** [comment] 2020-11-12 15:07
while testing yesterday we came up with a theory that Adzerk was purposely excluding certain creatives to spread out the impression target over the defined period of the flight.  There isn't a way to confirm this for sure, though we noted it was the creatives with higher impression counts that were excluded and their status in Adzerk changed to "likely to hit target" (the little status bar turned green).

**Comment by bobsilverberg** [comment] 2020-11-12 15:08
Is there anyone at Adzerk that we can ask about this?

**Comment by bobsilverberg** [comment] 2020-11-12 18:14
As this seems to be working fine on prod, I think we can re-close this issue.

**Comment by ioanarusiczki** [comment] 2020-11-13 10:23
@bobsilverberg 
-dev looks good today. 6/6 displayed all times.
- stage looks good today. 
- prod is having, 5 or 6. My guess is it will look fine if we wait a little more. 

The feature is on prod - I'll close this.

**Closed by ioanarusiczki** 2020-11-13 10:23 UTC
Labels: priority: p3
