### ISSUE TITLE
Star breakdown section is not updated after submitting a new review

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6093] opened 2018-08-28 14:07 UTC
STR:

1. Log in to AMO -dev
2. Select an add-on to view its details page
3. Observe the current star breakdown
4. Submit a new review
5. Observe the star breakdown again

Actual result:
The star breakdown is not updated after a new review is submitted

Expected result:
Star breakdown is updated to reflect the new rating

Notes:
- reloading the page will not fix the issue
- reproduced on AMO -dev with FF61, Win10x64

![star not populated](https://user-images.githubusercontent.com/31961530/44728235-9ee6ee80-aae4-11e8-87df-10a90aad3102.gif)

**Comment by bobsilverberg** [comment] 2018-08-28 14:46
This seems like a duplicate of https://github.com/mozilla/addons-frontend/issues/5986. What do you think @AlexandraMoga / @kumar303 ?

**Comment by AlexandraMoga** [comment] 2018-08-28 14:51
@bobsilverberg I have filed this as a separate issue because when #5968 was reported, the add-on details page was not affected, therefore I assumed that something was changed in between that caused/exposed this regression. It is possible that the root case is the same.

**Comment by kumar303** [comment] 2018-08-29 20:13
> reloading the page will not fix the issue

I refreshed after about 20 minutes and that fixed it. Thus, I think it's a duplicate of https://github.com/mozilla/addons-frontend/issues/5986

This wait time of 20 minutes is longer than before but I'm not sure if that's a dev issue or what. I will use https://github.com/mozilla/addons-frontend/issues/5986 to investigate what's going on here. It is definitely something we need to fix.

**Closed by kumar303** 2018-08-29 20:13 UTC
Labels: component: add-on ratings, priority: p2, type: regression

**Comment by kumar303** [comment] 2018-08-29 20:29
Actually, I just timed it with a stopwatch. It took 7 minutes to update.

**Comment by bobsilverberg** [comment] 2018-08-29 20:33
> Actually, I just timed it with a stopwatch. It took 7 minutes to update.

An actual stopwatch, or the stopwatch feature of your phone/computer?

**Comment by kumar303** [comment] 2018-08-29 20:50
The stopwatch app on my phone ☎️
