### ISSUE TITLE
"Oops! We can’t find that page" on the dictionaries page

### ISSUE THREAD

**Issue by NatoBoram** [mozilla/addons-frontend#7658] opened 2019-03-01 17:54 UTC
### Describe the problem and steps to reproduce it:

1. Right click in a text box
2. Languages
3. Add Dictionaries...

Alternatively, you can directly visit https://addons.mozilla.org/en-CA/firefox/dictionaries/

### What happened?

> **Oops! We can’t find that page**
>
> ---
>
> If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:
>
> * The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
> * Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.
>
> If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by [filing an issue](https://github.com/mozilla/addons-frontend/issues/new/). Tell us where you came from and what you were looking for, and we'll get it sorted.
> 
> Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available [extensions](https://addons.mozilla.org/en-US/firefox/extensions/) or [themes](https://addons.mozilla.org/en-US/firefox/themes/).

### What did you expect to happen?

This page should appear : https://addons.mozilla.org/en-CA/firefox/language-tools/

### Anything else we should know?

![Wrong page](https://user-images.githubusercontent.com/10495562/53656693-0e6ba100-3c22-11e9-8fb6-d4948361a706.png)

![Correct page](https://user-images.githubusercontent.com/10495562/53656738-33601400-3c22-11e9-8f5f-1f19b04cac3d.png)

![Firefox](https://user-images.githubusercontent.com/10495562/53656638-dbc1a880-3c21-11e9-8016-fb076dc7aa42.png)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

**Comment by kumar303** [comment] 2019-03-01 18:13
Thanks for the bug report. This looks like a regression caused by https://github.com/mozilla/addons-server/issues/10428

**Comment by muffinresearch** [comment] 2019-03-01 18:16
I think this is a higher priority than next couple of releases since it's a direct link from Firefox to a 404.

**Comment by muffinresearch** [comment] 2019-03-01 18:19
This will need a fix similar to https://github.com/mozilla-services/cloudops-deployment/pull/2924/commits/d5fac892d9709bf01158241a7198b8bff56e9308

**Comment by kerryland** [comment] 2019-03-02 19:33
You could throw in an http redirect in the meantime

**Comment by willdurand** [comment] 2019-03-04 13:29
cc @autrilla and @bqbn: this seems like an important issue as it comes from FF

**Comment by willdurand** [comment] 2019-03-04 17:40
A fix has been deployed to add a redirect. Sorry for the inconvenience!

**Closed by willdurand** 2019-03-04 17:40 UTC
Labels: component: legacy pages, priority: p1

**Comment by AlexandraMoga** [comment] 2019-03-05 10:36
Verified fixed in FF 65.0.2 on Win10x64

![2019-03-05_12-34-35](https://user-images.githubusercontent.com/31961530/53799504-28b7be80-3f43-11e9-977a-7b4868cf5019.gif)

**Comment by gijsk** [comment] 2019-03-13 10:23
@willdurand what measures are in place to ensure we don't redo the URL structures another time and break things again because we miss this link? Was there an audit of logs for 404s to see if there are other in-product links that have gone 404 since the transition in #10428 ?

**Comment by gijsk** [comment] 2019-03-13 10:24
(Note that the redirect will need to stay live at least until EOL of Firefox 60 ESR, and we're updating the Firefox side of things for the new "language-tools" URL in https://phabricator.services.mozilla.com/D21943 which hopefully will make 68.)

**Comment by autrilla** [comment] 2019-03-13 10:34
> @willdurand what measures are in place to ensure we don't redo the URL structures another time and break things again because we miss this link? Was there an audit of logs for 404s to see if there are other in-product links that have gone 404 since the transition in [#10428](https://github.com/mozilla/addons-server/issues/10428) ?

There is nothing in place right now. We don't remove rules very often, though. This bug (and a few others) happened because we switch our routing to default to the new frontend instead of to olympia.

This is one of the reasons I'm not a fan of using nginx for routing, because it's kind of hard to write tests for it to ensure our config works as expected. I suppose we could write some sort of integration test and make nginx return a header specifying what backend it used

**Comment by gijsk** [comment] 2019-03-13 11:01
@autrilla thanks for the quick clarifications.

> This bug (and a few others) happened 

Which others, and are any related to other Firefox in-product links that we should therefore update to avoid wasting HTTP cycles on redirects?

> This is one of the reasons I'm not a fan of using nginx for routing, because it's kind of hard to write tests for it to ensure our config works as expected. I suppose we could write some sort of integration test and make nginx return a header specifying what backend it used

To be clear, I don't know anything about nginx or the projects involved here. I'd just like us to ensure that we have mechanisms in place that help us not to make mistakes that affect our release users the way this did.

I understand that, on a human level, this doesn't happen "that often". But from the perspective of Firefox's 20+-year-old codebase, significant AMO website changes (that impacted URLs) have happened at least 5 times, probably more. I'd like us to get better at those, and not repeatedly run into the same issues. It's hard for humans to keep track of which URLs are relied upon by the product, that list changes every now and then, and ideally there should be a process to make sure those are all tracked separately like we do for SUMO, so it's easier to ensure all of them remain available when refactorings happen. If tests are not possible, perhaps it would be helpful to have a single root for those (://amo/in-product/some-unique-path-plus-locale-code or whatever), so it gets taken into account when changes happen?

**Comment by willdurand** [comment] 2019-03-13 11:15
@gijsk to add some more info based on what @autrilla already said, we should have done a better job because we did not review all the logs before (no in-depth audit before). We should have done that to make sure we did not forget URLs such as the one in this issue. That's too late now, though. We fixed everything ASAP and that put a lot of unexpected work to both ops and QA, so be reassured that, if we ever need to do that again, we'll have a better plan.

> @willdurand what measures are in place to ensure we don't redo the URL structures another time and break things again because we miss this link? Was there an audit of logs for 404s to see if there are other in-product links that have gone 404 since the transition in [#10428](https://github.com/mozilla/addons-server/issues/10428) ?

There is no measure yet but we do have a better understanding of what is used and what is not used anymore. There were URLs we wanted to sunset for a long time, this is done now. We know exactly which URLs are used in addons-frontend and thanks to the nginx changes that happened recently, we also know which addons-server URLs are still used.

There are numerous legacy URLs with redirects to new-ish URLs. This is maybe not documented but it should be documented so that FF could use those new-ish URLs instead of relying on very old URLs. I believe this could be a first actionable measure.

> (Note that the redirect will need to stay live at least until EOL of Firefox 60 ESR, and we're updating the Firefox side of things for the new "language-tools" URL in https://phabricator.services.mozilla.com/D21943 which hopefully will make 67.)

Great!

> To be clear, I don't know anything about nginx or the projects involved here. I'd just like us to ensure that we have mechanisms in place that help us not to make mistakes that affect our release users the way this did.

Yep, that makes sense. We are going to remove a lot of unused legacy code in addons-server and together with the nginx changes, we should have a clear overview of the URLs that are used. This would mean that, as of now, we don't have any unused endpoints. We could probably review some of these endpoints to see if there are endpoints we could deprecate because other endpoints would be more suitable.

> I understand that, on a human level, this doesn't happen "that often". But from the perspective of Firefox's 20+-year-old codebase, significant AMO website changes (that impacted URLs) have happened at least 5 times, probably more. I'd like us to get better at those, and not repeatedly run into the same issues. It's hard for humans to keep track of which URLs are relied upon by the product, that list changes every now and then, and ideally there should be a process to make sure those are all tracked separately like we do for SUMO, so it's easier to ensure all of them remain available when refactorings happen. If tests are not possible, perhaps it would be helpful to have a single root for those (://amo/in-product/some-unique-path-plus-locale-code or whatever), so it gets taken into account when changes happen?

I agree. I am not sure we can have test cases for that though, but we could probably write documentation for the FF endpoints and maybe come up with a roadmap to update endpoints in FF (and then, remove endpoints that become unused because no supported FF versions rely on them).

/cc @diox and @eviljeff because this is more about addons-server than addons-frontend.

**Comment by autrilla** [comment] 2019-03-13 11:22
> Which others, and are any related to other Firefox in-product links that we should therefore update to avoid wasting HTTP cycles on redirects?

I think all the bugs we found after we deployed this change to production were for URLs used by Firefox directly. I'm probably forgetting some, so consider this a non-exhaustive list: #7667, https://github.com/mozilla/addons/issues/931, #7652.

> To be clear, I don't know anything about nginx or the projects involved here. I'd just like us to ensure that we have mechanisms in place that help us not to make mistakes that affect our release users the way this did.
> 
> I understand that, on a human level, this doesn't happen "that often". But from the perspective of Firefox's 20+-year-old codebase, significant AMO website changes (that impacted URLs) have happened at least 5 times, probably more. I'd like us to get better at those, and not repeatedly run into the same issues. It's hard for humans to keep track of which URLs are relied upon by the product, that list changes every now and then, and ideally there should be a process to make sure those are all tracked separately like we do for SUMO, so it's easier to ensure all of them remain available when refactorings happen. If tests are not possible, perhaps it would be helpful to have a single root for those (://amo/in-product/some-unique-path-plus-locale-code or whatever), so it gets taken into account when changes happen?

I totally agree with you. I'm not content with the lack of tests we have for our routes. One thing that could help, other than having a single root, would be to explicitly list all routes used by Firefox in our nginx config, even if they should go to the default backend.

I'm not sure having a single root buys us much, because some requests on that root should go to addons-frontend, and some should go to addons-server.

**Comment by muffinresearch** [comment] 2019-03-13 16:42
@gijsk hi, we discussed this issue in our stand-up. A couple of suggestions came out of that from the team. 

* If all Firefox -> AMO links could be tested in Firefox tests against our stage env (https://addons.allizom.org) it would provide an early warning of 404s prior to any route changes moving to production. This would normally give a minimum of a 48 hour window to prevent broken routes making it into production (tags go to stage on Tuesday and are released on a Thursday).
* If all AMO links used by Firefox could be exposed as prefs that would make it a lot clearer what URLS firefox is linking to for visibility as well as facilitating testing should we need to change something in the future.

**Comment by gijsk** [comment] 2019-03-13 17:39
> @gijsk hi, we discussed this issue in our stand-up. A couple of suggestions came out of that from the team.
> 
>     * If all Firefox -> AMO links could be tested in Firefox tests against our stage env (https://addons.allizom.org) it would provide an early warning of 404s prior to any route changes moving to production. This would normally give a minimum of a 48 hour window to prevent broken routes making it into production (tags go to stage on Tuesday and are released on a Thursday).

Unfortunately that's not feasible as it stands, because Firefox tests are not allowed to rely on external servers (in fact, builtin Firefox code will force it to crash if it realizes it's running tests and is attempting to contact anything else than the local proxy + httpd servers). If they did, they'd go orange if e.g. you didn't have an internet connection, or the server/AWS went down (even for a few seconds) plus they'd cause loads of traffic. I don't see that requirement being relaxed any time soon.

>     * If all AMO links used by Firefox could be exposed as prefs that would make it a lot clearer what URLS firefox is linking to for visibility as well as facilitating testing should we need to change something in the future.

This seems feasible. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1535059 .
