### ISSUE TITLE
"Invisible" add-on is still listed through search suggestions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3815] opened 2017-11-07 09:11 UTC
Steps to reproduce:
1. Submit an extension i.e. https://addons-dev.allizom.org/en-US/developers/addon/webext-vv/versions
2. Wait to be auto-approved
3. Set it to "Invisible"
4. Search the add-on while logged out

Expected results:
Ad-on is not found and is not display through search suggestions.

Actual results:
Add-on is listed through search suggestions.

Notes/Issues:
Verified on AMO-dev FF56(Win 7).
- refreshing the page will list a 404 page;

Video for this issue:
- new pages
![invisible](https://user-images.githubusercontent.com/15685960/32485460-2c29ba3c-c3ac-11e7-80a4-1725d9b75cec.gif)

- old pages
![invisible-old](https://user-images.githubusercontent.com/15685960/32485611-b51a728c-c3ac-11e7-8e4f-6f126e64cb6a.gif)

Relates with #2261

**Comment by muffinresearch** [comment] 2017-11-07 12:56
This is likely to be fixed by the solution for https://github.com/mozilla/addons-server/issues/5999

**Comment by muffinresearch** [comment] 2017-11-07 12:58
Duplicate of https://github.com/mozilla/addons-server/issues/5999

**Closed by muffinresearch** 2017-11-07 12:58 UTC
Labels: project: amo, project: desktop pages
