### ISSUE TITLE
Add-on page for disabled add-on is 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#3522] opened 2017-10-16 16:33 UTC
### Describe the problem and steps to reproduce it:

Go to https://addons.mozilla.org/en-US/firefox/addon/update/ (disabled add-on).

### What happened?

500

### What did you expect to happen?

Something 200 with a page explaing what's going on.

### Anything else we should know?

https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/666643/

**Comment by muffinresearch** [comment] 2017-10-16 22:08
Duplicate of https://github.com/mozilla/addons-frontend/issues/2261

**Closed by muffinresearch** 2017-10-16 22:08 UTC
