### ISSUE TITLE
Implement EULA view

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5376] opened 2018-06-22 20:31 UTC
When you click on a license agreement link on a listing page (like [this one](https://addons.mozilla.org/addon/sovetnik/)), the old site is shown. We should open a EULA page or show it inline. I suppose the same approach would apply for this and the privacy policy (#1828). /cc @pwalm for ux.

**Comment by bobsilverberg** [comment] 2018-07-10 17:41
API support is available via http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-eula-and-privacy-policy.

@pwalm I think we need a mockup for this.

**Comment by pwalm** [comment] 2018-07-20 18:47
EULA/License/Privacy Policy page:
![privacy policy page - 1366px](https://user-images.githubusercontent.com/6797635/43019682-a90125e8-8c12-11e8-9a03-db0870a29791.png)

**Comment by muffinresearch** [comment] 2018-09-28 10:15
Duplicate of #3697

**Closed by muffinresearch** 2018-09-28 10:15 UTC
Labels: component: legacy pages, priority: p3, triaged
