### ISSUE TITLE
Total number of reviews is not correct after the user makes an empty review

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5959] opened 2018-08-16 12:00 UTC
STR:
1. Load AMO dev and go to an add-on's detail page.
2. From review section make an empty review - mark the stars click Submit review without adding text.
3. Observe the total number of reviews displayed on the top right corner.

Actual result:
Not present in "Reviews" ->the review is not counted but it is displayed in the detailed ratings below.

Expected result:
The number of ratings increased with one more in the "Reviews".

Notes:
This issue is reproducible on AMO -dev with FF61(Win10).
It is not reproducible on AMO -stage.

![number of reviews](https://user-images.githubusercontent.com/33448286/44207236-1ae84a80-a165-11e8-901c-08fed8e3088e.gif)

**Comment by bobsilverberg** [comment] 2018-08-16 12:25
@ioanarusiczki This looks like the expected behaviour. The number of reviews listed at the top is the number of ratings that include a text review, and yours does not, which is why it is not counted. However, the star breakdown component counts the number of ratings, which include ratings without a text review, and the one you added does fall into that category.

Does that make sense, or am I missing something else about this bug report?

**Comment by AlexandraMoga** [comment] 2018-08-17 10:41
@bobsilverberg I know that we've been seeing this behavior for quite some time, but before the star breakdown component was introduced, the difference between reviews  and ratings count was not so visible.
While for us this difference might make sense, for some of our users it might look confusing.

Take the following example:

- visit https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/?src=featured
- count the total number of ratings from the star breakdown - it should total 840
- check the Reviews count - it says 837

![image](https://user-images.githubusercontent.com/31961530/44262180-c5727300-a222-11e8-93c2-3d98f2597cdb.png)


Maybe we should think of a way to make this difference more transparent to the users

**Comment by bobsilverberg** [comment] 2018-08-17 17:54
I understand where you're coming from @AlexandraMoga, but everything you point out is as intended. We specifically changed the count at the top *from* being a count of ratings to being a count of reviews. I'm honestly not sure how many people would bother to add up all the numbers on the right and then feel confused that the total isn't the same as the total on top, so I do think that the screen is fine as is.

@jvillalobos and/or @pwalm what do you think?

**Comment by jvillalobos** [comment] 2018-08-17 18:45
One possible way to address this is to just use ratings, and display "empty" ratings in the All Reviews page.  Another would be to not show the numbers and just show the proportion of ratings.

However, I agree with Bob that at the moment it doesn't appear to be a big problem. We should reconsider if it turns out to confuse many users.

**Comment by kumar303** [comment] 2018-08-17 22:33
All of these design changes were intended and we believe that they will better communicate the ratings and reviews associated with an add-on.

> We should reconsider if it turns out to confuse many users.

I agree with this. As I recall, we have some more user research planned to get feedback on these new pages now that they have landed.

Since this is working as intended, I'm closing it. Thanks for all of the input.

**Closed by kumar303** 2018-08-17 22:33 UTC
Labels: component: add-on ratings, type: bug
