### ISSUE TITLE
500 error page (in development) when add-on recommendation service is down

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6001] opened 2018-08-21 21:00 UTC
### Describe the problem and steps to reproduce it:

- Do something in the recommendations saga to trigger [`abortFetchRecommendations()`](https://github.com/mozilla/addons-frontend/blob/4cbac1c586e49936e3a1327332e9d942d6b0e71e/src/amo/sagas/recommendations.js#L49). For example, if the API is down, the saga would abort with this error:

```
Error calling: /api/v3/addons/recommendations/ (status: 500)
```
- Load any add-on detail page

### What happened?

A 500 page is shown

### What did you expect to happen?

The add-on detail page should be shown without any recommendations.

### Anything else we should know?

The 500 page is caused by this component error:

```
Caught application error: Invariant Violation: "outcome is required"
```

See https://github.com/mozilla/addons-frontend/blob/4cbac1c586e49936e3a1327332e9d942d6b0e71e/src/amo/components/AddonRecommendations/index.js#L92

~~This will only affect development since `invariant()` doesn't throw in production~~ (it does throw 👻 ). I'm not sure what would happen in production but the tracking event will be strange at the very least.

This only happened to me while hot reloading so that may be a prerequisite. Low priority issue but nice to fix!

**Comment by hereisnaman** [comment] 2019-01-03 20:47
@kumar303 @willdurand I want to pick up this issue.

Why not we don't send any GA ping if the outcome is missing. Or I can handle it the error and set recommendations object with a proper fallbackReason and outcome to some strings.

**Comment by kumar303** [comment] 2019-01-22 19:12
Adding GA might be useful but please do it in a separate issue. The patch for this issue should be focused on solving the problem in the description.

**Comment by hereisnaman** [comment] 2019-01-23 04:11
@kumar303 the problem is only because there is no data in form of an object, assigned to `outcome` that can be sent to GA, either I can add proper data via state reducer or I can remove the Invariant Violation Check.

**Comment by kumar303** [comment] 2019-01-23 15:38
The first thing to do is to stop the invariant errors. You can do this by amending this line:

https://github.com/mozilla/addons-frontend/blob/eda73e0d139cbc0e4bd3255990d69d39341a24b5/src/amo/components/AddonRecommendations/index.js#L88-L90

with something more like:

```js
if (loading || this.props.errorHandler.hasError()) {
  return;
}
```

**Closed** 2020-02-04 20:05 UTC
Labels: component: code quality, contrib: welcome, priority: p4, triaged

**Comment by ioanarusiczki** [comment] 2020-02-10 13:12
@bobsilverberg If qa can verify this please add some STR. 
Thanks!

**Comment by bobsilverberg** [comment] 2020-02-10 14:09
@ioanarusiczki This isn't straightforward to reproduce without changing code and running it locally. I'm going to mark it as `qa:not needed`.

**Comment by bobsilverberg** [comment] 2020-02-10 14:11
@ioanarusiczki Actually, while you cannot easily reproduce this use case, we can still check for regressions with the `AddonRecommendations` card, and make sure that the GA pings are still being sent as expected.

**Comment by ioanarusiczki** [comment] 2020-02-11 15:13
@bobsilverberg 
- I did not find regressions on the frontend pages - the recommended badge is available. 
- I could add/remove the recommended badge for an add-ons. 
- the only available GA I see (when an add-on detail page is loaded) in the console is 
`[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Recommendations Shown","eventAction":"recommended_fallback-timeout","eventLabel":"Turlink"}` 

I don't know if that's the event you are referring to. Let me know if there's something else I should be checking. 
Thanks!

**Comment by bobsilverberg** [comment] 2020-02-11 15:26
> * the only available GA I see (when an add-on detail page is loaded) in the console is
>       `[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Recommendations Shown","eventAction":"recommended_fallback-timeout","eventLabel":"Turlink"}`
> 
> 
> I don't know if that's the event you are referring to. Let me know if there's something else I should be checking.
>

No, that's everything. Thanks!
