### ISSUE TITLE
Cards have tiny or cramped up text

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#4431] opened 2018-02-22 05:02 UTC
### Describe the problem and steps to reproduce it:

Go to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/.

Look at the first card, `.Addon-header-info-card`:
![screenshot-2018-2-22 ublock origin add-ons for firefox](https://user-images.githubusercontent.com/8336638/36520249-f9590f64-17b5-11e8-8083-6c2f8409ec03.png)
There is a whole lot of white space and yet the line-height is too small - the `g` in `uBlock Origin` is almost touching the `l` in `Raymond Hill`.

Also, look at the add-on description, `.AddonDescription-contents`:

![screenshot-2018-2-22 ublock origin add-ons for firefox 2](https://user-images.githubusercontent.com/8336638/36520633-0c45c098-17b8-11e8-9e93-9c0ff435cc0e.png)

This is just painful to read. Between the previous design and this one, at least on Windows, the font-size of what is usually the most text heavy section has gone down from 13px to 12px, while the x-height of the font in use has also slightly decreased. All of this while padding and line-height for the same section have both increased. If I change the font-size and the line-height to their older values, the entire section is significantly easier to read while being shorter in total height.

I'm on a 15.5", 1920x1080 screen at 125% scaling. I don't typically have trouble reading text on other sites.

**Comment by muffinresearch** [comment] 2018-02-26 11:19
@pwalm Assuming I'm reading the mocks in Sketch correctly the default text copy looks to be 15px not 12px - is that right?

**Comment by bobsilverberg** [comment] 2018-03-07 17:51
Duplicate of #4520

**Closed by bobsilverberg** 2018-03-07 17:51 UTC
Labels: component: accessibility, priority: p3, type: papercut
