### ISSUE TITLE
New Mobile Optimized website not available for Android phones

### ISSUE THREAD

**Issue by iamVP7** [mozilla/addons-frontend#241] opened 2016-04-20 20:25 UTC
- I was trying to open New tab in **Firefox for Android Version 45.0.2** and **Android 6.0**
- I got the link[1]
- Clicked the link and it opened in new tab and i saw a collection
![photo249824598658492409](https://cloud.githubusercontent.com/assets/3106852/14689215/0475d850-0764-11e6-9dd8-2f40a3fa61ef.jpg)

- On clicking Add-ons in the left top corner, I hope i am going to old view
![photo249824598658492410](https://cloud.githubusercontent.com/assets/3106852/14689243/2035cf8c-0764-11e6-91c0-07def5079334.jpg)

[1]https://addons.mozilla.org/en-US/firefox/collections/mozmj/sparkle/?utm_source=mobile-snippet&utm_medium=snippet&utm_content=theme&utm_term=134&utm_campaign=firefoxforandroid

**Comment by mstriemer** [comment] 2016-04-20 21:40
I believe this is expected. There are several pages throughout the site that never had mobile versions created and if you go to them you'll get the desktop version. The recent restyle of the site only targeted the desktop version so that's why this looks extra weird.

I believe it was decided to not restyle the mobile site since we don't have a visual design for it and it's probably a bit trickier to update, but @tofumatt would know more.

Thanks for filing, if you find anything else please file it at [mozilla/addons-server](https://github.com/mozilla/addons-server/issues/new) as this project is just starting out and isn't actually used in production yet.

**Comment by tofumatt** [comment] 2016-04-20 21:49
Confirmed; this is (unfortunately) working as expected. We don't have mobile pages for every page, and we don't have the resources to justify a mobile redesign right now. Sorry but for now this is closed as a won't fix issue.

But thanks a lot of your bug report. like @mstriemer said: if you find other issues please let us know 😄

**Closed by tofumatt** 2016-04-20 21:49 UTC
