### ISSUE TITLE
Grey blank page displayed when pressing on author's name on add-on details pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1732] opened 2017-02-07 14:07 UTC
Steps to reproduce:
1.On Android , go to  AMO-dev and open any add-on details page
2.Press on author's name

Expected results:
Details about author are displayed

Actual results:
Grey blank page displayed

Please see video for this bug : 
![greypage](https://cloud.githubusercontent.com/assets/1583842/22694323/7595692a-ed4f-11e6-9b7a-50c3f528998c.gif)

**Comment by muffinresearch** [comment] 2017-02-08 16:54
Could you use more investigation to determine what's going on.

**Comment by mstriemer** [comment] 2017-02-08 17:34
So if you try this on desktop in responsive mode it will load the old site in desktop (since it's in a new window). If you copy that url and paste it into the address bar you get a 500 from the frontend.

We don't have a page for this, so maybe we need to update nginx to proxy `/blah/blah/user/blah/` to addons-server.

**Comment by vcarciu** [comment] 2017-02-24 17:09
Do you still needs more info on this?

**Comment by mstriemer** [comment] 2017-02-24 18:01
I just tried this again and it still seems to be the case. @muffinresearch do you know if we have a list of URLs to allow for mobile pages set up? We should probably get Jason to update the nginx config with that.

**Comment by muffinresearch** [comment] 2017-02-24 19:46
> I just tried this again and it still seems to be the case. @muffinresearch do you know if we have a list of URLs to allow for mobile pages set up? We should probably get Jason to update the nginx config with that.

There's no specific config of URLS for the mobile site, that would be hard to keep track of the. We do hower have fall-backs in place. 

The way it works is that 404s in the mobile site are redirected to addons-server. There's still an edge case for some urls which shouldn't be getting a locale redirect, but that's been filed separately. 

In this particular case there are 2 bugs in 1 - First the url is a 500 and not a 404 due to an exception, and secondly the 500 is blank. 

This is a duplicate of https://github.com/mozilla/addons-frontend/issues/1880

**Closed** 2017-02-24 19:46 UTC
Labels: needs: info, priority: blocks release, project: mobile pages v1, state: duplicate
