### ISSUE TITLE
personas plus is not working , I can't change themes or add new ones. i uninstalled personaas & now i cant even install the add on again . every time i try to do anything wiht it i get this: 

### ISSUE THREAD

**Issue by peaches67** [mozilla/addons-frontend#5129] opened 2018-05-29 12:59 UTC

**Comment by peaches67** [comment] 2018-05-29 13:00
Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.

**Comment by muffinresearch** [comment] 2018-05-29 15:26
@peaches67 please can you provide more information? This sounds like an issue with personas plus but you also mention a server error. Can you provide the URL you're on when you see this message?

**Comment by willdurand** [comment] 2018-06-27 14:55
Duplicate of #5116

**Closed by willdurand** 2018-06-27 14:55 UTC
Labels: needs: info
