### ISSUE TITLE
Design break in featured/top rated extension

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#2800] opened 2017-07-13 17:22 UTC
### Describe the problem and steps to reproduce it:
Navigate to https://addons-dev.allizom.org/en-GB/firefox/extensions/

### What happened?
Design break on featured/top rated addons?

### What did you expect to happen?
Layout without break.

### Anything else we should know?
Produced only on dev server
<img width="1274" alt="screen shot 2017-07-13 at 10 47 49 pm" src="https://user-images.githubusercontent.com/5318732/28178903-bd6f380e-681d-11e7-82ab-c4444a007a18.png">

**Comment by tofumatt** [comment] 2017-07-13 17:41
Is this happening locally as well? Maybe just a bad deploy if not.

**Comment by tsl143** [comment] 2017-07-13 17:48
Yes its reproduced on local setup too

**Comment by tofumatt** [comment] 2017-07-17 12:49
#2814 is a dupe of this but I assigned it already so I'm closing this is a duplicate (even though it was first).

**Closed by tofumatt** 2017-07-17 12:49 UTC
Labels: platform: desktop, project: desktop pages, type: regression
