### ISSUE TITLE
Desktop view will appear after clicking the theme creator name.

### ISSUE THREAD

**Issue by danialmas** [mozilla/addons-frontend#2012] opened 2017-03-08 13:44 UTC
### Describe the problem and steps to reproduce it:
=> **Problem**: I clicked a theme in mobile view when I click on the creator name, it shown me the desktop view of it.
**Reproduce**: 
•	Go to the link "https://addons-dev.allizom.org/en-US/firefox/".
•	Click any of the theme.
•	Click to the theme creator name.

### What happened?
=> It will show the creator profile in desktop view.

### What did you expect to happen?
=>It should remain in mobile view after go to the creator profile.
![img_20170308_192210](https://cloud.githubusercontent.com/assets/15236297/23707050/06e37866-043b-11e7-8050-d4b570438e80.jpg)
![screenshot_2017-03-08-19-22-24-900_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23707049/06e228ee-043b-11e7-873d-b93a43aafd09.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ValentinaPC** [comment] 2017-03-08 13:57
According to https://github.com/mozilla/addons-frontend/issues/1975, this is how it suppose to work.

**Comment by muffinresearch** [comment] 2017-03-08 14:00
> According to #1975, this is how it suppose to work.

For now, the first release of the mobile site was to get parity with the existing mobile site. The users page doesn't currently exist in mobile form it will be added in due course.

**Comment by muffinresearch** [comment] 2018-01-29 17:06
Marking as a duplicate of https://github.com/mozilla/addons-frontend/issues/2749 since that's the issue that covers the implementation of this feature.

**Closed by muffinresearch** 2018-01-29 17:06 UTC
Labels: project: amo, project: desktop pages, triaged
