### ISSUE TITLE
Reviews are missing the title - only when the date of the added/edited review is clicked the reviews detail page is displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5469] opened 2018-07-02 09:32 UTC
STR:
1. Load AMO dev and go to View my profile. Make sure you reviewed some add-ons
2. Try to open the reviews page of an add-on by clicking it from the profile page

Expected result:
If the review is clicked the add-on's review detail page is displayed.

Actual result:
Only when the date it clicked the add-on's review detail page is displayed.

Notes:
This issue is reproducible on AMO dev with FF61(Win10).
The old pages contained a "Title" - the name of the reviewed add-on which could be clicked to open the page.

![title](https://user-images.githubusercontent.com/33448286/42156533-fb7d71e6-7df3-11e8-9a03-136a00154d13.gif)

**Comment by muffinresearch** [comment] 2018-07-02 11:29
The title is not there by design - it was removed previously both on the server and in the frontend. In general linking to a single review by the date is reasonable - it's a pretty common pattern. 

I'm not sure how strong the use-case is for needing to be able to click on the whole review. CC'ing @pwalm for UX input.

**Comment by pwalm** [comment] 2018-07-03 17:55
- Correct, no title for reviews.
- And yep, clicking the date should take you to the review page.
- No need to make the whole review clickable.

**Comment by willdurand** [comment] 2018-07-04 13:54
I guess we can close this issue now.

**Closed** 2018-07-04 13:54 UTC
Labels: component: user profile, needs: info
