### ISSUE TITLE
Replying to reviews should not be limited to visible owners

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6475] opened 2018-10-01 20:15 UTC
The new front-end is limiting review replies to visible owners. However, all users associated with an add-on, Developer or Owner, visible or not, should be able to reply.

Marking this as a P2, since developers are running into this due to last week's push of https://github.com/mozilla/addons-frontend/issues/2771.

**Comment by kumar303** [comment] 2018-10-02 17:17
Hmm, it looks like we don't have enough API data to do this yet. I opened https://github.com/mozilla/addons-server/issues/9573 to get access to this data.

**Comment by kumar303** [comment] 2018-10-02 19:14
Whoops, this is a dupe of https://github.com/mozilla/addons/issues/526 . Do we need to keep both open? They're in different repos.

**Comment by jvillalobos** [comment] 2018-10-02 23:01
It's okay to dupe this to that one, but the priority still matters. Developers will be running into this more.

**Comment by kumar303** [comment] 2018-10-03 14:21
Okay. I increased the priority of https://github.com/mozilla/addons/issues/526

**Closed by kumar303** 2018-10-03 14:21 UTC
Labels: component: add-on ratings, needs: api, priority: p2, state: duplicate, triaged, type: regression
