### ISSUE TITLE
Use "srcset" in screenshot viewer (add-on detail page)

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1519] opened 2016-12-22 04:13 UTC
UPDATE June 2018:

The API now returns screenshots of different sizes along with the dimensions for each version. We can request different dimension to be implemented in the API so that we can use them in the frontend.

The idea would be to use `srcset` for that, either using the current viewer (ttp://photoswipe.com/documentation/responsive-images.html) or by adopting a new viewer library that has `srcset` support built-in.

---

~~Currently the frontend has no idea what size an image is. Because of that it is currently set to 320x200 since that seemed reasonable for a mobile device. This is fine for landscape photos but isn't great for portrait and the full size image doesn't scale up at all unless you pinch to zoom.~~

~~addons-server has the size data, we need it returned in the API so that we can come up with a good size though.~~

~~Once we've got the data, let's pass it to photoswipe and maybe add some scaling logic so it's never bigger than the screen.~~

**Comment by muffinresearch** [comment] 2017-01-03 13:07
Does the component support `srcset` [1] ? If not we should think about adding that or patching upstream. Then we can supply various image sizes (we're planning to expand support at upload for more formats - we can add input to that project) and let the client do the heavy lifting as to what image is the best fit.

[1] http://caniuse.com/#search=srcset

**Comment by mstriemer** [comment] 2017-01-03 17:00
It doesn't support `srcset` but since we tell it what pictures to use we could do that ourselves. There is some documentation [1] on how to accomplish this, it doesn't look like a ton of fun unfortunately.

[1] http://photoswipe.com/documentation/responsive-images.html

**Comment by Ryuno-Ki** [comment] 2017-01-05 19:48
Could a service like Cloudinary's [Responsive Image Breakpoints Generator](http://www.responsivebreakpoints.com/) ease the job?

@darkwing seem to be [pretty excited](https://davidwalsh.name/cloudinary-filters) about Cloudinary after all …

**Comment by dessant** [comment] 2017-10-31 10:32
The carousel currently stretches images to fill the available area, making them blurred in most cases, because the backend limits screenshot sizes to 700x525.

**Comment by kumar303** [comment] 2017-10-31 17:50
@dessant could you provide a link to an add-on detail page that demonstrates this?

**Comment by eviljeff** [comment] 2017-10-31 18:30
Should be reproducible with any add-on that has screenshots, if your browser is above 700px wide.  e.g. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ - the screenshot always resizes to fill the browser width.

**Comment by dessant** [comment] 2017-10-31 19:17
Yeah, all listings are affected. @kumar303, it's easier to spot when the page is loaded in responsive design mode with 4k resolution.

**Comment by rebmullin** [comment] 2018-07-05 18:51
When addressing this, which should start looking into a new gallery that works well with srcset. Also consider https://github.com/mozilla/addons-frontend/issues/5326#issuecomment-402802879

**Comment by willdurand** [comment] 2019-07-05 10:05
I don't think we'll ever do this, so I'm closing this issue for now.

**Closed by willdurand** 2019-07-05 10:05 UTC
Labels: component: screenshot viewer, needs: api, priority: p3, triaged
