### ISSUE TITLE
Sorting on mobile is not working if trying to sort add-ons from categories

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1737] opened 2017-02-07 16:01 UTC
Steps to reproduce:
1.On Android, go to any add-ons categories(ie. Block Ads)
2.Try to sort the add-ons by any criteria(Recently Updated, Most Users, etc...)

Expected results:
Sorting is working

Actual results:
Sorting is not working inside categories and it looks like _Relevance_ is always selected

Notes:
Not reproducible in search results

Please see video for that bug : 
![sortmobile](https://cloud.githubusercontent.com/assets/1583842/22699144/4c314968-ed5f-11e6-9b99-564e06851c09.gif)

**Comment by tofumatt** [comment] 2017-02-07 17:27
This is a duplicate of #1626

**Closed by tofumatt** 2017-02-07 17:27 UTC
