### ISSUE TITLE
Horizontal scrollbar under carousel section at page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3364] opened 2017-10-05 14:13 UTC
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Observe carousel section 
3. Refresh the page with the eyes on the carousel

Expected results:
There are no display or layout issues.

Actual results:
There is a horizontal scroll-bar displayed for few seconds.

Notes/Issues:
Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Video for this issue:
![scrollb](https://user-images.githubusercontent.com/15685960/31231750-76eb944e-a9f0-11e7-9217-a8be7446ca42.gif)

**Comment by tofumatt** [comment] 2017-10-05 14:20
This is as intended; if the carousel is not entirely loaded I think we should provide a scrollbar.

**Comment by ValentinaPC** [comment] 2017-10-06 06:08
I think we should not show it, if we hide it after. :)
The carousel is not entirely loaded as we speak, but we have the dots, or we can swipe, to navigate between the options.
Just my opinion.

**Comment by tofumatt** [comment] 2017-10-06 08:41
I’d certainly prefer not to show it, to be clear... but doing so will reduce the accessibility of the site for users without JS as they won’t be able to scroll. 😓

But then it’s the homepage and most users use JS. Maybe it’s an okay trade off, it’s not vital content in terms of using the site overall.

Okay, yeah, let’s hide the scroll bars. 👍🏻

**Comment by muffinresearch** [comment] 2017-10-11 12:03
Since we're now replacing the carousel with static content this is a wontfix: https://github.com/mozilla/addons-frontend/issues/3430

**Closed by muffinresearch** 2017-10-11 12:03 UTC
Labels: component: homepage, project: amo, project: desktop pages, triaged
