### ISSUE TITLE
Title/Name and Description fields for Collection are blank and do not show up in Edit Collection view.

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4793] opened 2018-04-13 12:09 UTC
### Describe the problem and steps to reproduce it:

The page showing the content of an add-on contains the Title/Name of the Collection AND the description of the collection BUT when you go to edit the collection, that information is not populated in their respective fields. 

### What happened?
Name and Description fields in the Edit Collection window are blank, even though the data shows up on the content view of the collection.

(trying to upload a couple of examples but for some reason this site will not accept the image files)

### What did you expect to happen?
Name and Description fields should be populated so they can be edited.

**Comment by jvillalobos** [comment] 2018-04-13 15:51
Can you provide some links to the collections you're trying to edit? I tested it with one of mine and I can't reproduce the problem.

**Comment by smayer97** [comment] 2018-04-13 19:01
- ANY of my collections will not show the Title/Name in the Edit Collection page and ANY with description info will also not be populated.
Examples:
https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-parental-control/edit/
https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-mr-tech-toolkit/edit/
https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-managing-documents/edit/

**Comment by realslimshanky** [comment] 2018-04-13 19:05
@smayer97 links aren't helpful as they are not accessible. Could you please share screenshots or GIF?

**Comment by smayer97** [comment] 2018-04-14 11:41
I was asked to provide links...Anyway, try as I might, I cannot get github to load the images...I have tried copy & paste, drag & drop, and even selecting the files via the dialog box but github does not respond...it just does nothing. I tried different browsers... so not sure what else to try.

Here are the links again without the /edit/ at the end. That should take you to the collections. 

https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-parental-control/
https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-mr-tech-toolkit/
https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-managing-documents

**Comment by smayer97** [comment] 2018-04-14 16:55
![screen shot 2018-04-13 at 8 01 00 am](https://user-images.githubusercontent.com/6752849/38770565-7fa0fcc8-4004-11e8-89c1-49cbbf7e6c29.png)

![screen shot 2018-04-13 at 8 01 19 am](https://user-images.githubusercontent.com/6752849/38770573-8a5e3c16-4004-11e8-8414-5361e229e7ba.png)

![screen shot 2018-04-13 at 8 02 07 am](https://user-images.githubusercontent.com/6752849/38770574-90b236f8-4004-11e8-9f42-647f780bb531.png)

![screen shot 2018-04-13 at 8 02 25 am](https://user-images.githubusercontent.com/6752849/38770577-95067462-4004-11e8-9af7-7e9b34335ce8.png)

**Comment by bobsilverberg** [comment] 2018-04-16 14:28
I am also unable to reproduce this problem, either locally or in production. @smayer97 Could you possibly attach a picture of the console window for this page? I'm wondering if any errors are shown?

**Comment by smayer97** [comment] 2018-04-16 14:57
Web Console or Browser Console?

**Comment by bobsilverberg** [comment] 2018-04-16 16:32
Web Console, please and thank you. 😃

**Comment by smayer97** [comment] 2018-04-16 17:55
for https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-mr-tech-toolkit/edit/

![screen shot 2018-04-16 at 1 53 28 pm](https://user-images.githubusercontent.com/6752849/38826418-49715660-419f-11e8-8a5e-4dcbb64ad47f.png)

**Comment by smayer97** [comment] 2018-04-16 17:57
for https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-managing-documents/edit

![screen shot 2018-04-16 at 1 56 26 pm](https://user-images.githubusercontent.com/6752849/38826529-9db2149e-419f-11e8-8e97-4c08a4b0ef4c.png)

**Comment by smayer97** [comment] 2018-04-16 17:58
for https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-parental-control/edit/

![screen shot 2018-04-16 at 1 58 15 pm](https://user-images.githubusercontent.com/6752849/38826583-ca68b4de-419f-11e8-878b-8a51e14fe97f.png)

**Comment by jvillalobos** [comment] 2018-04-16 20:46
I can reproduce the issue with the links provided by @smayer97.

**Comment by bobsilverberg** [comment] 2018-05-09 20:49
I don't know what could be the cause of this problem, but I notice that it is a problem with the edit page on the legacy site. That page is currently the only one available on prod, but we do have a new version available on the new front-end on dev. I know that doesn't address the immediate issue, but I guess if we are going to fix this we would need to open an issue for addons-server.

Is this happening for all users?

**Comment by AlexandraMoga** [comment] 2018-05-10 06:26
My guess is that this has something to do with the selected locale.
I was also able to reproduce with my collections when changing to a different locale than the one in which the collection was originally created.

Example 1: 
https://addons.allizom.org/en-US/firefox/collections/amoga1/release-25-apr/edit/ - editable fields are populated
https://addons.allizom.org/en-GB/firefox/collections/amoga1/release-25-apr/edit/ - editable fileds are NOT populated

Example 2:
https://addons.allizom.org/en-GB/firefox/collections/amoga1/collection-in-en-gb/edit/ - editable fields are populated
https://addons.allizom.org/en-US/firefox/collections/amoga1/collection-in-en-gb/edit/ - editable fileds are NOT populated

**Comment by bobsilverberg** [comment] 2018-05-10 11:51
Ah, yes, that makes sense @AlexandraMoga, thanks for that! I'm not sure if there even is a fix for this, and I'm fairly certain if there is it will be complicated and not something we'd implement for the time this page is still only available on the legacy site. @eviljeff do you agree?

**Comment by eviljeff** [comment] 2018-05-10 12:13
@bobsilverberg I agree.  @AlexandraMoga's guess is right - it's locale related - underneath the fields are localizable, even though we don't expose UI to switch (other than changing the url)

**Comment by bobsilverberg** [comment] 2018-05-10 12:28
In that case, I think this issue can be closed. It's not an issue for addons-frontend, and it's not something that will be fixed in addons-server.

**Closed by bobsilverberg** 2018-05-10 12:28 UTC

**Comment by bobsilverberg** [comment] 2018-05-10 12:55
> So I am unclear on the solution or the impact... does this mean that users can still lose access to the title and description when using collections? Not sure how this can be closed without a solution. Is there a work-around?

The problem occurs because the collection was created/edited using one locale, and then an attempt was made to edit it using a different locale. The workaround is to make sure you only use a single locale when you are creating/editing collections. If you come across a collection in a specific locale that is missing these fields, you can just enter them again, after which they should appear on the edit screen, as long as you remain in that locale.

**Comment by smayer97** [comment] 2018-05-10 16:17
Pardon my ignorance but I am not sure what a locale is and how I would affect or change this. In the examples above, I am the creator and as far I can recall, this was created from the computer. And in performing edits all these years, it is only recently that this problem has appeared. HTH.

**Comment by bobsilverberg** [comment] 2018-05-10 16:21
A locale is the language of the web site. Your links all point to the en-GB locale (e.g., https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-parental-control/edit/). A different locale would look like, for example https://addons.mozilla.org/en-US/firefox/collections/smayer97/for-parental-control/edit/.

It seems like your collections were created when you were visiting the site via a locale other than en-GB.

@eviljeff Can we look in the database to verify for which locales names and descriptions have been added for one (or more) of the collections listed above?
