### ISSUE TITLE
The 'log out' state is not captured by the new frontend when a user signs out

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4212] opened 2018-01-24 13:52 UTC
STR:

1. Log into AMO -dev (new frontend)
2. Navigate to a page located on the old AMO (i.e. Developer Hub)
3. Sign out

Expected result:
User is redirected to (new) AMO homepage where he is also logged out

Actual result:
User is still shown as logged in on the new AMO homepage

Notes: 
Reproduced on AMO-dev and stage with FF58 (Win10)

![log out](https://user-images.githubusercontent.com/31961530/35335456-569400d4-011e-11e8-9101-74dc09b32adf.gif)

**Comment by kumar303** [comment] 2018-01-24 18:18
Well, huh. Log out is broken on stage too (but not prod) which means this is something to do with the release tag. I made it a blocker.

I can also reproduce it like this:
- Clear all cookies
- Sign into the frontend
- Click the logout button. This shows a logged out state.
- Refresh the page. This shows a logged in state (the same bug).

**Comment by kumar303** [comment] 2018-01-24 18:38
Wow, good catch @AlexandraMoga 💥 It looks like a server issue: https://github.com/mozilla/addons-server/issues/7388

**Comment by AlexandraMoga** [comment] 2018-01-25 13:14
This appears to be fixed on -dev.  Can we close this issue?

**Comment by diox** [comment] 2018-01-25 14:17
Closing, this was a server issue that was fixed in mozilla/addons-server#7388

**Closed by diox** 2018-01-25 14:17 UTC
Labels: priority: blocks release, project: amo, project: desktop pages

**Comment by AlexandraMoga** [comment] 2018-01-25 15:57
Verified as fixed on AMO-dev, FF58 (Win10, Android 7.0)
