### ISSUE TITLE
"Server error" when logged in.

### ISSUE THREAD

**Issue by dacomboman** [mozilla/addons-frontend#4891] opened 2018-04-28 12:56 UTC
### What happened?
If i try to add an extension when logged in, i get "server error" message and unable to install any extension.
https://snag.gy/go24O5.jpg

### What did you expect to happen?
Extensions would install as usual.
### Anything else we should know?
If i log out, no problem to install any extension.

**Comment by muffinresearch** [comment] 2018-04-30 13:06
@dacomboman could you provide an example of the URL you're on when you're seeing that message?

**Comment by dacomboman** [comment] 2018-04-30 13:12
Hi Stuart,

 

It basically happens on any extension page.

But, for the record, here's a sample:

https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/?src=search

 

If I log out, then I can install the extension.

 

Go figure, this has never happened to me since the beginning of Firefox.

 

-Daniel

**Comment by muffinresearch** [comment] 2018-04-30 16:51
@dacomboman do you see any error messages in the web or browser console? Does this problem persist in a new profile?

**Comment by dacomboman** [comment] 2018-05-01 12:32
Hi Stuart,

 

As previously sent, the only error message I get when trying to install an extension while logged into Mozilla online is this:

 

- - - - -

 

Server Error

Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.

Suggested Pages

*	Browse all extensions <https://addons.mozilla.org/en-US/firefox/extensions/> 
*	Browse all themes <https://addons.mozilla.org/en-US/firefox/themes/> 
*	Add-ons Home Page <https://addons.mozilla.org/en-US/firefox/> 

If you have additional information that would help us you can file an issue <https://github.com/mozilla/addons-frontend/issues/new/> . Tell us what steps you took that lead to the error and we'll do our best to fix it.

- - - - -

-Daniel

**Comment by willdurand** [comment] 2018-05-01 14:09
Hi @dacomboman, are you comfortable with the Dev Tools by chance? If so, could you please look into the network and console panels?

**Comment by EnTeQuAk** [comment] 2018-05-02 08:17
Just looked in sentry and found https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/4288440/ - which doesn't have to be the problem mentioned here but there are a few other errors that happen on the detail pages of an add-on. Might be worth looking into

**Comment by muffinresearch** [comment] 2018-05-02 08:27
@EnTeQuAk ah good catch - that looks like a regression.

**Comment by muffinresearch** [comment] 2018-05-02 08:38
> @EnTeQuAk ah good catch - that looks like a regression. 

As you say it's not clear this is the problem in this issue. I'll file a new issue for that one instead. Downgrading this one until we know more.

**Comment by dacomboman** [comment] 2018-05-02 10:43
Hi William,

 

Sorry didn't get back to you sooner.

I'm afraid I'm not familiar with Dev Tools.

Think I've spotted the window before but never did anything in that area.

 

-Daniel

**Comment by dacomboman** [comment] 2018-05-03 19:50
Hi,

 

Guess you've given up on my case?

For the record, disabled all extensions (more than 20) - still same problem.

 

-Daniel

**Comment by willdurand** [comment] 2018-05-03 19:51
@dacomboman ah no sorry, I think we found a fix and it should be deployed soon.

**Comment by dacomboman** [comment] 2018-05-03 20:15
Phew!

Thought it would be another "just me" type problem.

**Comment by willdurand** [comment] 2018-05-07 13:29
> Must be an account related issue 'cause I can't even log in with Palemoon.

Sorry what? I think we have fixed the bug, but let me know if you still have issues.

**Comment by dacomboman** [comment] 2018-05-07 14:56
Hi William,

 

Sorry, I didn't express that last message properly.

What I meant to say is that I still get same "server error" message when logged in.

This message is still ongoing for me with Firefox as well.

 

Will try deleting profile and setup again to see if that can help any.

 

-Daniel

**Comment by willdurand** [comment] 2018-05-07 15:16
> Will try deleting profile and setup again to see if that can help any.

I don't think it is a good idea, you will likely loose your data. I don't think your account is faulty but we would need more information now.

- Can you install an extension if you are not logged in?
- Do you get any specific error?
- Does it happen with other extensions?

**Comment by dacomboman** [comment] 2018-05-07 18:29
Too late!

 

Syncing went well (restoring extensions, passwords).

But, same issue as before with regards to signing online:

http://imagizer.imageshack.com/img924/7759/lJXIk2.png

The extension installed when not yet logged into online service.

The minute I log in, I get the above error message and there's no way to click to install the extension (as you can see).

 

-Daniel

**Comment by willdurand** [comment] 2018-05-07 18:54
@dacomboman could you give me the link to the addon you tried to install?

**Comment by dacomboman** [comment] 2018-05-07 21:44
Sure! But it does it for any extension:

https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/?src=search

 

-Daniel

**Comment by willdurand** [comment] 2018-05-08 05:31
Thanks @dacomboman, I want to look into our Sentry logs (error aggregator).

**Comment by willdurand** [comment] 2018-05-08 05:34
Thanks @dacomboman, I want to look into our Sentry logs (error aggregator).

**Comment by willdurand** [comment] 2019-01-08 14:01
This could potentially be related to #7322. Since we don't have any other idea, I am closing this issue for now.

**Closed by willdurand** 2019-01-08 14:01 UTC
Labels: needs: info
