### ISSUE TITLE
Pass specific src params to details page links

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4372] opened 2018-02-13 01:50 UTC
It appears the new AMO front-end isn’t passing tracking parameters as it did in the old site. 

In the old site, for example, when you’d click to an individual add-on’s detail page from within the “Featured Extensions” promo module, its passing URL included “src=hp-dl-featured”. With the new front-end, there is no URL change in the path. 

Perhaps the tracking params are hidden? Or are we not tracking discovery flow as we did with the old AMO? 

Perhaps there are more (ideas welcome!), but here are the critical source values we should track: 

Collections (src=collection)

Homepage hero area (src=hp-dl-promo)

Featured (src=featured)

Search (src=search)

Filtered groups
- Popular (src=mostpopular)
- Top-rated (src=rating)
- Recently added (src=created)
- Trending (src=hotness)

**Comment by jvillalobos** [comment] 2018-02-13 14:52
Flagging this as P2, since it has a negative effect on statistics tracking for developers and us.

**Comment by diox** [comment] 2018-02-14 16:31
Looks like a dupe of https://github.com/mozilla/addons-frontend/issues/4270 which is already a p2.

**Comment by jvillalobos** [comment] 2018-02-14 20:03
Closing as a dupe.

**Comment by muffinresearch** [comment] 2018-02-26 15:15
I don't think this is a dupe. #4270 is about allowing the src parameter in the url to be passed down to the install link, however this is about providing the src parameters to the details page links. I don't see them present if you go to the homepage for example and click through to the details page for an add-on in a collection.

**Comment by muffinresearch** [comment] 2018-02-26 15:16
As mentioned in the OP fixing this requires passing the relevant src params in the details page links.

**Comment by kumar303** [comment] 2018-02-26 22:42
What source should we use when linking to add-ons from the new *Re-imagine search* card on the home page?

<img width="850" alt="screenshot 2018-02-26 16 41 06" src="https://user-images.githubusercontent.com/55398/36699933-df29a804-1b13-11e8-995e-3cdc9fcbb5cf.png">

**Comment by kumar303** [comment] 2018-02-26 22:46
Here are all the home page curated shelves for which I don't see sources. Should I leave the source blank for now?

* Re-imagine search
* Privacy tools
* Dynamic media downloaders

**Closed** 2018-02-27 18:00 UTC
Labels: priority: p2

**Comment by kumar303** [comment] 2018-02-27 18:17
One other question that came up while working on this: should we use `src=collection` for add-ons in the *home page* collections? The fix I added only adds it for when you're on any collection detail page.

**Comment by AlexandraMoga** [comment] 2018-02-28 11:38
Verified  this on stage and here are my observations:
- **Working**
 `src=collection` -  param sent when accessing an add-on details page from "Customize the way Firefox works..." collections shelf or from a user's collection
`src=hp-dl-promo` -  param sent when looking at add-ons present in the hero banners
`src=search` - param sent when looking at add-on details from search results

- **Needs attention**
1. `src=featured` -  only works when accesing an add-on details page from AMO homepage; doesn't work for add-ons featured in [Extension/Theme homepage](https://addons.allizom.org/en-US/firefox/extensions/) or [Category pages](https://addons.allizom.org/en-US/firefox/themes/nature/)
2. Regarding Filtered groups - filters are normally applied after executing a search; this means that the `src=search` param will always precede  the `src=filter` parameter, [like in this example](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=search&sort=rating)
3. `src=mostpopular` - works for Popular Themes shelf in AMO homepage; not sure if there is another way to capture this on the new frontend; on the legacy site, this param was associated with the _weekly downloads_ sort option, which is no longer present on the new site.
4. `src=rating` - doesn't work for _Top Rated_ add-ons shelf  available in [Extension/Theme homepage](https://addons.allizom.org/en-US/firefox/extensions/) or [Category pages](https://addons.allizom.org/en-US/firefox/themes/nature/); not working as a filter parameter because of **point 2.**
5. `src=created` - there is no _Recently added_ filter on the new frontend, only _Recently updated_; maybe we need a parameter for this option;
6. `src=hotness` - doesn't work for _Trending_ add-ons shelf  available in [Extension/Theme homepage](https://addons.allizom.org/en-US/firefox/extensions/) or [Category pages](https://addons.allizom.org/en-US/firefox/themes/nature/); not working as a filter parameter because of **point 2.**

**Comment by kumar303** [comment] 2018-03-01 15:15
Thanks for catching all these. I created a new issue: https://github.com/mozilla/addons-frontend/issues/4475

The only one I didn't include was this:

> `src=mostpopular` - works for Popular Themes shelf in AMO homepage; not sure if there is another way to capture this on the new frontend; on the legacy site, this param was associated with the *weekly downloads* sort option, which is no longer present on the new site.

Since we no longer have *weekly downloads* then there is nothing to do here.

**Comment by AlexandraMoga** [comment] 2018-03-01 15:24
This can be marked as verified fixed as a new issue to follow up issue was opened.
