### ISSUE TITLE
RelaodEvery does not install and shows connection problem

### ISSUE THREAD

**Issue by mMARUF** [mozilla/addons-frontend#1991] opened 2017-03-07 17:26 UTC
Steps to reproduce : 

1. Go to https://addons-dev.allizom.org/en-US/firefox/addon/reloadevery/
2. Then use the slider button beside the star button to download it
  

Actual Result :

A pop-up comes which shows connection problem 

Expected Result :

It should have been installed. And if it is not compatible with mobile device then the pop-up should say that "it is not compatible with mobile device"  

Attachment  -

![17198039_1282377388519532_929326456_n](https://cloud.githubusercontent.com/assets/10638506/23668814/65dd0cec-038c-11e7-9117-8da00cd39a16.png)

**Comment by tofumatt** [comment] 2017-03-07 17:29
Guessing this is a duplicate of #1867.

**Closed** 2017-03-08 01:04 UTC
Labels: state: pull request ready
