### ISSUE TITLE
failed link

### ISSUE THREAD

**Issue by abs-plus** [mozilla/addons-frontend#8474] opened 2019-08-13 11:11 UTC
why is this link invalid?
https://de.wikipedia.org/wiki/ChatZilla

or - what am I doing here  ;-(        if this was probably a misunderstanding?    excuse me please

**Comment by muffinresearch** [comment] 2019-08-13 13:35
Duplicate of https://github.com/mozilla/addons-frontend/issues/8475

**Closed by muffinresearch** 2019-08-13 13:35 UTC
