### ISSUE TITLE
404 pages are not served by addons-frontend

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3984] opened 2017-11-27 17:53 UTC
### Describe the problem and steps to reproduce it:

* Clear all cookies
* Type in something like https://addons.mozilla.org/nope which redirects to https://addons.mozilla.org/en-US/firefox/nope

### What happened?

The 404 is served from `addons-server`:

<img width="1163" alt="screenshot 2017-11-27 11 49 20" src="https://user-images.githubusercontent.com/55398/33280947-4aa3abea-d369-11e7-85c1-3b07f8c15921.png">

### What did you expect to happen?

The 404 should be served from `addons-frontend`. Example:

<img width="885" alt="screenshot 2017-11-27 11 52 30" src="https://user-images.githubusercontent.com/55398/33281035-7cad2832-d369-11e7-8089-073fbe349524.png">

**Comment by bqbn** [comment] 2017-11-27 18:12
Per what's descibed in https://github.com/mozilla/addons-frontend/issues/2082, the original design of the redirection system is that only explicitly listed routes are to be served by the mobile site. 

> we could set up an explicit list of routes that the mobile pages responds to as this will be less prone to problems - the only downside will be one of maintenance. I'll add comments to the routes to make it clear that ops need to be told when new routes are added.

And interestingly, one of the reasons why we have had the design is to avoid fall back due to 404s.

> In addition to this we have a fallback which will fallback based on the mobile pages providing a 404. 

404 pages, by nature are not explicitly list-able, and that is basically why it is served by the desktop site.

I think the current "explicitly list for redirection" system works well. We may not want to go back to previous relatively messier 404 fallback system.

**Comment by bqbn** [comment] 2017-11-27 18:15
I assume that when we have the majority of the routes are migrated to the mobile site, then we can do something like "only explicitly listed routes are served by the desktop site", by which time, 404 can be served by the mobile site directly.

**Comment by kumar303** [comment] 2017-11-27 18:25
We need to serve 404s and all error pages from `addons-frontend` because they provide helpful context about what the user can do next.

This was implemented and working a long time ago. Did we regress the behavior back in March and no one noticed? I tried to find when QA last verified it but all I turned up was https://github.com/mozilla/addons-frontend/issues/1033#issuecomment-303105916 so it's possible that it has been broken since March.

**Comment by bqbn** [comment] 2017-11-27 18:55
It may have worked before https://github.com/mozilla/addons-frontend/issues/2082. But since then, only explicitly listed routes are redirected to the mobile site.

**Comment by bqbn** [comment] 2017-11-29 01:47
To be clear, what I meant in the above comments (particularly in https://github.com/mozilla/addons-frontend/issues/3984#issuecomment-347273290) is that, if the issue is to be solved at the nginx layer, it seems like we have to revert back to before #2082, which IMHO is not better than what we have now (i.e. explicit nginx routes for mobile pages).

**Comment by muffinresearch** [comment] 2018-01-30 18:25
I don't think there's much we can do about this one without a big change to how we use the explicit routing. 

It will likely get easier once there's nothing that needs to fall through to the old site. At that point we might be able to control it by just the cookie.

**Comment by willdurand** [comment] 2019-07-05 10:10
Given that we inverted the routing rules a while ago, I believe this is fixed now.

**Closed by willdurand** 2019-07-05 10:10 UTC
Labels: priority: p3, state: blocked, triaged

**Comment by AlexandraMoga** [comment] 2019-07-05 10:35
We haven't run for a good while into 404 errors served by the legacy site, so this issue can be marked as verified fixed.
