### ISSUE TITLE
went to select a theme for my browser and it was an error 

### ISSUE THREAD

**Issue by mickyfan2345** [mozilla/addons-frontend#5116] opened 2018-05-27 05:46 UTC

**Comment by mickyfan2345** [comment] 2018-05-27 05:48
went to themes for firefox and it use to work but now there's a service error what's going on  Server Error

Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it. is what i got

**Comment by jvillalobos** [comment] 2018-05-28 17:04
Do you have the URL of the page you tried to visit?

**Comment by mickyfan2345** [comment] 2018-05-29 01:52
https://addons.mozilla.org/en-US/firefox/themes/abstract/?sort=up-and-coming
it's all the theme's on that site we can't be logged in and save them

**Comment by wagnerand** [comment] 2018-05-29 09:52
That url works for me both in the old and new frontend.

Please provide detailed and complete steps to reproduce your issue.

**Comment by mickyfan2345** [comment] 2018-05-30 19:12
i sent you a screen shot of it not working what's going on

**Comment by jvillalobos** [comment] 2018-05-30 19:30
I don't see a screenshot on this issue. So, what you're saying is that your get a server error page when you try to add a theme to your favorites collection? Does it happen for any theme you try to add? Can you explain the exact steps you follow to add the theme to the collection?

**Comment by mickyfan2345** [comment] 2018-06-01 03:52
did you get the last screen shot i send you i sent you 2

**Comment by mickyfan2345** [comment] 2018-06-01 19:18
i hit the item i want and it wont even let me choice it

**Comment by mickyfan2345** [comment] 2018-06-01 19:44
do you think it could be the new firefox i have the 60.0.1 (64-bit)

**Comment by mickyfan2345** [comment] 2018-06-12 21:07
@jvillalobos what more do you want i've given you all 
![firefox2 png3](https://user-images.githubusercontent.com/39664884/41317398-13de7b5e-6e63-11e8-98c6-bffffd398f91.png) the circled items are the best i can do

**Comment by jvillalobos** [comment] 2018-06-12 21:32
Thanks for the screenshot, that helps a bit. Does this error happen for every theme page you click on? Does it happen when you click on [this link](https://addons.mozilla.org/addon/abstract-ribbon/)? Or does it only happen with the Pretty Romantic Pink theme?

**Comment by mickyfan2345** [comment] 2018-06-12 21:39
@jvillalobos not only that one but every one of the themes

**Comment by mickyfan2345** [comment] 2018-06-12 22:22
@jvillalobos it does it to every one of them

**Comment by mickyfan2345** [comment] 2018-06-12 23:30
@jvillalobos no it works fine when im logged out but i wanna save the ones i like

**Comment by mickyfan2345** [comment] 2018-06-12 23:42
@willdurand @jvillalobos  it works when im not signed i i wanna save them to my account the ones i like

**Comment by mickyfan2345** [comment] 2018-06-13 00:47
@jvillalobos @willdurand it works when im not signed in i wanna save them to my account the ones i like

**Comment by mickyfan2345** [comment] 2018-06-13 01:30
it works when im not signed in i wanna save them to my account the ones i
like

**Comment by jvillalobos** [comment] 2018-06-13 23:06
We get all of the messages, yes. Knowing that it only fails when logged in suggests that it's related to the collections feature. Maybe related to having a [collection with an empty name](https://addons.mozilla.org/firefox/collections/lynnette12/). /cc @bobsilverberg

**Comment by willdurand** [comment] 2018-06-13 23:35
We'll setup error reporting, hopefully next week, to get more insights. It could be an issue with reviews, collections or maybe recommendations.. We'll know when we'll receive the errors in Sentry.

**Comment by mickyfan2345** [comment] 2018-06-20 22:02
@jvillalobos @willdurand  hello what's going on with the problem

**Comment by mickyfan2345** [comment] 2018-07-11 22:20
@jvillalobos  still having troubles saving the themes to my account still the error i sent you the screen shot to

**Comment by jvillalobos** [comment] 2018-07-11 22:52
The issue hasn't been resolved, and may take some time before it is. I suggest you try changing the name of your second collection, that is currently empty, to see if that fixes the problem.

**Comment by willdurand** [comment] 2019-01-03 08:18
We updated a few things in the collection pages and there is some work in progress that changes some parts of the collection code. Hopefully, this will automagically solve this issue.

Otherwise, I don't really know what else we can do because logs/error reporting did not provide any relevant data. I am going to close this issue but feel free to reopen it (or create a new one) if the problem still occurs.

**Closed by willdurand** 2019-01-03 08:18 UTC
