### ISSUE TITLE
500 when accessing a locale other than en-US

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1628] opened 2017-01-16 23:02 UTC
### Describe the problem and steps to reproduce it:
When you access a language other than English a 500 error is returned.

### What happened?
The moment locale code is attempting to load a `../moment` module which does not appear to exist.

### What did you expect to happen?
Moment locales load fine and the page is served in the requested language.

### Anything else we should know?
```
[1] [2017-01-16T22:59:55.026Z] ERROR: server/58760 on mstriemer-30951: Cannot find module '../moment' (app=amo, err.code=MODULE_NOT_FOUND)
[1]     Error: Cannot find module '../moment'
[1]         at Function.Module._resolveFilename (module.js:325:15)
[1]         at Function._module2.default._resolveFilename (/Users/markstriemer/work/addons-frontend/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
[1]         at Function.module._load (/Users/markstriemer/work/addons-frontend/node_modules/piping/lib/launcher.js:24:23)
[1]         at Module.require (module.js:353:17)
[1]         at require (internal/module.js:12:17)
[1]         at /Users/markstriemer/work/addons-frontend/src/locale/fr/amo.js:70:51
[1]         at Object.anonymous [as _momentDefineLocale] (/Users/markstriemer/work/addons-frontend/src/locale/fr/amo.js:68:3)
[1]         at makeI18n (/Users/markstriemer/work/addons-frontend/src/core/i18n/utils.js:193:18)
[1]         at /Users/markstriemer/work/addons-frontend/src/core/server/base.js:232:24
[1]         at run (/Users/markstriemer/work/addons-frontend/node_modules/core-js/modules/es6.promise.js:87:22)

**Comment by tofumatt** [comment] 2017-01-17 01:44
Duplicate of #1558 but this title/description is better so closing the other issue 😅

**Comment by muffinresearch** [comment] 2017-01-17 09:05
The other bug had additional comments but since that one got closed copying here:

Looks like the try/catch might be better inside the function here: https://github.com/mozilla/addons-frontend/blob/162d46fed3e3283e3c973ec4abedd55d45496535/bin/build-locales#L57

**Closed** 2017-01-26 12:25 UTC
Labels: amo, blocks release, mobile pages v1, pull request ready, regression

**Comment by vcarciu** [comment] 2017-01-26 15:09
Verified as fixed : 

![gif](https://cloud.githubusercontent.com/assets/1583842/22336251/390121a2-e3ea-11e6-9536-da2ce6fd47ae.gif)
