### ISSUE TITLE
S3. translator  add-on removed for firefox

### ISSUE THREAD

**Issue by Astrulises** [mozilla/addons-frontend#8350] opened 2019-07-20 16:19 UTC
S3 TRANSLATOR is no longer available for firefox and is the best translator for firefox. I used it often but a year or more ago it is not available anymore. They could make it available again. please.

**Comment by willdurand** [comment] 2019-07-22 06:52
duplicate of https://github.com/mozilla/addons-frontend/issues/7470

**Closed by willdurand** 2019-07-22 06:52 UTC
