### ISSUE TITLE
Data for every extensions page is the same

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1571] opened 2017-01-06 16:26 UTC
Clicking around the newly linked categories the data always appears to contain the same results - maybe there's still something to do to hook up the data to those URLS correctly?

Also note the results contain both themes and extensions.

If this is covered in an existing issue elsewhere feel free to dupe it.

E.g:

https://addons-dev.allizom.org/en-US/firefox/extensions/feeds-news-blogging/

<img width="238" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/21724517/93cdf48e-d42c-11e6-97dc-0451eeb46610.png">

https://addons-dev.allizom.org/en-US/firefox/themes/fashion/

<img width="240" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/21724534/a81254da-d42c-11e6-96d2-a0a4a1491261.png">

**Comment by tofumatt** [comment] 2017-01-06 16:28
This is a duplicate of #1540, which has a PR ready for it that I just haven't merged yet.

**Closed by tofumatt** 2017-01-06 16:28 UTC
Labels: bug, duplicate, mobile pages v1
