### ISSUE TITLE
Cannot install webextension on Fennec/57 (Android)

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-frontend#3315] opened 2017-10-02 19:06 UTC
### Describe the problem and steps to reproduce it:
Using Fennec 57 (beta channel as of the filing of this bug), navigate to https://addons.mozilla.org/en-US/firefox/addon/metric-cooking/ and try to install the extension.

### What happened?
  The install button slides to the right but I never saw the progress bar effect and the switch never turned green.  In Android logs I found the following (obfuscated sorry) stack trace:

```
E/GeckoConsole(  641): [JavaScript Error: "TypeError: Parameter 'url' must be a string, not undefined" {file: "https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js" line: 1}]
E/GeckoConsole(  641): r.prototype.parse@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:265415
E/GeckoConsole(  641): o@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:264592
E/GeckoConsole(  641): y@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:20408
E/GeckoConsole(  641): a@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:315334
E/GeckoConsole(  641): value@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:338642
E/GeckoConsole(  641): install@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:340228
E/GeckoConsole(  641): t/r.handleClick@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:1052274
E/GeckoConsole(  641): r@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:157867
E/GeckoConsole(  641): a@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:156212
E/GeckoConsole(  641): u@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:156429
E/GeckoConsole(  641): p@https://addons-amo.cdn.mozilla.net/amo-8a5c5ae197ea61a3f757.js:1:109344
E/GeckoConsole(  641): v@https
```

### What did you expect to happen?
Either for the extension to be installed or for an error message to be displayed.

**Comment by kumar303** [comment] 2017-10-02 19:33
The issue here is that the add-on does not have an install file for Android yet its compatibility says the add-on supports Android. Here is a snippet from the API response (see 
[metric-cooking-addon.json.zip](https://github.com/mozilla/addons-frontend/files/1350089/metric-cooking-addon.json.zip)):

```
      "compatibility" : {
         "android" : {
            "max" : "*",
            "min" : "48.0"
         },
         "firefox" : {
            "min" : "48.0",
            "max" : "*"
         }
      }
```

This is odd because in the same API response it has file objects for `mac`, `linux`, and `windows`, but not `android`.

And, yes, this is the same error as in #3266 but I don't know if the compatibility definition is the same for each. The error is happening more or less here: https://github.com/mozilla/addons-frontend/blob/ea391c670b8da736c57f6a8d16ecc01106cc6cf2/src/core/addonManager.js#L52

I think the developer is in the process of working around this issue so I grabbed the source of the version which is causing the bug: 
[metric_cooking-1.5-an+fx-mac.zip](https://github.com/mozilla/addons-frontend/files/1350104/metric_cooking-1.5-an.fx-mac.zip)

**Comment by kumar303** [comment] 2017-10-02 19:34
@diox is it expected that an add-on could be marked as compatible with `android` but not contain an Android file in its current version?

**Comment by diox** [comment] 2017-10-03 15:34
Because of how Firefox for Android is both an app and a platform, it's technically possible, yes. You'd expect developers to upload a new file or mark the one already present as compatible with all, but nothing forces them to do it currently, so we can end up in that mess :(

Please file an addons-server issue for us to look into, but in the meantime, I'm afraid you'll have to find a workaround, because those add-ons definitely exist in the wild. I suggest marking the add-on as incompatible and preventing the install if you can't find a file that is available for the right platform (or "all"), on top of what the `compatibility` says.

**Comment by kumar303** [comment] 2017-10-03 20:02
Yep, we can work around this. Here is the server issue: https://github.com/mozilla/addons-server/issues/6576

**Comment by kumar303** [comment] 2017-10-09 17:32
I confirmed that this is a dupe of https://github.com/mozilla/addons-frontend/issues/3266 and that has some better STR so I'll use that for tracking purposes.

**Closed by kumar303** 2017-10-09 17:32 UTC
Labels: priority: mvp, project: 2017 Q3, project: amo, state: duplicate, triaged, type: bug
