### ISSUE TITLE
A collection name with an unbroken string will cause layout issues on the collection details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4185] opened 2018-01-19 08:05 UTC
STR:

1. Go to AMO homepage and access the following link displaying a collection page - https://addons-dev.allizom.org/en-US/firefox/collections/AlexandraMoga1/thiscollectiondoesn/
2. Observe the layout of the collection details block

Expected result:
Collection details are displayed without any layout issues

Actual result:
Collection name and description are not wrapped inside the collection details block

Notes:
Reproduced on all AMO servers with FF57 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/35140480-12f868b4-fd00-11e7-88cc-368f4cd8b9a1.png)

**Comment by muffinresearch** [comment] 2018-01-19 12:44
@kumar303 assigning this to you since it affects collections, but I'm thinking this might be an issue in general if this component style is shared>

**Comment by ioanarusiczki** [comment] 2018-02-01 15:47
After making some testing on AMO stage using FF58 (Android 8.0) I noticed that when the name of the creator is longer, it creates a display issue. 
This issue is reproducible only with portrait orientation.

![creator](https://user-images.githubusercontent.com/33448286/35687629-e75bc2be-0777-11e8-935e-8f0856cb5eec.png)

**Comment by ioanarusiczki** [comment] 2018-02-13 10:40
I verified this issue on AMO dev using FF58 (Win10).  When the Display Name is a long unbroken string it will cause display issues, it overlaps the text from Last Updated field. 

![overlaps the other text](https://user-images.githubusercontent.com/33448286/36145758-ff64ae7e-10ba-11e8-9774-4879c9bf8855.png)

**Comment by tsl143** [comment] 2018-03-04 06:36
@muffinresearch the title and description overflow is specific to collection, but `metadatacard` is shared. This PR will handle the text overflow for all the shared style.

**Closed** 2018-03-05 11:26 UTC
Labels: component: collections, component: ux, priority: p3, project: amo, project: desktop pages, size: S, triaged, type: bug

**Comment by AlexandraMoga** [comment] 2018-03-05 15:04
Verified as fixed on AMO-dev, FF58, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/36981869-efe52014-2096-11e8-859b-501e773e9a0b.png)
