### ISSUE TITLE
Rating stars not centered in All reviews page on mobile

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8437] opened 2019-08-05 08:22 UTC
### Describe the problem and steps to reproduce it:

1. Open 'All reviews' page for an add-on on mobile or in responsive design: see https://addons.mozilla.org/en-US/firefox/addon/voice-fill/reviews/
2. Observe the rating stars alignment 

### What happened?
Rating stars are aligned to the left

### What did you expect to happen?
Rating stars are centered

### Anything else we should know?
- also reproduced in EULA and Privacy policy pages, which are using the same rating component
- reproduced on all AMO servers with Fx68 

![image](https://user-images.githubusercontent.com/31961530/62449521-113f6480-b773-11e9-9fb7-1c20485acded.png)

![image](https://user-images.githubusercontent.com/31961530/62449530-156b8200-b773-11e9-9443-1eb62b335c5a.png)

**Comment by Shubhamchinda** [comment] 2019-08-05 11:34
Hey, I made a fix for this problem. In `/src/amo/components/AddonSummaryCard/styles.scss` under [class](https://github.com/mozilla/addons-frontend/blob/8ae1a08d38e72fc706f5c8862f94a2d801071d80/src/amo/components/AddonSummaryCard/styles.scss#L3).
I **added**
```js
display: grid;
justify-content: center;
``` 
and it fixed the problem. Here's the result :
![Screenshot (234)](https://user-images.githubusercontent.com/21038543/62461623-f684e400-b7a2-11e9-988b-ba69b4b7cea9.png)

Let me know if it's correct.
Thanks a lot!

**Comment by willdurand** [comment] 2019-08-05 12:59
@kumar303 could this be a regression? I thought this was centered initially. I don't find recent commits that touched that part, though.

**Comment by kumar303** [comment] 2019-08-05 15:52
@Shubhamchinda thanks for taking a look at this. I didn't see a PR and I wanted to make sure we ship a fix for this ASAP since it may affect wider Android screens (ones that mimic iPhone). I also wanted to use flex since that has better support and we don't need a grid specific feature here. https://github.com/mozilla/addons-frontend/pull/8440

@willdurand yeah, I'm pretty sure this is a regression but I couldn't find a commit that caused it. It's possible we missed this since it looks fine on the Android Galaxy S9 setting in responsive mode 🤷‍♂

**Comment by Shubhamchinda** [comment] 2019-08-05 16:15
> @Shubhamchinda thanks for taking a look at this. I didn't see a PR and I wanted to make sure we ship a fix for this ASAP since it may affect wider Android screens (ones that mimic iPhone). I also wanted to use flex since that has better support and we don't need a grid specific feature here. #8440

No problem @kumar303 . I didn't make any PR since I wanted to confirm if using grid is fine here. Anyways thanks, I'll be around. Let me know if I can be of any service.

**Closed** 2019-08-05 21:01 UTC
Labels: component: add-on ratings, contrib: welcome, priority: p4, type: regression

**Comment by AlexandraMoga** [comment] 2019-08-06 13:53
Verified fixed on -dev:

mobile:
![image](https://user-images.githubusercontent.com/31961530/62544867-3dd5a800-b869-11e9-8ded-5d1119a9db72.png)

tablet:
![image](https://user-images.githubusercontent.com/31961530/62544902-4ded8780-b869-11e9-8310-c8a46c6a0177.png)

RTL:
![image](https://user-images.githubusercontent.com/31961530/62544909-52b23b80-b869-11e9-8ff8-db6b85bb62ae.png)
