### ISSUE TITLE
Sharing on fb might result in the wrong text being used as description

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#4814] opened 2018-04-16 16:17 UTC
### steps to reproduce
- Pick an extension with a short short-description (e.g. [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/))
- share this URL on facebook
- read the copy facebook used to describe the extension

### expected result
I expected to see the short-description the extension-author wrote. 
(Maybe started with some text we provide…)

### actual result
Facebook picks a wrong text off the page to use it as a description for the link.
(The choice couldn't be much worse…)

[![screenshot-2018-4-16 facebook](https://user-images.githubusercontent.com/8145891/38821920-32e1ae06-41a2-11e8-9488-19822875d519.png)](https://screenshots.firefox.com/hPCXjW4mckysUXHE/www.facebook.com)

**Comment by jvillalobos** [comment] 2018-04-16 20:50
Dupe of https://github.com/mozilla/addons-frontend/issues/3969

**Closed by jvillalobos** 2018-04-16 20:50 UTC
Labels: contrib: maybe good first bug, priority: p3
