### ISSUE TITLE
A review written from the user profile page is not displayed after submission 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6417] opened 2018-09-26 08:39 UTC
Follow up for #6104 

STR

1. Log in to AMO stage
2. Go to your user profile page
3. Search for a rating posted that doesn't have any text written yet
4. Click on Write a review and Submit your comment

Actual result:
The written review is not displayed immediately after submission. A page refresh is required

Expected result:
Written review is immediately available

Notes:
- not reproduced when the review is written from a permalink
- not reproduced on -dev, only on stage, with FF62, Win10x64

![write a review](https://user-images.githubusercontent.com/31961530/46067939-aa2f4780-c180-11e8-9879-30fbe6a12c0e.gif)

**Comment by bobsilverberg** [comment] 2018-09-26 13:20
I'm not sure if we should invest any time in trying to fix this, because it uses the old UI for writing a review. This should be fixed when the new UI lands, which isn't far off.

As an interim fix we could consider hiding the "Write a review" button unless the new UI is enabled, but I'm not sure if even that is worth the time and effort.

What do you think @kumar303?

**Comment by bobsilverberg** [comment] 2018-09-26 19:29
This should be fixed via #6349, which we hope to land on stage at the end of this week, and on prod for next week's push.

**Comment by ioanarusiczki** [comment] 2018-09-27 08:51
This is also reproducible when a written review or a developer response is edited on the user profile page - refresh is needed to view the text after submission. - on AMO stage FF62(Win10) The issue is not reproducible on AMO -dev

**Comment by AlexandraMoga** [comment] 2018-10-02 09:14
This is now fixed on stage for all three scenarios: writing a review, editing a review, updating a dev reply

![stage review](https://user-images.githubusercontent.com/31961530/46339890-9bdba280-c63c-11e8-8733-ac5e9c1c78d2.gif)

**Closed** 2018-10-02 09:18 UTC
Labels: component: add-on ratings, priority: p2, state: verified fixed, type: bug
