### ISSUE TITLE
Navigating from one page to another in extensions categories, shows “No results were found” before loading the content on the page

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-frontend#1894] opened 2017-02-24 13:02 UTC
# Environment
Firefox: Nightly 54.0a1
Mobile device: Samsung S7 (Android 6.0.1)

# Steps to reproduce
1. Go to AMO mobile –dev homepage.
2. Tap on an extensions category (make sure the content is spread over multiple pages).
3. Navigate to the next page (tap Next at the bottom the list) and observe the behavior until the page is loaded.

# Expected results
A loading animation (loading spinner) indicates the content is loading.

# Actual results
“No results were found” message is displayed for a few moments (up to 3 seconds), then the page is loaded.

# Notes
Reproducibility: 5/5.

gif
![no results were found message](https://cloud.githubusercontent.com/assets/26005101/23366817/cef582cc-fd10-11e6-8b84-bb96cc0799bc.gif)

**Comment by ValentinaPC** [comment] 2017-08-09 09:22
This is happening on new desktop pages also.
Please see video:
![no results](https://user-images.githubusercontent.com/15685960/29114574-72e4469a-7cfd-11e7-9c90-c2802e66cee8.gif)

**Comment by kumar303** [comment] 2017-08-09 14:16
whoops, this is a regression from https://github.com/mozilla/addons-frontend/issues/2859 Thanks. I'll fix this.

**Comment by tofumatt** [comment] 2017-08-09 14:21
I think it might be covered by the sagas, may not be needed. Might want to wait until we merge those unless you feel it’s worth a hotfix for.

- tofumatt

**Comment by kumar303** [comment] 2017-08-09 17:06
ok, I'll try it in your branch first

**Comment by kumar303** [comment] 2017-08-09 17:08
It's still happening in your branch and actually it's broken, heh (page 2 loads for a minute then unloads). I'll keep an eye on it after reviewing your patch.

**Comment by tofumatt** [comment] 2017-08-09 17:12
Oh shoot, right. That is a bug and I forgot about it. I'll mark the saga branch as WIP again then. My bad.

**Comment by kumar303** [comment] 2017-08-17 21:07
This was fixed in https://github.com/mozilla/addons-frontend/pull/2909 I didn't close it earlier because we had other unrelated bugs with this page that would have made QA verification difficult (those are also fixed now).

**Closed by kumar303** 2017-08-17 21:07 UTC
Labels: component: ux, project: amo, project: mobile pages v1, triaged

**Comment by ValentinaPC** [comment] 2017-08-18 09:42
Verified this as fixed on AMO-dev FF55(Win 7).
Navigation through categories pages results display loading indicators with no other issues.
Postfix video:
![nav](https://user-images.githubusercontent.com/15685960/29453551-b0f29484-8412-11e7-86fd-777afd3cecd0.gif)
