### ISSUE TITLE
Remove must be clicked twice for a lw theme to display "'Undo"

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6685] opened 2018-10-19 11:26 UTC
Observed while testing https://github.com/mozilla/addons-frontend/issues/6329

STR:
1. Load AMO dev and install a lw theme from disco pane or a theme's detail page
2. Go to Themes Tab and click "Remove"
3. Observe screen 

Expected result:
"Undo" blue button is displayed. 

Actual result:
The "Disable" "Remove" buttons are still displayed.

Notes:
This issue is reproducible on all AMO servers - FF62 and FF64 (win10)
This is not reproducible with extensions or static themes. 

![double click to remove a lw theme](https://user-images.githubusercontent.com/33448286/47215871-a1aae500-d3ab-11e8-9356-5617a0d786a4.gif)

**Comment by willdurand** [comment] 2018-10-19 11:47
>  This issue is reproducible on all AMO servers - FF62 and FF64 (win10)

This is weird because I just tried in -prod and Nightly, and I don't reproduce the issue..

**Comment by willdurand** [comment] 2018-10-19 11:49
I also tried with FF Release (unbranded) and the Disco Pane in -dev, "remove" actually removes the theme.

**Comment by willdurand** [comment] 2018-10-19 11:54
I see that when the add-on detail page is open and `about:addons` is also open, sometimes I am able to reproduce the bug but not all the time and not with the Disco Pane.

**Comment by ioanarusiczki** [comment] 2018-10-26 09:09
@willdurand On further investigations, I tested this issue with FF63 (Unbranded) and I might have steps to reproduce it from Disco Pane: 
1. Install a static theme from disco pane 
2. Without clicking remove, install a lw theme from disco pane
3. Go to Themes tab in addon manager (in the same tab, do not use another tab for addon manager)
4. Click remove for the lw theme

**Comment by willdurand** [comment] 2019-04-18 15:03
We do not have any LWT anymore, so I guess we can close this issue now.

**Closed by willdurand** 2019-04-18 15:03 UTC
Labels: component: installation, priority: p4, type: bug
