### ISSUE TITLE
Star breakdown is not correctly updated on the add-on review page when rating stars are edited

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5986] opened 2018-08-20 08:08 UTC
STR:

1. Log in to AMO
2. Review an add-on
3. Go to the add-on Reviews page
4. Make a note of the star breakdown 
5. Edit your review, stars included, and click Submit review
6. Observe the star breakdown again

Actual result:
The star breakdown doesn't reflect the new star selection

Expected result:
The number corresponding to the new rating is increased while the number of the previous rating decreases 

Notes:
- this happens all the time, not only when the add-on Reviews page was visited before
- the updated numbers are visible after the page is reloaded
- reproduced on all AMO servers with FF61, Win10x64

![edit stars](https://user-images.githubusercontent.com/31961530/44327942-dc0a0b80-a468-11e8-8a37-acf51f234e06.gif)

**Comment by bobsilverberg** [comment] 2018-08-20 17:44
I did some digging into this, and it looks like the `GET` call to `/api/v3/reviews/review/?addon={addonId}&show_grouped_ratings=true` which is issued after the `PATCH` call to `/api/v3/reviews/review/{addonId}` does not return the new information in `grouped_ratings`. It returns the old counts. A subsequent `GET` call (which is forced when the page is refreshed) does return the new data.

I noticed that this problem doesn't exist when you change your rating from the details page for an add-on, but that seems to be because that page issues two `PATCH` calls, one for just the rating and one for the review.

As we're in the process of changing the rating and review flow, I don't think it's worth trying to fix this now, for the old flow, but it does seem like this will also be an issue for the new flow, so we should keep this issue open as a reminder to address it when the time comes.

**Comment by kumar303** [comment] 2018-08-20 20:42
This appears to be a caching issue so we should try to fix it ASAP. We may need to check if any other endpoints have problems similar to this.

API bug: https://github.com/mozilla/addons-server/issues/9208

**Comment by bobsilverberg** [comment] 2018-08-20 21:35
This may be an unpopular opinion, but should we discuss how important it actually is to have this data be 100% accurate in real-time? If the purpose of this data is to allow users to get an idea of what other users think about an add-on, how much will the data not being updated immediately impact a user seeking that information? I would suggest this is almost a non-issue, especially if the only user impacted is one who just submitted their own rating.

We may have users noticing this behaviour and thinking that their new rating has not been recorded, and we might get bug reports because of that, but other than that I don't see this as a major issue.

**Comment by willdurand** [comment] 2018-08-21 11:01
> We may have users noticing this behaviour and thinking that their new rating has not been recorded, and we might get bug reports because of that, but other than that I don't see this as a major issue.

That's a major issue if users think the website is broken: it is a terrible UX.

I do agree that we might not need real-time data, at least not from the API. This could be fixed with an optimistic UI or a simple confirmation message, stating that the review has been taken into account (and will be reflected shortly after).

**Comment by AlexandraMoga** [comment] 2018-09-12 11:04
Update:

I have one more scenario to add to this issue:

When you first select a rating star for an add-on on the detail page, the star breakdown is not updated. However, when you immediately edit your rating in the write a review form, the star breakdown is updated. The average rating is not updated though until you refresh the page. 

![ratings updates](https://user-images.githubusercontent.com/31961530/45421003-59a1ef80-b694-11e8-8f15-56178e5be3ff.gif)

**Comment by kumar303** [comment] 2018-09-18 22:40
OK, I'll address that scenario, too.

**Comment by kumar303** [comment] 2018-09-20 19:59
I can no longer reproduce this, not even the bug shown in https://github.com/mozilla/addons-frontend/issues/5986#issuecomment-420608604 . @AlexandraMoga can you still reproduce it?

**Comment by AlexandraMoga** [comment] 2018-09-21 07:20
I'm also unable to reproduce either of the scenarios anymore.

![star edit all rev](https://user-images.githubusercontent.com/31961530/45865922-b7ff5a00-bd87-11e8-9b23-b83df626f635.gif)

**Comment by kumar303** [comment] 2018-09-21 14:26
For this bug, I think we just got lucky. Since we introduced another request to the add-on detail view (to fix other issues), the request for `?show_grouped_ratings=true` happens just slightly later than before. Maybe this is enough to obtain eventual consistency. This is just a theory, I'm not sure.

**Comment by AlexandraMoga** [comment] 2018-09-21 14:36
Hmm...I did find a way to reproduce the sceanrio in https://github.com/mozilla/addons-frontend/issues/5986#issuecomment-420608604 again after all:

The most consistent way of reproducing this (for me at least) was by opening an unrated add-on by direct link:

Try to open https://addons-dev.allizom.org/en-US/firefox/addon/palm-and-sky/ and leave a rating. The star breakdown will most likely not get populated immediately. 

![star breakdown again](https://user-images.githubusercontent.com/31961530/45887564-b30ccb80-bdc4-11e8-9ab8-d4a4a825bbe6.gif)

**Comment by kumar303** [comment] 2018-09-21 17:01
OK, thanks for the screencast. I can't reproduce it myself but I see that you are still experiencing the eventual consistency problem. We should address this.

**Closed** 2018-11-26 18:21 UTC
Labels: component: add-on ratings, priority: mvp, priority: p3, type: bug

**Comment by kumar303** [comment] 2018-11-26 22:15
This issue points out the problem with the star breakdown but there is a related issue with review counts. I'll be addressing that one in https://github.com/mozilla/addons-frontend/issues/6958

**Comment by AlexandraMoga** [comment] 2018-11-27 16:20
Verified fixed on AMO -dev with FF63, Win10x64 and Android 8.0

![2018-11-27_18-13-00](https://user-images.githubusercontent.com/31961530/49095396-0f7ee200-f271-11e8-8983-5af3e605b7da.gif)
