### ISSUE TITLE
Cannot download addons from the addons page while using Firefox if user agent string is changed

### ISSUE THREAD

**Issue by jakebesworth** [mozilla/addons-frontend#9079] opened 2019-11-23 01:36 UTC
### Describe the problem and steps to reproduce it:

As you can see from the below image, the download button on the addons page reads: "Only with Firefox—Get Firefox Now". This is because the useragent string has been changed, or a user agent switcher is being used.

### What happened?

When I try to install an addon, the addon page will not provide the installation button.

### What did you expect to happen?

Expected the installation button, while using Firefox, to exist on the addon page.

### Anything else we should know?

![image](https://user-images.githubusercontent.com/10157328/69470873-a2106f00-0d67-11ea-93c1-a5c0e66c7ea9.png)

### Suggested fix

I understand the UX that if someone views a Firefox Addon (page) and their useragent doesn't represent Firefox, you would want to direct them to download Firefox.

Quick solution that takes into account the above UX case is display a download link below the button regardless of it's state, such as tiny-font, light-grey font-color, below the download button: "Download addon anyway...".

**Comment by willdurand** [comment] 2020-05-19 17:58
duplicate of https://github.com/mozilla/addons-frontend/issues/4910

**Closed by willdurand** 2020-05-19 17:58 UTC
