### ISSUE TITLE
Navigation links wrap at different screen resolutions

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10254] opened 2021-03-22 20:27 UTC
This is something I noticed when working on https://github.com/mozilla/addons-frontend/issues/10252, and is a regression from https://github.com/mozilla/addons-frontend/issues/9078 (I believe).

When we bumped up our fonts we ended up with a situation where our navigation links wrap at particular screen resolutions. This is because our current layout is based on certain breakpoints, and those are no longer valid with these new font sizes.

Here are a couple of examples from near the breakpoints:

900px wide:

![Screen Shot 2021-03-22 at 4 20 47 PM](https://user-images.githubusercontent.com/142755/112053320-9931d800-8b2a-11eb-8993-7142efdd2ced.png)

500px wide:

![Screen Shot 2021-03-22 at 4 21 38 PM](https://user-images.githubusercontent.com/142755/112053427-b797d380-8b2a-11eb-9a36-021afd7cc4b6.png)

I can think of a couple of ways of addressing this:

1. Change our breakpoints to be at larger resolutions. I think this makes the most sense as these are probably not the only things that look less than ideal with the new font sizes and the old breakpoints.
2. Reduce the size of the font for these particular menu items.

As mentioned, I am leaning towards number 1, which would involve bumping our `extraLarge` breakpoint from `900px` to `1050px` and our `medium` breakpoint from `500px` to `600px`. TBH, I'm not sure where our original breakpoints came from, and if this is a reasonable thing to do. It also might make sense to bump the other ones as well, but that is not needed to address this bug.

WDYT @muffinresearch @verdi et al?

**Comment by willdurand** [comment] 2021-03-22 20:42
It is already like that on -prod, so this does not seem to be a new regression. I checked both 500px and 900px wide.

> As mentioned, I am leaning towards number 1, which would involve bumping our `extraLarge` breakpoint from `900px` to `1050px` and our `medium` breakpoint from `500px` to `600px`. TBH, I'm not sure where our original breakpoints came from, and if this is a reasonable thing to do. It also might make sense to bump the other ones as well, but that is not needed to address this bug.

I don't think we should do that. Instead, we should fix our layout to have more space when screen width is small-ish.

**Comment by bobsilverberg** [comment] 2021-03-22 20:50
> It is already like that on -prod, so this does not seem to be a new regression. I checked both 500px and 900px wide.
> 

Oh, wow, I didn't check that. I wonder if that was a result of last week's patch moving to Inter, or if it was around even before that.

> > As mentioned, I am leaning towards number 1, which would involve bumping our `extraLarge` breakpoint from `900px` to `1050px` and our `medium` breakpoint from `500px` to `600px`. TBH, I'm not sure where our original breakpoints came from, and if this is a reasonable thing to do. It also might make sense to bump the other ones as well, but that is not needed to address this bug.
> 
> I don't think we should do that. Instead, we should fix our layout to have more space when screen width is small-ish.

Well, I am wondering where these breakpoints came from, and if they are still accurate today. I suppose that is a separate issue. I can tell you that when working on https://github.com/mozilla/addons-frontend/issues/10252 I came up with a number of instances where our current breakpoints just didn't seem to fit. Also, although this may not be a regression from this week's (upcoming) push, it still seems like something we should ideally fix in time for this week's push, as it's quite unprofessional looking. Doing one of the two things I mentioned seemed doable in the short term. Making significant changes to our layout will be more time consuming.

Do you think it's fine to not fix it for this week's push, or are you saying we should, and we need to find the time to change the layouts by tomorrow?

**Comment by bobsilverberg** [comment] 2021-03-22 21:14
@willdurand FWIW, I was able to fix up the `extraLarge` layout by providing less space for the search box, which I think is fine:

Before:
![Screen Shot 2021-03-22 at 5 07 20 PM](https://user-images.githubusercontent.com/142755/112058533-17917880-8b31-11eb-8af6-b972dcc26867.png)


After:
![Screen Shot 2021-03-22 at 5 06 31 PM](https://user-images.githubusercontent.com/142755/112058443-fa5caa00-8b30-11eb-9d6c-870b7dd0ceda.png)

but for the `medium` breakpoint it doesn't look quite as nice. I guess it might be acceptable but it really doesn't leave us with a very large search box:

Before:
![Screen Shot 2021-03-22 at 5 11 32 PM](https://user-images.githubusercontent.com/142755/112058997-adc59e80-8b31-11eb-802a-9af101aaa990.png)

After:
![Screen Shot 2021-03-22 at 5 10 02 PM](https://user-images.githubusercontent.com/142755/112058932-95ee1a80-8b31-11eb-9936-5b228d8c44a4.png)

I think ideally we'd move the search box up to the top at this screen size, like is done at `499px` and below, but that would mean changing the breakpoint, which you seem to be against. Example at `499px`:

![Screen Shot 2021-03-22 at 5 13 33 PM](https://user-images.githubusercontent.com/142755/112059236-f7ae8480-8b31-11eb-92b3-43773df225bb.png)

**Comment by willdurand** [comment] 2021-03-22 21:18
> Oh, wow, I didn't check that. I wonder if that was a result of last week's patch moving to Inter, or if it was around even before that.

Probably before that.

> Well, I am wondering where these breakpoints came from, and if they are still accurate today. I suppose that is a separate issue.

That's my point. I think these breakpoints work rather well, except for that menu, but this is more a bug than a problem with the breakpoints.

> Do you think it's fine to not fix it for this week's push, or are you saying we should, and we need to find the time to change the layouts by tomorrow?

I think we should aim to fix this bug without changing the breakpoints. I suppose we could do a few changes to the layout, e.g., reducing the width of the search bar at ~500px (medium) or keep the default (i.e. small) view for medium screens as well (the search bar would be at the top instead).

**Comment by willdurand** [comment] 2021-03-22 21:21
> > Do you think it's fine to not fix it for this week's push, or are you saying we should, and we need to find the time to change the layouts by tomorrow?
> 
> I think we should aim to fix this bug without [...]

I wanted to add that there is no rush. It's not a new regression, if it's fixed in 10 days, that will be fine.

**Comment by willdurand** [comment] 2021-03-22 21:22
> @willdurand FWIW, I was able to fix up the `extraLarge` layout by providing less space for the search box, which I think is fine:
> 
> Before:
> ![Screen Shot 2021-03-22 at 5 07 20 PM](https://user-images.githubusercontent.com/142755/112058533-17917880-8b31-11eb-8af6-b972dcc26867.png)
> 
> After:
> ![Screen Shot 2021-03-22 at 5 06 31 PM](https://user-images.githubusercontent.com/142755/112058443-fa5caa00-8b30-11eb-9d6c-870b7dd0ceda.png)
> 
> but for the `medium` breakpoint it doesn't look quite as nice. I guess it might be acceptable but it really doesn't leave us with a very large search box:
> 
> Before:
> ![Screen Shot 2021-03-22 at 5 11 32 PM](https://user-images.githubusercontent.com/142755/112058997-adc59e80-8b31-11eb-802a-9af101aaa990.png)
> 
> After:
> ![Screen Shot 2021-03-22 at 5 10 02 PM](https://user-images.githubusercontent.com/142755/112058932-95ee1a80-8b31-11eb-9936-5b228d8c44a4.png)
> 
> I think ideally we'd move the search box up to the top at this screen size, like is done at `499px` and below, but that would mean changing the breakpoint, which you seem to be against. Example at `499px`:
> 
> ![Screen Shot 2021-03-22 at 5 13 33 PM](https://user-images.githubusercontent.com/142755/112059236-f7ae8480-8b31-11eb-92b3-43773df225bb.png)

I didn't see this while I was typing the comment, this looks quite nice. For `medium`, I suppose as soon as we get a slightly larger width like `510` or `520px`, it's already better? If so, I think it's acceptable.

**Comment by bobsilverberg** [comment] 2021-03-22 21:24
> > > Do you think it's fine to not fix it for this week's push, or are you saying we should, and we need to find the time to change the layouts by tomorrow?
> > 
> > 
> > I think we should aim to fix this bug without [...]
> 
> I wanted to add that there is no rush. It's not a new regression, if it's fixed in 10 days, that will be fine.

I'm not convinced that it wasn't a regression from last week's push, and if it is then I think we can consider it a new regression. In any case, I think we should fix it ASAP.

**Comment by willdurand** [comment] 2021-03-22 21:31
Based on our discussion on Matrix, this seems to be a regression caused by this patch: https://github.com/mozilla/addons-frontend/pull/9440

**Comment by willdurand** [comment] 2021-03-22 21:45
We also found https://github.com/mozilla/addons-frontend/issues/3955, which is kinda similar to what we get at ~500px once #9440 is reverted. Looks like a old bug between `500px` and `510px`.

**Comment by Verdi** [comment] 2021-03-22 22:32
I think making the search bar smaller is fine. It's seems like it works acceptably down to 150px wide.

**Closed** 2021-03-25 12:36 UTC
Labels: component: ux, priority: p3, type: prod_bug

**Comment by ioanarusiczki** [comment] 2021-03-29 11:18
@bobsilverberg 

Verified on AMO dev - FF87(Win10). 

![fixed ux issue](https://user-images.githubusercontent.com/33448286/112829216-7a3ac500-9099-11eb-9eb2-4d043f8a6b6a.gif)
