### ISSUE TITLE
All reviews are displayed after "Show all reviews" is clicked and then navigating back on the detail page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7241] opened 2018-12-17 14:13 UTC
STR:
1. Click one of the star rating counts from an add-on's detail page
2. Click "Show all reviews" button 
3. Go back to the add-on's detail page
4. Click another star rating count

Expected result:
The correct number of ratings/reviews is displayed.

Actual result:
All ratings and reviews are displayed.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF64 (Win10).
Refreshing page will display the correct number of ratings and reviews.

![all reviews displayed](https://user-images.githubusercontent.com/33448286/50092263-4adc5300-0216-11e9-8b79-8bcb066ad0a3.gif)

**Comment by kumar303** [comment] 2018-12-17 15:54
I verified that this is indeed a dupe of https://github.com/mozilla/addons-frontend/issues/7206

**Closed by kumar303** 2018-12-17 15:54 UTC
Labels: component: add-on ratings, type: bug
