### ISSUE TITLE
link missing

### ISSUE THREAD

**Issue by arroyoshipp** [mozilla/addons-frontend#5418] opened 2018-06-27 04:00 UTC
### Anything else we should know?

I opened the settings, I went to add-ons, I wanted to disable aplets.  But the directions I was given didn't play out.  I found a box of icons with add-ons.  They were, I thought they were for me so I clicked on a couple of them. I entered my email and name and I downloaded the add-on.   The second or third in the box gave me an error. And heer Iam....

**Comment by muffinresearch** [comment] 2018-06-27 10:51
This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services. 

From the description it's unclear what the issue is related to. Please can you provide as much information as possible so that we can understand what the issue is?

Please include screenshots and URLs so we know where on the website the problem is occurring.

**Comment by arroyoshipp** [comment] 2018-06-28 12:50
The issue is that there is a privacy policy in place and there are people content on using my email address, my browsers, my applications and they are recovering passwords with tokens, cookies, special links and flash player storage.  I just recovered an app for Google cloud where Iam fully signed in and the project on it is not mine.  But its my app, probably my debit  card on file, and I bet it has more of my data stored in it.  Clearly a direct violation of the privacy policy.   Oh but we're taking about Firefox, 2 partitions, 1 user, 1 guest only one side has the ability to switch and when the switch is done the other user is logged out.  When I found those add on, they put the settings on my side, I didn't know what it was until the sync was disabled. Now that I know what to look for and with whom.  Iam going to KILL every trace of my old Data once and for all.

**Comment by bobsilverberg** [comment] 2018-07-05 17:33
@arroyoshipp Your response above doesn't really give us any idea of exactly what the problem is, but it does seem to not have anything to do with the addons.mozilla.org (AMO) website. I am therefore going to close this issue. Feel free to re-open it if you have a specific problem to report about AMO.

**Closed by bobsilverberg** 2018-07-05 17:33 UTC
Labels: needs: info
