### ISSUE TITLE
'Add to Firefox' button looks inactive on Search Tool details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4047] opened 2017-12-06 16:25 UTC
Steps to reproduce:
1. Go to AMO homepage and from the More... menu select Search Tools
2. Pick an option from the listed results to see its details page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/3-maps/)
3. Reload the page
4. Observe the 'Add to Firefox' button displayed on the Search tool details page

Expected result:
The Add to Firefox button is active and  blue colored 

Actual result:
The Add to Firefox button is grayed out and appears inactive on hover

Notes: when clicked, the button will trigger the installation process and the search plugin is added to the browser Search bar
Reproduced on AMO -dev and stage with FF57 (Win10)

![search tools](https://user-images.githubusercontent.com/31961530/33672085-febf1944-dab1-11e7-8b74-7efad4bd7e20.gif)

**Comment by muffinresearch** [comment] 2017-12-06 18:27
FWIW: On the first time loading I briefly  see a "Your browser is not compatible with search plugins" which disappears on-load.

**Comment by muffinresearch** [comment] 2017-12-06 18:28
@AlexandraMoga are there similar examples to this in production?

**Comment by ValentinaPC** [comment] 2017-12-07 07:12
> FWIW: On the first time loading I briefly see a "Your browser is not compatible with search plugins" which disappears on-load.

That was tracked in: https://github.com/mozilla/addons-frontend/issues/2412

**Comment by AlexandraMoga** [comment] 2017-12-07 07:50
>  are there similar examples to this in production?

The behavior in production is similar to [#2412](https://github.com/mozilla/addons-frontend/issues/2412)

![search_prod](https://user-images.githubusercontent.com/31961530/33704130-cc8ec6b8-db33-11e7-91e1-e1c2d37d939b.gif)

**Comment by ValentinaPC** [comment] 2017-12-08 07:29
The initial issue is happening in prod.
Example:
https://addons.mozilla.org/en-US/firefox/addon/youtube-10423/

Screenshot:
![2017-12-08_0927](https://user-images.githubusercontent.com/15685960/33755595-37d55b28-dbfa-11e7-994d-4919ec994e28.png)

Also, as Alexandra mentioned in her notes, search tool can be installed.

**Comment by tofumatt** [comment] 2017-12-08 11:38
The button is disabled but (due to a possibly different bug!) it seems search tools are still installable on a click.

That said, this is a bit strange because running the same code on production (tag `2017.12.07-1`) locally and running `master` locally the button is enabled. It seems to only happen on prod? Very weird...

**Comment by tofumatt** [comment] 2017-12-08 11:42
Actually, I had `disableSSR: true` on in my config. Server side rendering seems to set the install button state as off/incompatible.

**Comment by ValentinaPC** [comment] 2017-12-08 12:53
> The button is disabled but (due to a possibly different bug!) it seems search tools are still installable on a click.

Yes. As Alexandra and I, said.

**Comment by tofumatt** [comment] 2017-12-08 13:16
Sorry about that! I just skimmed the issue. My bad! 🤭

**Comment by davidhedlund** [comment] 2018-02-21 09:41
@jvillalobos Said:

> I can reproduce the issue:
> 
> 1. Go to https://addons.mozilla.org/en-US/firefox/search-tools/
> 2. Click on the Booking.com entry.
> 
> Result: the button has some transparency, but still allows installation (for me).
> 
> Oddly, if I go to AMO directly and search for "booking.com", I can find the same listing and the button looks right. So, it may have to do with the transition from old to new front end that causes the bug.

**Comment by AlexandraMoga** [comment] 2018-06-29 06:06
Maybe we should up the priority for this issue as well, considering that when #5447 it was marked a s a p1.

**Comment by willdurand** [comment] 2018-06-29 07:24
@AlexandraMoga isn't it the exact same issue as in #5447? It is a shame that we missed that one..

**Comment by kumar303** [comment] 2018-06-29 15:35
The STR in this doesn't make it a dupe of https://github.com/mozilla/addons-frontend/issues/5447 but the comment thread here suggests that you were talking about the same thing. I updated the STR to include the step *Reload the page* which is necessary to reproduce the bug. Let me know if that's not what you intended.

**Closed** 2018-06-29 18:34 UTC
Labels: priority: p1, project: amo, project: desktop pages, size: S, triaged, type: bug

**Comment by ioanarusiczki** [comment] 2018-07-02 13:17
Verified fixed on AMO dev with FF61(Win10&Android 8.0). 

![search tools reloading page2](https://user-images.githubusercontent.com/33448286/42166323-56c31582-7e13-11e8-9747-3de14b18b08b.gif)
