### ISSUE TITLE
Don't show 'Read More' link if there is not additional content to show

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-frontend#3560] opened 2017-10-18 20:24 UTC
### Describe the problem and steps to reproduce it:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/amo-admin-assistant/
2. Notice that there is a 'Read More' link under the 'About This Extension' section
3. Click on the 'Read More' link

### What happened?
'Read More' link is shown when there is no additional content to show.

### What did you expect to happen?
'Read More' link is only listed if there is content which is hidden to the user by default.

**Comment by willdurand** [comment] 2017-10-18 20:29
Hi, actually it displays one more line but I agree, our heuristic is a bit weird. A similar issue has been reported in #3511. Thanks!

**Comment by tofumatt** [comment] 2017-10-18 20:29
This is duplicate of #3511, which I'll keep open just because it's got screenshots 😉

**Closed by tofumatt** 2017-10-18 20:29 UTC
