### ISSUE TITLE
Wrap translate() calls in compose()

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1261] opened 2016-10-20 12:42 UTC
As mentioned in https://github.com/mozilla/addons-frontend/pull/1259#discussion_r84193227:

We often do
```js
export default translate({ withRef: true })(LanguagePickerBase);
```
when
```js
export default compose(
  translate({ withRef: true }),
)(LanguagePickerBase);
```
is nicer to read (and arguably easier to extend if needed.

We should switch any components not using connect over.

**Comment by muffinresearch** [comment] 2016-10-20 13:47
Duplicate of https://github.com/mozilla/addons-frontend/issues/909

**Comment by tofumatt** [comment] 2016-10-20 13:47
Oops, shoot, thanks.

**Closed by muffinresearch** 2016-10-20 13:47 UTC
Labels: code quality, duplicate

**Comment by kumar303** [comment] 2016-10-20 14:25
yeah! We should convert all components even if they only use one wrapper
