### ISSUE TITLE
Extensions homepage looks "wrapped up"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2814] opened 2017-07-17 08:17 UTC
Steps to reproduce:
1. Load Extensions homepage in AMO-dev https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Observe listed add-ons

Expected results:
There are no display or layout issues.

Actual results:
Add-ons names and number of users are wrapped up.

Notes/Issues:
Verified on FF54(Win 7). Issue is only reproducing on -dev.
Screenshot for this issue:
![2017-07-17_1050](https://user-images.githubusercontent.com/15685960/28259894-348a8e5a-6ae1-11e7-960e-aa236be04f1c.png)

**Comment by tofumatt** [comment] 2017-07-17 12:48
This is a dupe of #2800 but I've already assinged this one to me so I'll close the other.

**Comment by tofumatt** [comment] 2017-07-17 13:02
It looks like this was caused around the time I merged the CSS cleanup, so likely just messed up something there and didn't catch it. Should be an easy fix, will have it ready for tomorrow's tag.

**Comment by tofumatt** [comment] 2017-07-17 16:18
Bisect actually thinks it was 37c0000e2c64f414e9fd599f03e07181526ca2fb; investigating.

**Closed** 2017-07-17 23:22 UTC
Labels: priority: p1, project: amo, project: desktop pages, type: regression

**Comment by ValentinaPC** [comment] 2017-07-18 10:50
Verified as fixed on AMO-dev FF54(Win 7) (checked also non-en locales)
Postfix screenshot:
![2017-07-18_1346](https://user-images.githubusercontent.com/15685960/28313461-969626e8-6bbf-11e7-98d1-731d09b9d84d.png)
