### ISSUE TITLE
"Update review" button is clickable if review is edited with Space key 

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/addons-frontend#9718] opened 2020-10-01 13:45 UTC
### Describe the problem and steps to reproduce it:
1. Log in and write a review for an add-on.
2. Click "Edit review".
3. Make sure that the text box is selected and press the Space key.

### What happened?
"Update review" can be clicked to save the edited review.
### What did you expect to happen?
"Update review" can't be clicked.
### Anything else we should know?
Reproduced on all AMO servers with FF 81.0 on Win10x64.

![3](https://user-images.githubusercontent.com/54401091/94816682-d2538000-0404-11eb-943d-09298fa3f324.gif)

**Comment by ThamiMemel** [comment] 2020-10-18 14:59
Can someone kindly  label this to confirm this isn't an expected behaviour.
I can work on this.

**Comment by ioanarusiczki** [comment] 2020-10-20 11:17
cc @bobsilverberg Could this be considered a good first bug?

**Comment by bobsilverberg** [comment] 2020-10-20 12:13
It's a very simple fix, but will need an associated test, so I suppose it could be a good first bug. I'll add the "maybe" label to it.

I believe the only change required is to add some trimming to the condition at https://github.com/mozilla/addons-frontend/blob/master/src/ui/components/DismissibleTextForm/index.js#L183.

**Comment by caitmuenster** [comment] 2020-10-26 16:08
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

**Comment by grininja** [comment] 2020-10-26 17:45
I want to work on this issue

**Comment by caitmuenster** [comment] 2020-10-26 18:18
Go for it, @grininja! We'll assign you to the bug once you submit a PR. :) If you have any specific questions, please tag @bobsilverberg in a comment. :)

**Comment by bobsilverberg** [comment] 2020-10-29 15:13
@grininja, it looks like @Yrkan has submitted a PR to fix this issue. As you were initially assigned, I want to give you a chance to do it, if you still have the time and interest in doing so. Can you please let us know if you wish to continue with this issue, or if I can re-assign it to @Yrkan?

**Comment by Yrkan** [comment] 2020-10-29 15:31
Oops sorry i didn't catch up with the comments, i thought it was still unassigned.
@bobsilverberg Please feel free to close the PR if @grininja sends one.

**Comment by bobsilverberg** [comment] 2020-11-02 16:02
@Yrkan We haven't had a response from @grininja, so I will review your patch. Thanks!

**Closed** 2020-11-02 16:04 UTC
Labels: component: add-on ratings, contrib: good first bug, contrib: mentor assigned, priority: p3

**Comment by alexandra-martin** [comment] 2020-11-04 08:00
Verified issue as fixed on dev and stage environment with FF 82.0.2 on Win10x64.

![1](https://user-images.githubusercontent.com/54401091/98084409-6d1c0000-1e84-11eb-819d-a7f7e9ed1cea.gif)

**Comment by grininja** [comment] 2020-11-04 12:40
Sorry for very late response due to Ill health ,happy that bug got fixed,next time I will definitely take care of that.
