### ISSUE TITLE
CircleCI Integration tests failing - test_category_section_loads_correct_category

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#9652] opened 2020-09-16 18:31 UTC
Log Output

```
_____ test_category_section_loads_correct_category[Resolution: 1080x1920] ______
[gw0] linux -- Python 3.6.9 /usr/bin/python3

base_url = 'http://olympia.test'
selenium = <selenium.webdriver.firefox.webdriver.WebDriver (session="c98ac172-3349-4339-8871-484bc1c68041")>

    @pytest.mark.desktop_only
    @pytest.mark.nondestructive
    def test_category_section_loads_correct_category(base_url, selenium):
        page = Extensions(selenium, base_url).open()
        item = page.categories.category_list[0]
        name = item.name
        category = item.click()
>       assert name in category.header.name
E       AssertionError: assert 'Alerts & Updates' in 'Searching for add-ons'
E        +  where 'Searching for add-ons' = <pages.desktop.category.Category.Header object at 0x7f7eed7136a0>.name
E        +    where <pages.desktop.category.Category.Header object at 0x7f7eed7136a0> = <pages.desktop.category.Category object at 0x7f7eed713ac8>.header

tests/frontend/ui/test_home.py:42: AssertionError
```

Are there any ideas on what might be causing this? Maybe a category has been renamed or something?

**Comment by bobsilverberg** [comment] 2020-09-16 18:40
Hi Benny, as I mentioned on Slack, when you first navigate to a category screen, the category name is listed as "Searching for add-ons", and then resolves to the actual category name, which in this case would be "Alerts & Updates". So I don't think the problem is a renamed category, I think it's that the interim title of "Searching for add-ons" is being read, before it has a chance to update to "Alerts & Updates". I don't think anything landed recently that would be causing this, but I'll look through the commit history.

At this point it seems like a timing thing. I wonder if the test needs to wait for something before checking the name of the category?

**Comment by jrbenny35** [comment] 2020-09-16 18:48
Yeah that sounds like it could be it. We could add a wait for condition so it would wait until the name changed.

We could do something like this: https://selenium-python.readthedocs.io/waits.html#explicit-waits and use this expected condition, https://selenium-python.readthedocs.io/api.html#selenium.webdriver.support.expected_conditions.text_to_be_present_in_element

**Comment by bobsilverberg** [comment] 2020-09-16 19:03
Doing something like that makes sense, although I am still a bit confused about why this has just started to fail now. Nothing has changed about the timing of that heading.

**Comment by jrbenny35** [comment] 2020-09-16 19:04
It could be an update with selenium or firefox. Something is returning faster in the browser than it used to.

**Closed** 2020-09-22 18:37 UTC
Labels: component: testing, component: uitests, needs: info
