### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by natmac21007** [mozilla/addons-frontend#7666] opened 2019-03-04 02:47 UTC
### Describe the problem and steps to reproduce it:

I was updating a ticket (service-now) on a newly set up machine, and the inbuilt spell checker flagged a correctly spelled word (Australian) so I right clicked, languages, Add Dictionaries

### Anything else we should know? A little frustration to have to fill out so much if you were not already a GitHub user.

I can't give you a link to the page I was on, but it is repeatable on other pages, eg I just tested it at
https://www.google.com/search?q=organise&ie=utf-8&oe=utf-8&client=firefox-b 
![capture1](https://user-images.githubusercontent.com/31526020/53707672-0d39ae80-3e84-11e9-8834-3b9dc04ac2dd.PNG)
![capture2](https://user-images.githubusercontent.com/31526020/53707676-0f9c0880-3e84-11e9-8afb-3fb3f1aa74cc.PNG)
![capture3](https://user-images.githubusercontent.com/31526020/53707680-1165cc00-3e84-11e9-9664-87167e4fa67d.PNG)

**Comment by AlexandraMoga** [comment] 2019-03-04 08:17
Thanks for the report. This  is, however, a duplicate of https://github.com/mozilla/addons-frontend/issues/7658

**Closed by AlexandraMoga** 2019-03-04 08:17 UTC
