### ISSUE TITLE
Prevent the test suite from ever calling a real API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1138] opened 2016-09-26 17:31 UTC
### Describe the problem and steps to reproduce it:
- write a test for an action that calls the API
- forget to mock out the `callApi` method
### What happened?

This will attempt to make a real API request (depending on what server is configured). The result will probably be a harmless 401 Unauthorized since no real tokens are used in the test suite but this can cause slowness.
### What did you expect to happen?

It should not make any real API request at all even though it was a mistake not to mock the component.
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment] 2016-09-26 17:55
Dupe of https://github.com/mozilla/addons-frontend/issues/773 but I'll close that one since you've got a better description.

**Comment by muffinresearch** [comment] 2017-03-21 13:38
We should also look at the server tests and do the same there as per #773.

**Comment by kumar303** [comment] 2017-05-16 16:29
Here are some server tests that need to be fixed not to rely on the Internet:

<img width="581" alt="screenshot 2017-05-16 11 28 33" src="https://cloud.githubusercontent.com/assets/55398/26117082/e6a318a6-3a2a-11e7-8289-b04f3c22e77a.png">

**Comment by muffinresearch** [comment] 2017-06-02 16:44
I think this should be fixed with the server tests gone. But would love a way to programmatically ensure it.

**Comment by kumar303** [comment] 2017-06-02 17:23
The offending tests might be gone but we should add something to stop it from ever happening again

**Closed** 2018-07-30 19:00 UTC
Labels: component: code quality, priority: p4, triaged

**Comment by AlexandraMoga** [comment] 2018-07-31 05:46
Please add STR or the label 'qa:not needed'
Thanks
