### ISSUE TITLE
Editing a developer reply from a permalink is visually awkward

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6356] opened 2018-09-21 21:30 UTC
### Describe the problem and steps to reproduce it:

- Sign in as a developer
- Go to one of your add-ons that has some reviews
- Go to the review listing
- Reply to a review
- Click the timestamp of the review to view its detail page
- From the detail page, click *Edit my review*

### What happened?

It looks like:

<img width="746" alt="screenshot 2018-09-21 16 22 28" src="https://user-images.githubusercontent.com/55398/45906838-3c1f0500-bdbb-11e8-8ec5-9876e4db30a8.png">

### What did you expect to happen?

* There shouldn't be any stars
* ~~You should only see one review form. Multiple forms are open because the reply is also rendered further down in the listing.~~
  * https://github.com/mozilla/addons-frontend/issues/6443 has been opened to address this.
* ~~The link to edit should have been *Edit my reply*~~
* The buttons should say *Update reply*, etc

**Comment by AlexandraMoga** [comment] 2018-09-25 13:57
If you venture on selecting a star, an error message will also be displayed:

![image](https://user-images.githubusercontent.com/31961530/46019096-fed0b500-c0e3-11e8-8fe0-fd82a40799d7.png)

**Comment by bobsilverberg** [comment] 2018-09-26 19:40
@kumar303 maybe a change landed since you reported this, but there is one aspect of your report I cannot reproduce.  You say:

> The link to edit should have been Edit my reply

I do see "Edit reply" as the link in the featured review card:

![screenshot 2018-09-26 15 37 50](https://user-images.githubusercontent.com/142755/46104821-57668780-c1a2-11e8-9c10-e439a5adb599.png)

Is that bug no longer valid, or am I misunderstanding?

**Comment by kumar303** [comment] 2018-09-26 20:14
> I do see "Edit reply" as the link in the featured review card

Yep, this is fixed now. I crossed it out in the description. It looks like the other things I mentioned in the description still need fixing.

**Closed** 2018-09-28 15:11 UTC
Labels: component: add-on ratings, priority: p3, triaged

**Comment by bobsilverberg** [comment] 2018-10-01 17:32
> The page must be refreshed to see the updated text down below in the list of reviews. Same if the response is edited from the list of reviews, not a big issue but let me know if we should track this with another issue.

I opened https://github.com/mozilla/addons-frontend/issues/6441, which I think addresses the issue you describe. Do you agree @ioanarusiczki?

**Comment by ioanarusiczki** [comment] 2018-10-02 08:18
@bobsilverberg Yes, I agree. It's in here https://github.com/mozilla/addons-frontend/issues/6441
