### ISSUE TITLE
Turn the author name in the 'More extensions by` section into a link

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#6030] opened 2018-08-23 14:52 UTC
### Describe the problem and steps to reproduce it:

1. Be on an extension page from an author who has published other extensions too e.g. https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
2. Scroll down to the bottom of the page, until the `More extensions by [author name]` (`..AddonsByAuthorsCard`) section shows up.

### What happened?
The author name isn't a link.
![screenshot_2018-08-23 ublock origin add-ons for firefox](https://user-images.githubusercontent.com/8336638/44531813-493eca80-a70f-11e8-8958-9411d657e45d.png)

### What did you expect to happen?
I expected it to be a link. I know that there is an author link in the first `.Addon-header-info-card` but scrolling to the top is unintuitve and inconvenient. Many people might not even notice/remember the top card link.

### Anything else we should know?
The equivalent of this section in the previous design had this link:
![screenshot_2018-08-23 ublock origin](https://user-images.githubusercontent.com/8336638/44532958-ffa3af00-a711-11e8-91e5-6799ce93c0b2.png)

**Comment by jvillalobos** [comment] 2018-08-23 16:31
Duplicate of https://github.com/mozilla/addons-frontend/issues/3771

We decided to only link the name in the page header.

**Closed by jvillalobos** 2018-08-23 16:31 UTC
