### ISSUE TITLE
Accessing an admin disabled add-on returns its details page using a direct link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3817] opened 2017-11-07 09:31 UTC
Prerequisites:
User is logged with an admin account.

Steps to reproduce:
1. Submit an extension on AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-disabled-by-admin/
2. Disable it from Admin Tools page
3. Use a direct link to load its public page (above link)

Expected results:
A message is displayed informing the user that the add-on was disabled by an admin.

Actual results:
A 404 page is loaded.

Notes/Issues:
- old AMO site displays "This add-on has been disabled by an administrator." message while accessing an admin disabled add-on using a direct link.
- while being logged out a 404 page is displayed in new pages
Verified on AMO-dev FF56(Win 7).
Video for this issue:
- logged in
![admin disabled](https://user-images.githubusercontent.com/15685960/32486203-9852870a-c3ae-11e7-8d21-51a72e5cf510.gif)

- logged out
![404](https://user-images.githubusercontent.com/15685960/32486004-01048d08-c3ae-11e7-83be-7c10402e8684.gif)

Relates with #2261

**Comment by muffinresearch** [comment] 2017-11-07 10:32
Following the discussion on irc it sounds the API was built to do this by design. Whilst we are looking to mainly avoid returning different data for the same URL based on permissions @diox pointed out that there's a good use-case here for developers to see their own listing based on permissions.

We do need to ensure that privileged App and API responses are not cacheable because if they are this would mean that invisible or deleted responses could get cached upstream. _If they are cacheable then it's a higher priority issue._ 

Aside from the caching question for the future we need to consider the following:

* Look at the use-cases for this feature - if we do have valid reasons (the developer use-case sounds reasonable) we should make sure it's appropriately labelled to explain this isn't what everyone else sees. 
* Make it clearer in the API docs when we're changing responses based on permissions because otherwise it might catch implementers by surprise.

**Comment by muffinresearch** [comment] 2017-11-08 14:27
@diox iirc you had mostly completed looking into where we were re: caching headers - I lost track after the issue re: localized content showing up in curl for dates came up.

**Comment by muffinresearch** [comment] 2017-11-08 14:28
If the answer to the caching question is everything is fine, then we can close this and file some other issues for making the display clearer for the permission based access.

**Comment by diox** [comment] 2017-11-08 18:11
The only caching-related header we send at the moment is an `ETag`, so we're fine.

**Comment by diox** [comment] 2017-11-15 16:16
@muffinresearch anything left for me to do here? Not sure if it should be closed or handled better by the frontend.

**Comment by muffinresearch** [comment] 2017-11-15 16:17
@diox I think we can close it. I'll file an issue re: labelling it better.

**Closed by muffinresearch** 2017-11-15 16:17 UTC
Labels: project: amo, project: desktop pages, triaged
