### ISSUE TITLE
Submit review button should be visible without scrolling on Android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4630] opened 2018-03-23 14:26 UTC
Prerequisites:
User is logged in.

STR:
1. Load AMO stage and go to an add-ons detail page to write a review.
2. Write a text in the box and click on the Submit review. 
3. Check for the Submit review button.

Expected results:
The button is visible.

Actual results:
The Submit Review button is not visible unless scrolling.

Notes:
This issue is reproducible on all AMO servers with FF59 (Android 8.0) when the device is in portrait view.

![submit button android](https://user-images.githubusercontent.com/33448286/37834643-e1918dda-2eb6-11e8-8874-a52fde4be873.gif)

**Comment by kumar303** [comment] 2018-03-23 15:19
I think https://github.com/mozilla/addons-frontend/issues/3636 will address this issue

**Comment by ioanarusiczki** [comment] 2018-03-26 08:57
@kumar303 I wanted to reference #3636 to this issue too. Thanks !

**Comment by muffinresearch** [comment] 2018-03-28 13:42
Marking as duplicate of https://github.com/mozilla/addons-frontend/issues/3636

**Closed** 2018-03-28 13:46 UTC
Labels: component: add-on ratings, component: ux, platform: android, state: duplicate
