### ISSUE TITLE
error page

### ISSUE THREAD

**Issue by Waterismygod** [mozilla/addons-frontend#3921] opened 2017-11-15 23:21 UTC
### What happened?
Clicked on email link from firefox
### What did you expect to happen?
to go to the site for the new addons Extensions are like toppings for your baked potato — once you try them, you can't imagine going without them. Firefoxers use extensions to give their privacy a boost, play games, block ads, manage video downloads and all kinds of other extraordinary stuff.

Give your browser superpowers and discover the top Firefox extensions:

### Anything else we should know?

Page not found

Sorry, but we can't find anything at the address you entered.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

**Comment by kumar303** [comment] 2017-11-16 04:55
Thanks for taking the time to file an issue. I'm glad you like add-ons. What URL did you click on?

**Comment by willdurand** [comment] 2017-11-22 13:39
duplicate of #3951

**Closed by willdurand** 2017-11-22 13:39 UTC
Labels: needs: info
