### ISSUE TITLE
Google Analytics: Unable to capture full URL of the source. I am trying to capture the full URL of the website[The URL is different for different content].  But instead of capturing full URL I am only getting the hostname of the URL.

### ISSUE THREAD

**Issue by Sriram9894** [mozilla/addons-frontend#3881] opened 2017-11-13 06:14 UTC

**Comment by tofumatt** [comment] 2017-11-13 10:45
Closing due to lack of information.

Please add information to your issue including the error you encountered, a URL (if applicable), and steps to reproduce.

**Closed** 2017-11-13 10:44 UTC
Labels: state: invalid
