### ISSUE TITLE
not saving themes

### ISSUE THREAD

**Issue by mickyfan2345** [mozilla/addons-frontend#5271] opened 2018-06-11 21:59 UTC

**Comment by mickyfan2345** [comment] 2018-06-11 22:01
when i go to the main page for themes hit the item i want it wont let me do nothing it takes me to a page saying Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it. i go to report it and they don't do nothing what's going on it only happens when im signed in

**Comment by jvillalobos** [comment] 2018-06-12 20:31
Duplicate of https://github.com/mozilla/addons-frontend/issues/5203

Please don't file more issues about this. You are not providing enough information for us to find or fix the problem, so there's nothing we can do to assist you until you provide it.

**Closed by jvillalobos** 2018-06-12 20:31 UTC

**Comment by mickyfan2345** [comment] 2018-06-12 20:59
jvillalobos, what more do you want i have given you all the info i can give you it just doesnt wanna save a theme when im logged in  it takes me to this Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
Suggested Pages

Browse all extensions
Browse all themes
Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it. i go to report it and they don't do nothing what's going on it only happens when im signed in
