### ISSUE TITLE
A restart is required for a restartless addon first time after starting Firefox

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#723] opened 2016-07-07 12:33 UTC
Prerequisites:
Firefox beta 5
Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0

Steps to reproduce:
1.Set your disco pane to production following the steps from https://mana.mozilla.org/wiki/display/SVCOPS/AMO+Dev+Resources#AMODevResources-TestingDiscopaneinProd
2.Start your Firefox with a clean profile and open Disco Pane
3.Install a restartless addon like Adblock Plus from 

Expected results:
Addon is successfully installed and gets the green checkmark

Actual results:
Addon asks for restart in both disco pane homepage and Extensions tab

Please see video for this bug : http://screencast.com/t/QATSCmQ1

NOTES:
After restart , a subsequent install will not ask for restart .
Possible related to  #495 , but its a different bug .

**Comment by muffinresearch** [comment] 2016-07-07 12:55
Pretty sure this *is* a dupe of #495. We get the restart hint and it requires the user to restart. There's not anything we can do without firefox changes - and this doesn't happen after that first add-on is installed.

As per #495 this will only happen for someone who has never installed an extension and happens to do that for the first time via the disco pane.

The only thing that will fix this is firefox changes as per https://github.com/mozilla/addons-frontend/issues/495#issuecomment-229014152 there's nothing we can do from this side.

**Comment by muffinresearch** [comment] 2016-07-07 13:12
I'm going to mark this as a dupe of #495

**Closed by muffinresearch** 2016-07-07 13:12 UTC
Labels: disco pane, duplicate
