### ISSUE TITLE
Don't show incompatible addons with blue install buttons on Android

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3649] opened 2017-10-26 16:04 UTC
Steps to reproduce:
1.On your Android device,using FF Nightly, go to https://addons.allizom.org/en-US/android/addon/youtube-high-definition/

Expected results:
Install button should be greyed out and a red banner should warn that add-on is incompatible with this FF version

Actual results:
"Add to firefox" button is blue and there is no banner

NOTES:
When trying to install , the "Downloading add-on" pop-up is displayed, but add-on is never installed

Please see video for this bug : 
![incompat](https://user-images.githubusercontent.com/1583842/32063698-8572c136-ba80-11e7-9523-b477fdb56f8a.gif)

**Comment by kumar303** [comment] 2017-10-26 16:11
This is working as expected. The Add-on does not have compatibility rules for Android (only Firefox):

<img width="720" alt="screenshot 2017-10-26 11 07 29" src="https://user-images.githubusercontent.com/55398/32063945-208aa1fe-ba3e-11e7-842d-be61af54c507.png">

This means it is compatible with Android by default.

If they wanted to restrict the Android version they'd have to add it as an application to the compatibility section:

<img width="486" alt="screenshot 2017-10-26 11 08 06" src="https://user-images.githubusercontent.com/55398/32063982-3b31a8b8-ba3e-11e7-9015-6f22d5b9ff76.png">

**Comment by kumar303** [comment] 2017-10-26 16:12
Oh, sorry, I just read that it cannot be installed. That seems like a bug.

**Comment by kumar303** [comment] 2017-10-26 16:18
ok, we worked this out on IRC. The extension from the stage server is legacy (pre-57) which is why it can't be installed. In production, this extension is a webextension so it should work.

**Comment by kumar303** [comment] 2017-10-26 16:41
This is actually a bug. The problem is that when no compatibility rule exists for the client app at all then we should assume it is incompatible *even though* the extension has a file claiming to support all platforms.

**Comment by kumar303** [comment] 2017-10-27 14:05
Good catch @vcarciu 

This patch touches all of the compatibility code so could you also help check for regressions of the following features?

* Viewing an add-on page with Chrome should show an incompatible message
* Viewing an add-on with a Firefox version older than what the add-on supports should show an incompatible message
* Viewing compatible add-ons in Firefox and Android should show a working install button

**Comment by kumar303** [comment] 2017-10-27 22:12
FYI, I caught this regression https://github.com/mozilla/addons-frontend/issues/3669 I have proposed a patch for it. Let's wait for that to land.

**Comment by kumar303** [comment] 2017-10-30 16:36
#3669 is fixed now

**Closed by kumar303** 2017-10-30 16:36 UTC
Labels: priority: mvp-polish

**Comment by vcarciu** [comment] 2017-11-01 17:13
Verified as fixed based on comments from above.
