### ISSUE TITLE
The profile picture doesn't always show up immediately after updating

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5365] opened 2018-06-22 14:41 UTC
### Describe the problem and steps to reproduce it:
Go to your profile with a picture
Delete the picture
click Update my profile
click Edit Profile
Add picture
click Update my profile

### What happened?
profile image doesn't immediately appear

### What did you expect to happen?
profile image appears without having to refresh, etc

### Anything else we should know?
https://monosnap.com/file/6R6NGrPox1RTh6JOPjsJ7HiJGmqJOb#embed

**Comment by willdurand** [comment] 2018-06-27 14:30
I think it is a duplicate of #5252

**Closed by willdurand** 2018-06-27 14:30 UTC
