### ISSUE TITLE
User should be able to click reviews to view

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#4443] opened 2018-02-23 20:02 UTC
A user should be able to click the “reviews” section at the top of the page to view all reviews.

![b68aa4ae-f069-49be-8e09-43860be77901](https://user-images.githubusercontent.com/6797635/36614390-63e01d92-1891-11e8-85b4-e2695d6f5a18.jpeg)

**Comment by tofumatt** [comment] 2018-02-23 20:03
Duplicate of #4287 ^_^

**Comment by pwalm** [comment] 2018-02-23 20:04
@tofumatt  Lol, closed as I was adding labels

**Closed by tofumatt** 2018-02-23 20:03 UTC
