### ISSUE TITLE
Increase base font size on Add-Ons pages

### ISSUE THREAD

**Issue by risa-hdqc** [mozilla/addons-frontend#9078] opened 2019-11-14 23:29 UTC
### Describe the problem and steps to reproduce it:
The font size across the app should be bumped up. It's not accessible to those with even the slightest visual impairments.

### What happened?
I've been having some issues with my vision and was searching for a Firefox extension that would help make text more readable.

I found the following extension, which is great but it's ironic that the font size on the "About this Extension" section is unreadable in my current state.

### What did you expect to happen?
I expected I would be able to read about the extension and search for different extensions on your site.

### Anything else we should know?
Extension details page: https://addons.mozilla.org/en-US/firefox/addon/readability-based-reader-view/

Search results page:  https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=readability

![image](https://user-images.githubusercontent.com/47829929/68904773-967fd100-06f3-11ea-849a-02d8af90611f.png)

**Comment by Shivansh2407** [comment] 2020-01-17 09:47
Can I work on this @risa-hdqc and @bobsilverberg ?

**Comment by bobsilverberg** [comment] 2020-01-17 13:59
@Shivansh2407 I'm not sure this is actually something we want to implement. It's best to look for issues with the `contrib: welcome` label: https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22contrib%3A+welcome%22

@jvillalobos do you have an opinion here about whether this is something we want to do/change?

**Comment by jvillalobos** [comment] 2020-01-17 15:34
@aaronrbenson, @atsay  what do you think? I tend to agree that our font size is a bit small, but I don't feel very strongly about it.

**Comment by risa-hdqc** [comment] 2020-01-17 18:51
My opinion doesn't carry much weight but I think it's always a good idea to move from `px` to `em`s for font sizes. I imagine it could be frustrating to have your browser's default font size set pretty high due to visual disability but still end up on pages with 12px font because of these hard coded values/units.

**Comment by Sujay-Tandel** [comment] 2020-01-19 06:24
Can I work on this?

**Comment by willdurand** [comment] 2020-01-20 11:03
> Can I work on this?

@Sujay-Tandel I don't think so, sorry.  
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by FatOrangutan** [comment] 2020-01-31 18:23
In https://github.com/mozilla/addons-frontend/issues/4431 that I filed, [pwalm had said](https://github.com/mozilla/addons-frontend/issues/4431#issuecomment-369987147):

>As for body copy, I've got it spec'd out at 15px site wide, so 12px is a mistake. Our design system team is putting the finishing touches on a revised typography spec, so that will fix most (or all) of the issues you've brought up.

**Comment by jvillalobos** [comment] 2020-08-03 17:11
We recently discussed this with @aaronrbenson, and currently the recommendation is to use the [Protocol design system](https://protocol.mozilla.org/fundamentals/typography.html) for fonts. However, we don't have any concrete plans for making this change right now.

**Comment by willdurand** [comment] 2021-03-16 15:30
Thanks to @muffinresearch for mentioning this link: https://mozilla.design/firefox/typography/.

**Comment by willdurand** [comment] 2021-03-16 16:54
Marking as p2 because the new font (Inter) is a bit hard to read with the current font sizes.

**Comment by bobsilverberg** [comment] 2021-03-18 19:52
Looking at our fonts, and at https://mozilla.design/firefox/typography/, I see we use *a lot* of different font sizes. As I recall, this was done as we were developing different features and UX suggested we tweak sizes, but it means we've ended up with a large number of different font sizes on the site.

Is one of the goals of this issue to reduce the number of sizes we use, and try to standardize, as much as possible, on the suggested sizes in the design guide?

Also, the design guide specifically states to use Metropolis Bold for headings and Inter Regular for body copy, so I suspect that the sizes given for the headings, which use Metropolis in the guide, won't be equivalent to the same size in Inter. I'm going to experiment to see how close I can get text in Inter to resemble the same text in Metropolis and use those sizes, as opposed to the numbers in the doc, which pertain to Metropolis. Do people agree with that approach?

**Comment by willdurand** [comment] 2021-03-18 20:11
> Is one of the goals of this issue to reduce the number of sizes we use, and try to standardize, as much as possible, on the suggested sizes in the design guide?

Yes, that would be nice.

> Also, the design guide specifically states to use Metropolis Bold for headings and Inter Regular for body copy, so I suspect that the sizes given for the headings, which use Metropolis in the guide, won't be equivalent to the same size in Inter. I'm going to experiment to see how close I can get text in Inter to resemble the same text in Metropolis and use those sizes, as opposed to the numbers in the doc, which pertain to Metropolis. Do people agree with that approach?

Yes

**Comment by bobsilverberg** [comment] 2021-03-19 12:02
Having looked at our default font sizes, and compared them to the design guide, I've found that our body font sizes are somewhat close to the spec, but one step smaller:
 
- Our medium size (`$font-size-m`) is 16px, which is the same as the guide's "Body MD", but it really represents our larger body font size.
- We have a medium-smaller size (`$font-size-m-smaller`) which is 14px. This is the same size as "Body SM" in the guide. The guide doesn't have an equivalent intermediate size.
- Our small size (`$font-size-s`) which is 12px. This is the same size as "Body XS" in the guide, which does suggest it's probably too small for our purposes.
 
Looking at the guide, and comparing to our default fonts, we don't have anything that corresponds to "Body LG" in the guide (which is 18px). I think what makes the most sense, as a "first crack", would be to rename our `$font-size-m` to `$font-size-l` and make it 18px. We can then bump up the others (`$font-size-m-smaller` becomes `$font-size-m` at 16px and `$font-size-s` keeps its name and becomes 14px). That would bump up all of our sizes and bring us in line with the guide in terms of naming.

For headings, our sizes don't really match up:
- What we're now calling `$font-size-xl` is 36px, so I think we can bump that up to 40px, which is the same as the design guide's "Heading - MD", and we should change its name to `$font-size-heading-m`.
- What we're now calling `$font-size-l` is 28px, so I think we can bump that up to 32px, which is the same as the design guide's "Heading - SM", and we should change its name to `$font-size-heading-s`.

This doesn't address the myriad of other font sizes that we have sprinkled around the stylesheets, but I think it's a good start. I'll make this change and put up some screen shots.

I also think that some of the specific issues we've seen (such as with the Download File link) are more about font weight than size, as I think Inter is lighter in general than our previous font. We might need to just address those individually.

**Comment by bobsilverberg** [comment] 2021-03-19 12:14
Some screenshots:

<details>
<summary>Home Page - above the fold:</summary>

Note that many of the elements are the same because they are not using the default font sizes, but rather are using specific font sizes. That's something we should address, but I was thinking we might start with the default sizes for now.

Before:
![Screen Shot 2021-03-20 at 08 01 08](https://user-images.githubusercontent.com/142755/111777421-a67c6780-8889-11eb-8717-e8e4f723ffd9.png)

After:
![Screen Shot 2021-03-20 at 08 01 01](https://user-images.githubusercontent.com/142755/111777378-995f7880-8889-11eb-98fd-0474624f2392.png)
</details>

**Comment by bobsilverberg** [comment] 2021-03-19 12:50
@mozilla/addons-engineering @jvillalobos I have added some screenshots of a number of pages showing the difference with only bumping up the default font sizes to match the design doc, plus one extra fix for the "Download file" button. Please take a look when you have a chance and let me know what you think.

We may want to try pushing these changes for now, or we may want to take some extra time to deal with some of the elements that haven't changed yet, because they have unique font sizes.

**Comment by jvillalobos** [comment] 2021-03-19 14:13
This all looks good to me and I'm favor of shipping it. @verdi, can you confirm?

**Comment by willdurand** [comment] 2021-03-19 15:43
> This doesn't address the myriad of other font sizes that we have sprinkled around the stylesheets, but I think it's a good start. I'll make this change and put up some screen shots.

Can you clarify this part? It'd be nice to not have too many font sizes anymore.

**Comment by bobsilverberg** [comment] 2021-03-22 13:59
> > This doesn't address the myriad of other font sizes that we have sprinkled around the stylesheets, but I think it's a good start. I'll make this change and put up some screen shots.
> 
> Can you clarify this part? It'd be nice to not have too many font sizes anymore.

There are a couple of parts to this:

1. We have some other font size variables defined in `vars.scss` (e.g., `$font-size-form-header`, `$font-size-puffy-buttons`, `$font-size-hero-m`, etc.).
2. There are explicit font-sizes in a number of components' scss files (e.g., `.Footer-links-header` has `font-size: 16px;` in `Footer/styles.scss`).

I will file a follow-up to look into these are try to remove as many as possible, and just use our default font sizes where possible.

**Comment by Verdi** [comment] 2021-03-22 14:32
@bobsilverberg Looks good - let's do it.

**Closed** 2021-03-22 14:35 UTC
Labels: component: ux, priority: p2

**Comment by ioanarusiczki** [comment] 2021-03-23 15:38
@bobsilverberg 
- it looks good yet can't tell if it cannot look better:

this was before - the "y", "g" look truncated a bit but the menu is aligned:

![before](https://user-images.githubusercontent.com/33448286/112167443-20e61800-8bf9-11eb-821a-0c010a1b87a2.png)

now the user name seems to stand a bit higher:

![now](https://user-images.githubusercontent.com/33448286/112167829-6f93b200-8bf9-11eb-9882-deae1eb075e4.png)

log out view before:
![log out before](https://user-images.githubusercontent.com/33448286/112168077-a964b880-8bf9-11eb-9121-5c40af658502.png)

log out view now (the font size of 11px for "Register or log in" is the same as before)
![log out now](https://user-images.githubusercontent.com/33448286/112168124-b1bcf380-8bf9-11eb-8e77-5c7ec7d0ee1a.png)
 
- the footer of the page has "Add-ons" at 18 px, Browsers and Products are at 16px.
 
![footer](https://user-images.githubusercontent.com/33448286/112168873-59d2bc80-8bfa-11eb-93a9-e683163cd4c2.png)

- some elements don't look aligned:
"✓" with the message when adding an addon to a collection
![collection card from detail page](https://user-images.githubusercontent.com/33448286/112169351-cb126f80-8bfa-11eb-9171-3b6eae41a91d.png)
"!" into the site notice:

![warnings](https://user-images.githubusercontent.com/33448286/112169719-1e84bd80-8bfb-11eb-81d0-335331f3638c.png)

icons in the autocomplete results:

![autocomplete](https://user-images.githubusercontent.com/33448286/112169835-365c4180-8bfb-11eb-9f7d-070ff6a5522a.png)

- "Any" looks a bit cut for "Badging" sort filter:

![Badging](https://user-images.githubusercontent.com/33448286/112170171-8509db80-8bfb-11eb-8363-bbeafa4ca8e8.png)

- there's some 12 px font left but maybe it's intended: "What is this" link from primary hero - homepage, "Available for your locale" and "All Locales" from language tools page.
- on edit profile page - the 10px font is small compared to the rest of the page and quite blurry

![edit profile page](https://user-images.githubusercontent.com/33448286/112171561-9a333a00-8bfc-11eb-8768-0f108849afdf.png)

- text from the extensions/themes tab or search results was increased: 
"Extensions" from 36 px to 40 px (and the following text below from 16 px to 18 px)
when making a search- 254 results found for "search" - from 28 px to 32 px 

The increase of the 12px to 14 px makes the text easier to read, looks good. 
Looking at the frontend on Android with a small screen - looks good. 
I've looked over Chrome too and I'll check it in more detail tomorrow morning, the "Download file" looks better on large and small screens. 

Let me know what needs to be fixed and I'll file separate issues if necessary.
Thanks!

**Comment by bobsilverberg** [comment] 2021-03-23 17:09
> * it looks good yet can't tell if it cannot look better:
>

Thanks for checking it out @ioanarusiczki! My replies below... 
> 
> this was before - the "y", "g" look truncated a bit but the menu is aligned:
> 
> ![before](https://user-images.githubusercontent.com/33448286/112167443-20e61800-8bf9-11eb-821a-0c010a1b87a2.png)
> 

I can't reproduce this issue with "y" and "g" locally. Is this only with the old version or also with the new one?

> now the user name seems to stand a bit higher:
> 
> ![now](https://user-images.githubusercontent.com/33448286/112167829-6f93b200-8bf9-11eb-9882-deae1eb075e4.png)
>

This should be fixed via https://github.com/mozilla/addons-frontend/issues/10260
 
> log out view before:
> ![log out before](https://user-images.githubusercontent.com/33448286/112168077-a964b880-8bf9-11eb-9121-5c40af658502.png)
> 
> log out view now (the font size of 11px for "Register or log in" is the same as before)
> ![log out now](https://user-images.githubusercontent.com/33448286/112168124-b1bcf380-8bf9-11eb-8e77-5c7ec7d0ee1a.png)
>

We should fix this. Can you include it in a new issue? I think the ones that aren't fixed by https://github.com/mozilla/addons-frontend/issues/10260 can all be included in a single new issue.
 
> * the footer of the page has "Add-ons" at 18 px, Browsers and Products are at 16px.
> 
> ![footer](https://user-images.githubusercontent.com/33448286/112168873-59d2bc80-8bfa-11eb-93a9-e683163cd4c2.png)
> 

We should fix this. Can you include it in the new issue?

> * some elements don't look aligned:
>       "✓" with the message when adding an addon to a collection
>       ![collection card from detail page](https://user-images.githubusercontent.com/33448286/112169351-cb126f80-8bfa-11eb-9171-3b6eae41a91d.png)
>       "!" into the site notice:
> 
> 
> ![warnings](https://user-images.githubusercontent.com/33448286/112169719-1e84bd80-8bfb-11eb-81d0-335331f3638c.png)
> 
> icons in the autocomplete results:
> 
> ![autocomplete](https://user-images.githubusercontent.com/33448286/112169835-365c4180-8bfb-11eb-9f7d-070ff6a5522a.png)
> 

These should all be fixed via https://github.com/mozilla/addons-frontend/issues/10260

> * "Any" looks a bit cut for "Badging" sort filter:
> 
> 
> ![Badging](https://user-images.githubusercontent.com/33448286/112170171-8509db80-8bfb-11eb-8363-bbeafa4ca8e8.png)
> 

I'm not sure what this issue is. Is it the "y" thing again? 

> * there's some 12 px font left but maybe it's intended: "What is this" link from primary hero - homepage, "Available for your locale" and "All Locales" from language tools page.
> 
> * on edit profile page - the 10px font is small compared to the rest of the page and quite blurry
> 
> 
> ![edit profile page](https://user-images.githubusercontent.com/33448286/112171561-9a333a00-8bfc-11eb-8768-0f108849afdf.png)
> 

Those should be fixed. Can you include them in the new issue?

**Comment by ioanarusiczki** [comment] 2021-03-24 08:28
@bobsilverberg 
- the "y" and "g" used for the display name was an issue on the old version (with the 12px font-size) but it needs to be re-checked after https://github.com/mozilla/addons-frontend/issues/10260 lands.

- "Any" does not look bad anymore but "Badging" is a bit too close to the line:
![badging2](https://user-images.githubusercontent.com/33448286/112278585-ac0fee00-8c8b-11eb-85ad-1d499da81411.png)

**Comment by bobsilverberg** [comment] 2021-03-25 13:59
> @bobsilverberg
> 
> On Chrome - "Download Firefox" has 11 px font-size. - I mentioned when I filed the issue.
> 
> Also other buttons have 11px font-size: "Log in to rate this extension", "Log in to edit the profile", "Log in to view your collections", while editing a collection "Leave a note", "Remove" (Cancel and Save).

This will ideally be addressed via https://github.com/mozilla/addons-frontend/issues/10250
