### ISSUE TITLE
Recommended badge layout issues in the More extensions section on the detail page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8161] opened 2019-06-12 08:03 UTC
Followup for https://github.com/mozilla/addons-frontend/issues/8102
STR:
1. Go to an add-ons detail page to the More Extensions by _displayname_ section (make sure the user has recommended addons)
2. Observe the badge 

Expected result: 
No layout issues. 

Actual result:
The badge overlaps the number of users. 

Notes:
That would be reproducible for a number of 6 addons in the More Section - as display on a desktop - Win10(FF67). 

This is the example

![layout issues](https://user-images.githubusercontent.com/33448286/59333685-8bb6af80-8d01-11e9-8b41-670a5712140f.png)

**Comment by bobsilverberg** [comment] 2019-06-12 17:56
Assigning to @kumar303 as discussed at https://github.com/mozilla/addons-frontend/issues/8102#issuecomment-501090122

**Comment by kumar303** [comment] 2019-06-28 20:48
@ioanarusiczki I'm looking today on Win10, Firefox 67 and I cannot reproduce the screenshot anymore. Maybe something else fixed it? I do not see any overlap. 

Here's what I see at https://addons-dev.allizom.org/en-US/firefox/addon/white-frost/ on macOS (but I did check Win10):

<img width="515" alt="Screenshot 2019-06-28 15 47 46" src="https://user-images.githubusercontent.com/55398/60370374-182cc780-99bc-11e9-890d-b025ecf6f418.png">

**Comment by kumar303** [comment] 2019-06-28 21:43
In any case, the alignment looks off so I'm going to propose a fix for that.

**Closed** 2019-07-01 14:30 UTC
Labels: priority: p3

**Comment by ioanarusiczki** [comment] 2019-07-03 13:36
@kumar303 I can't reproduce the issue either.
Verified on -dev with FF67(Win10). 

![the badge](https://user-images.githubusercontent.com/33448286/60595964-a9cb7900-9db0-11e9-9b5e-d1b5263e43cb.png)
