### ISSUE TITLE
Discopane tests are hitting the dev server. Burn them with fire.

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1705] opened 2017-02-04 00:07 UTC
The add-ons dev server went down and discopane tests mysteriously started failing. When dev came back online, the tests passed.

<img width="830" alt="screenshot 2017-02-03 17 52 50" src="https://cloud.githubusercontent.com/assets/55398/22613155/912d3ee0-ea3b-11e6-8066-0ef29c312278.png">

Let's figure out why.

wezhou said the CDN was not affected but all app services were down.

**Comment by mstriemer** [comment] 2017-02-04 00:38
I think these tests just point at -dev for the API, which is why they fail if -dev is down.

The disco tests explicitly set the `apiHost` in [`config/test-disco.js`](https://github.com/mozilla/addons-frontend/blob/593b5742a76449879a344a6114ef3ad272253672/config/test-disco.js) but it looks like the default for tests is `http://localhost` though [`config/test.js`](https://github.com/mozilla/addons-frontend/blob/593b5742a76449879a344a6114ef3ad272253672/config/test.js).

**Comment by muffinresearch** [comment] 2017-02-06 12:18
Duplicate of your own bug https://github.com/mozilla/addons-frontend/issues/1138

**Closed by muffinresearch** 2017-02-06 12:18 UTC
Labels: code quality, triaged

**Comment by muffinresearch** [comment] 2017-02-06 12:23
> Duplicate of your own bug #1138

Reading #1138 which resulted in the duping of https://github.com/mozilla/addons-frontend/issues/773 I wonder if this should be re-opened since there's something of a distinction between server tests using a real api versus forgetting to mock api calls in a test - albeit they are related?

**Comment by kumar303** [comment] 2017-02-06 16:23
ha! I can't even remember what I did 5 minutes ago.

I don't really know what's happening but we should fix it. I would love to cripple all network connectivity at the start of any test suite similar to how we do it in [nose-blockage](https://pypi.python.org/pypi/nose-blockage/0.1.2) (which patches all network utilities).
