### ISSUE TITLE
The banner is not immediately displayed after the show-promo enrollment 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10794] opened 2021-07-27 12:01 UTC
Followup for 
https://github.com/mozilla/addons-frontend/issues/10774

After I cleared the cookie from the browser's settings I refreshed the detail page of the add-on and I've noticed the enrollment `show-promo` event and the `vpn-promo-banner-impression` with eventLabel:"1" being registered by the Console but the banner is not visible:

![no banner for show promo](https://user-images.githubusercontent.com/33448286/127148458-2d19532e-aaa6-425e-a095-1b4ea575cad8.png)

Then I refreshed the page, so "eventLabel:"2" was registered by the console but the banner was still invisible. I navigated to a different add-on detail page and then the promo appeared. 

Note:
In a different attempt, I was on the homepage and then landed on a detail-page. I could see the banner appearing and then disappearing (like a glitch) on the first detail page. I navigated to a different page and the banner was displayed. 
I think the issue is reproducible only for the first detail page clicked after the enrollment. 
I verified this on FF90 and Chrome - AMO Dev

**Comment by bobsilverberg** [comment] 2021-07-27 16:11
Thanks @ioanarusiczki. I tried to reproduce this locally and could not seem to do so. Here's what I did:
1. Have the cookie set to `hide-promo` so the banner is hidden.
2. Refresh the page. The banner is hidden.
3. Delete the cookie.
4. Refresh the page. The cookie is recreated with a value of `show-promo` (I hacked my code locally so this would happen). The enrollment event is sent, the impression event is sent, and the banner *is shown*.

See the attached screencast:

https://user-images.githubusercontent.com/142755/127188171-5608412a-b1a8-4828-87cb-27add0266b85.mov

I wonder if this is somehow different between my local setup and dev, although I'm not sure why it would be.

Out of interest, how were you able to conduct this test when the likelihood of getting the `show-promo` cookie is only 5%? Did you do something special, or did you just keep trying over and over again until you got lucky enough to get the `show-promo` value?

Is your STR identical to mine above?

**Comment by bobsilverberg** [comment] 2021-07-27 16:13
One last thought, I wonder if this could be related to caching? @diox do you have any thoughts about this, and whether caching could be contributing to this?

**Comment by bobsilverberg** [comment] 2021-07-27 16:21
Hmm, I think it's possible that the next patch in the series, which is https://github.com/mozilla/addons-frontend/pull/10787, might revolve the issue as it changes the logic for when the banner is shown. I'll try to land that soon and we can see if it resolves this issue on dev.

**Comment by diox** [comment] 2021-07-28 10:46
I don't see why caching would affect this right now. I'm slightly concerned by this issue, maybe it's worth digging into why this is happening for QA before moving on with #10787 and remembering the dismissal status.

**Comment by bobsilverberg** [comment] 2021-07-28 15:03
> I don't see why caching would affect this right now. I'm slightly concerned by this issue, maybe it's worth digging into why this is happening for QA before moving on with #10787 and remembering the dismissal status.

I will spend a bit if time trying to debug this, but it's difficult because:
a) I cannot reproduce it locally, and don't know what might be different between my local install and dev *other than* caching, and
b) It's difficult to debug on dev because the STR will only reproduce 5% of the time because of how experiment branches are allocated, so it involves testing over and over again until it happens.

While I am also curious about what is causing this, the fact is that the code currently on dev is not the code that will eventually be landing for this feature - it is just part of it. If the problem is resolved with the next patch, it's not really necessary to figure out a bug that no longer exists, so I will not spend a large amount of time on this, and I think it's acceptable to see if https://github.com/mozilla/addons-frontend/pull/10787 fixes it.

**Comment by bobsilverberg** [comment] 2021-07-28 19:45
@ioanarusiczki Can you please see if you can reproduce this as a logged in user? That will eliminate the possibility that this has anything to do with caching.

**Comment by bobsilverberg** [comment] 2021-07-28 21:22
@ioanarusiczki I think @willdurand and I might have figured it out. After you are able to reproduce this, please try scrolling up in your browser. I think the banner might be there, just scrolled out of view. Let me know how that goes.

**Comment by bobsilverberg** [comment] 2021-07-29 11:54
Here is an STR I was able to use to repro the problem on Chrome. Note that I haven't been able to repro it on Firefox:

1. Delete the experiment cookie.
2. Visit an add-on detail page on dev. The cookie should be automatically recreated and will likely have the value of "notInExperiment". Therefore the banner will not be shown.
3. Manually edit the cookie to change the value from "notInExperiment" to "show-promo".
4. Refresh the add-on detail page. It will look like the promo appears for a moment then disappears. If you refresh the page you will see the same thing.
5. Scroll up in the browser. The promo banner is actually there, but the browser did not automatically scroll up when the page refreshed. This would explain why it reproduces when you keep refreshing on the same page, but the banner appears when you move to a different page.

I suppose it's possible that this STR doesn't result in the same behaviour as the one noticed when the cookie is recreated with the "show-promo" value, but I suspect it's the same thing.

**Comment by ioanarusiczki** [comment] 2021-07-29 12:41
@bobsilverberg 
With Firefox - I could not reproduce the[ scenario](https://github.com/mozilla/addons-frontend/issues/10794#issuecomment-889054075) because the page refresh shows the header of the page and the promo is displayed without issues

![no glitch](https://user-images.githubusercontent.com/33448286/127491799-fff9edb8-9392-4ea3-b066-42d368bba471.gif)

But with Chrome there is a glitch because the header of the page is not loaded at refresh, yet if I scroll up the banner is visible. 

![Chrome with glitch](https://user-images.githubusercontent.com/33448286/127491912-015f815e-15e4-4c63-9724-dd3a39181b9c.gif)

It's not how I remember my initial issue - the banner was not displayed at all, and I think that happens
 if I switch between regions using my VPN (from a region that should show the banner to my region where it's restricted). 

This is when I refresh the page several times on region:DE with show-promo cookie in Chrome, then I go to a different detail page and the banner is loaded:

![vpn switch](https://user-images.githubusercontent.com/33448286/127493180-6faf8eb1-a5de-4596-a3b8-9560b3f3dc3c.gif)

**Comment by bobsilverberg** [comment] 2021-07-29 13:48
Thanks @ioanarusiczki. In that last screencap you added, I can see the flash of the banner when you refresh the page, but I don't see if you tried to scroll up to see it. Can you try that again with the VPN region change scenario and see if you can scroll up and see the banner in that case?

**Comment by ioanarusiczki** [comment] 2021-07-29 14:24
@bobsilverberg You were right - the banner is hidden and if I scroll up the banner is displayed

![scroll up](https://user-images.githubusercontent.com/33448286/127509439-06ac0c21-189f-4662-8bfc-a9f3b2c53133.gif)

**Comment by bobsilverberg** [comment] 2021-07-29 15:38
Thanks @ioanarusiczki!

@willdurand and I discussed this and while we could add some code to scroll the window up automatically, we think this is a wontfix because this isn't a situation that a user should ever realistically see. It only happens when a user manually deletes their cookie and then refreshes the web page. I don't think it can happen when a user originally lands on a page without a cookie.

Does that sound accurate to you, @ioanarusiczki?

**Comment by ioanarusiczki** [comment] 2021-07-30 12:38
@bobsilverberg Sounds good.

**Comment by bobsilverberg** [comment] 2021-07-30 12:54
Based on the above I'm making this a wontfix.

**Closed by bobsilverberg** 2021-07-30 12:54 UTC
Labels: priority: p2
