### ISSUE TITLE
"View classic desktop site" is not working on AMO-stage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2796] opened 2017-07-13 08:16 UTC
Steps to reproduce:
1. Load AMO-stage homepage on your android device https://addons.allizom.org/en-US/android/
2. Click on "View classic desktop site"

Expected results:
Desktop site is loaded.

Actual results:
Nothing happens.

Notes/Issues:
- a "#desktop" is added to the URL
- not working while on desktop using new desktop pages

Verified on FF54(Android 7.1.2, Win 7). Issue is ONLY reproducing on stage.
Video for this issue:

![videotogif_2017 07 13_11 13 48](https://user-images.githubusercontent.com/15685960/28156740-96590bde-67bc-11e7-9cdb-2f7c3504d50d.gif)

**Comment by muffinresearch** [comment] 2017-07-13 09:18
@ValentinaPC I can't reproduce this using Nightly Android or FF on OSX.

**Comment by tofumatt** [comment] 2017-07-13 09:25
Seems a lot of these are happening on Android... but a lot of these bugs see, to indicate a JS error on the page as all of these features that are broken require JS.

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment] 2017-07-13 09:33
I've tried this on Release, but, constantly able to reproduce this on Nightly while using Android. (and -dev works, so is not from prefs)

**Comment by muffinresearch** [comment] 2017-07-13 11:12
> I am constantly able to reproduce this on Nightly while using Android. (and -dev works, so is not from prefs)

@ValentinaPC does a new profile also repro this consistently?  Does it only repro on certain versions of Desktop Firefox?

**Comment by ValentinaPC** [comment] 2017-07-13 11:20
Is not reproduced on desktop using new profile.
Is still reproduced on Android using Nightly or Release.

**Comment by ValentinaPC** [comment] 2017-07-13 14:40
Seems like everything is working now. :|

**Comment by muffinresearch** [comment] 2017-07-13 14:45
I'm going to close this - but if it reappears we should reopen.

**Closed by muffinresearch** 2017-07-13 14:45 UTC
Labels: project: amo, project: desktop pages, project: mobile pages v1
