### ISSUE TITLE
Side-scrolling looks weird on Windows 10

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3762] opened 2017-11-02 19:49 UTC
Some Windows-related feedback I received today: There is a big thick scrollbar at the bottom of the screenshots area on a detail page, and it's there even if there is nothing to scroll.
![image](https://user-images.githubusercontent.com/6797635/32346868-2456560a-bfcc-11e7-8a85-1c6ff22d02f8.png)

Should we bring back the step-through buttons on screenshots?

**Comment by kumar303** [comment] 2017-11-02 19:55
Looks the same on Mac too. Are you suggesting to remove the scrollbar and provide alternate navigation?

**Comment by ValentinaPC** [comment] 2017-11-03 08:50
I think this is the same as https://github.com/mozilla/addons-frontend/issues/2965. Not sure. :)

**Comment by muffinresearch** [comment] 2017-11-03 09:09
@kumar303 I think the distinction is the scrollbar is always present on windows.

**Comment by muffinresearch** [comment] 2017-11-03 09:32
Dupe of #2965

**Closed by muffinresearch** 2017-11-03 09:32 UTC
Labels: needs: ux, priority: post release, state: duplicate
