### ISSUE TITLE
Footer on Mobile does not comply with mocks

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3402] opened 2017-10-09 06:59 UTC
Steps to reproduce:
1. Load AMO-dev on mobile: https://addons-dev.allizom.org/en-US/android/
2. Observe page footer

Expected results:
Footer correspond to mocks.

Actual results:
Actual footer differ from mocks.

Notes/Issues:
Verified on AMO-dev FF56(Android 7.2.1)
Screenshots for this issue:
1. Mocks
<img width="212" alt="30479292-8756bcb2-9a0c-11e7-9109-6021d634e32a" src="https://user-images.githubusercontent.com/15685960/31327505-5fd27058-acd8-11e7-92f0-61d633845660.png">
2. Actual representation 

![untitled](https://user-images.githubusercontent.com/15685960/31327621-2b0e1560-acd9-11e7-9e2e-b9674bff39a6.png)

Mocks observed in https://github.com/mozilla/addons-frontend/issues/3158

**Comment by tofumatt** [comment] 2017-10-09 08:09
We added headers (which help a lot I think) but otherwise the only differences are only one row of social media icons and the final links being on one line in mobile. I think these are improvements worth keeping so I think this should be closed as it’s working as intended. The footer as-is can be our reference point if that’s okay.

**Closed by tofumatt** 2017-10-09 08:09 UTC
Labels: component: homepage, project: amo, project: mobile pages v1
