### ISSUE TITLE
Language packs data is not loaded when opened from a deep-linked language details page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3939] opened 2017-11-17 16:17 UTC
## STR:

* https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2/
* click on "More..." -> "Dictionaries and Language Packs"

## What I expect to happen:

Language packs page should load

## What happens: 

<img width="1379" alt="dictionaries_and_language_packs_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32957094-a3741caa-cbb2-11e7-8773-89ad55d9cb9e.png">

There are no requests made for the data. Reloading the page shows the data.

**Comment by kumar303** [comment] 2017-11-17 18:41
We had a dupe of this in https://github.com/mozilla/addons-frontend/issues/3671 but I didn't know we had actual links that would trigger it.

**Comment by tsl143** [comment] 2017-11-18 06:19
@muffinresearch and @kumar303 , this is pretty edge case and this is caused specifically by [this line](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/LanguageTools/index.js#L79) and [this line](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/LanguageTools/index.js#L250)

When we open https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2/
which is `dictionary` type hence the `addon` props from [this line](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/LanguageTools/index.js#L250) already have data of `british-english-dictionary-` addon, so `fetchLanguageTools` is not dispatched from [this line](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/LanguageTools/index.js#L79).

PS: `this` keyword makes english chaotic too :P

**Closed** 2017-11-21 12:50 UTC
Labels: priority: p2, triaged, type: bug

**Comment by ValentinaPC** [comment] 2017-11-21 13:48
@muffinresearch : I could not reproduce this issue with other lang packs than the one mentioned here using FF57(Win 7), so my verification is not quite accurate. 
Could you give me a hand?

**Comment by muffinresearch** [comment] 2017-11-21 14:02
@ValentinaPC I'm not sure I follow you?

**Comment by ValentinaPC** [comment] 2017-11-21 14:05
Is this issue reproducing only for that exact example? (https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2/)

**Comment by muffinresearch** [comment] 2017-11-21 14:10
@ValentinaPC no it others. If you can't reproduce it's probably because you're not deep-linking the start page. Try refreshing the page on a language pack or dictionary before clicking through to the lanugage packs and dictionaries page.

**Comment by ValentinaPC** [comment] 2017-11-21 14:28
Yes! It works :)
Thanks!

Verified this as fixed on AMO-dev FF57(Win 7, Android 7)
Postfix video: 
![deep link](https://user-images.githubusercontent.com/15685960/33077655-f2f9f00a-ced8-11e7-9669-69f964f33868.gif)
