### ISSUE TITLE
[FF ESR] - Unbroken long name add-ons have layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4070] opened 2017-12-11 10:49 UTC
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Observe the layout of an add-on with long name in any of the sections from homepage i.e. NoScriptSecuritySuiteNoScriptSecuritySuiteNoScSuit 

Expected results:
There are no issues.

Actual results:
The name is not wrapped and overlays the number of users for that add-on.

Notes/Issues:
- issue can be seen in any category page, where an add-on of this type exists.

Verified on AMO-dev FF52.5.2 using Win 7.
Please see screenshot: 
![esr-longname](https://user-images.githubusercontent.com/15685960/33827499-429b7186-de71-11e7-9fba-ab5038d73b9c.png)

**Comment by wagnerand** [comment] 2018-02-07 18:11
@kumar could you add a little more information on what a fix would look like and where it would have to be applied? Thanks!

**Comment by kumar303** [comment] 2018-02-21 16:47
If you use [React devtools](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) on a local server you can inspect the HTML and it will tell you which component is rendering the text. This text is rendered by [`SearchResult`](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchResult/index.js). The fix is to update the CSS to handle long names.

**Comment by pwalm** [comment] 2018-03-02 21:47
UX sez: just truncate the copy on one line.
<img width="1390" alt="screen shot 2018-03-02 at 1 46 13 pm" src="https://user-images.githubusercontent.com/6797635/36923443-345dd174-1e20-11e8-9537-5f6d4de27700.png">

**Comment by caitmuenster** [comment] 2018-03-07 16:40
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @kumar303

**Comment by muffinresearch** [comment] 2018-05-01 16:52
@svitlana-galianova I've reverted the patch from #4070 in https://github.com/mozilla/addons-frontend/commit/b341fb78b51cba4f91ce7da47d9fdb3fa12b6a5f in because using ellipsis for truncation is used used very sparingly in the site currently and we should instead look to continue with the wrapping and fix the display issue so that a string that wraps does not cover the number of users information.

Sorry this wasn't brought up earlier - missing that was entirely my fault 🙈. Would you be interested in contributing a updated patch to fix the display instead?

**Comment by championshuttler** [comment] 2018-08-11 09:35
is this issue still available. I tried to reproduce it, but unable to do the same @ValentinaPC can you please verify it?

Thanks

**Comment by AlexandraMoga** [comment] 2018-08-13 05:46
@championshuttler I can still reproduce the issue but only with FF 52 ESR (FF 52.8.0, Win10x64)

![image](https://user-images.githubusercontent.com/31961530/44014546-3b8461a8-9ed5-11e8-8ce8-36b8b5919e69.png)

**Comment by willdurand** [comment] 2019-07-16 14:35
@AlexandraMoga is this issue still relevant?

**Comment by AlexandraMoga** [comment] 2019-07-19 07:39
I think not. In the latest ESR the issue will not reproduce and ESR 52 has been discontinued a while back.
In other words, this issue has been fixed by time :)

**Closed by AlexandraMoga** 2019-07-19 07:39 UTC
Labels: contrib: assigned, priority: p4, project: amo, project: desktop pages, triaged
