### ISSUE TITLE
Can't install addon in Nightly 58 on Android (TypeError: Parameter 'url' must be a string, not undefined)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/addons-frontend#3393] opened 2017-10-06 21:27 UTC
### Describe the problem and steps to reproduce it:

Originally reported here: https://github.com/webcompat/web-bugs/issues/11809

STR)
1. In Nightly 58 (untested anywhere else), go to https://addons.mozilla.org/en-US/android/addon/umatrix/
2. tap on install slider

### What happened?

Slider moved, no addon was installed

### What did you expect to happen?

Addon should be installed

### Anything else we should know?

`TypeError: Parameter 'url' must be a string, not undefined`

full stack here: https://github.com/webcompat/web-bugs/issues/11809#issuecomment-334873506

**Comment by kumar303** [comment] 2017-10-09 16:04
Thanks for re-filing this @miketaylr . I looked at the platform files for this add-on and I can confirm that the root cause is the same as https://github.com/mozilla/addons-frontend/issues/3315 . It will be fixed soon.

**Closed by kumar303** 2017-10-09 16:04 UTC

**Comment by kumar303** [comment] 2017-10-09 17:33
Actually it's a dupe of https://github.com/mozilla/addons-frontend/issues/3266

**Comment by miketaylr** [comment] 2017-10-10 15:34
Thanks!
